### PR TITLE
#17479 icon size fix (inline styles)

### PR DESCRIPTION
**Pull request by simialbi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17479, #18559

This PR fixes the icon size problem with inline styles

### CODE REVIEW

**Comment by bizley** [comment]
Hm, right, we need only these three, no reason to add all styles then.
@xfuturomax could you confirm this fix works in your case?

**Comment by xfuturomax** [comment]
No it doesn't.
I've updated to the latest commit 91d01fc.
In a big grid it's like:
image

In a smaller one:
image

Perhaps it's better to use fixed size in styles.

**Comment by bizley** [comment]
Are you sure this commit is the one with these changes? Please make a quick test by changing by hand the code in ActionColumn.

**Comment by simialbi** [comment]
Works like a charm:
https://test.dev.tonic.ag

**Comment by bizley** [comment]
Perfect, thanks!

**Comment by My6UoT9** [comment]
pls minify the svg some more..
https://jakearchibald.github.io/svgomg/
for example the eye, precision 0 - looks exactly same, specially at the small scale its used:
397 bytes → 328 bytes 82.62%
```
<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="height:1em;vertical-align:-.125em;width:1.125em" display="inline-block" font-size="inherit" overflow="visible" viewBox="0 0 576 512"><defs/><path fill="currentColor" d="M573 241C518 136 411 64 288 64S58 136 3 241a32 32 0 000 30c55 105 162 177 285 177s230-72 285-177a32 32 0 000-30zM288 400a144 144 0 11144-144 144 144 0 01-144 144zm0-240a95 95 0 00-25 4 48 48 0 01-67 67 96 96 0 1092-71z"/></svg>
```

**Comment by bizley** [comment]
Oh, nice. Every byte counts. Can we get one more PR with this? :)

**Comment by xfuturomax** [comment]
>Are you sure this commit is the one with these changes? Please make a quick test by changing by hand the code in ActionColumn.

Manually changes work perfect, thanks.

**Pull request merged**
