### PR TITLE
Get Customs File Types

### PR DESCRIPTION
**Pull request by GuilhermeLessa**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | not-found |

return local file types on function, or custom file types passed by
param

### CODE REVIEW

**Comment by samdark** [comment]
What's the use case for it?

**Comment by GuilhermeLessa** [comment]
if anybody want custom return for file extensions. i needed... thanks

Guilherme Lessa


Date: Wed, 6 Jul 2016 13:43:49 -0700

**Comment by samdark** [comment]
What's "custom return for file extensions"?

**Comment by GuilhermeLessa** [comment]
i needed that .docx, .json, .xml returned "files" and .mp3, ogg returned "medias", for example.
I needed and programed, offer if you want. I thought that this should have in a FileHelper
Guilherme Lessa


Date: Thu, 7 Jul 2016 01:47:03 -0700

**Comment by samdark** [comment]
OK. Got it. Won't merge it since it's not common enough to be part of the framework. Thanks for offering it though.

**Comment by GuilhermeLessa** [comment]
Thanks


Date: Thu, 7 Jul 2016 07:38:38 -0700From: notifications@github.com
To: yii2@noreply.github.com
CC: gl-lessa@hotmail.com; author@noreply.github.com
Subject: Re: [yiisoft/yii2] Get Customs File Types (#11911)

Closed #11911.

**Pull request closed without merging**
