### PR TITLE
kB instead of KB

### PR DESCRIPTION
**Pull request by diegotibi**
When kilobyte is referred to 1000 bytes the abbreviation should be written with lower case "k" as kB. Upper case K is usually intended to refer to 1024 multiplier
See this page: https://en.wikipedia.org/wiki/Kilobyte

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | none

### CODE REVIEW

**Comment by Thoulah** [comment]
They already have the difference between kB en KiB. You change is in the else part of `if ($this->sizeFormatBase == 1024)`

**Comment by Thoulah** [comment]
I think you should additionally edit all translation files as well, or this change will break other languages.

**Comment by diegotibi** [comment]
Yes, I know. I've just proposed to change **K**B in **k**B. KiB (Kibibyte, 2^10 or 1024 prefix) is written correctly.

**Comment by Thoulah** [comment]
And documentation on line https://github.com/diegotibi/yii2/blob/cd74431f24383db1767fc855d46f9f0377718580/framework/i18n/Formatter.php#L1308

**Review by ghost — APPROVED** [review]

**Comment by samdark** [comment]
Please add a line for changelog. The change itself looks OK.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
