### PR TITLE
optimize performance SQL-query (IN) with composite keys

### PR DESCRIPTION
**Pull request by pvsaintpe**
@samdark, Hi!

On large tables, there are serious problems with the performance of a SQL query, since indexes are not used in the construction
```SQL
WHERE (`a`,` b`, ..) IN ((1, 2, ..), (3, 2, ..), ..)
```

Below I present the evidence and tests on a small database in 130 thousand lines.

Please consider and download this pool request in yii2 (2.0.15.1) at least, since I do not want to fence bicycles and redefine your native traits.

SchemaTable (indexes):
image

My relation code in model:
```PHP
/**
 * @return \common\models\query\ContractStepQuery|\yii\db\ActiveQuery
 */
public function getLastContractStep()
{
     return $this->hasOne(ContractStep::class, [
         'contract_id' => 'id',
         'number' => 'number_steps'
    ]);
}
```

generated SQL (with your ActiveRelationTrait):
```SQL
SELECT * FROM `contract_step` `lastContractStep` WHERE (`contract_id`, `number`) IN (('74548', 2), ('74432', 4), ('74575', 2), ('74490', 3), ('74545', 4), ('74607', 3), ('74544', 2), ('74463', 4), ('74543', 3), ('74542', 5), ('74516', 4), ('74485', 5), ('74465', 5), ('74572', 3), ('74606', 2), ('74581', 5), ('74547', 4), ('74583', 3), ('74464', 4), ('74604', 4))
```

Explain:
image

Execution Time (on 130k rows in table):
image

Execution Time (on 2.5m rows in table): 2.6 sec

After my changes in ActiveRelationTrait....

generated SQL:
```SQL
SELECT * FROM `contract_step` `lastContractStep` WHERE ((`contract_id`='115199') AND (`number`=5)) OR ((`contract_id`='115198') AND (`number`=5)) OR ((`contract_id`='115193') AND (`number`=1)) OR ((`contract_id`='115192') AND (`number`=1)) OR ((`contract_id`='115191') AND (`number`=1)) OR ((`contract_id`='115190') AND (`number`=1)) OR ((`contract_id`='115189') AND (`number`=1)) OR ((`contract_id`='115187') AND (`number`=1)) OR ((`contract_id`='115186') AND (`number`=1)) OR ((`contract_id`='115185') AND (`number`=1)) OR ((`contract_id`='115183') AND (`number`=1)) OR ((`contract_id`='115182') AND (`number`=1)) OR ((`contract_id`='115181') AND (`number`=1)) OR ((`contract_id`='115165') AND (`number`=5)) OR ((`contract_id`='115124') AND (`number`=5)) OR ((`contract_id`='115123') AND (`number`=3)) OR ((`contract_id`='115122') AND (`number`=3)) OR ((`contract_id`='115121') AND (`number`=3)) OR ((`contract_id`='115120') AND (`number`=3)) OR ((`contract_id`='115107') AND (`number`=1))
```

Explain:
image

in my version, indexes are already used (PRIMARY), due to which maximum performance is achieved.

Execution time (on 130к rows):
image

Execution time (on 2.5m rows): 0.0007 - 0.0010 (stable time!!!)

Please consider this situation and comment on why you made such a decision in the implementation. If my argument is not enough, please contact me.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by pvsaintpe** [comment]
please help resolve conflicts?

**Comment by pvsaintpe** [comment]
I can not understand why the tests TravisCI fall, because I did not make changes to ActiveRecord ...

image

**Comment by pvsaintpe** [comment]
Please fill this fix in yii2 (2.0.15.1) because In my projects this version is used (or if patch 2.0.15.2 can be made).

**Comment by pvsaintpe** [comment]
image

**Comment by pvsaintpe** [comment]
image

**Comment by pvsaintpe** [comment]
Help me, please, deal with the tests, why does TravisCI fall and my tests fail?

**Comment by samdark** [comment]
@pvsaintpe is there any reason you can't update to 2.0.16?

**Comment by pvsaintpe** [comment]
@samdark I can, I did not know about its existence))
I will do in the coming days, but what?

**Comment by samdark** [comment]
There's going to be 2.0.16.1 fixing 2.0.16 regressions. Then 2.0.17 for which this pull request will be re-checked and likely merged.

**Comment by pvsaintpe** [comment]
@samdark Well, thank you!

Since This bug or a flaw on your part in forming the SQL query, makes the query heavier and the page with the gridview loads for a very long time ....

Perhaps, not everyone is turning to it, but it is strange that only I have gone deep into it and opened this problem ...

I hope, that this will help someones too.

**Comment by samdark** [comment]
I've checked with MariaDB and the following table with 187916 rows:

```sql
create table user
(
	id int auto_increment,
	username varchar(64) not null,
	email varchar(255) not null	
);

create unique index `idx-user-email-unique`
	on user (email);

create unique index `idx-user-username-unique`
	on user (username);
```

Explain for a query generated currently with `WHERE IN` is the following:

<table border="1" style="border-collapse:collapse">
<tr><th>id</th><th>select_type</th><th>table</th><th>type</th><th>possible_keys</th><th>key</th><th>key_len</th><th>ref</th><th>rows</th><th>Extra</th></tr>
<tr><td>1</td><td>SIMPLE</td><td>user</td><td>range</td><td>idx-user-username-unique,idx-user-email-unique</td><td>idx-user-username-unique</td><td>194</td><td>NULL</td><td>4</td><td>Using where</td></tr></table>

Explain for a query with multiple conditions and ORs:

<table border="1" style="border-collapse:collapse">
<tr><th>id</th><th>select_type</th><th>table</th><th>type</th><th>possible_keys</th><th>key</th><th>key_len</th><th>ref</th><th>rows</th><th>Extra</th></tr>
<tr><td>1</td><td>SIMPLE</td><td>user</td><td>range</td><td>idx-user-username-unique,idx-user-email-unique</td><td>idx-user-username-unique</td><td>194</td><td>NULL</td><td>4</td><td>Using index condition; Using where</td></tr></table>

Looks like [index condition pushdown](https://mariadb.com/kb/en/library/index-condition-pushdown/) but the thing is I don't have any difference in execution timings. It's 4 ms in both cases (values selected are from the start, in the middle and from the end to make sure scanning table is not lucky).

**Comment by samdark** [comment]
What's your table and index structure?

**Comment by samdark** [comment]
What's your database version?

**Comment by pvsaintpe** [comment]
@samdark,

Mysql 15.1
10.3.13-MariaDB

**Comment by pvsaintpe** [comment]
CREATE TABLE CODE
```SQL
CREATE TABLE IF NOT EXISTS `contract_step` (
  `contract_id` bigint(20) unsigned NOT NULL COMMENT 'Контракт',
  `number` tinyint(3) unsigned NOT NULL COMMENT 'Номер шага',
  `expiration` smallint(5) unsigned NOT NULL COMMENT 'Экспирация',
  `open_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время открытия',
  `close_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время закрытия',
  `result_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Время результата',
  `forecast_id` tinyint(3) unsigned NOT NULL COMMENT 'Прогноз',
  `forecast_digits` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Прогноз цифр',
  `important` tinyint(1) unsigned DEFAULT NULL COMMENT 'Важный шаг',
  `open_quote_time` timestamp NULL DEFAULT NULL COMMENT 'Время котировки открытия',
  `open_quote_ask` float unsigned DEFAULT NULL COMMENT 'Прямая котировка открытия',
  `open_quote_bid` float unsigned DEFAULT NULL COMMENT 'Обратная котировка открытия',
  `open_quote_asset` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Актив котировки открытия',
  `open_quote_source` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Источник котировки открытия',
  `no_open_quote` tinyint(1) unsigned DEFAULT NULL COMMENT 'Нет котировки открытия',
  `close_quote_time` timestamp NULL DEFAULT NULL COMMENT 'Время котировки закрытия',
  `close_quote_ask` float unsigned DEFAULT NULL COMMENT 'Прямая котировка закрытия',
  `close_quote_bid` float unsigned DEFAULT NULL COMMENT 'Обратная котировка закрытия',
  `close_quote_asset` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Актив котировки закрытия',
  `close_quote_source` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Источник котировки закрытия',
  `no_close_quote` tinyint(1) unsigned DEFAULT NULL COMMENT 'Нет котировки закрытия',
  `quote_direction_id` tinyint(3) unsigned DEFAULT NULL COMMENT 'Фактическое направление',
  `result` tinyint(1) unsigned DEFAULT NULL COMMENT 'Результат',
  `result_digit` tinyint(3) unsigned DEFAULT NULL COMMENT 'Цифра шага',
  `no_result` tinyint(1) unsigned DEFAULT NULL COMMENT 'Нет результата',
  `joker_used` tinyint(1) unsigned DEFAULT NULL COMMENT 'Джокер использован',
  `failed_step_used` tinyint(1) unsigned DEFAULT NULL COMMENT 'Неудачный шаг использован',
  `win_coef_lost` tinyint(1) unsigned DEFAULT NULL COMMENT 'Коэффициент выигрыша потерян',
  `win_coef_s` float unsigned DEFAULT NULL COMMENT 'S расчета переменного коэффициента результативности',
  `win_coef_s0` float unsigned DEFAULT NULL COMMENT 'S0 расчета переменного коэффициента результативности',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Создано в',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Обновлено в'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Шаги контрактов';
```

KEYS
```SQL
ALTER TABLE `contract_step`
  ADD PRIMARY KEY (`contract_id`,`number`),
  ADD KEY `contract_step-forecast_id` (`forecast_id`),
  ADD KEY `contract_step__quote_direction_id` (`quote_direction_id`);
```

**Comment by pvsaintpe** [comment]
image

**Comment by pvsaintpe** [comment]
The problem with performance and lack of use of indexes arises on large amounts of data, in my case with 2 million rows in the table, query execution time when using "IN" with composite keys, calculation by exponent, due to the fact that indexes are not used in this case.

When using the construction of "OR", "AND", this problem is absent, for any amount of data in the table - the time for execution of the SQL query is kept within the limits of the permissible level.

**Comment by samdark** [comment]
You previously said it's "130 thousand lines". That's why I've tested on 187916 rows.

**Comment by samdark** [comment]
@pvsaintpe let's reduce schema a bit:

```sql
CREATE TABLE IF NOT EXISTS `contract_step` (
  `contract_id` bigint(20) unsigned NOT NULL,
  `number` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`contract_id`,`number`)
) ENGINE=InnoDB;
```

Since we're using `contract_id` and `number` the rest should not matter.

**Comment by samdark** [comment]
So we have perfect index by composite PK and it's used when table rows number isn't too high. Looks like optimizer edge case: https://dba.stackexchange.com/questions/174945/mysql-not-using-index-on-large-where-in-clause

**Comment by rob006** [comment]
> ```sql
> CREATE TABLE IF NOT EXISTS `contract_step` (
>   `contract_id` bigint(20) unsigned NOT NULL,
>   `number` tinyint(3) unsigned NOT NULL,
>   PRIMARY KEY (`contract_id`,`number`)
> ) ENGINE=InnoDB;
> ```

I've made table with this schema and 2kk records, and AND-OR approach from this PR was ~2 times slower than IN condition from current implementation. MySQL 5.7.21

**Comment by pvsaintpe** [comment]
> You previously said it's "130 thousand lines". That's why I've tested on 187916 rows.

I have a lot of databases and servers, they are temporary to test the future load, at the moment the previous database is erased and this new one, because You asked to send the structure of the table - I made a screen with the current one.

At that time, I tested on a very large base.

**Comment by samdark** [comment]
It seems the optimization is quite controversial and needs more in-depth testing and explanation about when to apply it and when not. Not going to make it into 2.0.17...

**Comment by SamMousa** [comment]
> I've made table with this schema and 2kk records, and AND-OR approach from this PR was ~2 times slower than IN condition from current implementation. MySQL 5.7.21

@rob006 the time is not relevant, the execution plan is what matters.

Regardless, this feels like a bug in the mysql query optimizer, not in Yii.
The point of SQL is to tell the DMBS what we need not how to get it.
@pvsaintpe could you try the original query with index hints or even forced indexes? (https://dev.mysql.com/doc/refman/5.5/en/index-hints.html)

Mysql might be incorrectly thinking that not using an index is faster, try optimizing the table (I think that updates statistics for the query plan optimizer).

For reference, I've created a table containing ~ 500k records of 4 numbers. Composite key on the first 2 numbers.
Tried queries with 500 entries in the `IN` clause and it still always uses the key automatically.

Then I created a table containing ~ 4 million records of 4 numbers. Composite key on the first 2 numbers.
Tried queries with 100 entries in the `IN` clause and it still always uses the key automatically.

I have found a reliable way to break the query optimizer:
`SELECT * FROM `testpull17125` where (`a`, `b`) in ((floor(rand()*100000), floor(rand()*100000)))`.

Will never select a key, even when forced. This is not really relevant other than the fact that it illustrates the query optimizer can be tricked into not selecting a key even when it should be possible to use a key.


Your query uses a string for part of the composite key, I've had issues in the past with casting between character sets, this could be something similar.

I'm against merging this PR, if this issue exists outside of OPs specific dataset / MySQL version combination, it is still an issue with MySQL and should be fixed there.

**Comment by rob006** [comment]
> @rob006 the time is not relevant, the execution plan is what matters.

They're the same for both queries. 

be5c7fb1

**Comment by SamMousa** [comment]
I agree, just saying that the execution time difference is noise from something like network delay if the execution path is the same.

**Comment by rob006** [comment]
> I agree, just saying that the execution time difference is noise from something like network delay if the execution path is the same.

I don't think you can call it a noise - difference is quite constant and repeatable (at least in my case). Actual query execution is only one of many phases of query handling - even if execution plan is the same it does not mean that other phases will be the same.

**Comment by GHopperMSK** [comment]
```
...
`contract_id` bigint(20) unsigned NOT NULL COMMENT 'Контракт',
...
```
```
SELECT * FROM `contract_step` `lastContractStep` WHERE (`contract_id`, `number`) IN (('74548', 2), ('74432', 4), ('74575', 2), ('74490', 3), ('74545', 4), ('74607', 3), ('74544', 2), ('74463', 4), ('74543', 3), ('74542', 5), ('74516', 4), ('74485', 5), ('74465', 5), ('74572', 3), ('74606', 2), ('74581', 5), ('74547', 4), ('74583', 3), ('74464', 4), ('74604', 4))
```
Don't you suspect typecasting?

Here is related [link](https://makandracards.com/makandra/14955-mysql-will-not-use-indexes-if-you-query-the-wrong-data-type)

```
MySQL will not use indexes if you query the wrong data type
When MySQL refuses to use your index, you can do a number of things wrong. One of them might be conditions with improper data types.
```

**Comment by SamMousa** [comment]
It could very well be, but I think that's mostly an issue when using joins.
Note that the link you mentioned actually tells us it is not an issue for integer columns..

**Comment by samdark** [comment]
Won't be merged without further research. @pvsaintpe any ideas?

**Pull request closed without merging**
