### PR TITLE
fix yii migrate exit code not correct

### PR DESCRIPTION
**Pull request by haohetao**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #18339

### CODE REVIEW

**Review by schmunk42 — COMMENTED** [review]
Which error code is returned when migrations fail in `YII_ENV_PROD`?

**Comment by bizley** [comment]
@schmunk42 I'm not sure what you mean. It should not differ from other environments.

**Comment by schmunk42** [comment]
> @schmunk42 I'm not sure what you mean. It should not differ from other environments.

I remember an issue, where a failed `yii migrate` would not return an error in production, but I'd need to look it up... Just thought you may have stumbled across that.

The rationale was, that you do not want the whole page offline, when a migration fails. On the other hand, it can be tricky to find that this was going wrong. CC: @samdark

**Comment by bizley** [comment]
Yes, let's not be hasty about that. I didn't experienced such case before but there should not be a problem with sneaky failures anymore, unless something we missed.

**Review by schmunk42 — COMMENTED** [review]
How does it break BC?

**Comment by bizley** [comment]
Response is changed. Although from nothing to something so let's call it soft BC break.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
