### PR TITLE
adds getter / setter for the title to View to fix issues with the page title after pjax requests

### PR DESCRIPTION
**Pull request by Bhoft**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #10998 |

### CODE REVIEW

**Comment by SilverFire** [comment]
I meant to create `getTitle()` in `Pjax` class, not in `View`.

**Comment by Bhoft** [comment]
It wouldn't solve the issue. If a getTitle function will be added to the Pjax Class it also must be added to the View class as well.

**Comment by SilverFire** [comment]
Why? Then you can redeclare `getTitle()` in your own Pjax class and all works as you want

**Comment by Bhoft** [comment]
As i mentioned also on the issue page. 
Of course if i add a getTitle() function to the Pjax and use it it would solve `this` issue. But for external modules which maybe also use the $this->title in their views the page title would still be not correctly set. 

And as I mentioned in the [issue ](https://github.com/yiisoft/yii2/issues/10998#issuecomment-206352347) if I have as an example an dynamic page title in e.g. multi-language and the title prefix differs I would still have multiple places where I have to extend the code to get the correct result.

**Pull request closed without merging**
