### PR TITLE
Implement Array cache using Yii3 cache library

### PR DESCRIPTION
**Pull request by mtangoo**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | 19979

### CODE REVIEW

**Comment by bizley** [comment]
What are the benefits of using this package?

**Comment by mtangoo** [comment]
> What are the benefits of using this package?

For this array one not really anything significant. But given the plan is to move whole Yii2 caching to use Yii3 packages under the hood, that gives big advantages in terms of quality and easy to maintain.

**Comment by rob006** [comment]
Cache in Yii2 is quite mature and does not need that much of the maintenance. This approach also does not really help people to prepare their apps/libraries for Yii 3, which AFAIK was the main goal of Yii 2.2.

**Comment by mtangoo** [comment]
> Cache in Yii2 is quite mature and does not need that much of the maintenance. This approach also does not really help people to prepare their apps/libraries for Yii 3, which AFAIK was the main goal of Yii 2.2.

I picked the list from https://github.com/yiisoft/yii2/discussions/19875
To the best of my knowledge, no body objected it. Can we move tempoarily the discussion as to which libraries there merit the effort, if we are not going to replace all of them?

Another question would be, after Yii3 is fully adopted and before Yii2 is fully unsupported, will there be enough maintainers to fix issues like PHP version compatibility or new language feature as they come and go? IMHO, having as many Yii3 library under the hood will easy this whole burden as Yii3 libraries will be upd-to-date with language feature set/compatibility
Take it as a Yii1 thing of today.

**Comment by rob006** [comment]
From my understanding #19875 was not about using Yii3 packages through decorators, but using them directly, so people could switch to new API and easier migrate to Yii3.

**Comment by mtangoo** [comment]
So basically, assuming that you understood it correctly, PR should be about new Cache API (Yii3 api Actually) for Yii2 with Yii3 cache package replacing Yii2 caching everywhere in the framework itself. Is that correct?

**Comment by rob006** [comment]
I'm not entirely sure how to handle this, but I don't think that hiding Yii3 implementation behind decorators with Yii2 API is worth the effort - it is probably more work than maintenance of old implementation, and as a result you only get bugs and BC breaks. If Yii 2.2 is supposed to be a bridge between Yii 2.0 and Yii 3, then we should focus on that, not on refactoring.

**Comment by mtangoo** [comment]
> I'm not entirely sure how to handle this, but I don't think that hiding Yii3 implementation behind decorators with Yii2 API is worth the effort - it is probably more work than maintenance of old implementation, and as a result you only get bugs and BC breaks. 

I agree that I got this wrong. I think that is clear now

>If Yii 2.2 is supposed to be a bridge between Yii 2.0 and Yii 3, then we should focus on that, not on refactoring.

How is the bridge supposed to look like? I think we have not done a good job defining this one. We need somehow to reach clear resolution on definition of the bridge. What entails the bridge a part from language bar and removing deprecations due to old stuffs?

**Pull request closed without merging**
