### PR TITLE
Fixed sorting on extracting messages to PO and PHP files #16910.

### PR DESCRIPTION
**Pull request by aivchen**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | partially
| Fixed issues  | #16910.

I've written test and fixed messages extracting for PHP and PO files only. But the test doesn't pass for Db (Do we really need to sort extracted messages in db?)

### CODE REVIEW

**Comment by samdark** [comment]
There's no big need for sorting DB messages but since general config supports it, it's fine to implement it. Should be ORDER BY, right?

**Comment by Groonya** [comment]
Not really. Option $sort in MessageController just controls in what order messages should be inserted into translation target (file or db). It's very important for files because you can open any file and see ordered messages. But it is useless for a database. When you do SELECT * FROM table in most cases dbms doesn't guarantee the order - you have to specify the order.
So main question here is for whom we need to order messages in the database?
For user? No, he must specify the order if he wants to see ordered messages.
For framework? No, it's not important for it how messages are ordered.

**Comment by samdark** [comment]
Well, yes. There's no need to order for database but that breaks current inheritance design...

**Comment by Groonya** [comment]
What do you mean? 
If you are talking about tests, then we can skip the test for database?
Just want to be sure I'm thinking in a right way.

**Comment by samdark** [comment]
Yes, I think we can do it. Would you please mark test as skipped?

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
