### PR TITLE
Added and translated into Brazil of the Portuguese session of the URL helper

### PR DESCRIPTION
**Pull request by lukBarros**
Added and translated into Brazil of the Portuguese session of the URL helper.

Lets rock!

### CODE REVIEW

**Comment by SilverFire** [comment]
Thank you! Unfortunately, I don't know Portugalian to ensure that there are no spelling mistakes :)
We are always trying to get at least one review of a PR, therefore @gugoan may I ask you to check the spelling, please?

**Comment by lukBarros** [comment]
ok @SilverFire i have translater outhers files in the components boostrap, gii, etc.... I'm live from Brazil and português BR is my language default.

I checked it after PU submit. But a second review of a Brazilian is always good.

**Comment by lukBarros** [comment]
@janfrs ou @davidsonalencar  podem revisar isto?

**Comment by SilverFire** [comment]
Merged, thank you

**Pull request merged**
