### PR TITLE
update fa/yii.php

### PR DESCRIPTION
**Pull request by PooyaE**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | no |
| Fixed issues | none |

in persian we never use plural type of these words.
i.e. 5 روز 
not 5 روزها

### CODE REVIEW

**Comment by cebe** [comment]
@jafaripur seems you have added these lines, can you comment on this change?

**Comment by cebe** [comment]
seems to be in line with https://github.com/yiisoft/yii2/commit/e093e77027d0792dc66b83ad709923a8daeb7cb2 , @emadgh can you please check this change and confirm this is correct?

**Comment by jafaripur** [comment]
@cebe Yes translations for number or month can use without plural.

**Comment by cebe** [comment]
okay, thanks for the quick response!

**Comment by cebe** [comment]
merged, thank you!

**Pull request merged**
