### PR TITLE
9419 fix null column cant be incremented

### PR DESCRIPTION
**Pull request by RusAlex**
#9419 fix

### CODE REVIEW

**Comment by klimov-paul** [comment]
Using `null` field for the counter seems to be incorrect usage.
The fix make functionality too complicated for the simple case.

**Comment by cebe** [comment]
I agree that a counter field should be defined as `int NOT NULL DEFAULT 0` instead of allowing NULL. What would be the semantics of a NULL value in the DB?

**Comment by RusAlex** [comment]
In this way core should throw exception or warn user about updating
counters for NULL column.

**Comment by nineinchnick** [comment]
`null` in databases is an unknown values and can't be incremented, that's why `select null+1` will return null.

As a side note, `COALESCE(column, 0)` should be used instead of a `CASE` expression.

**Comment by nineinchnick** [comment]
> In this way core should throw exception or warn user about updating counters for NULL column.

The database does not throw an error, so why would the framework do it?

**Comment by nineinchnick** [comment]
Trying to increment a `null` value is a valid expression, just the result is still `null` because the value is stull unknown.

**Comment by RusAlex** [comment]
What about COALESCE @cebe, @klimov-paul ?

**Comment by samdark** [comment]
Closing for reasons @nineinchnick provided.

**Pull request closed without merging**
