### PR TITLE
fix return of BaseHtml::getAttributeValue

### PR DESCRIPTION
**Pull request by dicrtarasov**
Return type of BaseHtml::getAttributeValue expected to be `string|array`, but actually return `null|array|mixed`.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #18829

### CODE REVIEW

**Comment by bizley** [comment]
There are some errors in the tests.

**Comment by dicrtarasov** [comment]
> There are some errors in the tests.

Yes, because of incorrect test.
`BaseHtml::getAttributeValue` return `string|array|null`
Test expected invalid return `int 1` but actually got right `string '1'`

Don't know how to handle this situation for good.

**Comment by bizley** [comment]
Well, it was passing before so you change the situation and you must update tests to reflect it (and most probably add new ones). Please do so.

**Comment by samdark** [comment]
That would break selects as described in https://github.com/yiisoft/yii2/pull/18863/files#r702250746

**Pull request closed without merging**
