### PR TITLE
allow migrate/mark to mark the history base

### LINKED ISSUE #7890: yii migrate/mark m000000_000000_base not working
I want to mark the very first, "0. migration" command, but is not working. It is a bug or feature? (I think it's bug). How can i "delete" other way the first (1.) migration?
(The error message is: Error: Unable to find the version 'm000000_000000_base'.)

### PR DESCRIPTION
**Pull request by cebe**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #7890

fixes #7890

### CODE REVIEW

**Comment by cebe** [comment]
@klimov-paul do you remember why `getMigrationHistory()` does not return the base Migration anymore? If it did, that would also fix the issue.

**Comment by klimov-paul** [comment]
Why it should return a base migration? It will simply create a confusion for the developer.

**Comment by cebe** [comment]
It was returned in an early version and `migrate/mark` did work in this way back then. Thats why I ask about reasons.

**Comment by klimov-paul** [comment]
Can you find a commit, which does it?

**Comment by samdark** [comment]
Which early version?

**Review by samdark — APPROVED** [review]

**Comment by cebe** [comment]
> Can you find a commit, which does it?

okay, seems that was Yii 1.1 behavior, changed in https://github.com/yiisoft/yii2/commit/af4455eb03a79c4c24a92771a6f842641ec2a8fe#diff-952bc7045bade5b9e9c44621c5f93c19R606

**Comment by klimov-paul** [comment]
Well then, returning to the original question:

> do you remember why getMigrationHistory() does not return the base Migration anymore?

my anwser is 'I have no idea'.

Still fro me it seems logical that virtual 'zero' migration does not appear at the applied migrations list as it creates a confusion: why there is any migration present, while I have not created a single one yet?

**Comment by cebe** [comment]
> Still for me it seems logical that virtual 'zero' migration does not appear at the applied migrations list as it creates a confusion: why there is any migration present, while I have not created a single one yet?

Its fine to not have it in the history, I was just wondering why it was removed. Its still needed for the mark action to work. Do you agree with the changes in this PR?

**Comment by samdark** [comment]
Changes are fine.

**Review by klimov-paul — APPROVED** [review]

**Pull request merged**
