### PR TITLE
Fix UniqueValidator for PostgreSQL

### PR DESCRIPTION
**Pull request by lav45**
Checks the uniqueness of keys in `jsonb` field.

This add-on allows you to use special characters `[[` , `]]` in the `targetAttribute` settings

```php
class News extends ActiveRecord
{
    public function rules()
    {
        return [
            [['title'], 'unique',
                'targetAttribute' => [
                    'title' => "[[data]]->>'title'",
                ]
            ],
        ];
    }
}
```

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by rugabarbo** [comment]
Maybe it makes sense to do this for all databases? Not only for PgSQL. MySQL supports JSON-fields too.

**Comment by lav45** [comment]
@requilence You mean move the test out of `yiiunit\framework\db\pgsql\UniqueValidatorTest::testPrepareParams()` => `yiiunit\framework\validators\UniqueValidatorTest::testPrepareParams()` ?
The implementation will work for all databases. Just an error was seen on Postgresql

**Comment by rugabarbo** [comment]
Now I understand. Thanks for the explanation.

**Review by cebe — APPROVED** [review]

**Review by samdark — APPROVED** [review]
@lav45 would you please add a line for changelog?

**Comment by lav45** [comment]
@samdark done)

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
