### PR TITLE
Add checks to yii\db\ActiveRelationTrait::mapVia()

### PR DESCRIPTION
**Pull request by mgrechanik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |  #19161

### CODE REVIEW

**Comment by mgrechanik** [comment]
#19161

**Comment by mgrechanik** [comment]
no tests are needed because nothing really changed

**Comment by bizley** [comment]
Well, no, you added a check to fix the bug so it tells us that this part was not covered by a test and that is why it's needed to add one.

**Comment by mgrechanik** [comment]
I do not really know how to reproduce a bug, too many yii magic involved.
It is just that current code is not safe code, which is obvious.

**Comment by samdark** [comment]
Well, then it's tricky. If we have no way to reproduce the bug then either it's not a bug or we cannot verify it's fixed. Either way, merging code that we can not verify it's good.

**Comment by mgrechanik** [comment]
When a function heavily depends on receiving second argument as array with certain keys (what we see in it's code) and core gives her  null instead is a bug of a core.
That core code  is too entricated alas for me to figure out why it gets null, all hint I could give you I gave.

**Pull request closed without merging**
