### PR TITLE
Fixed ErrorException xdebug trace

### PR DESCRIPTION
**Pull request by Izumi-kun**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Review by arzzen — APPROVED** [review]

**Comment by samdark** [comment]
Closing since use case was not clarified.

**Comment by samdark** [comment]
@arzzen you've approved it. Probably you know something about it?

**Comment by Izumi-kun** [comment]
1. Use xdebug
2. Try to handle php error
3. In exception trace array you wish to see place with error as you see it without xdebug

```
    public function appLogic()
    {
        0 / 0;
    }

    public function actionIndex()
    {
        try {
            $this->appLogic();
        } catch (Exception $e) {
            return $e->getTraceAsString();
        }
        return 'page';
    }
```

**Comment by samdark** [comment]
The fix is correct.

Initially we were handing fatals directly without first converting them to exceptions: https://github.com/yiisoft/yii2/commit/2d5db951. Because of that trace was different and we had to cut some items.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request closed without merging**
