### PR TITLE
允许在使用Url::to和Url::toRoute生成Url的时候指定urlManager。

### PR DESCRIPTION
**Pull request by cdcchen**
在使用Advanced Template 模板架构的时候会有很多应用，有时候会需要生成非当前应用的url，添加$urlManager参数可以很方便的达到此目的。

### CODE REVIEW

**Comment by samdark** [comment]
Can't apply the change in 2.0 for sure since it breaks backwards compatibility.

**Comment by samdark** [comment]
How about introducing a class var $urlManager that could be set manually?

**Comment by cebe** [comment]
> How about introducing a class var $urlManager that could be set manually?

:+1:

**Comment by githubjeka** [comment]
An update is required for the phpDoc.

**Comment by samdark** [comment]
@githubjeka we aren't going to do it the way proposed.

**Comment by vistart** [comment]
> How about introducing a class var $urlManager that could be set manually?

@samdark @cebe 
How about this:[MultiDomainsManager](https://github.com/vistart/yii2-models/blob/master/components/MultiDomainsManager.php)

The `$subDomains` property contains all url manager configuration array and its scheme.

**Comment by samdark** [comment]
@vistart it's good for that specific use case but since use case isn't common, we'll better introduce a way to solve it rather than provide a full featured solution.

**Comment by vistart** [comment]
@samdark 
Yeah, the [MultiDomainsManager] is designed for web application which has a common base domain, like `a.example.com` and `b.example.com` contain the base domain `example.com`, not suitable for variable domains.

**Pull request closed without merging**
