### PR TITLE
[WiP] Add test coverage of yii\helpers\BaseConsole

### PR DESCRIPTION
**Pull request by ilyar**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | up
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Seems it's not possible to test progress part it in its current state. I think we need to add an ability to set a stream to write to first.

**Comment by ilyar** [comment]
надо что-то поправить?

**Comment by ilyar** [comment]
@samdark надо что-то поправить?

**Comment by samdark** [comment]
Нет. Пройдёт тест в travis — замёржу.

**Pull request merged**
