### PR TITLE
PHP 8.1 trim(): Passing null to parameter #1 ($string) of type string is deprecated

### PR DESCRIPTION
**Pull request by uaoleg**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by rob006** [comment]
Why would you pass `null` to `groupBy()`?

**Comment by uaoleg** [comment]
> Why would you pass `null` to `groupBy()`?

To clear GROUP BY

**Comment by terabytesoftw** [comment]
Please update branch,

Thks.

**Comment by bizley** [comment]
Please add a changelog, thanks.

**Comment by uaoleg** [comment]
@bizley done

**Comment by bizley** [comment]
Cheers

**Pull request merged**
