### PR TITLE
StringHelper fixes

### PR DESCRIPTION
**Pull request by alex-code**
Fixes issues with spaces in `truncateHtml` https://github.com/yiisoft/yii2/issues/12495
Includes new tests.

### CODE REVIEW

**Review by SilverFire — COMMENTED** [review]
:+1:

**Review by SilverFire — APPROVED** [review]
Fine

**Review by samdark — APPROVED** [review]

**Review by SilverFire — CHANGES_REQUESTED** [review]
Add a note to the CHANGELOG plese

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
Thank you!

**Pull request merged**
