### PR TITLE
ActiveRelationTrait: strictly checking attributes, update related PHPDoc's

### PR DESCRIPTION
**Pull request by WinterSilence**
- Adds  and integrate inner method `isModelAttribute()` to strict checking attributes to stop undocumented using any public/magic properties(via getter) as AR attributes.
- Extends related PHPDoc's,

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | 

Blocking undocumented using is BC or not? semi...

### CODE REVIEW

**Comment by samdark** [comment]
Overall it looks like a good idea but I wonder if this undocumented way of using it is used a lot...

**Comment by samdark** [comment]
@rob006, @yiisoft/reviewers are you aware of any such usage?

**Comment by rob006** [comment]
What is actually fixed by this change?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/19231

**Comment by rob006** [comment]
I don't see how this PR could fix anything in terms of #19231. If this changes anything, it would rather create more issues like #19231.

Also, form my experience on StackOverflow, it is not that rare situation where people creates relations like https://github.com/yiisoft/yii2/issues/19231. And while they have limitations, they could be useful in many cases.

**Comment by WinterSilence** [comment]
@rob006 this PR block using any model's properties as attributes, because AR declare attributes as table columns in documentation. This PR **not** block relations this as #19231, but user must do it correctly. We must separate attribute/column magic properties and other public/magic(via getter) properties. You can't use `joinWith` with "virtual" attribute (as @samdark called this property) in any case, my PR does not change anything in this case.

**Comment by WinterSilence** [comment]
@rob006
> I don't see how this PR could fix anything in terms of #19231

I'm not declare PR as fix #19231

**Comment by WinterSilence** [comment]
@samdark Please, stop give answers instead me. I **didn't** tell you this PR fixes #19231, I'm told you they **related**.

**Comment by rob006** [comment]
You still did not explained what is fixed by this change. From my understanding, people are using this kind of relations, and last release has regression that broke this use case. So instead of fixing regression you're legitimizing BC break, by adding explicit and redundant (?) check?

**Comment by WinterSilence** [comment]
@rob006 

> Adds and integrate inner method isModelAttribute() to strict checking attributes to stop undocumented using any public/magic properties(via getter) as AR attributes.

PR is explained. I'm add tool/method for strict checking model attributes in ActiveRelationTrait and integrate in his methods, but maybe this not integration fully - I'm don't checked **all** `yii\db` classes (it's so long to check alone).

**Comment by WinterSilence** [comment]
@rob006 
> people are using this kind of relations

Where declared "you can use any public/magic property as attribute"?

**Comment by WinterSilence** [comment]
@samdark @rob006 where declared that you can use any model property as attribute? and than what's role of `*Attribute` methods?

**Comment by samdark** [comment]
1. Docs aren't specifications. If something isn't documented it does not necessarily mean it should not work. It may mean that docs aren't correct.
2. Even if the current behavior is not entirely correct as in this case, we should take existing usage into account and, based on issues created, we can see there are at least some usages like that.

**Comment by samdark** [comment]
By issue number I've meant context and https://github.com/yiisoft/yii2/issues/19231#issuecomment-1039972819 this comment.

**Comment by Krakozaber** [comment]
In reality, I agree with @WinterSilence, such use is incorrect because it is applicable only with an artificially defined attribute and we will remove such use on the project. But keeping compatibility for others would be nice.

**Comment by bizley** [comment]
Yes, let's keep it instead of removing that possibility. We are not a government.

**Comment by WinterSilence** [comment]
@bizley yes, "we" are monarchy.
@samdark @bizley if you want keep it, then add something like this inside methods:
~~~php
if (YII_DEBUG) {
    Yii::info('{method}: Using invalid attribute, please replace in your code {fix}', ['method' => __METHOD__, 'fix' => '...']);
}
~~~

**Comment by samdark** [comment]
Closing since this behavior is already used in multiple projects and it's not a great idea to break BC in this case.

**Pull request closed without merging**
