### PR TITLE
Prevent null $result leading to unsupported + operand

### PR DESCRIPTION
**Pull request by joelataccelm**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by bizley** [comment]
`$result` should be an array or false all the time. Could you provide a case where it isn't?

**Comment by joelataccelm** [comment]
> `$result` should be an array or false all the time. Could you provide a case where it isn't?

If you return nothing from a `UrlRuleInterface->parseRequest()` method the $result is null

**Comment by bizley** [comment]
Yes, but signature of `UrlRuleInterface::parseRequest()` states it should return `array|bool` (`array|false` to be more precised).

**Comment by joelataccelm** [comment]
> Yes, but signature of `UrlRuleInterface::parseRequest()` states it should return `array|bool` (`array|false` to be more precised).

defensive programming is a good thing

**Comment by bizley** [comment]
True. Please add unit test for that.

**Comment by rob006** [comment]
> defensive programming is a good thing

It may hide errors. Like in this case. `UrlManager` has [`$result !== false`](https://github.com/yiisoft/yii2/blob/ea60fba0aea97beade39c108568cb27a5b70aba7/framework/web/UrlManager.php#L333-L335) check and returns result if it passes. It means that if you forget to return `false` in your rule, `UrlManager` will return `null` for this rule and ignore all further rules. After patch form this PR, it will be a nightmare to debug this, because `UrlManager` will ignore some rules without any warning, event if they're perfectly fine.

**Comment by samdark** [comment]
Defensive programming is about assertions and throwing exceptions, not about if-s and continuing execution with invalid data.

We may do `if (!is_array($result)) { throw` there but I'm not sure it will fix your issue.

**Comment by bizley** [comment]
I don't believe OP has an issue at all, it was probably just a matter of noticing it in the code. Closing.

**Pull request closed without merging**
