### PR TITLE
Allow `$options['uncheck'] => false` in `activeRadio`,  `activeCheckbox`

### PR DESCRIPTION
**Pull request by alex-code**
There's no way to remove the hidden input when using `activeRadio` and `activeCheckbox`.
This PR allows you to specify `['uncheck' => false]` to not render the hidden input.

### CODE REVIEW

**Comment by cebe** [comment]
from the docs: 

> If you do not want any hidden input, you should explicitly set this option as null.

doesn't that work?

**Comment by Alex-Code** [comment]
That would produce an empty hidden field.

If `unchecked` isn't specified the `active` functions add it to the options.
The `checkbox` and `radioButton` functions just check for the existence of `unchecked` not its value.

**Comment by Alex-Code** [comment]
@cebe I've done some unit tests for this now but as `BaseHtml` has changed should I do a new PR?

**Comment by samdark** [comment]
@Alex-Code would be easier to review, yes.

**Pull request closed without merging**
