### PR TITLE
Added ability to disable transliteration in Inflector::slug

### PR DESCRIPTION
**Pull request by gevorgmansuryan**
In some cases needed disable transliteration for non english characters. Changed preg_replace to support non english characters if transliteration is disabled, and strtolower to mb_strtolower.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by samdark** [comment]
Which cases are that?

**Comment by gevorgmansuryan** [comment]
@samdark for example needed keep original language in uri (based on project specs) for example in multilang apps and not specify language in uri.
For example:
en: `/news/simple-article`
ru: `/новости/простая-статья` instead of `/новости/prostaya-statya`

**Comment by gevorgmansuryan** [comment]
Also it will increase chances of page match in Search Engines, coz they take a look at uri also.

**Comment by samdark** [comment]
OK. Then enhancement makes sense. Will be merged in 3.x.

**Comment by samdark** [comment]
https://github.com/yiisoft/inflector/issues/2

**Pull request closed without merging**
