### PR TITLE
Show sub commands on top view.

### PR DESCRIPTION
**Pull request by callmez**
Related https://github.com/yiisoft/yii2/issues/6841#issuecomment-76645840

The result like:

``` console
$ php yii
This is Yii version 2.0.4-dev.

The following commands are available:

- asset                Allows you to combine and compress your JavaScript and CSS files.
  asset/compress       Combines and compresses the asset files according to the given configuration.
  asset/template       Creates template of configuration file for [[actionCompress]].

- cache                Allows you to flush cache.
  cache/flush          Flushes given cache components.
  cache/flush-all      Flushes all caches registered in the system.
  cache/flush-schema   Clears DB schema cache for a given connection component.
  cache/index          Lists the caches that can be flushed.

- fixture              Manages fixture data loading and unloading.
  fixture/load         Loads the specified fixture data.
  fixture/unload       Unloads the specified fixtures.

- gii                  This is the command line version of Gii - a code generator.
  gii/controller       Controller Generator
  gii/crud             CRUD Generator
  gii/extension        Extension Generator
  gii/form             Form Generator
  gii/index
  gii/model            Model Generator
  gii/module           Module Generator

- help                 Provides help information about console commands.
  help/index           Displays available commands or the detailed information

- message              Extracts messages to be translated from source files.
  message/config       Creates a configuration file for the "extract" command.
  message/extract      Extracts messages to be translated from source code.

- migrate              Manages application migrations.
  migrate/create       Creates a new migration.
  migrate/down         Downgrades the application by reverting old migrations.
  migrate/history      Displays the migration history.
  migrate/mark         Modifies the migration history to the specified version.
  migrate/new          Displays the un-applied new migrations.
  migrate/redo         Redoes the last few migrations.
  migrate/to           Upgrades or downgrades till the specified version.
  migrate/up           Upgrades the application by applying new migrations.


To see the help of each command, enter:

  yii help <command-name>

```

### CODE REVIEW

**Comment by samdark** [comment]
How about 2 extra spaces before sub-commands?

```
$ php yii
This is Yii version 2.0.4-dev.

The following commands are available:

- asset                Allows you to combine and compress your JavaScript and CSS files.
    asset/compress       Combines and compresses the asset files according to the given configuration.
    asset/template       Creates template of configuration file for [[actionCompress]].

- cache                Allows you to flush cache.
    cache/flush          Flushes given cache components.
    cache/flush-all      Flushes all caches registered in the system.
    cache/flush-schema   Clears DB schema cache for a given connection component.
    cache/index          Lists the caches that can be flushed.
```

**Comment by callmez** [comment]
@samdark done!

**Comment by qiangxue** [comment]
What about the default sub-command display?

**Comment by qiangxue** [comment]
Another problem is that this display totally drops the summary display of each command class. This is a big con for me.

**Comment by samdark** [comment]
?

**Comment by cebe** [comment]
should be done, the default subcommand should be highlighted.

**Comment by callmez** [comment]
ok, done!
```console
This is Yii version 2.0.4-dev.

The following commands are available:

- asset                         Allows you to combine and compress your JavaScript and CSS files.
    asset/compress (default)    Combines and compresses the asset files according to the given configuration.
    asset/template              Creates template of configuration file for [[actionCompress]].

- cache                         Allows you to flush cache.
    cache/flush                 Flushes given cache components.
    cache/flush-all             Flushes all caches registered in the system.
    cache/flush-schema          Clears DB schema cache for a given connection component.
    cache/index (default)       Lists the caches that can be flushed.

- fixture                       Manages fixture data loading and unloading.
    fixture/load (default)      Loads the specified fixture data.
    fixture/unload              Unloads the specified fixtures.

- gii                           This is the command line version of Gii - a code generator.
    gii/controller              Controller Generator
    gii/crud                    CRUD Generator
    gii/extension               Extension Generator
    gii/form                    Form Generator
    gii/index (default)
    gii/model                   Model Generator
    gii/module                  Module Generator

- help                          Provides help information about console commands.
    help/index (default)        Displays available commands or the detailed information

- message                       Extracts messages to be translated from source files.
    message/config              Creates a configuration file for the "extract" command.
    message/extract (default)   Extracts messages to be translated from source code.

- migrate                       Manages application migrations.
    migrate/create              Creates a new migration.
    migrate/down                Downgrades the application by reverting old migrations.
    migrate/history             Displays the migration history.
    migrate/mark                Modifies the migration history to the specified version.
    migrate/new                 Displays the un-applied new migrations.
    migrate/redo                Redoes the last few migrations.
    migrate/to                  Upgrades or downgrades till the specified version.
    migrate/up (default)        Upgrades the application by applying new migrations.


To see the help of each command, enter:

  yii help <command-name>
```

**Comment by samdark** [comment]
Thanks!

**Pull request closed without merging**
