### PR TITLE
Minor Doc update

### PR DESCRIPTION
**Pull request by SOHELAHMED7**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | -
| Fixed issues  | -

### CODE REVIEW

**Comment by machour** [comment]
Hi @SOHELAHMED7,

What are the changes you meant to provide in this PR ? Just the one in `framework/web/HeaderCollection.php` ?

**Comment by SOHELAHMED7** [comment]
Yes that one only @machour

**Comment by machour** [comment]
It might be simpler to close this PR, and edit the file at https://github.com/yiisoft/yii2/blob/master/framework/web/HeaderCollection.php (using the pencil icon). GitHub will open a new PR for you which will be easier to review for the team.

**Comment by samdark** [comment]
Closing since this PR can't be merged as is. @SOHELAHMED7 please open another one. Thanks.

**Pull request closed without merging**
