### PR TITLE
Use the ActiveQuery syntax for examples in doc

### PR DESCRIPTION
**Pull request by Faryshta**

### CODE REVIEW

**Comment by SilverFire** [comment]
Looks good

**Comment by samdark** [comment]
It's OK but `{{table}}` syntax becomes kinda hidden. It's not easy to figure out you can do it.

**Comment by Faryshta** [comment]
Maybe for that we would need a different section, I think thats more for the ´ActiveQuery´ class than ´ActiveRecord´

**Comment by samdark** [comment]
Overall I don't think it should be merged as is.

**Comment by Faryshta** [comment]
at least we should change lines like

```
 'COUNT({{order}}.id) AS ordersCount'
// to
'ordersCount' => 'COUNT({{order}}.id)'
```

**Comment by Faryshta** [comment]
@samdark what do you say about changing the alias usage on the select?

**Comment by samdark** [comment]
I see no profit in changing it.

**Comment by Faryshta** [comment]
its more adhoc with the documentation and the way its adviced to write the alias in yii2.

**Comment by samdark** [comment]
Where is it advised to write alias like that?

**Pull request closed without merging**
