### PR TITLE
docs/guide/input-forms.md - minor improvements [ci skip]

### PR DESCRIPTION
**Pull request by softark**

### CODE REVIEW

**Comment by samdark** [comment]
Good changes. Thanks!

**Comment by softark** [comment]
@cebe has a deepest stack in his brain to compose and/or comprehend a long and complex statement, but I don't (grin)

**Comment by samdark** [comment]
I tend to do it as well. I guess that's because of our native languages.

**Comment by softark** [comment]
I agree.
Because the Japanese language doesn't have **relative pronouns**, all the qualifying sub-statements must be put just before the word to be qualified. And what's worse, the Japanese grammatical order must be "S + O + V" instead of "S + V + O". So the simple word-to-word translation could sometimes result in a very long and complicated modifier between S and O, which requires a very deep stack to push/pop the pending elements to comprehend the whole statement. I sometimes have to divide a long sentence into several ones in order to make the translation more acceptable to the Japanese readers.

**Comment by cebe** [comment]
Yeah, germans are cazy with long sentences, there are books where a sentence is one page long :)
(thats of course only those who make fun of the fact that it is possible ;) )

**Pull request merged**
