### PR TITLE
Add HTML::tel() helper

### PR DESCRIPTION
**Pull request by CyberPunkCodes**
Pull request for adding `HTML::tel()` helper function. Feel free to make any recommendations/fixes and I will update this pull.

@samdark  

| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #9079 , #8075 |

### CODE REVIEW

**Comment by pstddc** [comment]
https://github.com/yiisoft/yii2/issues/1022

**Comment by pstddc** [comment]
https://github.com/yiisoft/yii2/issues/169

**Comment by WadeShuler** [comment]
Are you referencing them for letting others now we have re-opened the issue? Or are you trying to agree with them and these should not be added?

No disrespect, but I believe that it should, and many other members do too. Even kartrik-v and others who have contributed to the community, think so.

If we have one for mail to, we should have one for tel!

**Comment by samdark** [comment]
How about https://github.com/yiisoft/yii2/issues/8075#issuecomment-92920262?

**Comment by WadeShuler** [comment]
It takes care of all his cases, except the half-width char. It removes all spaces and extra chars (dashes, dots). It only accepts a `+` sign at the beginning and 0-9 digits. So by passing any phone number through it, it should generate a useable `tel` link. If I recall, it should work with skype, chrome, safari, firefox, on your mac, on your phone.. 

I don't know much about the half-width chars. Should we accommodate for it in the framework? I am open to suggestions and I will update the code.

**Comment by samdark** [comment]
Yes, half-width characters should be handled somehow as well...

**Comment by samdark** [comment]
That's why it's not there yet...

**Comment by WadeShuler** [comment]
I just tested this, with my normal phone and it works for me.

**Comment by samdark** [comment]
Good. Now we need some unit tests and a line for changelog.

**Comment by SilverFire** [comment]
@WadeShuler would you like to continue work in this PR?

**Comment by WadeShuler** [comment]
Yes I just never got back to making a unit test

**Comment by SilverFire** [comment]
Then could you like to add a unit test to this PR to get it merged?

**Comment by SilverFire** [comment]
I've thought better about this case and decided that all this char converting and normalization should be done *before* saving data, rather than on output. 

Kicking out 

```php
$phone = mb_convert_kana($phone, 'a', 'UTF-8');
$phone = preg_replace('~[^+0-9]+~', '', $phone);
```

these lines make method useless.

**Comment by SilverFire** [comment]
Thank you for your effort, but IMO we should not accept this PR to the `HtmlHelper`

**Comment by rob006** [comment]
@SilverFire 

There is lots of nuances on this matter (see https://github.com/yiisoft/yii2/issues/8075#issuecomment-92920262) such helper will be much more useful than `mailto()` (which is in the core).

**Comment by SilverFire** [comment]
Thank you, I've seen it. Case 2 looks the most correct (am I right?) and the most normalized simultaneously. My point is that as we should just normalize phone to digits only, there will no work left for `Html::tel()` method.

**Comment by rob006** [comment]
> Case 2 looks the most correct (am I right?)

You need ask? If so, this means that this is not obvious how such link should look like and such helper could save lots of hours on searching "why my tel links does not work correct on browser X on system Y". I can't say the same about `mailto()` although it is in core.

**Comment by WadeShuler** [comment]
It should remove everything except for numbers. I kept the + sign in front, because it is for international numbers.

**Comment by SilverFire** [comment]
> You need ask? If so, this means that this is not obvious how such link should look like

For me is obvious that phone must be normalized to digits only. Otherwise you will have 1001 different forms of phone format in your DB and it will blow up your mind in one moment.

> why my tel links does not work correct on browser X on system Y

You will find many interesting things in this case. For example [this](http://stackoverflow.com/questions/27164715/tel-href-click-to-call-link-not-working-in-android), [this](https://bugs.chromium.org/p/chromium/issues/detail?id=364522) and most probably [this](http://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari). However, there is even more advanced and SEO-friendly way, like [this](http://microformats.org/wiki/hcard).

I don't want to encourage developers to store mobile phones without normalization so IMO this helper should not be included in core.

**Comment by rob006** [comment]
> For me is obvious that phone must be normalized to digits only.

And it was obvious for you, that you should convert full-width digits to half-width version?

> I don't want to encourage developers to store mobile phones without normalization

Why? This is developer decision how he want store this data. In some cases keeping formating of user input is a feature without any drawback.

Anyway, if you expect that phone numbers should be normalized before saving to database, there should be validator for this.

**Comment by samdark** [comment]
Yes. Anyway, the pull request can't be merged without tests. @WadeShuler if you'll add tests, feel free to ping us to reopen it. Thanks!

**Comment by WadeShuler** [comment]
This has nothing to do with normalization. This is to generate an HTML link to "tel". This is exactly like "mailto". You can write/store emails in incorrect ways. You can enter "MYEMAIL@MAIL.COM", but should convert and store it as lowercase in the db.

When storing phone numbers, you should normalize them so all your data in the db is the same.

However, this feature has nothing to do with any of that. If we have a mailto function, we should have a tel one. Your always going to have people who don't know what the hell they are doing. You can't hold back on things just because of the small percent of people who can't read the docs or follow standards.

**Comment by SilverFire** [comment]
> You can't hold back on things just because of the small percent of people who can't read the docs or follow standards

:+1: 

> This has nothing to do with normalization. This is to generate an HTML link to "tel".

```php
        $phone = mb_convert_kana($phone, 'a', 'UTF-8'); // normalization
        $phone = preg_replace('~[^+0-9]+~', '', $phone); // normalization

        // does not makes much sense without normalization
        // because you can simply call just call Html::a('tel:' . $phone, $phone)
        $options['href'] = 'tel:' . $phone; 
        return static::tag('a', $text, $options);
```

So all this method is about normalization (which should be done before saving IMO) and adding `tel:` (which could be added manually with no drawbacks).

**Comment by WadeShuler** [comment]
That is not why we want this function.

Your exact same argument can be used to justify removing "mailto" from Yii2. People can write "mailto:" in the link tag just the same.

**Comment by SilverFire** [comment]
And I'd remove it, but it will break BC

**Comment by rob006** [comment]
@SilverFire You probably could remove half of methods from `Html` helper - most of them are only shortcuts for 1-2 lines of code...

**Comment by samdark** [comment]
I disagree about removing these ones and even about not including `tel:` but I agree that it's tricky because of normalization and that it's not a good idea to accept pull request without tests.

**Comment by SilverFire** [comment]
@WadeShuler, @rob006 thank you for discussing this PR and sharing your opinion.

I've said all I wanted to say on this matter. Let the majority of @yiisoft/core-developers decide about necessity of `Html::tel()` helper with built-in normalization.

**Pull request closed without merging**
