### PR TITLE
Fix #2146: Active Record scopes

### LINKED ISSUE #2146: ActiveRelation: support custom Scopes
`$this->hasOne(Report::className(), ['fk_goal' => 'id'])->myScope()->one();`
have exception
`Calling unknown method: yii\db\ActiveRelation::myScope()`
I must to redeclare createActiveRelation ?

Now i solve i like:

```php
class Report extends ActiveRecord {

    public static function createQuery()
    {
        return new ReportQuery(['modelClass' => get_called_class()]);
    }

    public static function createActiveRelation($config = [])
    {
        return new ReportRelation($config);
    }

}

//scopes
trait ReportScopes
{
    public function myScope() {
        return $this;
    }
}

//apply scopes to query
class ReportQuery extends ActiveQuery
{
    use ReportScopes;
}

//apply scopes to relations
class ReportRelation extends ActiveRelation
{
    use ReportScopes;
}
```

### PR DESCRIPTION
**Pull request by klimov-paul**
Fix #2146: Added ability to declare scopes for `yii\db\ActiveQuery` as static methods of `yii\db\ActiveRecord`

### CODE REVIEW

**Comment by SamMousa** [comment]
I like the commit but if we use reflection shouldn't we also check the hinted type of the first parameter since it must be (a descendant of) ActiveQuery?

**Comment by SamMousa** [comment]
Also, I was wondering (I know this was in my example code as well) if we should return the result from the static scope method or just return the query object.

1. Objects are always passed by reference.
2. If we return the return value it could be:
A) Of a different type (not so bad since this will throw clear errors)
B) A different ActiveQuery object.

In case of B this could cause unexpected behavior but it also could add new power.

**Comment by klimov-paul** [comment]
> shouldn't we also check the hinted type of the first parameter since it must be (a descendant of) ActiveQuery?

Nope: such information may be missing. Developer may ommit type restriction and doc comments.

> we should return the result from the static scope method or just return the query object.

Need to check with original implementation. Perhaps returning of the query instance is better, allowing reducing the code inside the scope declaration method.

**Comment by SamMousa** [comment]
The doc comments don't need to be there. But the type restriction is not a weird requirement. It would also allow us to differentiate between scope and non-scope static methods.

**Comment by klimov-paul** [comment]
Just found original implementation:
https://github.com/yiisoft/yii2/blob/2.0.0-alpha/framework/yii/db/ActiveQueryTrait.php

**Pull request closed without merging**
