### PR TITLE
17268 fix formatter

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17268

### CODE REVIEW

**Comment by GHopperMSK** [comment]
We can use `number_format` - it gets both a number and a string and returns a number. So, all we need is single line of code in Formatter class:


```
    public function asCurrency($value, $currency = null, $options = [], $textOptions = [])
    {

        $value = number_format($value, 10);
...
```

**Comment by samdark** [comment]
@GHopperMSK the issue isn't in `asCurrency` only. It's decimals formatting overall.

**Comment by samdark** [comment]
Also `number_format` can not deal with huge numbers.

**Comment by GHopperMSK** [comment]
> Also `number_format` can not deal with huge numbers.

```
$ php -r "var_dump(number_format(1E-10, 100));"
string(102) "0.0000000001000000000000000036432197315497741579165547065599639608990401029586791992187500000000000000"
```

**Comment by samdark** [comment]
It cannot deal with input such as `87,654,321,098,765,440.0000000000`.

**Comment by GHopperMSK** [comment]
> It cannot deal with input such as `87,654,321,098,765,440.0000000000`.

I can't deal with such a number too )

**Comment by samdark** [comment]
Well, current implementation can and there are tests for it.

**Pull request merged**
