### PR TITLE
fix code style

### PR DESCRIPTION
**Pull request by unasoft**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14119

### CODE REVIEW

**Comment by cebe** [comment]
I am against this change, it makes code less readable and does not add any value.
When creating new class on the fly in parenthesis it is better to leave off constructor parenthesis if nothing is passed to the constructor.

**Comment by ejsoft** [comment]
I think it's better to stick to some kind of standard, or use the `new className ()` or `new className` construct, presently it's used so and so.

**Comment by rob006** [comment]
[PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) requires parenthesis.

**Comment by samdark** [comment]
I think it's better to accept the change.

**Comment by rob006** [comment]
BTW: In #14100 there is [fixer for this](https://github.com/yiisoft/yii2/pull/14100/commits/dddd5c50d67b5e0ac39a91753dcf0a6dfd1988f7) - it will not fix examples in phpdocs, but will force parenthesis in code.

**Comment by samdark** [comment]
Closing in favor of @rob006 pull request.

**Pull request closed without merging**
