### PR TITLE
Updated setActivePlaceholder to be consistent with activeLabel

### PR DESCRIPTION
**Pull request by edwards-sj**
Updated setActivePlaceholder to be consistent with activeLabel for when indexes are present in the attribute name

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15740

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Please add a line for changelog. Thanks.

**Comment by edwards-sj** [comment]
Should this be added to the existing 2.0.15 heading or is 2.0.14.1 needed?

**Comment by samdark** [comment]
Existing one would do. Will be used for 2.0.14.1.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
