### PR TITLE
Changed ActiveField __toString method to catch all php 7 error types.

### PR DESCRIPTION
**Pull request by diego-mathis**
When developing code, error message related to ActiveField are very obscure. The actual error is not shown. All what is given, is that __toString is not allowed to throw an error.

\Throwable is part of php 7+, so I left the \Exception in for older php.
According to 3v4l.org this seems to work.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   |  ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
@My6UoT9 do you have a good way to reproduce the issue this pull request is fixing?

**Comment by My6UoT9** [comment]
I tried to make a small example, but seems its not so easy. The code which had the issue, is complex, as it does extend ActiveForm and ActiveField - and I am not allowed to share that.
So far, all my simple tries to cause an error in the view or in some widget where handled correctly - and I saw a proper error msg, not sure how to make a proof of this problem. 
Will try again tomorrow.

As info in cakephp they made something smiliar, https://github.com/cakephp/cakephp/issues/9043

**Comment by My6UoT9** [comment]
Ok this is a total artificial test, but its shows that the error information is almost compeletely lost.
A CRUD which uses the ActiveField is required for this "test".

In the `public function render($content = null)` (`vendor/yiisoft/yii2/widgets/ActiveField.php`), add `throw \CompileError;` as first line in the function body. 
Then just load a page which uses ActiveField, 
You should get with (YII_DEBUG enabled) 
```
PHP Fatal Error – yii\base\ErrorException
Method yii\widgets\ActiveField::__toString() must not throw an exception, caught Error: Undefined constant 'CompileError'
...
...
...
```

Now if we add my PR, the error shows as:
```
PHP User Error – yii\base\ErrorException
Exception 'Error' with message 'Undefined constant 'CompileError''

in C:\laragon\www\fire\vendor\yiisoft\yii2\widgets\ActiveField.php:206
...
...
...
```

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
