### PR TITLE
Documentation: Clarified what a relation name is

### PR DESCRIPTION
**Pull request by winternet-studio**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? |  |
| Fixed issues |  |
| Documentation improvement | yes |

### CODE REVIEW

**Comment by samdark** [comment]
It looks a bit too verbose. @yiisoft/core-developers need your opinions.

**Comment by dynasource** [comment]
'If you can't explain it simply, you don't understand it well enough' (Albet Einstein)

**Comment by winternet-studio** [comment]
If you can abbreviate it while keeping it clear it's great. Otherwise I would say: is it better keep it short, or is it better to keep it understandable?? If it's not understandable what's the point of having text there at all?

It could also be a link to a page that explains Yii terms, eg. "relation name". The Definitive Guide doesn't even explain what the argument is comprised of - even though it talks about the link() methods.

**Comment by bizley** [comment]
I'm not sure if it's necessary here. And Guide [does explain the relation name](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#declaring-relations).

**Comment by winternet-studio** [comment]
Ah I see now, it was just far away from where I needed it! :) I spent quite a bit of time googling and trying to figure out what relation name was but failed. Maybe it was just my bad. But may I ask what the issue of making the documentation very clear is? That is what I LOVE about PHP documentation and why I think it has become so popular...

**Comment by cebe** [comment]
Imo it is fine to give an example in the place where it is needed. relation name itself is not defined explicitly anywhere so adding this makes sense to me. Added with different wording: 1433d8a Thanks!

**Pull request closed without merging**
