### PR TITLE
fix IIS Web site link

### LINKED ISSUE #18704: broken link
### What steps will reproduce the problem?
https://www.yiiframework.com/doc/guide/2.0/en/start-installation#iis-configuration

### Additional info
**How to set up your first IIS Web site** broken

### PR DESCRIPTION
**Pull request by Arhell**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Tests pass?   | ✔️/❌
| Fixed issues  | https://github.com/yiisoft/yii2/issues/18704

### CODE REVIEW

**Review by bizley — COMMENTED** [review]
This doesn't sound related. What about [that one](https://docs.microsoft.com/en-us/iis/application-frameworks/scenario-build-a-php-website-on-iis/configure-a-php-website-on-iis)?

**Comment by Arhell** [comment]
@bizley, I think not, this link is the 2nd item in the list

**Comment by bizley** [comment]
Oh, right. I've added the same one, lol, sorry. I can see that the original link was somehow different (at least the version of it at archive.org) but this might do. Is there a chance to fix this for other languages as well?

**Comment by Arhell** [comment]
> Oh, right. I've added the same one, lol, sorry. I can see that the original link was somehow different (at least the version of it at archive.org) but this might do. Is there a chance to fix this for other languages as well?

I looked before doing PR
This fix is only in the en version

**Comment by bizley** [comment]
Thanks.

**Pull request merged**
