### PR TITLE
Bug #16552: Cached relatation is not used in relation through `via`

### PR DESCRIPTION
**Pull request by drlibra**
Added check in `yii\db\ActiveQuery::prepare()` to prevent populating already populated relation when another relation is requested with `via`

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16552 

I am not sure that I made the sentence in the changelog right.

### CODE REVIEW

**Comment by samdark** [comment]
Seems there's something wrong with tests. Would you please try running these locally first?

**Comment by drlibra** [comment]
I see no difference in tests results. Maybe I execute wrong suite. Can you tell me what test is broken now?

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by samdark** [comment]
Well, it was broken and I haven't seen it because travis was hit with a MySQL bug and tests timed out :(

```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/13618

**Comment by drlibra** [comment]
This is strange because I ran the tests and there wasn't any changes. I'll check what is wrong today or tomorrow.

**Pull request merged**
