### PR TITLE
Update security-authorization.md

### PR DESCRIPTION
**Pull request by RomanBush**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | change deprecated function to actual

### CODE REVIEW

**Comment by samdark** [comment]
👍

**Comment by bizley** [comment]
Oh, sweet, I wasn't sure if we should keep the old way or not. May I update all the guides to `::class` then?

**Comment by samdark** [comment]
Yes, that's fine.

**Comment by My6UoT9** [comment]
So support for php 5.4 is dropped?
https://web.archive.org/web/20201205192011/https://www.php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name

**Comment by samdark** [comment]
Nope. We just encourage people to use 5.5+. Older projects will work as they are.

**Comment by My6UoT9** [comment]
Ah its just the guide!

**Pull request merged**
