### PR TITLE
Add support for "u" modifier for Regex validators

### PR DESCRIPTION
**Pull request by Dzhuneyt**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16974

### CODE REVIEW

**Comment by Dzhuneyt** [comment]
@samdark pushed unit test to cover the change.

**Review by samdark — APPROVED** [review]
Looks good. Need a line for changelog.

**Comment by Dzhuneyt** [comment]
@samdark changelog entry added.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
