### PR TITLE
PregReplace Action Filter

### PR DESCRIPTION
**Pull request by Faryshta**
Very simple class, you configure a set of regular expressions and their respective replacement and the content of a web page is replaced on the after action event.

### CODE REVIEW

**Comment by Faryshta** [comment]
If someone can help me explain how to use the `@see` attribute on phpDoc to link http://php.net/manual/en/function.preg-replace.php to this page I would be very thanksful

**Comment by samdark** [comment]
I don't think it's needed in the core framework. Use cases are extremely rare.

**Comment by Faryshta** [comment]
All the CMS's I know have a similar feature to minify their html output or do things like changing regular urls cor CDN urls.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/widgets/Spaceless.php

**Comment by Faryshta** [comment]
@lynicidn I think my approach is more general since it allows you to configure the regular expression and their replacement. WIth that wiget you get only one predefined regular expression. My usage example also removes html comments.

Also this code

```html
 <?php Spaceless::begin(); ?>
<h1>Hola Mundo</h1>
<p>Texto <b>bold</b> <i>Italic</i>
 <?php Spaceless::end(); ?>
```

Would read: Hola MundoTexto bolditalic

**Comment by cebe** [comment]
@Faryshta we could extend spaceless widget to remove comments.

**Comment by Faryshta** [comment]
@cebe sounds good. But how about a more direct approach?

On the example I provide on my PR you can configure the regular expressions to replace.

```php
[
    'class' => 'yii\filters\PregReplace',
    'rules' => [
        '/<\!--.*-->/Us' => '', //erase html comments
        '/\w+/s' => ' ', // multi whitespace to a single space
    ],
],
```

So is it possible to create a `RegExpReplace` widget that can configure the patterns and replacements?

```php
<? RegExpReplace::begin([
    '/<\!--.*-->/Us' => '', //erase html comments
    '/\w+/s' => ' ', // multi whitespace to a single space
   '/(<script)/' => '<blockquote', // turn scripts to blockquotes
   '/(</script>)/' => '</blockquote>',
]); ?>

<!-- jquery example -->
<script>
$(function () { alert ('hello world');});
</script>
<?php RegExpReplace::end(); ?>
```

will return

```html
<blockquote> $(function () {alert ('hello world');}); </blockquote>
```

In this case `Spaceless` would be a particular case of usage for a more general purpose.

**Comment by cebe** [comment]
thats maybe a bit too generic, I though about adding the comment stripping to Spaceless. Or are there other use cases? script to blockquote does not  really count :)

**Comment by Faryshta** [comment]
@cebe to add the comment stripping just use this regular expression '/<\!--.*-->/Us' I can make the commit if you want.

Maybe I don't get it. @samdark says it would rarely be used and @cebe says its too generic.

Other use cases. How about the ability to use CDN's?

http://www.cyberciti.biz/faq/wordpress-offloading-old-static-images-urls-to-cdn-urls/

'/scr="([\\w\/\]+)\.[(png)|(jpg)|(gif)|(js)|(css)]/'  => 'cdn.yiiframework.com/$1.$2'

**Comment by samdark** [comment]
@Faryshta I've meant it's not really wise to remove spaces and comments from HTML output since after enabling gzip it doesn't matter sizewise.

As for CDN, there are asset bundles for it.

**Comment by Faryshta** [comment]
@samdark wouldn't that be an argument to remove the `Spaceless` widget?

**Comment by samdark** [comment]
Well, no. Spaceless phpdoc states the following:

```
This method is not designed for content compression (you should use `gzip` output compression to
achieve it). Main intention is to strip out extra whitespace characters between HTML tags in order
to avoid browser rendering quirks in some circumstances (e.g. newlines between inline-block elements).
```

But personally I'd remove it since browser issues from extra spaces are things from old IEs past.

**Comment by samdark** [comment]
Too bad some corporations still have thousands instnaces of IE6 used.

**Comment by Faryshta** [comment]
For SEO one of the common practives is to 'minify' the html removing extra whitespaces, comments, optional tags, optional attributes and after that use gzip. If you are using a cache system (like `yii\filter\PageCache` ) then it will get executed less often and the cache will be smaller so its a win-win.

As for IE. Which browsers is Yii2 supposed to support? Because bootstraps 3 doesn't fully suppport IE 8 http://getbootstrap.com/getting-started/#support

**Comment by cebe** [comment]
> Which browsers is Yii2 supposed to support?

Yii2 is not a frontend framework so its browser support depends on what you put in front of it.

**Comment by samdark** [comment]
@Faryshta are you sure it helps for SEO? I doubt it. Also preg-replace on the whole page is generally not a CPU and memory-friendly operation.

**Comment by Faryshta** [comment]
@samdark Yes I am sure, I have to work with Joomla too for marketing campaigns and almost every SEO plugin has something like that.

I have found similar plugins for  wordpress, drupal, magento and the `SpaceLess` widget here in yii2.

> Also preg-replace on the whole page is generally not a CPU and memory-friendly operation.

I know, thats why when you do it you make sure to use other things like PageCache and the 'last-modified' http header

But I think thats not the point is it?

**Comment by samdark** [comment]
@Faryshta Joomla has it because it's often deployed at cheapest hosts possible where gzip is turned off and can't be turned on. In this case it makes sense to "compress" page using such method because of Google's pagespeed score ranking factor. If gzip is used, there's no gain doing such "compression".

Again `SpaceLess` was introduced not for compression or SEO reasons.

**Comment by Faryshta** [comment]
@samdark I don't think thats a good argument to deny the usability of this feature. It just mean it works better on cheap servers.

**Comment by samdark** [comment]
Probably. Anyway, personally I think it doesn't belong to core framework. You can distribute it as extension though.

**Comment by dynasource** [comment]
Agree. Its resource intensive and rarely required. Both two arguments not to put in core imho

**Pull request closed without merging**
