### PR TITLE
Saving AR without values / calling Command::insert without columns

### LINKED ISSUE #7374: Inserting new ActiveRecord attempts to set primary key to NULL
When inserting a new ActiveRecord corresponding to a database table consisting only of one autoincremening primary key column, it attemps to set the primary key to NULL. This causes issues in postgresql. It should instead insert a row of DEFAULT VALUES.

### PR DESCRIPTION
**Pull request by nineinchnick**
When `Command::insert` is called without any column values defaults are used. Resolves #7374.

This PR should wait for #8030 to be accepted to make `QueryBuilder::insert()` easier to overload.

### CODE REVIEW

**Comment by nineinchnick** [comment]
This is ready for adoption, any comments?

**Comment by samdark** [comment]
@nineinchnick is it adjusted to deal with the fact that #8030 wasn't merged and alternative implementation was?

**Comment by samdark** [comment]
Changelog is missing.

**Comment by samdark** [comment]
Also I think this one fixes something...

**Comment by nineinchnick** [comment]
@samdark yes, I think I've updated it after #8030 has been resolved.

**Comment by samdark** [comment]
#7374

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
