### PR TITLE
use /dev/random in not linux systems

### PR DESCRIPTION
**Pull request by vlad-khramov**
#11111

### CODE REVIEW

**Comment by SilverFire** [comment]
:+1: 

@tom-- @yiisoft/core-developers

**Comment by tom--** [comment]
This looks very good.

**Comment by tom--** [comment]
On second thoughts (sorry) I think the branching logic should be a bit different. The purpose of the `$_randomSource` property is to "cache" the branch decision for the next call (and all subsequent calls) to `generateRandomKey()`. So if, on the second call, we don't test `$_randomSource` *first* and immediately use the cached value then the property isn't doing any useful work for us--in fact setting and checking it is just added complexity.

**Comment by tom--** [comment]
Let's take this opportunity to consider the design.

The only argument *pro* `$_randomSource` (i.e. "caching" the branch decision for subsequent calls) is performance when the application makes multiple calls during the life of one instance of the Security component.

The *contra* arguments are

1. it makes performance a little worse when the app makes only one call
2. it adds complexity

The performance argument is not really persuasive one way or the other given that the Yii framework supports many kinds of apps and processing. It's an optimization that helps in some use cases.

Otoh, code complexity is never desirable. Get rid of this optimization and the method simplifies considerably.

**Comment by samdark** [comment]
Unlike password hashing, random numbers may be used in performance-critical app parts. I think `$_randomSource` makes sense in this case.

**Comment by quantum13** [comment]
>I think the branching logic should be a bit different

Yes, I understand it. But overhead in my code is only of two conditions and two variables assignment before checking _randomSource

In another way it could be done like this https://github.com/quantum13/yii2/commit/4ee2f474ed5b77477e16138e7488bd691aa9a8d2 , but I thought, that three almost identical ternary operators is uglier than pre assignment.

And, I think, full copypaste of this branch with condition about Linux and replacing urandom to random isn't good choice.

**Comment by samdark** [comment]
Closed in favor of https://github.com/yiisoft/yii2/issues/11146

**Pull request closed without merging**
