### PR TITLE
Guide PL

### PR DESCRIPTION
**Pull request by bizley**
README updated with current links.
Start Installation updated with fixed configuration.
Full names added in translators.json (@Yupik is ok with it).

### CODE REVIEW

**Comment by cebe** [comment]
@bizley your branch has conflicts, can you rebase on master and squash the commits?

**Comment by cebe** [comment]
could you also provide a [blocktypes.json](https://github.com/yiisoft/yii2/blob/master/docs/documentation_style_guide.md#blocks) file for the polish guide?

**Comment by bizley** [comment]
@cebe it was ok when PRed, probably conflict with #12273 
Maybe just close it, I will remove guide-pl branch because it's pain to keep it up-do-date and will go for more direct approach. I will send another PR.
With blocktypes.json as well.

**Comment by cebe** [comment]
ok, thanks!

**Pull request closed without merging**
