### PR TITLE
Update schema-mysql.sql

### PR DESCRIPTION
**Pull request by auerswald**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| Fixed issues  | #17975

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Please add a line for changelog. Thanks.

**Comment by auerswald** [comment]
how and where? i am not so familiar with github 😎

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md this one. Just edit/push it to the same branch.

**Comment by rob006** [comment]
What about migration and schemes for other DBMS?
Why `ON UPDATE RESTRICT`? Shouldn't we use `CASCADE` everywhere?

**Comment by auerswald** [comment]
> What about migration and schemes for other DBMS?

these files are partly also wrong. I have only tested it with mysql.
but that should be taken care of by someone who knows more about it.

> Why `ON UPDATE RESTRICT`? Shouldn't we use `CASCADE` everywhere?

"ON UPDATE" and "ON DELETE" refers to the _id_ of the table _message_source_. it is not intended that this _id_ is changed in the program. but if a record in the table _message_source_ is to be deleted, all entries in the translation table _message_ should also be **optionally** deleted.

this happens if the property _'removeUnused'_ in the message-config is _true_ or the console parameter _'-r'_ or _'--remove-unused'_ is used.

btw... **the migration script creates the tables correctly.** the error occurs only if you have created the messages tables manually using the sql files (this is mentioned in the api documentation).

**Review by cebe — APPROVED** [review]

**Comment by cebe** [comment]
> What about migration and schemes for other DBMS?

made the change here: https://github.com/yiisoft/yii2/pull/17978

**Comment by samdark** [comment]
Merged in https://github.com/yiisoft/yii2/commit/d07cbdaab3e467d1a8875249d17db04af8e79864. Thanks!

**Pull request closed without merging**
