### PR TITLE
New method for creating the tel links

### PR DESCRIPTION
**Pull request by palexandrite**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by rob006** [comment]
Related: https://github.com/yiisoft/yii2/issues/8075#issuecomment-92920262

**Comment by samdark** [comment]
First of all, thanks for contributing. But as @rob006 mentioned, adding `tel` was already considered and final decision was not having it.

**Comment by rob006** [comment]
Just to be clear - IMO this helper should be added, but there is more things to address than simple generating `a` tag with `tel:` prefix.

**Comment by samdark** [comment]
@rob006 seen @SilverFire comments?

**Comment by rob006** [comment]
@samdark Yes, and I completely disagree with him.

**Comment by samdark** [comment]
I see. Anyway, this pull request can't be merged in its current form.

**Comment by shoomlix** [comment]
> Just to be clear - IMO this helper should be added, but there is more things to address than simple generating `a` tag with `tel:` prefix.

Could you please to explain that abbreviation IMO?

**Comment by samdark** [comment]
IMO = In My humble Opinion

**Comment by shoomlix** [comment]
> In My humble Opinion

samdark, thank you very much for explaining.

**Pull request closed without merging**
