### PR TITLE
enhanced BaseListView summary display with no result

### PR DESCRIPTION
**Pull request by taobig**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | yes |
| Tests pass? | yes |
| Fixed issues | comma-separated list of tickets # fixed by the PR, if any |

if the dataProvider has no result, the summary div will be hidden. the outer list view div will move up.

### CODE REVIEW

**Comment by cebe** [comment]
this text is already provided by the `$emptyText` property. With your change the text would appear twice.

**Comment by taobig** [comment]
the $emptyText is not effective on summary div

**Comment by cebe** [comment]
and it should not as the text is already displayed below the summary, why do you want to display it twice?

**Comment by taobig** [comment]
As we konw, the summary-div is above of list-view div. If the dataProvider has no result, the summary-div will be hidden. the list-view div will up to the position of summary-div. To avoid going up, we can fill in the several words in the summary-div.

**Pull request closed without merging**
