### PR TITLE
avoid use common class like another code

### PR DESCRIPTION
**Pull request by bscheshirwork**
Like 
https://github.com/yiisoft/yii2/blob/0ee17dcb7d763b00819ad764a60e8d582f62f662/framework/base/ArrayAccessTrait.php#L23-L32

Same style is better.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
?

**Comment by bscheshirwork** [comment]
This minor changes
- for equal code
- use global class with \ (1 times new 2 times PHPDoc)

**Comment by bscheshirwork** [comment]
So.. yii2-core-team 
what is the official position
of standard class?
```
use ArrayIterator;
```
or
```
\ArrayIterator
```

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by cebe** [comment]
why not add it in `use`?

**Comment by rob006** [comment]
I'm also for leaving it in `use` block.

**Comment by samdark** [comment]
Using root namespace IMO is better in this case since it hints that it's built-in class.

**Comment by rob006** [comment]
See https://youtrack.jetbrains.com/issue/WI-26767#comment=27-944565

**Comment by samdark** [comment]
Yes. It's about preferences... If you have a strong opinion about it, let's create a vote issue and, when it's done, fix decision in the code style.

**Comment by rob006** [comment]
In my projects I always import everything. It is easier to automate, more DRY and  summary with list of used classes can be really useful. So yes, I have a strong opinion on this, but not strong enough to force this on every project I contribute to. :D

**Pull request merged**
