### PR TITLE
Add test for issue #14663

### PR DESCRIPTION
**Pull request by darkdef**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #14663
It's only test. Issue #14663 may be closed. PR #14722 may be closed as not actually.

### CODE REVIEW

**Comment by samdark** [comment]
👍

**Comment by rob006** [comment]
This test does not prove anything in context of #14663. #14663 is about using ActiveRecord with bigint column on 32-bit system (or unsigned bigint on 64-bit system). You can't really test #14663 without using AR, because that is where casting is happening.

**Comment by samdark** [comment]
Reopened #14663.

**Comment by samdark** [comment]
@rob006 I've re-checked. `ColumnSchema::dbTypecast()` is used in query builder as well.

**Comment by rob006** [comment]
> We can't fix the "issue" with using string for 32-bit systems anyway.

Why not? Just don't cast to string in `dbTypecast()` if int is expected.
Also note that this is not only 32-bit system issue. Original report is about unsigned bigint on 64-bit system.

**Comment by samdark** [comment]
Right. Both me and @darkdef misunderstood the problem. Thanks for insisting that we're wrong.

**Pull request merged**
