### PR TITLE
Added `Formatter::asDuration`

### LINKED ISSUE #5146: Add yii\i18n\Formatter::asDuration()
` NumberFormatter::DURATION (integer) `

http://php.net/manual/en/class.numberformatter.php

### LINKED ISSUE #9704: Provide a Formatter for time interval
Please provide a formatter for time intervals, e.g. given a value in seconds:
2050 -> 34 minutes, 10 seconds
26967 -> 7 hours, 29 minutes

### PR DESCRIPTION
**Pull request by SilverFire**
Continue of @nineinchnick work in #9710
- Added PHPDoc
- Added missing test
- Added RU and UK messages translation
- Added to RU, EN guides

Closes #9710
Closes #5146
Closes #5704 
Closes #9704

### CODE REVIEW

**Comment by samdark** [comment]
Anything missing?

**Comment by SilverFire** [comment]
No, it's fully ready to be merged.

**Comment by samdark** [comment]
Found no issues during review. Merged!

**Comment by samdark** [comment]
Thanks @SilverFire and @nineinchnick.

**Pull request merged**
