### PR TITLE
Don't cast int to string if the value type is set as int, #14663

### PR DESCRIPTION
**Pull request by bittenApple**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14663

### CODE REVIEW

**Comment by Faryshta** [comment]
this is done when `$phpType` is an string. Which use cases happen to have `$phpType` equals 'string' and `$dbType` equals 'integer'?

**Comment by bittenApple** [comment]
> this is done when $phpType is an string. Which use cases happen to have $phpType equals 'string' and $dbType equals 'integer'?

Yes, I think it is necessary to cast int to string in this case

**Comment by Faryshta** [comment]
Your patch is done inside a `switch` statement  for the case when `$phpType` equals 'string'.

**Comment by bittenApple** [comment]
> Your patch is done inside a switch statement for the case when $phpType equals 'string'.

Sry, I don't get your point, do you mean it's better not to set $phpType to 'string' when the db field is 'unsigned bigint'?

**Comment by Faryshta** [comment]
currently there is no bigint support in php https://wiki.php.net/rfc/bigint http://php.net/manual/es/language.types.integer.php

basically they get turned into `float` with uncertain behavior. using bigint would require you to use external libraries such as http://php.net/manual/es/function.gmp-intval.php

```php
public function getIntValBigNumber()
{
       return gmp_intval($this->big_number);
}
```

i am closing this pr since its outside yii2 scope.

**Comment by rob006** [comment]
@Faryshta Pleas read #14663. This is about unnecessary casting integers to string on query generation. PHP bigint support has nothing to do with it.

**Comment by rob006** [comment]
I think that `ColumnSchema::phpTypecast()` and `ColumnSchema::dbTypecast()` should use different implementation. Right now both uses `typecast()` method and changes intended for casting values for generating db query affects casting query results of this query. This may result some weird side effects.

**Pull request closed without merging**
