### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by charescape**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by WinterSilence** [comment]
it's not true, Yii2 is legacy framework

**Comment by charescape** [comment]
@WinterSilence No, it's about Yii2 framework itself, not about comparing to other frameworks.

**Comment by WinterSilence** [comment]
@terabytesoftw 
Yii2 not optimized for PHP7, not to mention PHP8

**Comment by terabytesoftw** [comment]
> @terabytesoftw @charescape Yii2 not optimized for PHP7, not to mention PHP8

In the README.md it doesn't say that it's optimized, it just says that it's better to use the latest versions of PHP.

**Comment by charescape** [comment]
> - The minimum required PHP version of Yii is PHP 5.4.
> - It works best with PHP 7 & PHP 8.

I don't think there's anything wrong with that description.

**Comment by WinterSilence** [comment]
@terabytesoftw it's cheating - logical to assume that new versions of PHP are better than the previous ones, but Yii2 don't use new features.

**Comment by charescape** [comment]
> ..., but Yii2 don't use new features.

@WinterSilence `It works best with PHP 7 & PHP 8`, **NOT** `It works best with PHP 8`

**Comment by WinterSilence** [comment]
@charescape you mean Yii 2 work with PHP 5 worst than PHP 7-8?

**Comment by charescape** [comment]
@WinterSilence I mean PHP 8 can be simply treated as PHP 7 with some new features.

**Pull request merged**
