### PR TITLE
Support default value for `Console::select()`

### PR DESCRIPTION
**Pull request by rhertogh**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | -

Currently `yii\helpers\BaseConsole::prompt()` and `yii\helpers\BaseConsole::confirm()` support a "default" value.
This PR adds similar support to `yii\helpers\BaseConsole::select()` and `yii\console\Controller::select()`.

`yii\console\Controller::select()` now also respects the `yii\console\Controller::$interactive` setting.

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Comment by bizley** [comment]
Isn't it BC break?

**Comment by rhertogh** [comment]
@bizley 
> Isn't it BC break?

In which scenario would it be BC breaking?

**Comment by bizley** [comment]
After this change if you call Controller::select('', []) with $this->interactive = false it will return null, so far it calls Console::select().

**Comment by rhertogh** [comment]
@bizley 
> After this change if you call Controller::select('', []) with $this->interactive = false it will return null, so far it calls Console::select().

You're right, that behavior will indeed change. Although I think it's unlikely that would have an impact since running an app with `interactive = false` when there is a 'select' involved is currently impossible to run noninteractive. In that regard this PR could also be considered a bugfix.
I'll add a note in the upgrade.md.

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
