### PR TITLE
FIX: ETag never matched if "-gzip" added by Apache

### PR DESCRIPTION
**Pull request by mcd-php**
https://issues.apache.org/bugzilla/show_bug.cgi?id=45023

### CODE REVIEW

**Comment by qiangxue** [comment]
Thanks!

**Comment by mcd-php** [comment]
Thank you very much for quick adoption, but I have a little objection: bulk replace function was for the purpose of easily adding another disturbing strings. Maybe I should have written it more clear in comment ;(

**Comment by qiangxue** [comment]
> bulk replace function was for the purpose of easily adding another disturbing strings

I don't quite get you. Could you explain a bit more?

**Comment by mcd-php** [comment]
@qiangxue Yours - where to insert more substrings to be removed, if need arise ?
```php
return preg_split('/[\s,]+/', str_replace('-gzip', '', $_SERVER['HTTP_IF_NONE_MATCH']), -1, PREG_SPLIT_NO_EMPTY);
```
Mine - just add them to an array:
```php
return preg_split('/[\s,]+/', strtr($_SERVER['HTTP_IF_NONE_MATCH'],array_fill_keys([
    '-gzip', // Add more disturbing infixes here
],'')), -1, PREG_SPLIT_NO_EMPTY);
```

**Comment by qiangxue** [comment]
We can do that when the new need arises. Also, it's an overkill to call `array_fill_keys()` to construct an array which you can explicitly create.

**Pull request closed without merging**
