### PR TITLE
Update Persian translation.

### PR DESCRIPTION
**Pull request by jafaripur**
Add translation for compare validation.

### CODE REVIEW

**Comment by SilverFire** [comment]
Neighbor translations used in CompareValidator should be translated as well

**Comment by jafaripur** [comment]
If you check /validators/CompareValidator.php the compare translation is not exist in ``fa`` translation file.
```{attribute} must be equal to "{compareValueOrAttribute}".```

**Comment by SilverFire** [comment]
Please, check out all the messages used in [CompareValidator](https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L91-L112)

**Comment by jafaripur** [comment]
I checked it and test it multiple time.

https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L90-L95

The compare validation messages for equal is not available in ``fa`` locale translation.

**Comment by cebe** [comment]
@jafaripur have you tried running the extraction message command?

```
./yii message messages/config.php --languages=fa
```

run in the `framework` directory

**Comment by jafaripur** [comment]
@cebe No, in validation the compare validate is not translated in ``fa`` locale, I checked it and see the compare validate is not translated in framework core validate for ``fa`` locale.

I added it and not translated successfully.

**Comment by cebe** [comment]
@jafaripur okay, I see the misunderstanding now :) The message you added was not translated before. We all agree on that. But there are even more messages that need translation.

Could you please add translation for the following messages also?

```php
    'Powered by {yii}' => '',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => '',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => '',
    'Yii Framework' => '',
    '{attribute} contains wrong subnet mask.' => '',
    '{attribute} is not in the allowed range.' => '',
    '{attribute} must be a valid IP address.' => '',
    '{attribute} must be an IP address with specified subnet.' => '',
    '{attribute} must be equal to "{compareValueOrAttribute}".' => '',
    '{attribute} must be greater than "{compareValueOrAttribute}".' => '',
    '{attribute} must be greater than or equal to "{compareValueOrAttribute}".' => '',
    '{attribute} must be less than "{compareValueOrAttribute}".' => '',
    '{attribute} must be less than or equal to "{compareValueOrAttribute}".' => '',
    '{attribute} must not be a subnet.' => '',
    '{attribute} must not be an IPv4 address.' => '',
    '{attribute} must not be an IPv6 address.' => '',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => '',
    '{delta, plural, =1{1 day} other{# days}}' => '',
    '{delta, plural, =1{1 hour} other{# hours}}' => '',
    '{delta, plural, =1{1 minute} other{# minutes}}' => '',
    '{delta, plural, =1{1 month} other{# months}}' => '',
    '{delta, plural, =1{1 second} other{# seconds}}' => '',
    '{delta, plural, =1{1 year} other{# years}}' => '',
```

**Comment by jafaripur** [comment]
@cebe OK, I will add this translations.

**Pull request closed without merging**
