### PR TITLE
use getTargetClass in function checkTargetAttributeExistence

### PR DESCRIPTION
**Pull request by RodrigoDornelles**
found this small modification interesting, to subtract redundancy, and also facilitate modification of `checkTargetAttributeExistence`, when you only want to change `getTargetClass `.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by bizley** [comment]
While this is a good change since we don't repeat code and use existing method, I'm a bit confused because the description you provided states that you would like to change visibility of `getTargetClass()`?

**Comment by RodrigoDornelles** [comment]
> While this is a good change since we don't repeat code and use existing method, I'm a bit confused because the description you provided states that you would like to change visibility of `getTargetClass()`

That would be another point, besides decreasing the repeated code.

when think its facilitates to control a extend of the class, and you don't need to repeat function `checkTargetAttributeExistence`, to want modify just only `getTargetClass ` (I made some modifications).

will change the issue description.

**Comment by RodrigoDornelles** [comment]
> While this is a good change since we don't repeat code and use existing method, I'm a bit confused because the description you provided states that you would like to change visibility of `getTargetClass()`?

I did correction of my explanation.

**Review by bizley — APPROVED** [review]

**Comment by bizley** [comment]
Thank you!

**Pull request merged**
