### PR TITLE
Null in data filter

### PR DESCRIPTION
**Pull request by bizley**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

This enables providing `null` value in filters when there is no option to use literal `null` (like through URLs). I have seen SO questions asking for this several times.

I have put this on 2.0.40 to discuss it more before releasing (if at all). Automatic change from `'NULL'` to `null` might be messing apps using `'NULL'` strings currently so maybe it should be `'$NULL'`? I hope this change fills the gap in filters usability but maybe I forgot about something so please take a look if you are interested. All comments are welcomed.

### CODE REVIEW

**Comment by samdark** [comment]
Overall the implementation is OK. I don't see where it may break existing apps.

Any refereces to where it was asked?

**Comment by bizley** [comment]
https://stackoverflow.com/questions/64630624/yii2-how-to-get-null-and-not-null-filtered-results-using-yii2-rest-web-service
https://stackoverflow.com/questions/51876668/how-to-find-records-with-null-values-in-a-column-in-yii2-datafilters-or-rest-api

The current solution right now is to make custom handling so it's sometimes inconvenient.

**Comment by samdark** [comment]
Alright. Let's have it in the next release (current one has enough changes already).

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
