### PR TITLE
Update start-installation.md

### PR DESCRIPTION
**Pull request by bizley**
Mention `patch` command #18584

### CODE REVIEW

**Comment by rob006** [comment]
Patch is not used if you install Yii 2 as dependency, it is only needed if you want to contribute and run `composer install` directly on https://github.com/yiisoft/yii2. It makes more sense to mention this somewhere in https://github.com/yiisoft/yii2/tree/master/docs/internals instead of in installation guide.

**Comment by bizley** [comment]
Yes, I wrote "directly" there. I'm afraid no one reads internals, that is why I put it here. Should we move it there?

**Comment by rob006** [comment]
I don't think that "directly" clarifies anything here. This is clearly a documentation for framework users, such comment will only confuse them. Also, I don't think it will be more visible for contributors. I probably never read this section of guide, and I definitely would not search there for instruction how to setup dev environment for framework contributions. IMO it would be better fit for https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md. 

Although I'm not sure how useful this comment is - #18584 is about invalid shell used for running `composer` command - OP already had git installed, since you need it to checkout source code in the first place. :P

**Comment by bizley** [comment]
Ok, you are right, I will move it there. In the issue OP shows screen with `patch` missing and this is not the first time it happened.

**Comment by rob006** [comment]
> In the issue OP shows screen with `patch` missing and this is not the first time it happened.

AFAIK you get such error if you use `cmd.exe` as shell instead of `git-bash.exe`.

**Comment by bizley** [comment]
Closing since the notice loses its point if it would be in the git-workflow doc ;)

**Pull request closed without merging**
