### PR TITLE
Modified setAttributes()

### PR DESCRIPTION
**Pull request by pBazsi**
Added condition in if statement. Now it does not update the unchanged attributes, so they don't become 'dirty'.

### CODE REVIEW

**Comment by cebe** [comment]
unchanged attributes aren't marked as dirty anyway, why did you add this?

**Comment by samdark** [comment]
@pBazsi please provide a case where current code fails.

**Comment by pBazsi** [comment]
I can't easily provide exact code sample, because this needs AR to work, but see the following.

If you create a new instance of an AR class, all attributes are set to `null`.
Assume, class `Test` has an attribute named `city`. If I set anywhere the `city` attribute to the same `null` value, I don't want it to get dirty.

@cebe unchanged attributes aren't marked as dirty, if you load an existing record of the database, and it has old attributes, but they do get dirty, when you create an empty new model and set some attributes to `null`

```php
$model = new Test(); // AR class, has attribute `city`
var_dump($model->city); // This dumps `null`
var_dump($model->getDirtyAttributes()); // This dumps `[]`
$model->city = null; // Setting to the same value
var_dump($model->getDirtyAttributes()); // This dumps `array(1) ['city'=>null]`
```

My other idea is to fix `BaseActiveRecord::getDirtyAttributes()`, because it's mainly an AR problem, and my fix was in `Model::setAttributes()`.

In `getDirtyAttributes()`, from line 552 it does not check the `null` value.

```php
if ($this->_oldAttributes === null) {
    foreach ($this->_attributes as $name => $value) {
        if (isset($names[$name])) {
            $attributes[$name] = $value;
        }
    }
}
```

I would change to the following:
```php
if ($this->_oldAttributes === null) {
    foreach ($this->_attributes as $name => $value) {
        if (isset($names[$name]) && $value != null) {
            $attributes[$name] = $value;
        }
    }
}
```

**Comment by samdark** [comment]
Making attribute dirty when setting it to null is expected. Null is a valid value.

**Comment by tibee** [comment]
I don't understand why, because `null` is a valid value, but thinking of a new, empty model, replacing `null` with `null` why should make it dirty? On an old record, replacing an attribute with same value does not make it dirty.

@cebe wrote that 'unchanged attributes aren't marked as dirty anyway', why not on new, empty models?

**Comment by mj4444ru** [comment]
If the getter will be overridden, the result is unpredictable.

**Comment by mj4444ru** [comment]
Perhaps this lack may fix elsewhere.

**Comment by mj4444ru** [comment]
If `$safeOnly` is `true` and the value has not changed, is called `onUnsafeAttribute`.

**Comment by mj4444ru** [comment]
This pull request adds an error in the code. I have previously described how. Why is this pull request is still open?

**Comment by samdark** [comment]
Right. Closing it because it doesn't work in all cases and there are now typecasting capabilities in the core.

**Pull request closed without merging**
