### PR TITLE
New proposal fix for ColumnSchemaBuilder not null column

### PR DESCRIPTION
**Pull request by sugiruu**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #10422, #9574 |

### CODE REVIEW

**Comment by cebe** [comment]
it's a bit confusing to have two properties for the same method.
It could be possible to have semantics like: 

- `isNotNull = true` - explicit `NOT NULL` is added
- `isNotNull = null` - implicit null
- `isNotNull = false` - explicit `NULL`

**Comment by nevermnd** [comment]
Makes sense. I've changed it.

**Comment by thiagotalma** [comment]
Solve this too: #9574

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
