### PR TITLE
* Add registerJsonLd()

### PR DESCRIPTION
**Pull request by khalwat**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11018

### CODE REVIEW

**Comment by samdark** [comment]
Thanks for a pull request.

Sorry but it looks too specific to be included into framework. The issue was reopened not because of JSON-LD specifically but because there's something which isn't possible to achieve in an easy way.

**Comment by khalwat** [comment]
JSON-LD is a pretty important standard, with Google, Apple, and schema.org behind it, but oh well.

https://developers.google.com/search/docs/guides/intro-structured-data

Hopefully you'll find some way to allow for it to be doable in the Yii2 framework, perhaps generalizing the `$view->includeJs()` method.

**Comment by samdark** [comment]
There are many important standards for meta-markups of different kinds: OpenGraph, microdata etc. We can't support all of them.

**Comment by khalwat** [comment]
OpenGraph is already supported by Yii2, by virtue of the `meta` tag support. Microdata is just adding properties to existing HTML, and is largely deprecated in favor of JSON-LD, due to how troublesome it is to implement.

Under the umbrella of "Structured Data", the preferred encoding is JSON-LD, due to its simplicity, and that it's not intertwined with HTML tags the way microdata is (and thus relatively unmanageable).

I'll take a whack at another PR, if you're interested, which would just generalize `$view->registerJs()` to accept `$options` the way the other register calls do, it you'd like.

It'd be nice to have consistency in the APIs, as well as supporting a modern structured data standard like JSON-LD. All it'd need is to be able to accept an `$options` parameter, and then to put each script into it's own tag, rather than coalescing them together.

**Pull request closed without merging**
