### PR TITLE
Add doc for issue #8420

### PR DESCRIPTION
**Pull request by ihipop**
https://github.com/yiisoft/yii2/issues/8420#issuecomment-303956282

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #8420

### CODE REVIEW

**Comment by samdark** [comment]
@ihipop, @tom--, @beowulfenator please check docs this pull request.

**Comment by beowulfenator** [comment]
How do I add something to this PR?

**Comment by samdark** [comment]
You can't since you don't have write access to this repo. Either comment inline or, alternatively, access could be given.

**Comment by ihipop** [comment]
@samdark Thank you for your great work. 
But I have some different advice.

> The table may remain locked by MySQL and cannot be written to by other queries. Thus, new connection should be created for this purpose.

This is not the purpose that we establish  a new connection to MySQL server, we establish   a new connection to MySQL server because :

> Unless whole data set has been retrieved, no other query could be done through the same connection

Even we establish  a new connection to MySQL server ,tables may still `remain locked by MySQL and cannot be written to by other queries`  ，[Because MySQL keeps locks on data in the case of MyISAM on the entire table](https://stackoverflow.com/questions/5753948/php-mysqli-use-result-store-result-and-myisam-table-locks/5782924) ,and In `Unbuffered Query` Mode, because the loop  done by PHP is much more slow than `Buffered Query`  done by PDO (Not only because PHP is slower than C, but also the developer usually do some business logic in the loop for their specify reason), the lock time to table will much more longer  than `Buffered Query` , these two reason are too different.

So, The `lock table statement` should be moving to the `warning part` as I've commited.

`Unbuffered Query` is not a silver built indeed, just as what @SamMousa [have said](https://github.com/yiisoft/yii2/issues/8420#issuecomment-296109257):

> As I've said before, no solution is valid for all cases and therefore we should not just implement something. Instead implement it yourself as a custom function or behavior in your query class.

Maybe the total solution should be done by the developer in their business code, for us , a well document is on call.


@beowulfenator

**Comment by ihipop** [comment]
And, also, I think that [the paragraph  about the memory strategy of PHP before 5.6](https://github.com/yiisoft/yii2/pull/14215/commits/c1e6e6da62c6b2dca8b762f2af06bc9e95be1e8f#diff-356211f47ae64830fff2dadc9d65d7acR661) should not be removed
It explains that why `batch()` and `each()`  _seems to work_ (will not hit the memory limit problem,But will eat the server's memory at all) and lead a  meditate to `Bunffered query`

**Comment by beowulfenator** [comment]
Can you guys give me access to the repo?

**Comment by ihipop** [comment]
@beowulfenator https://github.com/ihipop/yii2/invitations invited

**Comment by beowulfenator** [comment]
Does this look better?

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Looks great to me now.

**Comment by samdark** [comment]
@ihipop how do you find it now?

**Comment by ihipop** [comment]
@samdark did not contains[ the opinion I‘ve said](https://github.com/yiisoft/yii2/pull/14215#issuecomment-304768532)
I still want add these, can I have your  agreement ?

**Comment by ihipop** [comment]
@beowulfenator excellent work.
 I would like to tweak a few words

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by tom--** [comment]
This is good. Thanks

**Pull request merged**
