### PR TITLE
Autocomplete for help

### PR DESCRIPTION
**Pull request by Valkeru**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | no

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Please add a line for changelog.

**Review by SilverFire — CHANGES_REQUESTED** [review]
ZSH completion should be updated as well https://github.com/Valkeru/yii2/blob/bc8089651c7ff0199384ff8e5e27e4853312c18a/contrib/completion/zsh/_yii

**Comment by Valkeru** [comment]
@samdark changelog added
@SilverFire zsh autocomplete updated

**Review by SilverFire — APPROVED** [review]

**Review by dmirogin — APPROVED** [review]

**Review by cebe — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
