### PR TITLE
Optimize AttributeTypecastBehavior::detectAttributeTypes()

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by bizley** [comment]
This is fine except for the use of array union, previously we used the last detected type for a given attribute, after this we will use the first one, I'm not sure how serious this bc break would be.

**Comment by WinterSilence** [comment]
@bizley 
> , I'm not sure how serious this bc break would be.

you can't use "type" validators together, they mutually exclusive

**Comment by WinterSilence** [comment]
@samdark how long to wait for merge PR?

**Comment by samdark** [comment]
Are there tests covering it?

**Comment by WinterSilence** [comment]
@samdark it's covered by [testAutoDetectAttributeTypes()](https://github.com/yiisoft/yii2/blob/f07cdf98dbd16c21c852085d650200c32924ff30/tests/framework/behaviors/AttributeTypecastBehaviorTest.php#L213)

**Review by samdark — APPROVED** [review]

**Pull request merged**
