### PR TITLE
Pressing "Enter" key  does not depend on the option "filterOnFocusOut"

### PR DESCRIPTION
**Pull request by s1lver**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #16716

### CODE REVIEW

**Comment by s1lver** [comment]
hmm, there is already a test for this behavior

**Comment by samdark** [comment]
If there's already a test and it was passing then either the test is wrong or there's nothing to fix.

**Comment by s1lver** [comment]
I will check it

**Comment by s1lver** [comment]
Added tests for three behaviors

default

**Review by samdark — APPROVED** [review]
Looks good to me. Please add a line for changelog.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
