### PR TITLE
Add namespace to Requeirement checker

### PR DESCRIPTION
**Pull request by githubjeka**
All classes should be namespaced by code style.

### CODE REVIEW

**Comment by samdark** [comment]
Bad idea since requirements checker should be able to run even on PHP 5.2 to tell you that your version is outdated.

**Comment by githubjeka** [comment]
If
 ```php
 if (version_compare(PHP_VERSION, '4.3', '<')) {
     echo 'At least PHP 4.3 is required to run this script!';
     exit(1);
``` 
move to requirements.php ?

**Comment by samdark** [comment]
I don't think there's much sense in doing so. It works as is and isn't part of the core framework. It's not autoloaded at all.

**Comment by githubjeka** [comment]
I understand that. But it is strange that it inside yii folder as folder/class. 
Looks like as extension (module).

**Comment by githubjeka** [comment]
Okay, leave it as is. Only, I get error - `PHP Fatal error: Cannot redeclare class yii\requirements\YiiRequirementChecker` without namespace. Because push PR.

**Comment by samdark** [comment]
???

**Comment by githubjeka** [comment]
I did iteration classes from Yii::$classes and get it. If ever somebody will emerge, then come back. Now leave as is.

**Comment by cebe** [comment]
the issue with classmap and requirementschecker is valid, it should not be included in class map.
Will fix it.

**Pull request closed without merging**
