### PR TITLE
Allow itemOptions in ListView to be a closure

### PR DESCRIPTION
**Pull request by webdevsega**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues |  |

### CODE REVIEW

**Comment by webdevsega** [comment]
This feature is similar to option rowOptions in GridView. This can be useful to highlight some of the line.

**Comment by dynasource** [comment]
* Can you please further elaborate why 'highlighting' of the line can only be done by other your PR?
* Can you also add unit tests?

**Comment by cebe** [comment]
> Can you please further elaborate why 'highlighting' of the line can only be done by other your PR?

because itemOptions depend on the data in this case.

> Can you also add unit tests?

yes, unit tests would be nice.

**Review by SilverFire — APPROVED** [review]
Good change. Ready to merge just after tests submission

**Review by samdark — CHANGES_REQUESTED** [review]
Unit tests needed.

**Comment by SilverFire** [comment]
Added unit tests https://github.com/yiisoft/yii2/commit/24a5532ca9a57024088b16d19848096ceee49078
Fixed CHANGELOG https://github.com/yiisoft/yii2/commit/964f600ef9880a567fc54d5329e9277d6f58bfbb

Merged. Thank you

**Pull request closed without merging**
