### PR TITLE
makes ModuleTest pass in windows environment

### PR DESCRIPTION
**Pull request by dynasource**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |

### CODE REVIEW

**Review by SilverFire — CHANGES_REQUESTED** [review]
Looks like a hack rather than fix :)

Could you try to wrap `$this->controllerPath` with a `realpath()` function?

**Comment by dynasource** [comment]
well, these paths are quite messed up in the first place. Therefore realpath doesnt work. I choose this solution instead of this one:
```php
        $this->assertEquals(__DIR__ . DIRECTORY_SEPARATOR . 'controllers', str_replace(['/','\\'], DIRECTORY_SEPARATOR , $module->controllerPath));
```

which one do you prefer?

**Comment by SilverFire** [comment]
The second one. It it clear to understand that we do something only with slashes in the path, but do not affect the path itself.

Is this the only place where tests fail on Win env?

**Comment by dynasource** [comment]
it seems so on the filepath subject. I will push the second solution

**Review by SilverFire — APPROVED** [review]

**Pull request merged**
