### PR TITLE
Fixed: Controllers in sub folders is not visible in list commands

### PR DESCRIPTION
**Pull request by idsulik**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #15200

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by dmirogin** [comment]
Just a question, controllerMap won't resolve this issue ?

**Comment by samdark** [comment]
Yes, it will resolve the issue as well, I guess. Do you suggest we need to build dynamically when scanning for controllers?

**Comment by dmirogin** [comment]
I think it would be better, but if we already have worked solution in this pull request than i ok with that.

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by Sarke** [comment]
Why was this merged instead of #13902 ?

**Comment by samdark** [comment]
Because there were no unit tests in #13902.

**Pull request merged**
