### PR TITLE
Bug #9906: Fixed PHPUnit test case of date formatting in Russian lang

### LINKED ISSUE #9906: Failed asserting of Russian UTF8 date
In PHP 5.6.4 (built: Sep 29 2015 12:44:47) the test `FormatConverterTest::testIntlUtf8Ru()` fails:

```
1) yiiunit\framework\helpers\FormatConverterTest::testIntlUtf8Ru
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'24 авг 2014 г.'
+'24 авг. 2014 г.'
```

Looks like something changed in PHP intl. Need to update test

### PR DESCRIPTION
**Pull request by SilverFire**
Closes #9906

### CODE REVIEW

**Comment by samdark** [comment]
Travis fails on it: https://travis-ci.org/yiisoft/yii2/builds/85142896

**Comment by SilverFire** [comment]
Yeah, I see. Ubuntu 15.04, PHP:

```
#> php -v
PHP 5.6.4-4ubuntu6.3 (cli) (built: Sep 29 2015 12:44:47) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans

#> php --info | grep -A 10 intl
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 52.1
ICU Data version => 52.1
```

Can anybody try on the save environment?

**Comment by samdark** [comment]
Origianl tests fails for me as well under Windows and is OK after the fix:

```
$ php -v
PHP 5.4.41 (cli) (built: May 14 2015 02:34:29)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans


$ php --info | grep -A 10 intl
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 49.1.2
ICU Data version => 49.1.2
```

**Comment by samdark** [comment]
Travis fail is with ICU 4.8.1.1 which seems to be quite old. I guess we can adjust test so it accepts both variations since both are OK in Russian.

**Comment by SilverFire** [comment]
Updated.
P.S.: We definitely need this https://github.com/auchenberg/volkswagen :)

**Comment by samdark** [comment]
Thanks!

**Pull request closed without merging**
