### PR TITLE
use binary save string comparison

### PR DESCRIPTION
**Pull request by cornernote**

### CODE REVIEW

**Comment by cebe** [comment]
can you explain what this change is for? What problem are you trying to solve?

**Comment by cornernote** [comment]
I want to check for dirty attributes and some of my attributes are gzcompressed.  It tells me the data is changed, although its the same.

**Comment by cebe** [comment]
can you provide a unit test for this? Or some example PHP code to reproduce the issue?

**Comment by cornernote** [comment]
I just realised it causes issues.  It also needs to check that the attribute is in fact a string.

I'll make some tweaks, and provide a unit test.

**Comment by dynasource** [comment]
there are some caveats as you can see at php.net
http://php.net/manual/en/function.strcmp.php#108563

**Comment by cornernote** [comment]
While creating the test to prove my point I found that the `!==` operator works fine and the issue was somewhere else in my code.

Sorry for being hasty about this and not providing tests to begin with.

**Pull request closed without merging**
