### PR TITLE
Corrected #18499

### PR DESCRIPTION
**Pull request by bizley**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | hopefully
| Fixed issues  | #18499 #18525

### CODE REVIEW

**Comment by samdark** [comment]
@bizley tests passed. What's the next step?

**Comment by bizley** [comment]
Um, merging? :)

**Comment by samdark** [comment]
OK. Then CHANGELOG is needed.

**Comment by bizley** [comment]
No, it's the same as in https://github.com/yiisoft/yii2/commit/d1037db68dbd3d1fd5ee098ff802e3fe2fe4f45b

**Comment by samdark** [comment]
Ah. Alright.

**Comment by samdark** [comment]
👍

**Pull request merged**
