### PR TITLE
Add CSS class to preserve form design

### PR DESCRIPTION
**Pull request by joshijitendra**

### CODE REVIEW

**Comment by samdark** [comment]
What's wrong with it currently?

**Comment by joshijitendra** [comment]
If we use 
<?= $form->field($model, 'from_date')->widget(\yii\jui\DatePicker::classname(), [
    //'language' => 'ru',
    //'dateFormat' => 'yyyy-MM-dd',
]) ?>

the textbox appears as plain textbox without bootstrap style i.e. layout appears broken so adding the CSS class brings back the lost style when adding DatePicker.

**Comment by samdark** [comment]
Won't accept the pull requests because it's jQueryUI widget that could be used without bootstrap.

**Comment by joshijitendra** [comment]
Ok. How about I add a specific example when working with Bootstrap?

**Comment by samdark** [comment]
http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#practical-usage

**Comment by joshijitendra** [comment]
You mean, I can add the specific example here under "Practical Usage" section?

**Comment by samdark** [comment]
No, I mean you can set additional class application-wide using it.

**Pull request closed without merging**
