### PR TITLE
Calculation of activity menu item through the closure

### PR DESCRIPTION
**Pull request by voskobovich**
Look changed code

### CODE REVIEW

**Comment by SilverFire** [comment]
@voskobovich for the future - please, set your username and email in your local git settings to have commits linked to your account.
https://help.github.com/articles/set-up-git/#setting-up-git

**Comment by voskobovich** [comment]
Thanks for the comments. Already corrected=)

**Comment by cebe** [comment]
what is the use case for this? normally expressions in view code are sufficient.

**Comment by samdark** [comment]
I agree with @cebe. I can't name any use case where state can't be determined with an expression on top of menu code.

**Comment by voskobovich** [comment]
I'm taking a menu at boot application.
```
[
    'id' => 'app-name',
    'basePath' => dirname(__DIR__),
    'language' => 'en-US',
    'bootstrap' => [
        'log',
        function () {
            $menus = require(__DIR__ . '/params_menu.php');
            Yii::$app->params = array_merge(Yii::$app->params, $menus);
        }
    ],
    ...
]
```
Activity menu items depends on the name of the controller.
```
[
        'pages' => [
            'label' => 'Pages',
            'url' => ['/page/index'],
            'active' => function () {
                return Yii::$app->controller->id == 'page';
            }
        ],
        ...
]
```
But the controller has not been initialized, and I can not get his ID.
To do this I need to use a callback function.

**Comment by cebe** [comment]
I acutally remember to have had this issue in a project too :)

**Comment by cebe** [comment]
the original pull request was about this commit: https://github.com/yiisoft/yii2/pull/10493/commits/f71c8ba92d0e4f75b8f9822f4f1543cf11a167a8 somehow new, unrelated commits have been added.

**Comment by samdark** [comment]
Aha. That commit makes sense. I'm for applying it.

**Comment by voskobovich** [comment]
@samdark, check the result of my merge.

**Comment by samdark** [comment]
@voskobovich why all the changes in User class?

**Comment by voskobovich** [comment]
@samdark, my fault. I sent different improvements in one branch. How can I fix this situation?

**Comment by samdark** [comment]
Create a separate branch from master. Cherry-pick commit. Send pull request. Close this one.

**Pull request closed without merging**
