### PR TITLE
Added external link functionality in bootstrap/tabs

### PR DESCRIPTION
**Pull request by dynasource**
Usecase is if content should not be loaded inline by Ajax because of:
- content is on different route
- content cannot (correctly) be loaded by inline ajax

### CODE REVIEW

**Comment by samdark** [comment]
Would be great to get additional unit tests for this case.

**Comment by dynasource** [comment]
of course. I'll add them.

**Comment by Okeanos** [comment]
Any idea when this'll make it into a release?

**Comment by cebe** [comment]
it is tagged for release 2.0.4

**Comment by Okeanos** [comment]
Yeah, I saw that :) … I guess I phrased my question poorly, sorry about that. I was looking for [this](https://github.com/yiisoft/yii2/milestones) I suppose, i.e. an estimate _when_ it'll be released.

**Comment by cebe** [comment]
yeah right, 2.0.4 will be on May 3, 2015

**Comment by klimov-paul** [comment]
@dynasource, can you please resubmit this PR up to <a href="https://github.com/yiisoft/yii2-bootstrap">yii2-bootstrap</a> repo?

**Comment by qiangxue** [comment]
https://github.com/yiisoft/yii2-bootstrap/commit/554c3ccf04ee0c5ae699615d2866d8a6826d1ffb
Thanks!

**Comment by Okeanos** [comment]
Is it intended that the newly added `url` parameter is only available for top level items and not in dropdown items?

**Comment by cebe** [comment]
it could be added to tabs also but this has to be implemented differently then. Can you please open a separate issue?

**Pull request closed without merging**
