### PR TITLE
Use ActiveRecord models for the RBAC module

### PR DESCRIPTION
**Pull request by Faryshta**
Related to #570 that uses ActiveRecord models to handle the roles, permission and assignments of the RBAC module

### CODE REVIEW

**Comment by Faryshta** [comment]
@samdark I saw an issue the other day (can't find it anymore) about support for mongodb rbac.

Do you think I should change this PR to use traits and interfaces that will later be used on other ActiveRecord instances? Like mongo, elasticsearch, etc.

**Comment by cebe** [comment]
I do not think so, we can refactor it later if we find that there is duplicate code.

**Comment by Faryshta** [comment]
@samdark why was this closed?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/42#issuecomment-210142421

**Comment by samdark** [comment]
Generally because using AR for it will lead to people using these models directly which we don't want.

**Pull request closed without merging**
