### PR TITLE
type cast on validation

### PR DESCRIPTION
**Pull request by Bhoft**
this would fix so this issue won't be posted again.
And only "changed" columns would be updated on the sql.
And the columns wouldn't be marked as dirty on form submit.

https://github.com/yiisoft/yii2/issues/7792
https://github.com/yiisoft/yii2/issues/2790
https://github.com/yiisoft/yii2/issues/4284

### CODE REVIEW

**Comment by cebe** [comment]
whats wrong with adding a filter validator afterwards that casts as needed?

**Comment by Bhoft** [comment]
you have to manually do it for each column.
therefore you have to add this rules after you have created the models with gii.
In my opinion if an attribute is validated as either a integer or float value (which is checked before that code lines), it should also have the correct type.
So int is an int and a float value is a float.

With this change you will fix several issues:
only changed columns are updated in sql because the columns aren`t marked as dirty after form post and you can use the getDirtyAttribues() function now beforeSave and afterSave to create log entries (otherwise you have to double check if the value is really changed) and the type is correct after validation.

Sure this all can also be achieved by adding the filter which do the same, but in my opinion this should be done automatically.

**Comment by qiangxue** [comment]
This is risky. For example, you are using `number` validator to validate a decimal number (stored as a string in DB). You should not cast it into a float because you would otherwise lose precision. Also, for integer typecasting, this may not always be desirable if all you want is a big decimal number.

**Comment by Bhoft** [comment]
i agree i guess this wasn't well thought of me, then please close the pull request. then we have to use the intval filters to get the same results.

**Pull request closed without merging**
