### PR TITLE
Added support parsing json when json string in url query

### PR DESCRIPTION
**Pull request by darkfriend**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | Fixed empty `Yii::$app->request->getBodyParams()` when http request in GET and json in url query. Example bug: `http://mydomain.com/?{"key1":"value1","key2":"value2"}`

### CODE REVIEW

**Comment by samdark** [comment]
Is that related to https://github.com/yiisoft/yii2/issues/18578?

**Comment by darkfriend** [comment]
No, he does there bad request, because make GET key. If you http with GET and json, then json string add to url query, look like `http://mydomain.com/?{"key1":"value1","key2":"value2"}`. My PR added support this. Try it :)

**Comment by darkfriend** [comment]
### I mean next use case
There is json:
```json
{
  "fields": ["id", "name", "other"],
  "filters": {
    "name": "Robert"
  }
}
```

I use request: POST `http://mydomain.com` and in body `{"fields":["id","name","other"],"filters":{"name":"Robert"}}`
I get data: `Yii::$app->request->getBodyParams()` -> return array with data

And now:
I use request: GET `http://mydomain.com?{"fields":["id","name","other"],"filters":{"name":"Robert"}}`
I get data: `Yii::$app->request->getBodyParams()` -> return empty array (no data)

I fixed here and now:
I get data: `Yii::$app->request->getBodyParams()` -> return array with data (how in POST)

**Comment by samdark** [comment]
Current behavior seems to be correct since `getBodyParams()` is to get *body* parameters. In our case the parameter is in the URI of the request, not in its body.

**Pull request closed without merging**
