### PR TITLE
Integrate some section with example or suggestion

### PR DESCRIPTION
**Pull request by minitia**
For me, it wasn't easy to understand where register event handlers

### CODE REVIEW

**Comment by minitia** [comment]
I was wrong with the link of advanced template, and I like to add a reference to the stackoverflow page where I found the example:
https://stackoverflow.com/questions/28575636/how-to-use-events-in-yii2

**Comment by samdark** [comment]
Thanks for contribution but these changes won't be accepted:

1. Events section is general purpose. Events could be attached to anything so model example looks odd.
2. Events could be registered anywhere so I'm not sure why it's important to emphasize on bootstrap specifically.

**Comment by machour** [comment]
I think that this is a signal that events documentation is not clear enough for new comers.

**Comment by samdark** [comment]
Likely. @minitia I think for your examples the wiki fits quite well: https://www.yiiframework.com/wiki. Would you mind creating an article there?

**Comment by minitia** [comment]
I've done here
https://www.yiiframework.com/wiki/2548/events-registration-examples
thank you guys

**Pull request closed without merging**
