### PR TITLE
Fixed `quoteColumnName` for table start with `{{` or `[[`

### PR DESCRIPTION
**Pull request by edgardmessias**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #11088; #11135 |

### CODE REVIEW

**Comment by samdark** [comment]
What was wrong exactly?

**Comment by edgardmessias** [comment]
The main problem is in orderBy

Example: 
```php
$query->orderBy('{{table}}.id')
```
```sql
-- Current:
ORDER BY `table`.id
ORDER BY "table".id

--Correct:
ORDER BY `table`.`id`
ORDER BY "table"."id"
```

See the test: https://github.com/yiisoft/yii2/pull/11238/files#diff-816ca92a69886fa03b41cb133f3822a2R91

**Comment by edgardmessias** [comment]
Another Example without table:
Example: 
```php
$query->orderBy('id')
```
```sql
-- Current:
ORDER BY `id`
ORDER BY "id"

**Comment by edgardmessias** [comment]
groupBy is affected too.

See in docs/guide/db-active-record.md has ```groupBy('{{customer}}.id')```

**Comment by mdmunir** [comment]
If i not wrong
```php
$query->orderBy('table.id'); // ORDER BY `table`.`id`
$query->orderBy('{{table}}.id'); // ORDER BY `table`.id
$query->orderBy('{{table}}.[[id]]'); // ORDER BY `table`.`id`
$query->orderBy('{{%table}}.[[id]]'); // ORDER BY `prefix_table`.`id`
```
I mean, if you want to quoting them. Quote both of them. IMO

**Comment by Ni-san** [comment]
related: 
https://github.com/yiisoft/yii2/pull/11176
https://github.com/yiisoft/yii2/pull/11135
https://github.com/yiisoft/yii2/issues/11088
Need be checked with tests from https://github.com/yiisoft/yii2/pull/11135

**Comment by edgardmessias** [comment]
Tests with #11135 passed

**Comment by cebe** [comment]
@mdmunir correct, but if you use {{%table}} format for table names this causes problems internally in ActiveQuery structure.

@edgardmessias thanks for the fix! I have a slightly different version and more tests in #11403, so I'm closing this one.

**Pull request closed without merging**
