### PR TITLE
fix BaseMailerTest class

### PR DESCRIPTION
**Pull request by hyuzea**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by sup-ham** [comment]
My testing env resulting errors:
```
There were 6 errors:

1) yiiunit\framework\mail\BaseMailerTest::testSetupView
yii\base\Exception: Failed to create directory "/media/xubuncup/905C5F905C5F7048/cup/www/.dev/osp/yii2/tests/runtime/yiiunit\framework\mail\BaseMailerTest_27890": mkdir(): Invalid argument
```

**Comment by samdark** [comment]
What are your operating system and file system?

**Comment by sup-ham** [comment]
Here
>xubuncup@ThinkPad-E440:/media/xubuncup/905C5F905C5F7048/cup/www/spionam-2.2$ php -v
PHP 7.3.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:37:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by samdark** [comment]
OK. Looks valid.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
