### PR TITLE
Added submenuOptions property to Dropdown

### PR DESCRIPTION
**Pull request by spikyjt**
A submenu options array adds flexibility to the dropdown, allowing custom attributes to be added to submenus. This patch doesn't break BC, as it sets submenuOptions to options, if it has not been explicitly set. However it does get the rid of the dropdown-menu class that is currently set on submenus, causing them to be hidden by default.

### CODE REVIEW

**Comment by cebe** [comment]
You have a failing test here: https://travis-ci.org/yiisoft/yii2/jobs/52027817#L917 can you please fix it?

**Comment by spikyjt** [comment]
Looks like that fixed it. Sorry, I'm new to unit tests. They're still on my todo list to get familiar with!

**Comment by samdark** [comment]
That's not the wat to fix it :)

**Comment by samdark** [comment]
Test doesn't look right now.

**Comment by spikyjt** [comment]
@samdark do you think that the submenu _should_ have the class `dropdown-menu`? Having this class is incorrect as far as Bootstrap is concerned. You can't have a dropdown inside a dropdown. You can have a submenu, Bootstrap just doesn't provide styling for them by default. Removing the `dropdown-menu` class from the submenu makes it behave as expected, i.e. shown by default with the parent dropdown, instead of being hidden with no way to show it.

**Comment by samdark** [comment]
Ah, then it's probably fine.

**Comment by spikyjt** [comment]
Thanks @samdark . The test is definitely now correct as far as my code change is concerned. As long as you are all happy with the logic of my code change, then all is well.

**Comment by spikyjt** [comment]
Should I add to the test to include settings for the new submenuOptions property?

**Comment by samdark** [comment]
Yes, that would be great.

**Comment by spikyjt** [comment]
Ok, my new test passes, but I'm wondering if I should make submenuOptions a property of each item, rather than the whole widget. That way you could set it differently per level, if required. Perhaps I should have created an issue for this rather than just a PR?!

**Comment by klimov-paul** [comment]
@spikyjt, can you please resubmit this PR up to <a href="https://github.com/yiisoft/yii2-bootstrap">yii2-bootstrap</a> repo?

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2-bootstrap/issues/41

**Pull request closed without merging**
