### PR TITLE
Markdown set default flavor

### PR DESCRIPTION
**Pull request by mdmunir**
| Q | A |
| --- | --- |
| Is bugfix? | yes/no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues |  |

### CODE REVIEW

**Comment by mdmunir** [comment]
property `Markdown::$defaultFlavor` is introduced since the begining. But cannot be used until now :D

**Comment by cebe** [comment]
good catch :-D

**Comment by SilverFire** [comment]
How about a changelog line?

**Comment by mdmunir** [comment]
> How about a changelog line?

That always be my missing. Because i am not good to describe something :D

**Comment by SilverFire** [comment]
Thank you, @mdmunir!
Looks good to me

**Comment by cebe** [comment]
> Because i am not good to describe something :D

you can only get better when you practise ;)

**Comment by cebe** [comment]
Merged. thank you!

**Pull request closed without merging**
