### PR TITLE
Container type for pjax must be string

### PR DESCRIPTION
**Pull request by execut**
Here in pjax is checking this https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L176
For this reason, I received an error after the click on delete action in ActionColumn:

2017-10-03-161049_1920x1080_scrot

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no

### CODE REVIEW

**Comment by samdark** [comment]
@SilverFire, @arogachev, would you please check it?

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
Thank you for fix.

You handle the click in ActionColumn with your own code, right?

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/dfac2292edf43a76147f1d45167febef4087ab4a

Merged, thank you

**Comment by mirkhamidov** [comment]
What I have to do to get this fix?

**Comment by samdark** [comment]
Either wait for the next release or use dev-master as version.

**Pull request closed without merging**
