### PR TITLE
 Fix not taking default value when unable to resolve abstract class via DI container

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18378

### CODE REVIEW

**Comment by SamMousa** [comment]
@samdark this PR breaks the DI container in some cases.
It now marks all class typed dependencies as optional even when they are not.

This should be reverted before it lands in a release.

**Comment by vjik** [comment]
> this PR breaks the DI container in some cases.
> It now marks all class typed dependencies as optional even when they are not.

Can you give an example?

**Comment by SamMousa** [comment]
Yes:
```php
class A {

    public function __construct(SomeThing $x) {

   }
}

class B {

    public function __construct(A $a) {}
}

```

If something goes wrong with instantiating `SomeThing`, instead of the container throwing an error it will try to pass `null` as a parameter  to the construct of A, which will then fail because `null` is not a valid value for `SomeThing $x`.

The reflectionparam has a method `isOptional()`, why not use that as the 2nd param to `Instance:of()` ?

**Comment by vjik** [comment]
There will be an exception in any case. Exception should be throwed by container, not by incorrect type in constructor. Right?

**Comment by SamMousa** [comment]
> Exception should be throwed by container, not by incorrect type in constructor

That's the expected behavior, but due to this PR no longer the observed behavior

**Comment by samdark** [comment]
@SamMousa does the PR https://github.com/yiisoft/yii2/pull/18396 fix your issue?

**Comment by SamMousa** [comment]
Haven't tested the code, but did an in depth review and given the test samples I think it will solve the issue. Just a minor thing about changing exception type which we shouldn't do, other then that it LGTM.

**Pull request merged**
