### PR TITLE
Fix #17469: Fixed updating `Yii` logger instance when setting new logger via configuration

### LINKED ISSUE #17469: logger not working if it's set from config
### What steps will reproduce the problem?
Inside any controller, put this:
```php
public function actionIndex()
{
        Yii::info('Hello World');
        return $this->render('index');
}
```

inside the config:
```php
'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'logger' => Yii::createObject('yii\log\Logger'),
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'info'],
                ],
            ],
],
```

### What is the expected result?
Log inside the `runtime/logs/app.log`

### What do you get instead?
Nothing in `runtime/logs/app.log`

### Additional info
It'll work if  `'logger' => Yii::createObject('yii\log\Logger'),` is removed

I have found location from where it's misbehaving.
**Class** : `yii\log\Logger` 
```php
public function __construct($config = [])
    {
        // ensure logger gets set before any other config option
        if (isset($config['logger'])) {
            $this->setLogger($config['logger']);
            unset($config['logger']);
        }
        // connect logger and dispatcher
        $this->getLogger();

        parent::__construct($config);
    }

```
and
```php
/**
     * Gets the connected logger.
     * If not set, [[\Yii::getLogger()]] will be used.
     * @property Logger the logger. If not set, [[\Yii::getLogger()]] will be used.
     * @return Logger the logger.
     */
    public function getLogger()
    {
        if ($this->_logger === null) {
            $this->setLogger(Yii::getLogger());
        }

        return $this->_logger;
    }

    /**
     * Sets the connected logger.
     * @param Logger|string|array $value the logger to be used. This can either be a logger instance
     * or a configuration that will be used to create one using [[Yii::createObject()]].
     */
    public function setLogger($value)
    {
        if (is_string($value) || is_array($value)) {
            $value = Yii::createObject($value);
        }
        $this->_logger = $value;
        $this->_logger->dispatcher = $this;
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      | 7.3.7-1+ubuntu16.04.1+deb.sury.org+1
| Operating system | ubuntu16.04.1+deb.sury.org+1

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17469

### CODE REVIEW

**Comment by rob006** [comment]
I have mixed feelings about this. It looks like ugly voodoo magic that assumes that you always have only one dispatcher and it is `Yii::$app->log` (which is really naive assumption). Shouldn't we at list check if `$this === Yii::$app->log` before implicitly assigning static global logger.

**Comment by samdark** [comment]
That will return `false` most of the time since logger is initialized early and then cached statically forever. That is indeed, a bit of voodoo magic but that is what service locator brings us :(

**Comment by rob006** [comment]
> a bit of voodoo magic but that is what service locator brings us :(

Not it's not. This is the result of ugly shortcut which creates twisted relation between `Yii::getLogger()` and `Yii::$app->log->logger`. This PR just make it way more magic (by introducing BC break BTW - this is really ugly and unexpected side effect). You could have service locator without assuming that one class could be instantiated only once.

**Comment by samdark** [comment]
Yes but in this case it was already working that way (when getting it) but without the ability to configure it properly. That part was fixed.

**Comment by rob006** [comment]
There is a difference between using `Yii::getLogger()` as a fallback, and between implicitly setting global logger when you use setter on **local object**. Now if you use in your code `new Dispatcher(['logger' => $myFakeLogger]);` it will magically break your app by overriding global logger.

**Comment by samdark** [comment]
Right. Is there a better way to solve original issue?

**Comment by rob006** [comment]
I'm not sure. But I would rather do not touch it at all than introduce BC break that makes this part of framework even more magic. This issue is known from at least 3 years (#12163) with known (`Yii::setLogger(new MyLogger())` before app initialization) and consistent (you should use `Yii::setLogger()` to change logger returned by `Yii::getLogger()`) workaround, I'm not sure it is a good time to make such changes.

**Comment by schmunk42** [comment]
I agree with @rob006, please no BC breaks in 2.x

**Comment by samdark** [comment]
OK. Will be reverted next release.

**Pull request merged**
