### PR TITLE
Add Psr7 ServerRequest to \yii\web\Request and abstract Super Gloabls

### LINKED ISSUE #10824: Abstract Super Globals such as $_SERVER for each request into \yii\web\Request
With the release of PHP7 and the new Pthreads package, running a threaded HTTP Server from the PHP CLI is now a viable thing to do (as opposed to running a webserver and running PHP as a FastCGI script). The Yii2 Framework directly references Super Globals such as $_SERVER variables in many places, which are global variables and cannot be changed on each request. In order to support multiple requests within the same process, these variables would need to abstracted.

I think that supporting long-running PHP web servers from the CLI is going to be an increasingly important thing for developers since development is shifting towards microservices.  This would allow for state to be stored in memory from one request to the next.

### PR DESCRIPTION
**Pull request by caleblloyd**
Closes #10824

Needs tests.  So far I was able to run an application using:

```
use Zend\Diactoros\ServerRequestFactory;
...

$application = new yii\web\Application($config);
$serverRequest = ServerRequestFactory::fromGlobals();
$_SERVER = [];
$_GET = [];
$_POST = [];
$_COOKIE = [];
$_FILES = [];
$application->run($serverRequest);
```

### CODE REVIEW

**Comment by samdark** [comment]
How about providing default server request wrapper instead of doing check and fallback implementations here and there?

**Comment by caleblloyd** [comment]
We would have to implement the entire psr7\http interface, or import Zends's, or wait for Guzzle's to be ready and import that.

yii\web\request already contains it's own version of message abstraction for Headers, Cookies, GET and POST. It would be a lot of double-work to implement psr7 for FastCGI and maintain backwards compatiblity.

**Comment by caleblloyd** [comment]
I agree that having a default implementation would make \yii\web\Request a lot cleaner, though.  I'm working up a change set with just the bare minimum to support a PSR7 ServerRequest object.  That way we won't have to import a specific PSR7 implementation.  Should have another draft ready in a day or two.

**Comment by klimov-paul** [comment]
Resolved by commit 722022f744dbac8b0ef930caf877efdf388898e5

**Pull request closed without merging**
