### PR TITLE
Compare Validator: Support of compareValue being also a closure

### PR DESCRIPTION
**Pull request by mmonem**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Review by samdark — APPROVED** [review]
Please add a line for CHANGELOG.md

**Comment by mmonem** [comment]
In `CompareValidator`, now `compareValue` can also take a closure returning a value

**Comment by bizley** [comment]
@mmonem Could you please update CHANGELOG.md file in your PR stating the change you prepared so we can merge it?

**Comment by mmonem** [comment]
I have updated CHANGELOG.md

**Comment by samdark** [comment]
Thanks! Merged.

**Pull request merged**
