### PR TITLE
fix file upload bug if used with dynamic forms and elements are zero

### PR DESCRIPTION
**Pull request by RobinKamps**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

If used with dynamic forms and fileInput it comes to typeError if there are no file-inputs (min elements = 0). Due to this error the whole form will not be validated at the client side.
I tested other input validations (url, string etc) on a similar setting (dynamic forms with zero elements) and all worked fine, only the file-input-validation did not work.
This little addition fixes the issue.

The error was:
[Error] TypeError: undefined is not an object (evaluating '$(attribute.input, attribute.$form).get(0).files')
	getUploadedFiles (yii.validation.js:371)
	file (yii.validation.js:75)
	validate (create:1090:2956)
	(anonyme Funktion) (yii.activeForm.js:338)
	each (jquery.js:365)
	validate (yii.activeForm.js:323)
	submitForm (yii.activeForm.js:427)
	dispatch (jquery.js:4737)
	handle (jquery.js:4549)

### CODE REVIEW

**Comment by cebe** [comment]
could you add a comment to explain what the code is supposed to do, i.e. in which situation it is relevant? Also if possible, a unit test should be created for this case.

**Comment by RobinKamps** [comment]
// Continue validation if file input does not exist
// (in case file inputs are added dynamically and no file input has been added to the form)

Should i add the comment to the code/pull request?

I have to little experience with testing javascript to add a test-case for this pull request (i just played around with yii.validation.test.js and tried something with jasmine). Perhaps someone more experienced can help out?

**Comment by samdark** [comment]
> Should i add the comment to the code/pull request?

Yes.

**Comment by SilverFire** [comment]
@arogachev could you enhance tests?

**Comment by s1lver** [comment]
Looks like the author has stopped working. I will check and add tests

**Comment by s1lver** [comment]
At first glance, it does not look good and the tests do not pass.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/0f0e895475a9031f061fcecf557049642bd5af6d

**Pull request closed without merging**
