### PR TITLE
Get gridview footer content after cells content

### PR DESCRIPTION
**Pull request by ElisDN**
I override Column::renderDataCellContent with own counter implementation, but as a result it returns zero in Column::renderFooterCellContent, because it calls by GridView before data cells loop.

### CODE REVIEW

**Comment by svit-ws** [comment]
in which release this enhancement will be emplemented?

**Comment by samdark** [comment]
I think it's already there. It was mergeed in 2014.

**Comment by svit-ws** [comment]
`php
            [
                'attribute' => 'total',
                'value' => function ($model) use (&$total) {
                    $total += $model->total;

                    return $model->total;
                },
                'format' => 'currency',
                'footer' => $total,
            ],
`
the $total is 0

Yii 2.0.10

**Comment by rob006** [comment]
Did you try `'footer' => &$total,`?

**Comment by svit-ws** [comment]
> Did you try 'footer' => &$total,?

this no effect too...

moreover, I would like to format value before passing - indicated 'format' working only for 'value'

**Comment by ElisDN** [comment]
@svit-ws create own number column class:

```
namespace app\widgets\grid;
use yii\grid\DataColumn;

class NumberColumn extends DataColumn
{
    private $total = 0;

    protected function renderDataCellContent($model, $key, $index)
    {
        $value = $this->getDataCellValue($model, $key, $index);
        $this->total += $value;		
        return parent::renderDataCellContent($model, $key, $index);
    }

    protected function renderFooterCellContent()
    {
        return $this->grid->formatter->format($this->total, $this->format);
    }
}
```

and use it in your GridView widget:

```
'columns' => [
    'id',
    [
        'class' => \app\widgets\grid\NumberColumn::className(),
        'attribute' => 'total',
    ],
],
```

**Comment by svit-ws** [comment]
@ElisDN nice alternative!
Thanx

**Pull request merged**
