### PR TITLE
Added French runtime-sessions-cookies.md [skip ci]

### PR DESCRIPTION
**Pull request by jaaf**
| Q | A |
| --- | --- |
| Is bugfix? | yes/no |
| New feature? | yes/no |
| Breaks BC? | yes/no |
| Tests pass? | yes/no |
| Fixed issues | comma-separated list of tickets # fixed by the PR, if any |

### CODE REVIEW

**Comment by SilverFire** [comment]
Thank you

**Comment by SilverFire** [comment]
Please, check out the guide article [Setting up Git](https://help.github.com/articles/set-up-git/#setting-up-git) and make commits bound to your account

**Comment by jaaf** [comment]
Hi. I apologize. I am not a developer (not very used to git) and I have trouble understanding what " make commits bound to your account" means. I seems to me I strictly followed this article https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md. Could you please tell me what is wrong and where, because reading the article you point doesn't bring me light ?

**Comment by samdark** [comment]
Everything's OK except your contributions aren't liked to your account i.e. the email you're using to commit is different from the one you're using for your GitHub account. For the French guide readers there's no difference but we want to make sure you're listed properly as contributor.

**Comment by jaaf** [comment]
Here is my git config
```
[jaaf@jaaf-pc yii2]$ git config --list
user.name=jaaf
usser.email=jaaf64@zoraldia.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/jaaf/yii2.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.upstream.url=git://github.com/yiisoft/yii2.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
branch.run-cookies.remote=origin
branch.run-cookies.merge=refs/heads/run-cookies
[jaaf@jaaf-pc yii2]$
``` 
It seems that the email is the same as the one I use on github.com

**Comment by samdark** [comment]
Weird. Your commits are using `jaaf@jaaf-pc.home`.

**Comment by jaaf** [comment]
Should I pass the option --author= 'José Fournier<jaaf64@zoraldia.com>' with each commit?
Apparently it works and is returned by git log

**Comment by samdark** [comment]
Aha! `usser.email` note double `s`.

**Comment by jaaf** [comment]
Ok. Thanks!

**Pull request merged**
