### PR TITLE
[PHP 8.4] Fixes for implicit nullability deprecation

### PR DESCRIPTION
**Pull request by Ayesh**
Fixes all issues that emit deprecation notices on PHP 8.4 for implicit nullable parameter type declarations.

See:
 - [RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
 - [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | N/A

### CODE REVIEW

**Comment by samdark** [comment]
Thanks for contributing. Is that a backwards compatibility break for the case of inheritance?

**Comment by Ayesh** [comment]
Hi @samdark , thanks for the response. 

Both `string $v = null` and `?string $v = null` are considered "nullable" for inheritance, so yes, this is not a BC break. 

However I just realized Yii also has to support PHP 5.4 through 7.0 as well, which have no nullable type support, so this change is breaking on those versions.

**Comment by Ayesh** [comment]
I will close this PR because we can not merge this as-is unless we either bump the minimum version to 7.1 (or drop these type declaration).

**Comment by samdark** [comment]
You can target the pull request for 2.2 branch which is PHP8+

**Comment by Ayesh** [comment]
Thank you! I rebased for 2.2.

**Comment by rob006** [comment]
@samdark AFAIK we had plans to increase min PHP version in v2.0.50 to 7.3. Something changed in that matter? If not, we could still merge this PR to master.

**Comment by samdark** [comment]
Won't this be a BC break anyway because of signature mismatch?

**Comment by Ayesh** [comment]
Quite fortunately it's not a BC break. If there any sub classes extending _our_ classes, they will need the nullability fix to avoid the deprecation, but they will still be compatible.

**Comment by rob006** [comment]
https://3v4l.org/i7dQn#v7.3.33

**Comment by samdark** [comment]
Could go into master then. @Ayesh sorry to ask but could you rebase it back? :)

**Comment by Ayesh** [comment]
No problemo, I opened #20133 separately targeting `master` branch. It will fail because it still builds on PHP <= 7.0, but contains all places I found to trigger the deprecation notice.

**Comment by samdark** [comment]
Closing since it will be merged from master into 2.2.

**Pull request closed without merging**
