### PR TITLE
Update QueryBuilder.php

### PR DESCRIPTION
**Pull request by aik84from**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | no |

### CODE REVIEW

**Comment by cebe** [comment]
why?

**Comment by aik84from** [comment]
Added missed phpDoc

**Comment by samdark** [comment]
This isn't needed. `@inheritdoc` means "use docs from parent class".

**Comment by aik84from** [comment]
ok =)

**Pull request closed without merging**
