### PR TITLE
Enable `heredoc_to_nowdoc` rule in php-cs-fixer

### PR DESCRIPTION
**Pull request by rob006**
Continuation of #14100
See https://github.com/FriendsOfPHP/PHP-CS-Fixer

http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc

### CODE REVIEW

**Comment by samdark** [comment]
I think it should be other way around...

**Comment by rob006** [comment]
@samdark Could you elaborate? Changing heredoc to nowdoc is the same kind of change as changing quoting from `"` to `'` (which was already accepted in #14100) - it is a little bit faster and more readable/safe (less risk of accidental variable parsing).

**Comment by samdark** [comment]
Ah. Right. Then it's good.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
