### PR TITLE
fix aliases rendering

### PR DESCRIPTION
**Pull request by np25071984**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17133 

We can now use both notations in aliases definition.
```
public function optionAliases()
{
    return array_merge([
        'n' => 'numMessages',
    ], parent::optionAliases());
}
```

or

```
public function optionAliases()
{
    return array_merge([
        'n' => 'num-messages',
    ], parent::optionAliases());
}
```

### CODE REVIEW

**Comment by GHopperMSK** [comment]
Should  add test for this case?

**Comment by samdark** [comment]
Won't hurt, yes.

**Comment by GHopperMSK** [comment]
I couldn't suppress console output by `ob_start()/ob_get_contents()` statements. That is why I introduced `FakeHelpControllerWithoutOutput` controller. Maybe it isn't an optimal solution.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
