### PR TITLE
Minified SVGs

### PR DESCRIPTION
**Pull request by simialbi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17479, #18559, #18571

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Comment by rob006** [comment]
If we care about size, wouldn't be better to save them as separate files, publish as assets and link using `img` tag? In that way we wouldn't repeat them 50 times on grid with 50 rows.

**Comment by simialbi** [comment]
Is an idea. But if you reference them as separate images, you have 4 requests instead of one. I'm not sure what to prefer...

**Comment by bizley** [comment]
If these very bigger, yes, maybe. In that case I don't see the value in having separate files.

**Comment by My6UoT9** [comment]
For reasons, Github also went with separate svg's. https://github.blog/2016-02-22-delivering-octicons-with-svg/#our-approach

For sake completness:
A grid with 10 rows will not suffer from performance issues.
not sure how many rows it needs; In any case, having inline svg is worse then a img tag referencing a svg.
Reason is its part of the dom, js can interact with it, css can interact with, each svg has to be handled separately in each row.
But browsers are pretty fast by now.

Also it would be more then one request on first load, later its cached.
Lastly like with png's, svg's can also be collected into one file (but as one can see in github's approach, that comes with a different set of problems).
https://w3bits.com/svg-sprites/

**Comment by bizley** [comment]
Hm, if I read it correctly they are using inline svgs and not the files.

**Comment by My6UoT9** [comment]
> Hm, if I read it correctly they are using inline svgs and not the files.

Yeah should had written, I would keep it as is, just inline them.

**Comment by rob006** [comment]
> Is an idea. But if you reference them as separate images, you have 4 requests instead of one. I'm not sure what to prefer...

With HTTP/2 becoming a standard, it should not be a big problem. This is also one-time cost - icons will be cached by browser on firs view and there will be no additional requests on next pageviews.

> If these were bigger, yes, maybe. In that case I don't see the value in having separate files.

Assuming that this is 500 chars per icon overhead, for 50 rows with 3 icons you have 75 kB overhead. And this is for each request - if you display 100 pages, you have 7.5 MB in total. For most of relatively simple grids these icons may easily triple weight of HTML generated by widget.

**Comment by bizley** [comment]
Ok, let's do it like than. What is the preferred way these days? Something like?

```
<svg viewBox=" ">
   <use xlink:href=" "></use>
</svg>
```

**Comment by simialbi** [comment]
> Ok, let's do it like than. What is the preferred way these days? Something like?
> 
> ```
> <svg viewBox=" ">
>    <use xlink:href=" "></use>
> </svg>
> ```

This is inline variant too, the difference is less code, because you put the svg in the shadow root and only reference to it.
I think what they meant is:
```html
<a href="">
    <img src="/path/to/svg.svg">
</a>
```

**Comment by bizley** [comment]
Can we modify svg with color, etc. when it's added as `img`?

**Comment by simialbi** [comment]
Nope

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

Merged since it's already an improvement. Whenever to use separate files is separate question.

**Pull request merged**
