### PR TITLE
Update ActionColumn.php

### PR DESCRIPTION
**Pull request by caboosesw**
Added content to give a clear example to those that don't intuitively know how to set the template property using array notation.

### CODE REVIEW

**Comment by cebe** [comment]
Changed it a bit before merging, thanks!

**Comment by caboosesw** [comment]
We should probably refer to the "array notation" ... but also ... it updated it in the code but not in the online wiki documentation.  Do I need to do something else to refresh that?

This is my first GitHub contribution! Yay!

**Comment by samdark** [comment]
Which wiki documentation are you referring to?

**Comment by caboosesw** [comment]
http://www.yiiframework.com/doc-2.0/yii-grid-actioncolumn.html I was on this page when I hit "edit" and tried to edit the documentation by updating the code comments.


-------- Original Message --------
Subject: Re: [yii2] Update ActionColumn.php (#6811)

**Comment by samdark** [comment]
Ah, it's OK. Docs are updated from time to time but not instantly.

**Comment by cebe** [comment]
> We should probably refer to the "array notation"

This is not necessary because yii uses this syntax in all parts of the documentation.

The documentation on yiiframework.com is updated daily from the github repository, so you should find your changes online tomorrow :)

**Pull request closed without merging**
