### PR TITLE
Bug log migration sqlite bigint autoincrement

### PR DESCRIPTION
**Pull request by dynasource**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #11652 |

### CODE REVIEW

**Comment by samdark** [comment]
Merged https://github.com/yiisoft/yii2/commit/0a60466729661ab1f8429875f096955f88311c42. Thank you!

**Comment by rob006** [comment]
Why remove `AUTOINCREMENT` instead of change `bigint` to `integer`? https://github.com/yiisoft/yii2/issues/11527#issuecomment-218152227

**Comment by samdark** [comment]
I see it as a better alternative.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/7cea46bcb4816b10a15ee945643999b7ddfd9fbe

**Pull request closed without merging**
