### PR TITLE
Exception within useMaster() completely disables slaves

### PR DESCRIPTION
**Pull request by Vovan-VE**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | ~hope yes~ yes
| Fixed issues  | (not reported yet)

### CODE REVIEW

**Comment by samdark** [comment]
Could you elaborate about it?

**Comment by Vovan-VE** [comment]
`Connection::useMaster()` disables slaves by `enableSlaves = false`, than calls callback and restore `enableSlaves` to old value in the end. In case of uncaught exception from a callback `enableSlaves` will not restore.

**Review by samdark — APPROVED** [review]
Looks good to me.

**Review by SilverFire — CHANGES_REQUESTED** [review]
Could you add a CHANGELOG and a test case?

**Review by SilverFire — APPROVED** [review]

**Review by dynasource — APPROVED** [review]
look good. Well done.

**Pull request merged**
