### PR TITLE
Update db-migrations.md

### PR DESCRIPTION
**Pull request by agamayaservers**
добавлено Содержание

### CODE REVIEW

**Comment by cebe** [comment]
@agamayaservers there is no need to add these manually. they will be auto generated on the website.

**Comment by agamayaservers** [comment]
what website? give me direct link to page with auto generated table of contents

**Comment by agamayaservers** [comment]
it is a translation, there is no site for translations now and people read documentation directly from github
add my changes to page please

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/guide-index.html has it auto generated, the russian version is just not out there yet.
I'd consider putting it up somewhere before we have the [new website, which is developed right now](https://github.com/yiisoft-contrib/yiiframework.com).

**Comment by cebe** [comment]
Here you go: http://stuff.cebe.cc/yii2docs-ru/guide-README.html (updated every 15min from master, same as the english version: http://stuff.cebe.cc/yii2docs/guide-README.html)

**Comment by agamayaservers** [comment]
good, thank you!

**Comment by cebe** [comment]
you may also retweet this to spread the word: https://twitter.com/cebe_cc/status/673660269919342593

**Pull request closed without merging**
