### PR TITLE
 Fixed ambiguous error sql while using unique validator

### PR DESCRIPTION
**Pull request by vladis84**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | yes/no
| Tests pass?   | yes
| Fixed issues  | #13842

### CODE REVIEW

**Comment by samdark** [comment]
Helper isn't really good idea and I wanted to discuss it first. You're too fast doing a pull request :) Helpers in general contain methods which could be reused by end users. Active Query helper is rather internal thing and it doesn't really make sense to expose it.

**Comment by vladis84** [comment]
I am think this is an ActiveQuery duty.
Don't know how to do it.

**Comment by samdark** [comment]
Then maybe add it to active query itself?

**Comment by samdark** [comment]
There are `getTableNameAndAlias()` and `alias()` methods which could be relevant.

**Comment by vladis84** [comment]
I will propose options before the end of the week.
I am  want #13799 finish.

**Comment by vladis84** [comment]
I have no other ideas.
Sorry.

**Comment by samdark** [comment]
OK. I'll take care about it. Thank you for contributing.

**Comment by Renkas** [comment]
Any update on this getting merged?

**Comment by samdark** [comment]
@Renkas not yet. Too many other things are in the works. Methods should be moved to ActiveQuery. If you have extra time to do it, please send a pull request.

**Comment by Renkas** [comment]
Unfortunately it's not something I feel comfortable doing. Any chance @vladis84 can finish this up?

Other possibility would be to add a flag to UniqueValidator that would switch on/off prefixing column names with table name. As this functionality was added to cover an edge case - but from my point of view always prefixing with table names affects more developers than not prefixing it.

**Comment by samdark** [comment]
Moved to https://github.com/yiisoft/yii2/pull/14049

**Pull request closed without merging**
