### PR TITLE
Fix validation on missing attributes in DynamicModel

### PR DESCRIPTION
**Pull request by michaelarnauts**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️ (not sure)
| Fixed issues  | #19811 

See #19811 for an explanation.

DynamicModel is made for validating dynamic data. It doesn't make sense to expect that all the attributes are there, since that's exactly what we are trying to validate.

### CODE REVIEW

**Comment by bizley** [comment]
I like it. Tests require update though.

@yiisoft/reviewers what do you think?

**Comment by samdark** [comment]
I like it as well. Do you think this change of behavior may break things?

@rob006 you're good at detecting bad BC breaks. Do you see any in this case?

**Comment by rob006** [comment]
Technically, it could fail if you attach behavior or extend this class and rely on virtual attributes, but I'm not sure if someone is using it like that.

But I don't like breaking `Component` "contract", and I definitely don't like inconsistency between `__get()`, `__set()`, `__isset()` etc. This will also silently ignore any typo in attribute name in rule config. Personally I would rather adjust validators to deal with such cases (undefined attribute) instead of hacking `DynamicModel`.

**Comment by michaelarnauts** [comment]
FYI, for the "default" validator to work, I also had to modify the __set. I didn't do this in this PR yet, since I wanted to wait for the discussion first.

**Comment by rob006** [comment]
Maybe dynamically define missing attributes based on rules passed to `validateData()` (and maybe `addRule()`)? It should fix case from https://github.com/yiisoft/yii2/issues/19811, but model still should behave consistently.

**Comment by bizley** [comment]
@michaelarnauts could you be so kind to check the @rob006 's solution?

**Comment by michaelarnauts** [comment]
@bizley and @rob006 I think this is what you are suggesting.

The original test now still fails (about the undefined attribute), and my added test passes (since the attribute is now defined with value null) when the validator is added.

**Review by samdark — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
