### PR TITLE
Remove hidden input's value attribute in BaseHtml::activeFileInput method

### PR DESCRIPTION
**Pull request by alex-chuev**

### CODE REVIEW

**Comment by AntonYu** [comment]
Agreed with @chuev, it's very strange behavior - if you don't want to upload a new file in actionUpdate(), you should get the old path from $model->getOldAttribute() to save it in a model attribute later.

**Comment by cebe** [comment]
Why do you allow the file path attribute to be set by input from the browser?
Sounds like wrong and insecure usage to me... please give more details about how your code works.

**Comment by AntonYu** [comment]
@cebe,

Model:
```php
public function rules()
{
    return [        
        ['preview', 'image', 'extensions' => ['png', 'jpg', 'jpeg'], 'skipOnEmpty' => true],
    ];
}

public function checkIfFileIsUploaded($attributeName)
{
    $this->$attributeName = UploadedFile::getInstance($this, $attributeName);
    if (null === $this->$attributeName) {
        $this->$attributeName = $this->getOldAttribute($attributeName);
    }
}

public function uploadPreviewFile()
{
    if ($this->preview instanceof UploadedFile) {

        $path = $this->generatePreviewPath();

        $fullPath = \Yii::getAlias('@webroot') . $path;
        if (!is_dir(dirname($fullPath))) {
            mkdir(dirname($fullPath), 0755, true);
        }

        if ($this->preview->saveAs($fullPath)) {
            $this->deleteOldPreview();
            $this->preview = $path;
            return true;
        }
    }

    return false;
}
```

Controller:
```php
public function actionUpdate($id)
{
    $model = $this->findModel($id);

    if (\Yii::$app->request->isPost) {

        $model->load(\Yii::$app->request->post());
        $model->checkIfFileIsUploaded('preview');

        if ($model->validate()) {

            $model->uploadPreviewFile();
            if ($model->save()) {
                return $this->redirect($model->getUrl());
            }
        }
    }

    return $this->render('update', [
        'model' => $model,
    ]);
}
```

**Comment by chuev** [comment]
Attached file name is the same data as other form fields but with one feature - something in a file system. In addition anytime I can check this value on the model validation phase.

**Pull request closed without merging**
