### PR TITLE
Some more tests for Console helper

### PR DESCRIPTION
**Pull request by MysteryDragon**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

Tests added for `Console::input()`, `Console::output()`, `Console::error()`, `Console::prompt()`, `Console::confirm()`, `Console::select()` methods.

### CODE REVIEW

**Comment by MysteryDragon** [comment]
I saw https://travis-ci.org/yiisoft/yii2/jobs/311211156#L814, will think about that. Seems like second try to read something from php://memory stream even after data truncating leads to error in HHVM-3.12...

**Comment by MysteryDragon** [comment]
Looks OK for now.

**Comment by MysteryDragon** [comment]
@samdark actually maybe I will have some time to write some more tests for this helper. You can wait for my signal about implementing that, or I will just create another PR, when it will be ready.
I guess it's about this/next week, not so much time due to New Year dead-lines )

**Review by SilverFire — APPROVED** [review]

**Review by dmirogin — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
