### PR TITLE
Extract messages

### PR DESCRIPTION
**Pull request by rob006**
Alternative for https://github.com/yiisoft/yii2/pull/19996.

In addition to https://github.com/yiisoft/yii2/pull/19996:
1. I tried to fix some translations that has changed placeholder name (see [this diff](https://github.com/rob006/yii2-dev/compare/NabiKAZ/update-all-messages..messages)).
2. Forced order - this PR is hard to review mostly because phrases changed their position. On long run it would be easier to review any change here if all messages will be ordered. Untranslated messages can be easily found by searching for `=> ''`.

### CODE REVIEW

**Comment by rob006** [comment]
BTW: please use "squash and merge" while merging this PR, I used really bad commit messages...

**Comment by NabiKAZ** [comment]
It seems to be merged but I just wanted to clarify.
Two default parameters in config.php have been changed, while it was applied with command line parameters and only for this order.
- The sort of untranslated items is not very interesting and if they are at the same end, they will be seen much better instead of searching through all the files.
- Deleting @@ items is also good, but not as a default, and if they exist by default, and if the user wishes, he can delete them with the relevant parameter.
Anyway, this was my personal opinion.

image

**Comment by rob006** [comment]
@NabiKAZ With fixed order it is much easier to review diff, since it is clear which messages were added, changed or removed. It is not so clear if you start moving messages across the file.

**Comment by bizley** [comment]
I agree with @rob006 - sorted is better

**Comment by NabiKAZ** [comment]
@bizley 
They will sort!
The subject of sort is the untranslated items that used to appear at the end of all translations and were separated so that they were easily visible to the translator.
But now they are mixed with all other translated and untranslated expressions, which makes it difficult to find untranslated items.

**Comment by bizley** [comment]
I don't think this is a big problem. Easy to find with quick search.

**Pull request merged**
