### PR TITLE
Rename bower to bower-asset and npm to npm-asset

### PR DESCRIPTION
**Pull request by mishamx**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Why?

**Comment by rob006** [comment]
This breaks BC. Such adjustment should be made in app template: https://github.com/yiisoft/yii2-app-basic/blob/master/config/web.php#L10-L13

**Comment by mishamx** [comment]
`fxp/composer-asset-plugin` removed, `asset-packagist` use `bower-asset` and `npm-asset`

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii2-app-basic/blob/master/config/web.php#L10-L13

**Pull request closed without merging**
