### PR TITLE
Issue #12580 Make yii.js comply to js strict mode

### PR DESCRIPTION
**Pull request by mikehaertl**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #12580 |

### CODE REVIEW

**Review by samdark — CHANGES_REQUESTED** [review]
Makes sense. Please add a changelog for 2.0.10 and I'll merge it.

**Comment by mikehaertl** [comment]
@samdark Done!

**Review by SilverFire — APPROVED** [review]

**Comment by mikehaertl** [comment]
@samdark @SilverFire Resolved conflicts and force pushed update.

**Comment by SilverFire** [comment]
Thank you!

**Pull request merged**
