### PR TITLE
Updated callout in view of debug.

### PR DESCRIPTION
**Pull request by githubjeka**
There were
image

Became
image

Red color is confusing me and I tried to find errors in logs . Please merge :)

### CODE REVIEW

**Comment by cebe** [comment]
we could apply the status color instead, as it is in the status field.

**Comment by githubjeka** [comment]
Possible. Beginning you can merge my PR, neutral view.

**Comment by samdark** [comment]
Changing color sounds better to me.

**Comment by cebe** [comment]
Thanks!

**Pull request closed without merging**
