### PR TITLE
Update and extract all messages to translate

### PR DESCRIPTION
**Pull request by NabiKAZ**
Some people do not have enough technical knowledge of programming to translate and only translate phrases online on the website.
I ran the `yii message/extract messages/config.php` command to update all translation files and make the untranslated version of all repository statements available on the web.

### CODE REVIEW

**Comment by xicond** [comment]
what is @@{attribute} mean ?

**Comment by NabiKAZ** [comment]
> what is @@{attribute} mean ?

The parts that no longer exist in the source are placed on both sides of the `@@` string, which can be removed in the translation. for example:
```
'{attribute} must be less than "{compareValue}".' => '@@{attribute}, "{compareValue}" dən kiçik olmalıdır.@@',
```

>  * Each array element represents the translation (value) of a message (key).
>  * If the value is empty, the message is considered as not translated.
>  * Messages that no longer need translation will have their translations
>  * enclosed between a pair of '@@' marks.

**Comment by bizley** [comment]
Thanks, indeed it was long overdue. Could you remove the translations with `@@` since we don't use them anymore, and apply alphabetical sorting for each?

**Comment by rob006** [comment]
https://github.com/yiisoft/yii2/pull/19995#issuecomment-1759741100 should be addressed first.

**Comment by NabiKAZ** [comment]
> [#19995 (comment)](https://github.com/yiisoft/yii2/pull/19995#issuecomment-1759741100) should be addressed first.

Merged.
And I'm waiting to this for doing another commit related this.

**Comment by rob006** [comment]
Now there should be no `zh-CN` directory, since there is no such locale in config.

**Comment by NabiKAZ** [comment]
> Now there should be no `zh-CN` directory, since there is no such locale in config.

From the beginning, there was no zh-CN directory.
Now according to my latest commits in this branch, now we only have zh and zh-TW in config and directories.

**Comment by rob006** [comment]
Your PR added zh-CN directory.

c83c0307


Also, some translations could be fixed, since they only have changed placeholder name.

a1513a9c

**Comment by NabiKAZ** [comment]
@rob006 
You're right, I'm sorry I confused you.
This was due to the yii message command that generated it automatically.
- Now `zh-CN` dir has been deleted.
- `master` merged and a conflict has also been resolved.
- As for the `@@`s, I removed them by adding the `--remove-unused` parameter to the corresponding command.

**Comment by rob006** [comment]
@NabiKAZ I created alternative PR with more translations restored: https://github.com/yiisoft/yii2/pull/20022

**Comment by bizley** [comment]
Guys, great job, looks like you managed all here, just tell me which one to merge or both and then in which order. Thank you.

**Comment by rob006** [comment]
@bizley I think you should merge mine - it contains everything here + some fixed translations + reordering.

**Comment by bizley** [comment]
Closing in favour of https://github.com/yiisoft/yii2/pull/20022

**Comment by NabiKAZ** [comment]
I wrote my review here:
https://github.com/yiisoft/yii2/pull/20022#issuecomment-1773848437

**Pull request closed without merging**
