### PR TITLE
Update yii.activeForm.js

### PR DESCRIPTION
**Pull request by depesr**
Patch for yii activeForm javascript to validate all fields dependless on their status attribute.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by SilverFire** [comment]
It is by design and prevents validation of fields that were not changed.
The PR will not be accepted, sorry.

**Comment by depesr** [comment]
@SilverFire Well, the thing is this.
I have one field which is conditionally required when other field has an exact value.
I change the other field to that exact value and the first one won't get error message unless focused and defocused?
Is there any other way to get the error message shown? The validation message from ajax validation is correctly in the response, just the javascript won't show it.

**Comment by SilverFire** [comment]
Your use case is partially related to issue #9811

See 
https://github.com/yiisoft/yii2/issues/10700#issuecomment-176647176
https://github.com/yiisoft/yii2/issues/9500#issuecomment-166013061

**Comment by depesr** [comment]
Didn't help :(
Can't trigger entire form ajax validation using javascript. But that's not the issue. The ajax validation works ok, it returns json with error message. The issue is that the error message won't show since yii.activeForm.js just shows messages for fields that are changed.

I've created an issue: https://github.com/yiisoft/yii2/issues/13648

**Pull request closed without merging**
