### PR TITLE
Add getFile method for $request

### PR DESCRIPTION
**Pull request by 243083df**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by 243083df** [comment]
According to https://github.com/yiisoft/yii2/wiki/Plan-for-next-major-versions

**Comment by samdark** [comment]
It could be added to 2.0.13 instead of 2.1.

**Comment by cebe** [comment]
should not be limited to one method but all static methods in `UploadedFile` should be integrated into request in some way.

**Comment by klimov-paul** [comment]
I suppose a new class called `UploadedFileCollection` should be introduced instead of static methods at `UploadedFile`. It can be integrated into `Request` in the same way as `HeaderCollection`.
The final interface will be:

```php
$uploadedFile = Yii::$app->request->uploadedFiles->getByName('foo');
```

**Comment by samdark** [comment]
There's PSR-7 interface for that btw. http://www.php-fig.org/psr/psr-7/

**Comment by samdark** [comment]
```php
function getUploadedFiles()
{
    // returns an array similar to $_FILES where, instead of arrays
    // there are instances of Psr\Http\Message\UploadedFileInterface
}
```

Since it's likely that we'll adopt PSR-7 in the future, I'd name the method in a similar way i.e. `getUploadedFile()`.

**Review by dynasource — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by klimov-paul** [comment]
Resolved via #14801

**Pull request closed without merging**
