### PR TITLE
Possbible pjax form event selector to be changed

### PR DESCRIPTION
**Pull request by ghost**
I have added a new variable that makes it possible to change the selector on the .on() function that used to call the submit for a form with pJax.

### CODE REVIEW

**Comment by samdark** [comment]
What's use case for it?

**Comment by Bvanleeuwen** [comment]
Yesterday I was developing a search box that is in a pjax container, and we would like the event selector to have a different selector then submit, since we have no submit button visible. We would like it to be keyup or change (we are still discussing that internal).

**Comment by samdark** [comment]
OK. Makes sense.

**Comment by samdark** [comment]
Merged: https://github.com/yiisoft/yii2/commit/1dc688e35f4b918a44e2159bb4fe6e41017aea28. Note that the name of the property was changed.

**Comment by nevermnd** [comment]
This commit broke pjax form submit. The following javascript is being registered:
```js
jQuery(document).on('"submit"', "#form-historico", function(event) {
    jQuery.pjax.submit(event, '#w1', {
        "push": true,
        "replace": false,
        "timeout": 2000,
        "scrollTo": false
    });
});
```

**Comment by Bvanleeuwen** [comment]
Strange, it did work for me when I created it, I see what is wrong, and I will fix it tomorrow.

**Pull request closed without merging**
