### PR TITLE
Remove deprecated method `className()` for branch `2.2`.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Review by machour — APPROVED** [review]

**Review by rhertogh — APPROVED** [review]

**Comment by rhertogh** [comment]
yii2-gii has the option to use the class constant or not in the model generator (https://github.com/yiisoft/yii2-gii/blob/master/src/generators/model/Generator.php#L53).
It won't cause immediate problems since the composer.json specifies `"yiisoft/yii2": "~2.0.46"` but this PR will brake that setting in the future.
I think it would be good to have a central place to keep track of these breaking changes. We could, for example, create an issue in the yii2-gii repo and add a Yii2.2 milestone.
@samdark What do you think about it?

**Comment by terabytesoftw** [comment]
> Yii2-GII tiene la opción de utilizar la constante de clase o no en el generador de modelos (https://github.com/yiisoft/yii2-gii/blob/master/src/generators/model/Generator.php#L53). No causará problemas inmediatos ya que el composer.json especifica, pero este PR frenará esa configuración en el futuro. Creo que sería bueno tener un lugar central para hacer un seguimiento de estos cambios de última hora. Podríamos, por ejemplo, crear un problema en el repositorio yii2-gii y agregar un hito Yii2.2. ¿Qué opinas al respecto?`"yiisoft/yii2": "~2.0.46"`

If it is a good suggestion create the `2.2` branch. in all `yii2` repositories, and run tests with the `2.2` branch, and update all changes.

**Review by Arhell — APPROVED** [review]

**Comment by schmunk42** [comment]
This creates also a lot of problems with 3rd party extensions, making it quite impossible to upgrade existing apps.

Could we just keep in `BaseObject.php` (for now):

```
    public static function className()
    {
        return get_called_class();
    }
```

Maybe with an additional `Yii::info(...)` call.

**Comment by mtangoo** [comment]
@schmunk42 if we do that, then we will have problems as there will always be extension lagging.
That change can be fixed with simple search/replace and any extension unwilling to do that shouldn't really be considered as maintained.

Best option is letting extensions update themselves for that change

**Comment by schmunk42** [comment]
> shouldn't really be considered as maintained.

I basically agree, but it's the reality.
There are also cases where this might be patched in an extension, but you still need an older version due to other constraints.

It's a fine line between BC and using more clean code.

But this is a huge blocker for existing projects. And makes it impossible just to test `2.2` for a lot of existing stuff.
In our case we'd have to override `BaseObject` in a very ugly way, since we can't fork a dozen repos just for a search and replace.

How about something like:
```
if (YII_ENABLE_20_BC_MODE) {
    public static function className()
    {
        return get_called_class();
    }
}
```
it has not to stay there forever, but would give developers the opportunity to have a more graceful way of upgrading.
PHP usually does the same for `x.0` versions, hence the bigger problems with `8.1` and `8.2` atm.

**Comment by terabytesoftw** [comment]
> > shouldn't really be considered as maintained.
> 
> I basically agree, but it's the reality. There are also cases where this might be patched in an extension, but you still need an older version due to other constraints.
> 
> It's a fine line between BC and using more clean code.
> 
> But this is a huge blocker for existing projects. And makes it impossible just to test `2.2` for a lot of existing stuff. In our case we'd have to override `BaseObject` in a very ugly way, since we can't fork a dozen repos just for a search and replace.
> 
> How about something like:
> 
> ```
> if (YII_ENABLE_20_BC_MODE) {
>     public static function className()
>     {
>         return get_called_class();
>     }
> }
> ```
> 
> it has not to stay there forever, but would give developers the opportunity to have a more graceful way of upgrading. PHP usually does the same for `x.0` versions, hence the bigger problems with `8.1` and `8.2` atm.

For now we can keep it in `BaseYii` without deprecesiacion giving everyone time to change.

**Comment by mtangoo** [comment]
>How about something like:

>```php if (YII_ENABLE_20_BC_MODE) {
>    public static function className()
>    {
  >      return get_called_class();
    >}
>}```

I think we can keep without adding the constant check. But with deprecation to warn people that it is going away!

**Comment by mtangoo** [comment]
> > > shouldn't really be considered as maintained.
> > 
> > 
> > I basically agree, but it's the reality. There are also cases where this might be patched in an extension, but you still need an older version due to other constraints.
> > It's a fine line between BC and using more clean code.
> > But this is a huge blocker for existing projects. And makes it impossible just to test `2.2` for a lot of existing stuff. In our case we'd have to override `BaseObject` in a very ugly way, since we can't fork a dozen repos just for a search and replace.
> > How about something like:
> > ```
> > if (YII_ENABLE_20_BC_MODE) {
> >     public static function className()
> >     {
> >         return get_called_class();
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it has not to stay there forever, but would give developers the opportunity to have a more graceful way of upgrading. PHP usually does the same for `x.0` versions, hence the bigger problems with `8.1` and `8.2` atm.
> 
> For now we can keep without deprecated giving everyone time to change.

How are people going to notice that the function will be going away without deprecation?

**Comment by terabytesoftw** [comment]
> > > > shouldn't really be considered as maintained.
> > > 
> > > 
> > > I basically agree, but it's the reality. There are also cases where this might be patched in an extension, but you still need an older version due to other constraints.
> > > It's a fine line between BC and using more clean code.
> > > But this is a huge blocker for existing projects. And makes it impossible just to test `2.2` for a lot of existing stuff. In our case we'd have to override `BaseObject` in a very ugly way, since we can't fork a dozen repos just for a search and replace.
> > > How about something like:
> > > ```
> > > if (YII_ENABLE_20_BC_MODE) {
> > >     public static function className()
> > >     {
> > >         return get_called_class();
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it has not to stay there forever, but would give developers the opportunity to have a more graceful way of upgrading. PHP usually does the same for `x.0` versions, hence the bigger problems with `8.1` and `8.2` atm.
> > 
> > 
> > For now we can keep without deprecated giving everyone time to change.
> 
> How are people going to notice that the function will be going away without deprecation?

You are so right.

**Comment by rhertogh** [comment]
@schmunk42 
> This creates also a lot of problems with 3rd party extensions, making it quite impossible to upgrade existing apps.

I agree with this, but could we do the following:

```php
public static function className()
{
        return static::class;
}
```
Then we have at least some benefits of the newer PHP version 😅.

**Pull request merged**
