### PR TITLE
Fix #17147: Correct form validations for empty select (fixes #16253)

### LINKED ISSUE #16253: Required client validation don't work when checkboxlist items is an empty array.
### Code of ClassificationForm Model:
```php
    public $class_id;
    public $students;

    public function rules()
    {
        return [
            [['class_id', 'students'], 'required'],
        ];
    }
    public function attributeLabels()
    {
        return [
            'class_id' => Yii::t('school', 'Classroom'),
            'students' => Yii::t('school', 'Students'),
        ];
    }
```
### Code of action:
```php
    public function actionClassification()
    {
        $model = new ClassificationForm();
        $students = UserStudent::find()->all();
        $classrooms = Classroom::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->validate()){
            // do classification
        }

        return $this->render('_classification_student', [
            'model' => $model,
            'students' => $students,
            'classrooms' => $classrooms,
        ]);
    }
```

### Code of view:
```php
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'students')->checkboxList(ArrayHelper::map($students, 'id', 'national_code')) ?>

    <?= $form->field($model, 'class_id')->dropDownList(ArrayHelper::map($classrooms, 'id', 'title'), [
        'prompt' => Yii::t('school', 'Choose a classroom...'),
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('school', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
```
### What is the expected result?
show client validation error for checkboxlist and prevent of post form.
screenshot from 2018-05-09 17-38-51

### What do you get instead?
not showing error (Students cannot be blank.), when $students is an **empty** array
screenshot from 2018-05-09 17-27-57
and allow to post form and then serverside validation return false and now show error message for checkboxlist.
screenshot from 2018-05-09 17-29-26

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2.4-1
| Operating system | Ubuntu 18.04 LTS

### LINKED ISSUE #17147: 2.0.16 breaks certain select2 fields validation in active form
Just found that since upgrade 2.0.16 my select2 fields with ajax option are no longer validated. Those with preset data still are. No JS errors in console. Downgraded to 2.0.15.1 and got my forms working again.

### PR DESCRIPTION
**Pull request by kartik-v**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #16253, #17147

### CODE REVIEW

**Comment by samdark** [comment]
@GHopperMSK, @HenryVolkmer, @buttflattery would you please check this pull request against your codebases? Thanks.

**Comment by samdark** [comment]
@kartik-v is it possible to cover desired behavior with tests so it's won't break in the future?

**Comment by kartik-v** [comment]
> @kartik-v is it possible to cover desired behavior with tests so it's won't break in the future?

I did test it with a sample view file with various SELECT DROPDOWN scenarios to check the code above. I have not submitted tests here on this repo earlier - if someone can help/guide on that.

**Comment by kartik-v** [comment]
Here is the testing I did on my environment for 12 dropdown input MODEL attributes which has `required` validator set for all.

The TEST RESULTS are in comments.

```php
use yii\widgets\ActiveForm;
use yii\helpers\Html;

$form = ActiveForm::begin();
// Selection: Single; Options: Empty; Required: TRUE; Size: 1
// TEST RESULT: Fires native required validation. SKIPS model required validator. 
// Always sets REQUIRED MODEL VALIDATION to TRUE.
echo $form->field($model, 'dropdown_1')->dropdownList([] , [
    'required' => true
]);

// Selection: Multiple; Options: Empty; Required: TRUE; Size: 1
// TEST RESULT: Fires native required validation and validates model REQUIRED validator correctly
echo $form->field($model, 'dropdown_2')->dropdownList([] , [
    'multiple' => true,
    'required' => true
]);

// Selection: Single; Options: Empty; Required: FALSE
// TEST RESULT: Fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_3')->dropdownList([] , [
    'required' => false
]);

// Selection: Multiple; Options: Empty; Required: FALSE
// TEST RESULT: Fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_4')->dropdownList([] , [
    'required' => false,
    'multiple' => true
]);

// Selection: Single; Options: 2 records; Required: TRUE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_5')->dropdownList(['a' => 'Option A', 'b' => 'Option B'] , [
    'required' => true
]);

// Selection: Single; Options: 2 records; Required: TRUE; Size: 2
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_6')->dropdownList(['a' => 'Option A', 'b' => 'Option B'] , [
    'required' => true,
    'size' => 2
]);


// Selection: Single; Options: 1 record with empty value (PROMPT); Required: TRUE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_7')->dropdownList([] , [
    'required' => true,
    'prompt' => 'Select...'
]);

// Selection: Multiple; Options: 1 record with empty value (PROMPT); Required: TRUE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_8')->dropdownList([] , [
    'multiple' => true,
    'required' => true,
    'prompt' => 'Select...'
]);

// Selection: Single; Options: Normal data with PROMPT; Required: TRUE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_9')->dropdownList(['a' => 'Option A', 'b' => 'Option B'] , [
    'required' => true,
    'prompt' => 'Select...'
]);

// Selection: Multiple; Options: Normal data with PROMPT; Required: TRUE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_10')->dropdownList(['a' => 'Option A', 'b' => 'Option B'] , [
    'multiple' => true,
    'required' => true,
    'prompt' => 'Select...'
]);

// Selection: Single; Options: Normal data with PROMPT; Required: FALSE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_11')->dropdownList(['a' => 'Option A', 'b' => 'Option B'] , [
    'required' => false,
    'prompt' => 'Select...'
]);

// Selection: Multiple; Options: Normal data with PROMPT; Required: FALSE
// TEST RESULT: Fires native required validation and fires model REQUIRED validator correctly
echo $form->field($model, 'dropdown_12')->dropdownList(['a' => 'Option A', 'b' => 'Option B'] , [
    'multiple' => true,
    'required' => false,
    'prompt' => 'Select...'
]);

echo '<hr>';
echo Html::submitButton('Submit', ['class' => 'btn btn-primary']) . ' ';
echo Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']);
ActiveForm::end(); 
echo '<hr>';
echo Html::submitButton('Submit', ['class' => 'btn btn-primary']) . ' ';
echo Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']);
ActiveForm::end(); 
```

**Comment by buttflattery** [comment]
```
 if (top < 0) {
    top = 0;
} else {
    if (top > $(document).height()) {
          top = $(document).height();
    }
}
```
@kartik-v you can change the above code block to the following to avoid cyclomatic complexity 

```
top<0?0:(top>$(document).height()?$(document).height():top);
```

**Comment by buttflattery** [comment]
@rob006 that code block was in reference to the cod climate highlighted issue, is there something wrong in that suggestion?

**Comment by kartik-v** [comment]
> @rob006 that code block was in reference to the codeclimate highlighted issue, i missed one thing that i have updated now, is there anything else wrong in that suggestion?

@buttflattery - that code snippet you pointed was something that existed even before and not changed as part of this PR. Not sure why that needs to be changed though.

**Comment by kartik-v** [comment]
> @rob006 that code block was in reference to the codeclimate highlighted issue, i missed one thing that i have updated now, is there anything else wrong in that suggestion?

Corrected that part of the snippet (even though it was not an impacted area as part of the PR - seems the IDE had autoformatted in last run).

**Comment by buttflattery** [comment]
@kartik-v  the merge was blocked by the only issue codeclimate was pointing to
> Avoid deeply nested control flow statements.

 so i thought i might add my input if that fixes and allows the merging.

**Comment by rob006** [comment]
> @rob006 that code block was in reference to the codeclimate highlighted issue, i missed one thing that i have updated now, is there anything else wrong in that suggestion?

It does not reduce cyclomatic complexity, since this is exactly the same condition, only converted to ternary syntax, which usually less readable (especially if you nest them).

**Comment by samdark** [comment]
Thank you for working on it!

**Comment by lukegradtouch** [comment]
thanks for fixing this guys

is there any kind of expected time when 2.0.37 will be released with this patched? we're kind of ancy for the fix :D

**Comment by samdark** [comment]
@lukegradtouch I plan doing it this week but not sure all the issues planned will be OK by that time.

**Comment by lukegradtouch** [comment]
that would be fantastic, thank you :)

**Comment by lukegradtouch** [comment]
thank you, can confirm this fixes our issue :D

**Pull request merged**
