### PR TITLE
Just move Identity Cookie code into separate functions in web\User.php

### PR DESCRIPTION
**Pull request by ghost**
OK.  This just creates two new protected functions that separate out the cookie functions.

### CODE REVIEW

**Comment by samdark** [comment]
It seems to be changing behavior. Not time to verify it for 2.0.6.

**Comment by maine-mike** [comment]
OK.

**Comment by samdark** [comment]
Doesn't look merge-able to me.

**Comment by maine-mike** [comment]
Can you tell me why?

**Comment by samdark** [comment]
1. It changes behavior.
2. Extracted method name doesn't match return value.
3. The scope of extraction is questionable.

**Comment by maine-mike** [comment]
Would you please explain those three things?

What behavior is changed?

**Comment by samdark** [comment]
This: https://github.com/yiisoft/yii2/pull/8714/files#diff-12395c67a35c91aa5fc9ac3f6554375fR591

There are more issues. For example, https://github.com/yiisoft/yii2/pull/8714/files#diff-12395c67a35c91aa5fc9ac3f6554375fR570. Parameter isn't used anywhere.

**Comment by maine-mike** [comment]
OK.  Thanks for letting me know.

The first thing I considered a bug.  If a call is made to switchIdentity with duration > 0, then a cookie is created.  If the next call to switchIdentity has duration = 0 then the cookie isn’t removed.  So I’ll report this as a bug separately.

The $identity variable is passed to sendIdentityCookie, so I thought it would make sense to pass it to removeIdentityCookie.  My implementation of cookie logins uses information in the $identity variable in both the sendIdentityCookie and removeIdentityCookie procedures.  $identity is obtainable though other means, so I can remove that.

Thanks for explaining this to me.  I’ll report that bug and see how that goes.

Mike.

**Comment by samdark** [comment]
OK.

**Pull request closed without merging**
