### PR TITLE
Add start looking ahead ar doc

### PR DESCRIPTION
**Pull request by aneeshikmat**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by aneeshikmat** [comment]
Thank you @samdark 

Hi @cebe , Depends of your comment [here](https://github.com/yiisoft/yii2/pull/16784), I ping you, After accept start-looking-ahead by @samdark, we can say all **start-*.md** was added to Arabic guide. Thanks.

**Comment by cebe** [comment]
I also noted that you have used `<pre>` tags instead of `<code>` for inline code blocks, this results in the text to be broken into lines.

**Comment by aneeshikmat** [comment]
Thank you @cebe for interested, about your question I can say:

1. I use `dir="rtl"` to make display text from right to left in github, I read how I can make text dispay from right and I found I need to set direction and work like Html player.
2. In yii website, its not necessary, Thats true:D
3. Sure I will, and I will replace all `div` in all translation page to `span`.
4. About using `<pre>` I think its used in mistake...Since I use `<code>` tag most time...I will find `<pre>` tag where is it used and replace it. 

If I need to work in these changes, Would you like to I create a new branch or I use **WIP arabic guide** branch?

Many Thanks

**Comment by aneeshikmat** [comment]
Please noted, I remember why I using `div` nested of `span`, If I set `span` the direction will not work truth, since its inline, and `div` is a block...so that the direction will be work in block element only....so that how would you like to fix issue? would you like to keep it in `div` or using inline style like` display:block` inside `span`...?

**Comment by aneeshikmat** [comment]
Thank you!

**Comment by cebe** [comment]
I merged and deployed https://github.com/yiisoft-contrib/yiiframework.com/pull/411, please check it on the website and report if there is anything broken.

**Comment by aneeshikmat** [comment]
Sure I will, Thank you :D

**Comment by aneeshikmat** [comment]
I found some issue: 
1) Main Grid Need Reflection from left to right in [main page](https://www.yiiframework.com/doc/guide/2.0/ar). for example: "المقدمة" most be in first column from right.
 
2) Internal links issue. for example: https://www.yiiframework.com/doc/guide/2.0/guide/db-active-record.md - this issue received since I set anchor tag like this in Arabic guide `<a href="../guide/db-active-record.md">action</a>`, I use this way to keep Arabic guide reference to updated English guide...so that what do you like to I do with this? 

3) Search in Guide for Arabic dose not return any results like search "تثبيت".

I fix some issue too in this [branch - Fixing Arabic Guide WIP issues](https://github.com/aneeshikmat/yii2/tree/fixing-arabic-guide-wip-issue/docs/guide-ar).

Note: Im try to find `<pre>` tag in our Readme, I not found where it, if you can reference me to page. thanks.

**Comment by cebe** [comment]
1 and 2 should be fixed by https://github.com/yiisoft-contrib/yiiframework.com/commit/10381ae21d21245ad652db7fad4d66cc9846074e now.

3 could be caused by Arabic language not being set up in elasticsearch. added a comment here: https://github.com/yiisoft-contrib/yiiframework.com/issues/254#issuecomment-446928814



> Note: Im try to find `<pre>` tag in our Readme, I not found where it, if you can reference me to page. thanks.

https://www.yiiframework.com/doc/guide/2.0/ar/start-installation#verifying-installation
below the image.

`start-installation.md` line 173 and following.

**Comment by aneeshikmat** [comment]
Thank you @cebe, Its Perfect!

I fixing related issue too, and I pull #16963  to Yii.
If you have any note, issue in any time I will be happy to doing my best to improve this community.
 
My next step is share this update and try to got Arabic Yii Developer to contribute Arabic guide, and I/WE will continue work in translation.

Many Thanks cebe!

**Pull request merged**
