### PR TITLE
Converts empty string (char) to null value in dbTypecast

### PR DESCRIPTION
**Pull request by ezoterik**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |

This problem has appeared after closing #9562

### CODE REVIEW

**Comment by SilverFire** [comment]
I'll build a test for SchemaColumn

**Comment by ezoterik** [comment]
@SilverFire, @samdark pushed the same fix https://github.com/yiisoft/yii2/issues/11532 (earlier I could`t find this issue). This request can be rejected...

**Comment by githubjeka** [comment]
You have a test. You have power. But it is only in the world ponies.:stuck_out_tongue:

**Comment by samdark** [comment]
@ezoterik oh, sorry. I wasn't aware that you've pull requested. A test definitely should be merged.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/515732c7b8c5527720592fc87747657de659f1f5

**Comment by githubjeka** [comment]
It's magic.

**Comment by githubjeka** [comment]
No sun. It's Git power.

**Pull request closed without merging**
