### PR TITLE
Fix initializing db component configuration

### PR DESCRIPTION
**Pull request by bizley**
Follow-up of #18472

### CODE REVIEW

**Comment by bizley** [comment]
Yup, some tests need fixing.

**Review by samdark — APPROVED** [review]

**Comment by rob006** [comment]
This does not look right. If `db` is `null`, connection should be inherited from related AR in Query:

https://github.com/yiisoft/yii2/blob/5995edb6703c0dc7dd4da11050076dcf2fff7b0e/framework/db/ActiveQuery.php#L323-L325

Now it is always overwritten by `Yii::$app->db` by data provider, ignoring connection returned by `ActiveRecord::getDb()`.

/cc @bizley @samdark

**Comment by bizley** [comment]
Hmm, right. Looks like it's a deadlock then regarding the initialization.

How about we update the doc for this property and initialize it only when it's set to not-null?

**Comment by samdark** [comment]
Alright.

**Pull request merged**
