### PR TITLE
Fix migration with a comment containing an apostrophe

### PR DESCRIPTION
**Pull request by CheckeredFlag**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | not tested
| Fixed issues  | #15866

### CODE REVIEW

**Comment by SilverFire** [comment]
Good job! Could you add a test [like this](https://github.com/yiisoft/yii2/blob/1a74b3d4f8fce600aa4369b8ba26c9f9d8c8ac82/tests/framework/db/mysql/QueryBuilderTest.php#L62-L66) to ensure your fix works properly?

**Comment by MarcoMoreno** [comment]
I'd be happy to do add a test but I've never used phpunit and don't know what I'm doing.

I've set up the testing environment as described [here](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md).  I then ran tests via `phpunit --group=console` but I get a number of failures even before making any changes.  They all seem to be related to json so I presume it is because I'm running MAMP which includes MySQL 5.6 that lacks json support.  Must I upgrade to MySQL 5.7?

I also don't know what my test code should look like.  Is this correct?
```php
[
    Schema::TYPE_PK . " COMMENT 'testing ''quote''' AFTER `col_before`",
    $this->primaryKey()->comment('testing \'quote\'')->after('col_before'),
    "int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'testing ''quote''' AFTER `col_before`",
],
```
Does this test compare 3 ways of writing the same thing?
Is it ok to submit a test even if I can't get phpunit to pass?

Thanks for your help!  I'm learning....

**Comment by SilverFire** [comment]
> I've set up the testing environment as described here. I then ran tests via phpunit --group=console but I get a number of failures even before making any changes. They all seem to be related to json so I presume it is because I'm running MAMP which includes MySQL 5.6 that lacks json support. Must I upgrade to MySQL 5.7?

You can run only the test you are changing just to make sure it works. Try this:

```bash
phpunit --group=mysql --filter=testGetColumnType --debug
```

> Does this test compare 3 ways of writing the same thing?

Yes, and test checks, that it is consistent. Look [here](https://github.com/yiisoft/yii2/blob/1a74b3d4f8fce600aa4369b8ba26c9f9d8c8ac82/tests/framework/db/QueryBuilderTest.php#L1052). It's the place where this three-elements array is being interpreted.



> Is it ok to submit a test even if I can't get phpunit to pass?

Yes, Travis runs tests when you commit to branch with pull request and will email you if something goes wrong.

> Thanks for your help! I'm learning....

You're welcome. We are happy to see contributors that are interested in mastering framework and knowledge.

**Review by samdark — APPROVED** [review]
Please add a line for changelog. Thanks.

**Comment by MarcoMoreno** [comment]
Should I add this under the 2.0.14.2 section?  Or create a new 2.0.15 section since that is the milestone assigned to this?

Sorry, this is my first PR for Yii and I'm learning the ropes.

**Comment by SilverFire** [comment]
We already have a section for 2.0.15 in changelog. Merge master branch in your `quotefix` branch:

```bash
git checkout master
git fetch upstream
git pull upstream/master
git checkout quotefix
git merge master
git push
```

**Review by dmirogin — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
