### PR TITLE
Menu widget active with Closure #19060

### PR DESCRIPTION
**Pull request by atrandafir**
Menu parent active status gets broken for the rest of the items when using Closure for one item #19060

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #19060

### CODE REVIEW

**Comment by samdark** [comment]
@atrandafir is that possible to add some tests for this case so it's not broken again?

**Comment by samdark** [comment]
Also would need a line for CHANGELOG to merge it.

**Comment by atrandafir** [comment]
@samdark added the tests and also updated the CHANGELOG

Had to change the mock from application to webApplication to find a way to actually make the widget check for `real urls` in order to be able to test the `active` item behavior.

**Review by samdark — APPROVED** [review]

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
