### PR TITLE
Update validateAttribute for PHP 8.1

### PR DESCRIPTION
**Pull request by samuelexyz**
In function validateAttribute call_user_func does not control if $value is null

Added control to fix

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  |  ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by samuelexyz** [comment]
In PHP 8.1 we need to check if argument of a function is not null, when try to generate code with gii throw an error 

PHP Deprecated Warning – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
trim(): Passing null to parameter #1 ($string) of type string is deprecated
image

**Review by samdark — APPROVED** [review]
Please add a line for CHANGELOG. Thanks.

**Comment by samuelexyz** [comment]
@samdark Added to Changelog

Thanks

**Review by Arhell — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Comment by samdark** [comment]
Hmm... seems it broke existing tests: https://github.com/yiisoft/yii2/commit/d056c7f209c3e14c36959225383b0ca4aaaf171f

**Comment by samdark** [comment]
Re-checked and reverted. The error depends on what's in the `$this->filter` so it's a case specific to Gii and should be fixed there instead.

**Pull request merged**
