### PR TITLE
[WIP] Securing and simplification advanced app template deployment using famous "dotenv" approach

### PR DESCRIPTION
**Pull request by creocoder**
More information: https://github.com/vlucas/phpdotenv

What it give us:
- sensitive credentials storing approach
- deployment simplification (for single devs and teams)

### CODE REVIEW

**Comment by creocoder** [comment]
@qiangxue, @samdark, @cebe What you think about this?

**Comment by creocoder** [comment]
Hmm... looks like "dotenv" approach makes directory "environments" completely useless and we can have all features by eliminating this directory.

**Comment by creocoder** [comment]
Rethink my mind. This complettely changes deploy procedure and probably better provide it as alternate 3rd party application template.

**Comment by cebe** [comment]
http://phundament.com/ by @schmunk42 uses dotenv afaik.

**Comment by schmunk42** [comment]
Yes, Phundament uses .dotenv.
It's also true, that we had to change the app configuration-setup.

Give it a try, it's very close to a stable release and well tested and documented.

**Comment by creocoder** [comment]
@schmunk42 Its based on basic application template which it not fit mine needs. Anyway thanks :)

**Comment by a-komarev** [comment]
.dotenv applicable only for DEV environment, am I right?

**Comment by creocoder** [comment]
@a-komarev No, its for any environment.

**Comment by schmunk42** [comment]
@creocoder I had the advanced template, but switched back to basic layout - personally I think the advanced layout has a lot of problems regarding too much complexity (especially configuration and dockerization).

But I'd really like to hear your concerns, if you'd like to send me an email: schmunk@usrbin.de or create an issue here https://github.com/phundament/app/issues

**Comment by a-komarev** [comment]
@creocoder I've found earlier this repo which using .env: https://github.com/trntv/yii2-starter-kit
Could be useful.

**Comment by creocoder** [comment]
@schmunk42 You have really cool replace for basic layout. But basic and advanced have different scopes. In reality its possible to fit any application into basic (using modules concept), but smart "tiers" usage will give less and clean code.

@a-komarev I saw this already. Its really strange for me. `.env` concept complettely replace `environments` directory solution, but this templates contains both o_O

I decided try to introduce my own vision of advanced enhancement inside https://github.com/creocoder/yii2-app-ninja. Currently there is only environments approach replaced, but i have big plans on it ;)

**Comment by schmunk42** [comment]
> smart "tiers" usage will give less and clean code.

@creocoder What are smart tiers ... backend, frontend, console, common? And why smart?

**Comment by samdark** [comment]
They aren't that "smart". Just tiers i.e. to separate stuff that's likely to be used separately.

**Comment by trntv** [comment]
> Its really strange for me. .env concept complettely replace environments directory solution, but this template contains both o_O

It is strange for me too :-) At the very begining i've used my own environment concept, then moved to ``*-local`` and after it i found that ``.env`` is very convinient to share configuration between yii and node.js services. Now i abandon ``environments`` folder too, because it was redundant.

**Comment by creocoder** [comment]
@schmunk42 , @samdark I does not mean "tiers" smart itself, i mean it can be used smart and give better results than using *application dependent* modules. Ofcourse everything depends on task. But for example when at least REST api necessity come, basic times momentally over.

**Comment by schmunk42** [comment]
> But for example when at least REST api necessity come, basic times momentally over.

In our current project we have an API and this was a main reason why we switched back to basic. Having two separate apps (also repos).

Do you mean you rather have an API "tier" in your application, than having two applications or an api module?

**Comment by creocoder** [comment]
> Do you mean you rather have an API "tier" in your application, than having two applications or an api module?

Ofcource and "tiers" is main idea when advanced born. In relity tier is just separated application which can use some shared code between other tiers. I see strengh of advanced template in common part. It allow build more interesting solutions from architectural point of view than 2 independent applications in 2 separate repos or using module for api. Usually common (shared) part is M layer.

> and this was a main reason why we switched back to basic, using two separate apps (also repos).

Ok, what with M layer than? Its dublicated? If not and if M layer shared i see no difference between that solution and advanced template principles. Just another variation of it.

**Comment by creocoder** [comment]
@schmunk42 Btw api tier itself usually need its own modules for versioning. If implement api tier itself as module you'll come to nested modules. And for me any nesting automatically means some wrong architectural smells (analog of code smells).

**Comment by samdark** [comment]
@schmunk42 tiers in advanced app are actually applications.

**Pull request closed without merging**
