### PR TITLE
Closes #16411. Fix windows tests

### LINKED ISSUE #16411: Fix Windows tests
Currently AppVeyor tests fail but not to fail the whole build these are displaying as success. The tests failing should be either fixed in the frameowork on in tests themselves. Then `allow_failures` should be removed from `.appveyor.yml`.

### PR DESCRIPTION
**Pull request by alexkart**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16411

### CODE REVIEW

**Comment by samdark** [comment]
Still some failures: https://ci.appveyor.com/project/samdark/yii2/builds/25361717#L286

**Comment by alexkart** [comment]
> Still some failures: https://ci.appveyor.com/project/samdark/yii2/builds/25361717#L286

Yes, I know, it's a draft PR, I'm still working on it.

**Comment by alexkart** [comment]
Ready for review.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
