### PR TITLE
Optimize `yii\db\ActiveRecord::tableName()`

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by WinterSilence** [comment]
@rob006 any ideas why tests are failed?

**Comment by rob006** [comment]
This is how static properties work in PHP - `ActiveRecord::$_tableName` will be used regardless of class used to call `tableName()`.

You need to solve this in the same way as in `StaticInstanceTrait`:

https://github.com/yiisoft/yii2/blob/03235e6c12010441e360c8e4c336cee0b5cbba5b/framework/base/StaticInstanceTrait.php#L37

**Comment by WinterSilence** [comment]
@rob006 you are not confusing with `self::$_tableName`?

**Comment by WinterSilence** [comment]
@rob006 can you check problem in https://github.com/yiisoft/yii2/runs/4092203996?check_suite_focus=true?

**Pull request closed without merging**
