### PR TITLE
Bug in yii\db\mysql\QueryBuilder class

### PR DESCRIPTION
**Pull request by DrmagicE**
In the insert() function,the $columns should be an array for the foreach.
Here is a simple fix that just turns the param into an array.

An example for reproducing the bug:

``` sql
-- (without a  primary key)
create table `yiitest`（
     `test`  int(11) default 1
）
```

//The code below will throw a warning

``` php
Yii::$db->createCommand()->insert('yiitest',[]);
```

### CODE REVIEW

**Comment by klimov-paul** [comment]
Need a CHANGELOG line.

**Comment by cebe** [comment]
a unit test would be nice too.

**Comment by DrmagicE** [comment]
@klimov-paul I have added the CHANGELOG. I am new here. If I did wrong, plz tell me. Thank you !

**Comment by cebe** [comment]
seems you have reverted your fix and then added the changelog :)

You can try again sending another PR. If you do so, please follow our guide, as you have not created a new branch for your changes: https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

If not, I can fix it for you.

**Comment by klimov-paul** [comment]
@DrmagicE, do not use `master` branch for the puul requests.
Please rework your PR according to https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Pull request closed without merging**
