### PR TITLE
The gridEventHandlers object keys generation updated.

### PR DESCRIPTION
**Pull request by floor12**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | #18090

I checked the problem described in issue #18090 and found that the problem was in rewriting element in `gridEventHandlers` in `yii.gridView.js` file in `initEventHandler` function. 
Looks like the CheckboxColumn was designed to use only once in one GridView Widget. 
After a few different tries to fix this issue and not fail a lot of test, I found this solution, with fails inly one JS test. 
Now all seems to be work good, so I think we need to update *setSelectionColumn method with repeated calls* JS test (line 675 in `yii.gridView.test.js`), because it was designed to work only with one checkbox column. I'm not a big specialist in JS test, so some help needed.

### CODE REVIEW

**Comment by samdark** [comment]
@floor12 Seems it breaks another case. See tests: https://github.com/yiisoft/yii2/pull/18103/checks?check_run_id=770426107#step:8:1385

**Comment by floor12** [comment]
Yes, this is I was talking about. This test, like the checkboxField,  was designed to use only once per gridView widget. I think we need to update this test and add one another. Im not a big specialist in js testing. It would be great if someone helped in this matter. If there is no specialist in JS-Testing, I will have to dive into this question.

**Comment by samdark** [comment]
Yes. Test should be updated and no, there's no specialist about it :(

**Comment by floor12** [comment]
Ok. I will take a look to these tests with more attention.

**Comment by floor12** [comment]
Having studied the problem again, as well as tests and documentation on this issue, I came to the conclusion that this described behaviour is normal. 
Most likely, we need to edit the documentation, adding information that the grid is designed to use only one column with checkboxes using `checkboxField` column widget.
The solution I proposed turned out to be not entirely correct. In my case the `yiiGridView.setSelectionColumn()` method works fine with any number of columns, but GridView also has the `yiiGridView::getSelectedRows()` method, which has no parameters and returns the selected columns. However, to work with several columns, its signature must be changed by adding an optional parameter to clarify which column selects rows needs to be returned.
In order not to lose backward compatibility, this parameter must be optional.
Tests for this will have to write decently. )
I would change the ticket label from a bug to something else ... Because its not a bug.
The question remains, is there really a need for such modernization? )

**Comment by samdark** [comment]
> The question remains, is there really a need for such modernization? )

It is not a pressing matter for sure. If you have more time, you're welcome but I'd spent it on docs / tests instead.

**Comment by samdark** [comment]
Closing the pull request since we agreed that this code isn't for the master branch.

**Pull request closed without merging**
