### PR TITLE
Fixes #12080. Whenever updateInputs is called, it will trigger 'after…

### LINKED ISSUE #12080: js form afterValidate executes only if form being submitted
### What steps will reproduce the problem?

Setup before and afterValidate events for form, for example for blocking submit button:

``` javascript
  $('form').on('beforeValidate', function (e) {
    $(e.target).find(':submit').prop('disabled', true);
    console.log('beforeValidate');
  }).on('afterValidate', function (e) {
    $(e.target).find(':submit').prop('disabled', false);
    console.log('afterValidate');
  });
```
### What is the expected result?

Both event triggered
### What do you get instead?

Only beforeValidate event happens
### Additional info

In yii.activeForm.js afterValidate event described as it is triggered after validating the whole form.
But actually it happens only after validation triggered by form submission: see updateInputs method: it placed only if submitting is true

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.6 |

### PR DESCRIPTION
**Pull request by czzplnm**
…Validate'. Decouples the submitting restriction to afterValidate.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12080

### CODE REVIEW

**Comment by czzplnm** [comment]
@samdark added an afterValidate test

**Review by samdark — APPROVED** [review]
Code looks OK. Need extra testing.

**Comment by samdark** [comment]
I've checked it with basic application login form. The pull request breaks behavior significantly. Steps to reproduce:

1\. Install basic application. Apply the fix.
2\. Go to login form.
3\. Remove focus from username by clicking anywhere on the page.

**Expected**

- Usename cannot be blank error.
- Password stays as is.

**Actual**

- Usename cannot be blank error.
- Password is green.

4\. Focus on username.

**Expected**

- Usename cannot be blank error.
- Password stays as is.

**Actual**

- Username is green.
- Password cannot be blank.

Overall: if the field wasn't focused and submit wasn't triggered then that field should not be validated yet.

**Comment by czzplnm** [comment]
I'll look into it.

**Comment by czzplnm** [comment]
@samdark  I built the basic app from my forked Yii2, but I can not get it to ~/repos/yii2/apps/basic/framework/yii serve 

Error:
Document root "/home/hschultz/repos/yii2/apps/basic/framework/console/web" does not exist.

Do we have any docs on getting a basic app to serve from a forked Yii2 project?

**Comment by samdark** [comment]
Adjust index.php to point to your checked out fork.

**Review by samdark — APPROVED** [review]
Tested with basic app login form.

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by czzplnm** [comment]
@samdark Thanks! Looking forward to contributing again the future!

**Pull request merged**
