### PR TITLE
Fixed empty checkboxlist validation

### PR DESCRIPTION
**Pull request by np25071984**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #16253

### CODE REVIEW

**Comment by GHopperMSK** [comment]
I can fix the tests, so let me know if the solution worth it.

**Comment by GHopperMSK** [comment]
image

**Comment by samdark** [comment]
Is it triggering validation on page load now?

**Comment by GHopperMSK** [comment]
No, it isn't. The screenshot have been taken right after I submit empty form. It shows that checkboxlist component verified successfull if it doesn't contain any `option`.

**Comment by samdark** [comment]
OK. Please check why tests are now broken.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
