### PR TITLE
Made yii\web\User::checkRedirectAcceptable() public

### PR DESCRIPTION
**Pull request by rhertogh**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

The `checkRedirectAcceptable` is also very useful outside the User component.

### CODE REVIEW

**Comment by bizley** [comment]
Hm, yes, I think we could make it public. @samdark ?

**Review by githubjeka — APPROVED** [review]

**Review by samdark — APPROVED** [review]
Looks OK. Please add a line for CHANGELOG

**Comment by rhertogh** [comment]
> Looks OK. Please add a line for CHANGELOG

@samdark done

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
