### PR TITLE
add a PgsqlMutex

### PR DESCRIPTION
**Pull request by nineinchnick**
I didn't found any unit tests for other mutexes, should there be any?

### CODE REVIEW

**Comment by samdark** [comment]
@nineinchnick I don't think there currently are any. Would be great if you'll contribute tests for it.

**Comment by CSharpRU** [comment]
This enhancement is awesome! Can we merge this into the master? :smile:

**Comment by cebe** [comment]
@CSharpRU could you help creating a unit test for it?

**Comment by CSharpRU** [comment]
@cebe of course :)

**Comment by samdark** [comment]
Merged https://github.com/yiisoft/yii2/commit/84f37705bfa80380fa6b035654d6633689f5e40c and https://github.com/yiisoft/yii2/commit/db1a96d87612c558166f91d78fdd22b933694ee5. Thanks!

**Pull request closed without merging**
