### PR TITLE
Added min/max option to DateValidator.

### PR DESCRIPTION
**Pull request by nkovacs**
Refs #7514

### CODE REVIEW

**Comment by nkovacs** [comment]
The version of ICU on travis is too old, so one of the tests is failing.

**Comment by nkovacs** [comment]
I don't get it, why is the php 5.6 test failing on travis?

**Comment by cebe** [comment]
no need to waste time on scrutinizer if it does not point out obvious errors. will check the unit test failure when I find time for it. I do not think it is related to your code.

**Comment by nkovacs** [comment]
Yeah, I activated travis on my fork and it's working fine there. Might be the cache feature that's caching the vendor directory.

**Comment by cebe** [comment]
Merged, thank you!

**Pull request closed without merging**
