### PR TITLE
Use PHP 5.5+ `::class` instead of full class namespace

### PR DESCRIPTION
**Pull request by Faryshta**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |

### CODE REVIEW

**Comment by Faryshta** [comment]
notice that ::class is determined on compilation time, not execution time, that means the classes won't be autoloaded using this change.

**Comment by SilverFire** [comment]
Aha, we will accept this PR. Actually it's the only places where it should be changed:

```bash
grep -F -ir --exclude="classes.php" "'yii\\" framework
```

**Comment by cebe** [comment]
> Use PHP 5.6+ `::class` instead of full class namespace

it's a 5.5 feature ;)

@SilverFire you mean it's **not** the only places, right? :)

**Comment by SilverFire** [comment]
Oops :)
Yes, __not__ the only places

**Comment by Faryshta** [comment]
I made the changes suggested. Also can we reconsider #11487. I think its consistent to have a `->class` property on an object since we have now an static way to call the class

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
