### PR TITLE
Chg #7555: yii\log\Logger refactoring

### PR DESCRIPTION
**Pull request by kop**
According to #7555, this PR makes a small refactoring of `yii\log\Logger` class in order to make it possible for people who needs PSR-3 to have it working:
1. Renamed class `yii\log\Logger` to `yii\log\BaseLogger`;
2. Renamed method `yii\log\BaseLogger::log()` to `yii\log\BaseLogger::logInternal()`, access level changed to `protected`;
3. Created class `yii\log\Logger` extends `yii\log\BaseLogger` that implements method `log()`:

```
public function log($message, $level, $category = 'application')
{
    $this->logInternal($message, $level, $category);
}
```

### CODE REVIEW

**Comment by creocoder** [comment]
Looks like hack which breaks current Logger design and make it just strange... I understand that this is done for make possible integrating PSR logger, but such things should be solved by much more simplier solution? Want to integrate PSR logger === use PSR interface for that. Since all PSR logger proposals was closed this does not mean that its acceptable to make PSR logger integrable by hacking current fw design.

**Comment by creocoder** [comment]
@kop Want to integrate PSR-3 logger — use Adapter pattern.

**Comment by kop** [comment]
@creocoder, Using Adapter pattern was my first idea.

But this means that I have to duplicate a lot of constants and properties of the parent class to make it compatible (e.g. LEVEL_ constants, $messages, $flushInterval, etc.). And if something is changed in the parent class, all adapters will have to be updated.

Another possibility is to use a lot of magic methods... And this does not look very nice too.

So yes, problem can be solved by Adapters, but this does not look like a clear and nice way. And I don't really see how it breaks the logger design. From my point of view it just makes it more flexible. It's possible to extend pretty much any Yii2 component now and make it work absolutely different. And this looks really strange that we can't extend Logger in a normal way to support different interfaces.

**Comment by creocoder** [comment]
> So yes, problem can be solved by Adapters

We need interface for our own Logger. Problem not can, problem **should** be solved by using Adapter pattern.

> It's possible to extend pretty much any Yii2 component now and make it work absolutely different.

In object oriented world thinking that way usually call like "inheritance oriented coding" which has nothing similar with OOP. Yes, its possible to extend because classes not final. In 99% cases its wrong solution.

> And this looks really strange that we can't extend Logger in a normal way to support different interfaces.

Mainest thing that its **not** normal way. All we need is interface for our own Logger.

> So yes, problem can be solved by Adapters

Q.E.D. In original issue you write that integrating PSR-3 Logger is impossible )

**Comment by kop** [comment]
> Q.E.D. In original issue you write that integrating PSR-3 Logger is impossible )

Well, ok it's possible. But it's not possible in any easy way :)

As for other design questions... I just don't know which architecture decisions Yii2 is currently following. So if you think it's better to go with an interface - I don't mind. For me it sounds very nice too. I'm just saying that it would be nice to discuss this topic and come up with a decision how to make Logger easy to customize and support new features/interfaces.

**Comment by creocoder** [comment]
> how to make Logger easy to customize and support new features/interfaces

Its incorrect by it definition. Its wrong as much as wrong your previous

> possible to extend ... and make it work absolutely different
> extend ... to support different interfaces

Just reread yourself... Its nonsense ) Inheritance mechanist born not to make something work different and not to make childs support different interfaces. Extends born... sorry... to extends.

What is possible. Possible is to create our own LoggerInterface which have nothing similar with PSR-3 LoggerInterface. After that you can make adapter which can make PSR-3 Logger work using Yii 2 LoggerInterface. If you want use pure PSR3 LoggerInterface inside end user application you need create different component for that. One component can't support 10 different interface. So i recommend you create LoggerInteface PR and than you can just make:

```php
class PSR3LoggerAdapter implements Yii2LoggerInterface {
    public functiion __constuct(PSR3LoggerInterface $logger) {
        // ...
    }
}
```

This is what possible in normal OOP world. If you want to use PSR3 interface itself, which mean use different `log()` signature you should create separate component which have nothing similar with current logger since their interfaces is different. And this is normal way. On other side i think adapter idea will satisfy your needs. You want use PSR 3 logger? You'll use PSR 3 logger with Yii 2 Logger interface.

**Comment by creocoder** [comment]
@kop If you need example how to implement adapter for anything. Look at mine adapter for Yii 2 cache https://github.com/creocoder/yii2-flysystem/blob/master/src/YiiCache.php , it make possible to use Yii 2 Cache components for caching in places where original library expect cache with absoluttely different interface. By creating your own adapter for PSR3 Logger you'll be able to use any PSR3 Logger with Yii 2.

**Comment by samdark** [comment]
Close since can't be merged as is. @creocoder points are a bit exaggerated but still valid.

**Pull request closed without merging**
