### PR TITLE
Change is_callable insted method_exists in Object

### PR DESCRIPTION
**Pull request by ZAYEC77**

### CODE REVIEW

**Comment by samdark** [comment]
What are you trying to fix with it?

**Comment by ZAYEC77** [comment]
@samdark I try to implement correct work in case when behavior has magic `__set` or `__get`.

**Comment by klimov-paul** [comment]
`Object` can not have a behavior. It is covered correctly at `Component`.

**Comment by ZAYEC77** [comment]
@klimov-paul but `canSetProperty` and `canGetProperty` methods implement in Object class

**Comment by klimov-paul** [comment]
So what?

**Comment by klimov-paul** [comment]
If there is something, which troubles you, describe it by answering the following questions:
1) How to reproduce the issue?
2) What did you expected to see?
3) What did you seen instead?
4) Any extra comments.

**Comment by ZAYEC77** [comment]
I created behavior with overrided  method `__get`.
This behavior has to implement dynamic relation for ActiveRecord.
I try to call `$model->vendor->title` but get error `Getting unknown property`.
I want to get relation record by behavior.

**Comment by klimov-paul** [comment]
If you have overridden `__get()` inside your behavior, you should as well override its `canGetProperty()` value accordingly.

**Comment by ZAYEC77** [comment]
@klimov-paul thanks

**Pull request closed without merging**
