### PR TITLE
Attempt to fix ICU tests

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #13750

### CODE REVIEW

**Comment by mikehaertl** [comment]
@samdark Should this also go into the requirement checker? We had a discusstion yesterday where @schmunk42 pointed out, that the checker is not reliable when it comes to ICU. He suggested to run the complete yii2 test suite when building the docker images instead of just the requirement checker. I'd say we should rather fix the checker instead.

**Comment by samdark** [comment]
@mikehaertl what exactly should go into the checker?

**Comment by schmunk42** [comment]
> that the checker is not reliable when it comes to ICU

What I meant is that the checker just checks the version of the library, the failing tests go much deeper.

I can't tell if the tests are wrong or a framework function, but in any case, it's good to see that early.

**Comment by schmunk42** [comment]
What's about those, btw?

```
5) yiiunit\framework\validators\DateValidatorTest::testIntlValidationWithTime with data set #0 ('UTC')
Failed asserting that false is true.

/project/tests/framework/validators/DateValidatorTest.php:294
/project/vendor/phpunit/phpunit/phpunit:52
```

Are they also related to ICU problems?

**Comment by samdark** [comment]
That would require PHPUnit. Not a good idea IMO since checker was meant to be lightweight.

**Comment by samdark** [comment]
> Are they also related to ICU problems?
Probably. I haven't checked these ones yet.

**Comment by mikehaertl** [comment]
> That would require PHPUnit. Not a good idea IMO since checker was meant to be lightweight.

@samdark I haven't looked into the details of this issue und if this could happen at runtime. But if there's a potential runtime error due to a problem with some extension, shouldn't the checker inform you about that? 

As a user I would probably trust the checker and would be surprised to see app errors that are caused by a problem with some extension.

**Comment by samdark** [comment]
Yes, as a user I'd be surprised too but also as a user I won't tolerate installing phpunit at the server just for the sake of checking requirements once.

**Comment by mikehaertl** [comment]
>  as a user I won't tolerate installing phpunit at the server just for the sake of checking requirements once.

Of course not. Is there really no way to test this without PHPUnit? What kind of special tests are these that we can't include them as simple PHP commands in the req checker?

**Comment by samdark** [comment]
Ah, right. We can do that.

Tests aren't small in this area so I though you propose reusing these.

**Pull request merged**
