### PR TITLE
#15678 - ActiveForm "attribute" not found within local scope

### PR DESCRIPTION
**Pull request by lubosdz**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15678

### CODE REVIEW

**Comment by SilverFire** [comment]
Could you add tests to make sure this thing works as exected?

**Comment by lubosdz** [comment]
No, I am sorry, I have no experience writing javascript tests. I always write server-side tests. I checked existing JS tests, but it would take me few hours to setup environment & get familiar with syntax ...

**Comment by SilverFire** [comment]
Ok, we will do it ourself. Thank you

**Comment by samdark** [comment]
Closed in favor of https://github.com/yiisoft/yii2/pull/15747

**Pull request closed without merging**
