### PR TITLE
Added PageCache info of in log 

### PR DESCRIPTION
**Pull request by githubjeka**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
### not found:

image
### found:

image

### CODE REVIEW

**Comment by cebe** [comment]
shouldn't the log level be trace instead of info?

**Comment by SilverFire** [comment]
I don't think that `print_r` is suitable in application logs at all

**Comment by githubjeka** [comment]
May be ArrayHelper:toArray ?

**Comment by SilverFire** [comment]
It is enough to trace whether the valid cache was found

**Comment by githubjeka** [comment]
IMHO  'Valid page content is not found in the cache.' is worthless without details.

**Comment by SilverFire** [comment]
What information is the most valuable in this `print_r`?

**Comment by samdark** [comment]
Looks fine to me. @SilverFire how about merging it into 2.0.10?

**Comment by SilverFire** [comment]
I'm fine with it. @githubjeka could you add a CHANGELOG line please?

**Comment by kidol** [comment]
I don't like this. Logging should be implemented in cache component, which would make this PR obsolete.

**Comment by SilverFire** [comment]
@kidol do you suggest to trace all `cache->get()` and `cache->set()` calls?

**Comment by kidol** [comment]
Yes. Here you can see how it was done in Yii1: https://github.com/yiisoft/yii/blob/master/framework/caching/CCache.php#L102

Also DebugToolbar could make use of these logs to show cache hits/misses (#2365).

Though, I'm not interested in working on this in any way. So, see it as my 2 cents on this topic...

**Comment by SilverFire** [comment]
I don't know the original reasons why this trace has been removed, by I guess because of performance reasons. @cebe @samdark

**Comment by samdark** [comment]
Could be added. Trace is rarely used in production.

**Comment by cebe** [comment]
guess it was performance, not sure.

**Comment by SilverFire** [comment]
Merges as is, thank you

**Comment by githubjeka** [comment]
@kidol if you want you could send your PR for all cache by deleting this code. 

Thanks.

**Pull request merged**
