### PR TITLE
ActiveRecord relations support dependency injection

### PR DESCRIPTION
**Pull request by pavlelee**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | yes/no |
| Tests pass? | yes |
| Fixed issues | https://github.com/yiisoft/yii2/issues/11505 |

### CODE REVIEW

**Comment by Faryshta** [comment]
whats the use case?

**Comment by lynicidn** [comment]
fix it also for active query
echo User::find()->model_class

**Comment by Liv1020** [comment]
@Faryshta if you injection class, but ActiveRecord relations not support.
example:
https://github.com/yiisoft/yii2/issues/11505

**Comment by samdark** [comment]
Description in #11505 is a bit vague. I understand technical part of it but why do you need it?

**Comment by Faryshta** [comment]
I mean why not use `\app\resources\Order::findOne(1)` instead of `\app\models\Order::findOne(1)` ?

**Comment by Liv1020** [comment]
@samdark   
I inject a class(app\resources\Order) to container,a product model has related attribute named getOrders():common\models\Order. then I called $product->orders, it should return common\models\Order[], Ideally this would be app\resources\Order. 
because I have changed common\models\Order logically,it's like usage :\Yii::$container->set('yii\data\Sort', 'app\modules\xg\components\Sort');

**Comment by Liv1020** [comment]
@Faryshta  because I called $product->orders, not Order::find()

**Comment by samdark** [comment]
@Liv1020 I perfectly understand technical side of it. I'm asking for the reasons doing so.

**Comment by Liv1020** [comment]
@samdark Reasons?Since the use of the injection , of course, every place using an injection classes , rather than in some places .

**Comment by Liv1020** [comment]
@samdark laravel use injection anywhere,I do not know my bad English, can you understand?

**Comment by klimov-paul** [comment]
Dependency injection at ActiveRecord layer will produce huge performance impact.

> I inject a class(app\resources\Order) to container,a product model has related attribute named getOrders():common\models\Order. then I called $product->orders, it should return common\models\Order[], Ideally this would be app\resources\Order. 

Why do not declare relation to `app\resources\Order` at the first place? What is a reason for such twisted approach?

**Comment by samdark** [comment]
I don't like the idea of using DI everywhere for the sake of using it w/o any real need.

**Comment by lynicidn** [comment]
ar isolated from all, only service locator
http://programmers.stackexchange.com/questions/119352/does-the-activerecord-pattern-follow-encourage-the-solid-design-principles

is pattern problem

**Comment by Liv1020** [comment]
@samdark @klimov-paul 
Your views I carefully thought for a moment, and finally I use a rewrite every relation attributes to solve rest expand returned

**Comment by Faryshta** [comment]
> Your views I carefully thought for a moment, and finally I use a rewrite every relation attributes to solve rest expand returned

how i solved it.

I have `common\models\Orders` which are used in `backend` and `frontend` applications `api\models\Orders` for my `api` application.

```php
   public static $orderClass = 'common\\models\\Orders';

   public function getOrders()
   {
       return $this->hasMany(static::$orderClass, ['id' => 'order_id']):
   }

   // on api

   Client::$orderClass = 'api\\models\\Order';
```

**Pull request closed without merging**
