### PR TITLE
Update core-code-style.md

### PR DESCRIPTION
**Pull request by des1roer**
http://symfony.com/doc/current/contributing/code/standards.html

Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement);

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Yes. That's fine to add such rule. It is in line with what we're actually doing.

Rules in https://github.com/yiisoft/yii2/tree/master/cs should be updated.

**Comment by rob006** [comment]
@samdark I already tried it, but as a hard rule it generates too many dumb empty lines (IMO).

**Comment by samdark** [comment]
@rob006 was it with "unless" part?

**Comment by rob006** [comment]
Yes, but still sometimes I prefer some code stick to return statement and such empty line  breaks code grouping and creates many "lonely lines". 

Anyway, I could open PR with such rule enable and you can decide about it. In this week I want to move this CS stuff forward anyway.

**Comment by samdark** [comment]
OK. Sounds perfect.

**Comment by rob006** [comment]
@samdark #14666

**Pull request closed without merging**
