### PR TITLE
ContentNegotiator generates 406 HTTP status code

### PR DESCRIPTION
**Pull request by PowerGamer1**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | I think currently tests for Yii2 are broken elsewhere anyway 
| Fixed issues  | https://github.com/yiisoft/yii2/issues/14467

### CODE REVIEW

**Comment by Kolyunya** [comment]
@PowerGamer1 are you sure this patch does not break the backward compatibility? Legacy code which was catching `UnsupportedMediaTypeHttpException` will break now since the filter now throws `NotAcceptableHttpException`.

**Comment by PowerGamer1** [comment]
> are you sure this patch does not break the backward compatibility? Legacy code which was catching  UnsupportedMediaTypeHttpException  will break now since the filter now throws  NotAcceptableHttpException .

To catch exception thrown by `ContentNegotiator` you will have to override a method like `Application::run()` or `Application::handleRequest()`. I highly doubt any application at all both override these methods AND catch `UnsupportedMediaTypeHttpException`.

Regardless, even IF such an app exists it MUST be fixed. The "415 Unsupported Media Type" code has completely different meaning in HTTP so you might as well start sending random codes in response to HTTP requests.

**Comment by sergeymakinen** [comment]
Technically it breaks BC. But I think a BC impact is low while misusing HTTP codes is a pretty bad thing.

**Comment by PowerGamer1** [comment]
I ma not sure what and how you'd want to unit test in this case and even if any tests are needed at all. Regardless, I don't do unit tests, take it from here please.

**Comment by sergeymakinen** [comment]
I could take care of this as soon as I finish with a migration builder PR.

**Comment by klimov-paul** [comment]
Resolved by commit 2e01076abc2c5d4db9edbc2043e8e9442bdfe294

**Pull request closed without merging**
