### PR TITLE
fixed #17479

### LINKED ISSUE #17479: Missing Icons in ActionColumn with Bootstrap 4.3.x
With the Version 4 of Bootstrap, the icons were removed from the default library.

https://getbootstrap.com/docs/4.0/extend/icons/

### What steps will reproduce the problem?

AppAsset: 

~~~
            'yii\bootstrap4\BootstrapAsset',
            'yii\bootstrap4\BootstrapPluginAsset',
~~~

GridView: 
~~~
 
   <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'description:ntext',
            'image',

            [
                'class' => 'yii\grid\ActionColumn',
            ]
        ],
    ]); ?>


~~~
### What's expected?

Seeing the icons in the last column of the gridview.

### What do you get instead?

The css classes are not present in boostrap, so the icon's as not visible.

### Additional info

| Q                | A
| ---------------| ---
| Yii version   | 2
| PHP version  | 7.2
| Operating system | Linux Debian Stretch

For the Moment I use the awesome font library and a function which creates the Buttons:

~~~
        function createActionButtons($buttons=['view','update','delete']){
                $actionButtons = [];
                $actionButtons['update']= function($url,$model) {
                         return Html::a('<i class="fa fa-edit"></i>', $url, [
                                 'title' => Yii::t('app', 'edit')
                         ]);
                };
                $actionButtons['delete'] = function($url,$model) {
                         return Html::a('<i class="fas fa-trash"></i>', $url, [
                                 'title' => Yii::t('app', 'delete')
                         ]);
                };
                $actionButtons['view'] = function($url,$model) {
                         return Html::a('<i class="fas fa-eye"></i>', $url, [
                                 'title' => Yii::t('app', 'view')
                         ]);
                };
                return array_intersect_key($actionButtons,array_flip($buttons));
        }
~~~

### PR DESCRIPTION
**Pull request by simialbi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | 〰️ (not glyphicons any more by default)
| Tests pass?   | ✔️
| Fixed issues  | #17479

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Comment by alex-code** [comment]
There's an issue with this PR.
I think they require FontAwesome's SVG JS to render correctly otherwise the SVG fills the available width as the CSS classes don't exist.

Also I'm not sure if there's a copyright issue using FontAwesomes' SVG directly embedded.

**Comment by bizley** [comment]
Hmm, maybe I was too hasty approving this. @simialbi could you answer these questions? I could not find anything about the copyrights for this as well, apart from them saying it's opensource.

**Comment by simialbi** [comment]
@bizley: @alex-code is right, there is a small piece of css missing. I'll append it.

About the license: https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt
> Font Awesome Free is free, open source, and GPL friendly. You can use it for
commercial projects, open source projects, or really almost whatever you want.
Full Font Awesome Free license: https://fontawesome.com/license/free.

The icons I used are all in the FA5 free package and are downloadable from [fontawesome.com](https://fontawesome.com)

**Comment by alex-code** [comment]
Could use UTF8 icons as default if no other library is being used.

🗑 https://www.utf8icons.com/character/128465/wastebasket
✎ https://www.utf8icons.com/character/9998/lower-right-pencil
👁 https://www.utf8icons.com/character/128065/eye

**Comment by bizley** [comment]
@simialbi ok, open new PR please. Maybe add some comment about the origin of the svgs.

**Comment by simialbi** [comment]
I don't want to refer to an external library, I'd insert this 4lines as Inline-CSS with a key, so it can be reused in other widgets, without double loading. The utf-8 proposal was declined in https://github.com/yiisoft/yii2/issues/17479#issuecomment-516446520

**Comment by simialbi** [comment]
@bizley I just implemented the missing css part and asked myself, if it makes sense to create a `Trait` for reusability (e.g. other widgets). Something like `FontAwesomeTrait` in `widgets` directory. Or maybe build a method directly in `yii\base\Widget`? What do you think?

**Comment by bizley** [comment]
What would be in that trait?

**Comment by simialbi** [comment]
something like
```php
protected function registerFontawesomeStyles()
{
        $view = $this->getView();
        $css = <<<CSS
.svg-inline--fa {
    display: inline-block;
    font-size: inherit;
    height: 1em;
    overflow: visible;
    vertical-align: -0.125em;
}
.svg-inline--fa.fa-lg {
    vertical-align: -0.225em;
}
.svg-inline--fa.fa-w-1 {
    width: 0.0625em;
}
.svg-inline--fa.fa-w-2 {
    width: 0.125em;
}
.svg-inline--fa.fa-w-3 {
    width: 0.1875em;
}
.svg-inline--fa.fa-w-4 {
    width: 0.25em;
}
.svg-inline--fa.fa-w-5 {
    width: 0.3125em;
}
.svg-inline--fa.fa-w-6 {
    width: 0.375em;
}
.svg-inline--fa.fa-w-7 {
    width: 0.4375em;
}
.svg-inline--fa.fa-w-8 {
    width: 0.5em;
}
.svg-inline--fa.fa-w-9 {
    width: 0.5625em;
}
.svg-inline--fa.fa-w-10 {
    width: 0.625em;
}
.svg-inline--fa.fa-w-11 {
    width: 0.6875em;
}
.svg-inline--fa.fa-w-12 {
    width: 0.75em;
}
.svg-inline--fa.fa-w-13 {
    width: 0.8125em;
}
.svg-inline--fa.fa-w-14 {
    width: 0.875em;
}
.svg-inline--fa.fa-w-15 {
    width: 0.9375em;
}
.svg-inline--fa.fa-w-16 {
    width: 1em;
}
.svg-inline--fa.fa-w-17 {
    width: 1.0625em;
}
.svg-inline--fa.fa-w-18 {
    width: 1.125em;
}
.svg-inline--fa.fa-w-19 {
    width: 1.1875em;
}
.svg-inline--fa.fa-w-20 {
    width: 1.25em;
}
.svg-inline--fa.fa-fw {
    text-align: center;
    width: 1.25em;
}
CSS;
        $view->registerCss($css, [], 'fontawesome5');
}
```
optionally extended with param `$onlySizes = []` where you can pass which widths you'd like to consider (1-20)

**Comment by bizley** [comment]
I would like asset better. Samdark, what do you think?

**Comment by My6UoT9** [comment]
So if I want to use different icons, how would I do that here?
It seems to me heavily depending on fontawesome.

And css should be in a asset, that way it can be inline included or bundled without hassle.

**Comment by simialbi** [comment]
@My6UoT9 Good intention, maybe we should create an `IconInterface` wich can be implemented either with `FontAwesome` or `Glyphicons` or whatever, defaults to `FontAwesome`.
@bizley Using asset means referring to [FontAwesome](https://github.com/FortAwesome/Font-Awesome) repo? Or build a leightweight version directly into yii? The FontAwesome repo is a really big one for only this purpose.
> Alternative for usage only in `GridView`: inline the css lines in this 3 svgs... Would answer @My6UoT9's question about using different icons too...

**Comment by bizley** [comment]
No, just a single CSS file.

**Pull request merged**
