### PR TITLE
add script for composer installation

### PR DESCRIPTION
**Pull request by vchenin**

### CODE REVIEW

**Comment by zelenin** [comment]
composer should be a global tool, not project specific

**Comment by vchenin** [comment]
not always
for example translators don't need globally accessible composer, but need it for producing reports with `php build translation`

**Comment by zelenin** [comment]
@vchenin it's not argument for it.
Are you place PHPStorm or your other IDE/editor to project dir? Git? Other tools for project developing?

**Comment by cebe** [comment]
still this script does not belong to yii in this form. Add it to your project if you need it.
For translators we could enhance the build command so that it ensures it can run out of the box.

**Comment by vchenin** [comment]
I already advance functionality of script, now it's more useful.
Now is possible to install composer globally:
`sudo sh getcomposer.sh -g`
or locally:
`./getcomposer.sh -l`
or with specified options:
`./getcomposer.sh -o --filename=composer --version=1.0.0-alpha8`

**Pull request closed without merging**
