### PR TITLE
Fix BC in Exist Validator (#13533)

### LINKED ISSUE #13533: Possible BC break in ExistValidator
### What steps will reproduce the problem?

https://github.com/yiisoft/yii2/commit/b82caa97e82ff8b99389b56958fb1e1310637c4b#diff-c36c8f68f6255dc8840038b8c921813eL54

> ~If the key and the value are the same, you can just specify the value.~

Upgrade Yii 2.0.10 => 2.0.11.1

```php
/**
 * @property integer $foo_id
 */
class A extends ActiveRecord {
}

/**
 * @property integer $foo_id
 * @property integer $a_id
 */
class B extends ActiveRecord {
    public function rules()
    {
        return [
            [
                ['a_id'],
                'exist',
                'targetClass' => A::class,
                'targetAttribute' => ['a_id' => 'id', 'foo_id'],  // shortcut 'foo_id' as documented before
            ],
        ];
    }
}
```

So, `B::foo_id == A::foo_id` and `B::a_id == A::id`

A:

id | foo_id
-- | --
42 | 997

```php
$b = new B();
$b->foo_id = 997;
$b->a_id = 42;

if (!$b->save()) {
    \Yii::error($b->errors);
    throw ...;
}
```

### What is the expected result?

```mysql
SELECT EXISTS(SELECT * FROM `a` WHERE (`id`=42) AND (`foo_id`=997))
```

Validation passed.

### What do you get instead?

```mysql
SELECT EXISTS(SELECT * FROM `a` WHERE (`id`=42) AND (`foo_id`=42))
```

Validation failed: `Attribute "a_id" is incorrect`.

### Additional info

Fix code as such:

```diff
- [['a_id'], 'exist', 'targetClass' => A::class, 'targetAttribute' => ['a_id' => 'id', 'foo_id']]
+ [['a_id'], 'exist', 'targetClass' => A::class, 'targetAttribute' => ['a_id' => 'id', 'foo_id' => 'foo_id']]
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.1
| PHP version      | 7.0.13
| Operating system | Ubuntu 16.04

### PR DESCRIPTION
**Pull request by developeruz**
It was about simplifying targetAttribute (have discussed in #13475). Related changes from #13318 rolled back.

fixes #13533

### CODE REVIEW

**Comment by ddinchev** [comment]
Shouldn't we make sure we have tests for new code as a policy so that we run into such situations less often?

**Comment by cebe** [comment]
@ddinchev sure that is the plan but it did not help in this case. Tests were written for the new changes but not for the old behavior. That is the main problem we have with breaking changes. Seen in this release. We need more test coverage for existing features to make sure they do not break.

**Comment by cebe** [comment]
There is a test for this code but it does not catch this change because of bad choice of IDs...
https://github.com/yiisoft/yii2/blob/a941b3536f5d53ab4c791705a7d40ef7ceab8c1b/tests/framework/validators/ExistValidatorTest.php#L136-L141

**Review by cebe — APPROVED** [review]

**Comment by cebe** [comment]
failing test added in fba4e434695b7d25629967cbc7281ced7bbe03ab, merged. Thank you!

**Comment by ddinchev** [comment]
@cebe cool - I was asking for the current PR change. Thank you for fixing this so quickly!

**Pull request closed without merging**
