### PR TITLE
Fixes #8670: Allow DbSession store particular data in the separated column

### LINKED ISSUE #8670: Allow DbSession store particular data in the separated column.
For the custom session storages like DB, MongoDB or Redis, It would be nice to have built-in support for storing particular session data in separated fields. For example, allow to store `userId` in the separated column of 'session' table with `DbSession`.

Typical use case: I want to see all active sessions for the particular user and perhaps drop some of them (or all of them) if needed. Such functionality provided by GMail for example.
In morden systems with high security demands restriction: 1 active session per 1 registered user is very common.
Of course this can not be implemented at plain `yii\web\Session` or `yii\web\CacheSession`, but can be present in `DbSession`, `MongoSession` and so on.

We can introduce array map in format: sessionKey => storageColumnName, which can be used for actual data set composition.
Common related functionality can be composed into a trait or a abstract base class.

### PR DESCRIPTION
**Pull request by klimov-paul**
Fixes #8670 : Allow DbSession store particular data in the separated column.

Base class `yii\web\MultiFieldSession` created.
Support for custom fields provided via callbacks.

### CODE REVIEW

**Comment by samdark** [comment]
Found no code issues. :+1:

**Comment by samdark** [comment]
Add a test for it and it would be perfect.

**Comment by cebe** [comment]
:+1:

**Comment by klimov-paul** [comment]
Unit test for `yii\web\Session` added. Note: unit testing of the feature is limited due to PHP restrictions on `session_decode()` and `session_encode()` calls.

**Pull request merged**
