### PR TITLE
Update Connection.php

### PR DESCRIPTION
**Pull request by antonmarin**
How to disable load balancing

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  |

### CODE REVIEW

**Comment by antonmarin** [comment]
@SilverFire, how should i test docs?

**Comment by SilverFire** [comment]
There are no tests confirming that setting `null` will work as expected. It will be good to test that it works as is documented

**Comment by antonmarin** [comment]
Okay. Understand now

**Comment by SilverFire** [comment]
Merged with tests and docs adjustment: b642c36019790e45e916493318458938165066d0

**Pull request merged**
