### PR TITLE
change echo to return in BaseListView

### PR DESCRIPTION
**Pull request by pkirill99**
'echo' is not true ...

### CODE REVIEW

**Comment by cebe** [comment]
for widgets that have no call to begin() and end() it does not matter:
https://github.com/pkirill99/yii2/blob/ab9d13834df5406672638072e0921833d66973a6/framework/base/Widget.php#L107

should be consistent about all widgets, @pkirill99 could you go through and make sure it is consistent?

**Comment by pkirill99** [comment]
I am not sure that I understood you correctly, sorry for my bad english

if we look in https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php#L98 

`$out = $widget->run();`

and in https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php#L107

`return ob_get_clean() . $out;`

now - _echo_ send data in ob_ , and if use _return_ - data was in $out

**Comment by pkirill99** [comment]
GridView also need fix if apply this patch

https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L288

to 

`return parent::run();`

**Comment by cebe** [comment]
moved this to 2.1, as it might break something.

**Comment by cebe** [comment]
merged, thank you!

**Pull request closed without merging**
