### PR TITLE
Added EVENT_INIT event to Component

### PR DESCRIPTION
**Pull request by is7116**

### CODE REVIEW

**Comment by samdark** [comment]
How you're going to use it?

**Comment by is7116** [comment]
Use case for me is to statically attach behaviors to any component. This could be helpfull for extending components from another module.
```
Event::on(SomeComponent::className(), Component::EVENT_INIT, function($event){
    $event->sender->attachBehavior('foo', FooBehavior::className());
});
```

**Comment by unclead** [comment]
@samdark i think it can be useful when i need to attach behavior which will implement some logic after initialization.
For example i have a menu in main module and filter in rbac module which remove all disallowed items before rendering
For solving this i implement my own event, but if component had AFTER_INIT event i would used it

**Comment by qiangxue** [comment]
This will have big performance hit.

**Comment by samdark** [comment]
Yep. I tend to reject such addition...

**Comment by klimov-paul** [comment]
Requested use case can be resolved using `DI`: `yii\di\Container::set()`.
Sinse introduction of proposed event will produce perfromance impact, issue rejected.

**Pull request closed without merging**
