### PR TITLE
Bug #17325  Fixed yii\db\mysql\Schema::findTableNames() will not retu…

### PR DESCRIPTION
**Pull request by maximw**
Fixed bug Bug #17325  - yii\db\mysql\Schema::findTableNames() will not return Views. Also added yii\db\mysql\Schema::findViewNames()

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | probably
| Tests pass?   | yes
| Fixed issues  | #17325

### CODE REVIEW

**Comment by samdark** [comment]
Seems to fail existing tests: https://travis-ci.org/yiisoft/yii2/jobs/544282487#L823 (changelog format fixed by me, ignore it).

**Comment by samdark** [comment]
@maximw are you going to work on it further?

**Comment by maximw** [comment]
> @maximw are you going to work on it further?

Excuse me, but maybe later. Please, reject and close that pull request. I would create new one, if will make it properly.

**Comment by samdark** [comment]
Deal. Thank you for contributing.

**Pull request closed without merging**
