### PR TITLE
fix bug #6553 DateValidator return valid for date "2012-12-12foo"

### LINKED ISSUE #6553: DateValidator return valid for date "2012-12-12foo"
There is an error in DateValidator using Intl extension.
When I provide wrong string having valid date validator should return "not valid".
Example value: 
2012-12-12foo is valid but it shouldn't

PHP: 5.5.9-1ubuntu4.5, ICU: 52.1

### PR DESCRIPTION
**Pull request by gajahlemu**
compare position at which date value parsing ended with its string length ensure validation when using php intl extension to parse date value

fix #6553

### CODE REVIEW

**Comment by cebe** [comment]
Looks good to me, can you add a test case too?

**Comment by gajahlemu** [comment]
try this quick test case
```php
$value = "2012-12-12foo"; //invalid date
//$value = "2012-12-12"; //valid date
$locale = "en_US";
$timezone = "UTC";
$format = "y-M-d";
$formatter = new IntlDateFormatter($locale, IntlDateFormatter::NONE, IntlDateFormatter::NONE, $timezone, NULL, $format);
$formatter->setLenient(false);
$parse_pos = 0;
$parsedDate = @$formatter->parse($value, $parse_pos);
if($parsedDate !== false && $parse_pos === strlen($value)) {
  echo "VALID: ".$parsedDate;
} else {
  echo "INVALID DATE VALUE";
}
````

**Comment by cebe** [comment]
I meant to add it to https://github.com/yiisoft/yii2/blob/master/tests/unit/framework/validators/DateValidatorTest.php but I can do that myself too.

**Comment by cebe** [comment]
merged, thanks!

**Pull request closed without merging**
