### PR TITLE
add getCurrencyCode method to formatter

### PR DESCRIPTION
**Pull request by antgubarev**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #8527

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by cebe** [comment]
quite sure this should not belong to formatter. Formatter is meant to be used for formatting input values and not for retrieving general locale data. This should be part of i18n component or a separate helper.

**Comment by amarox** [comment]
Why? Formatter return format of currency.

**Comment by cebe** [comment]
Formatter implements methods that convert some input value into a human readable format based on the locale, it is not used to provide generic information about locale. That should be a separate component. What is your use case for this method?

**Comment by amarox** [comment]
For example, show label with currency in table head. 

```html
<th>Price (currency)</th>
```
and in rows

```html
<td>3 567</td>
```

**Comment by amarox** [comment]
Currency locale config in Formatter but not i18n. And i mean that Formatter should return human readable currency code.

**Comment by amarox** [comment]
unit tests added

**Review by samdark — APPROVED** [review]

**Comment by rob006** [comment]
Fixes #8527

**Comment by cebe** [comment]
I still think it should be part of a separate component, there are many other locale dependent information that could be retrieved, formatter is not the right place for it.

**Review by dynasource — APPROVED** [review]

**Comment by samdark** [comment]
@cebe any suggestions on how to name the component?

**Comment by bupy7** [comment]
@samdark `Sign`.

**Comment by samdark** [comment]
`yii\i18n\info\Currency`?

**Comment by rob006** [comment]
`yii\i18n\Locale`?

**Comment by samdark** [comment]
Sounds good, @rob006. @amarox do you have some time to adjust placement of the code?

**Comment by amarox** [comment]
@samdark Sure. I will fix it

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/63fdd26b7eb5e567e48795b91aa1af534a9c1fa2

**Comment by samdark** [comment]
Thanks for starting it.

**Pull request closed without merging**
