### PR TITLE
Fix #15684: JsonExpression in Command::update() method

### LINKED ISSUE #15684: JsonExpression in Command::update() method
### What steps will reproduce the problem?
Update postgres table contains JSON(B) object using  $connection->createCommand()->update () method

### What is the expected result?

Updated record

### What do you get instead?

Database Exception – yii\db\Exception
Object of class yii\db\JsonExpression could not be converted to string
Failed to prepare SQL: UPDATE "object_attributes" SET "attr_value"=:qp2 WHERE "UUID" = :uuid and "attr_name"=:attr_name
↵
Caused by: yii\base\ErrorException
Object of class yii\db\JsonExpression could not be converted to string
in /private/var/www/zzz/www/vendor/yiisoft/yii2/db/Command.php at line 315

1. in /private/var/www/zzz/www/vendor/yiisoft/yii2/db/Command.php at line 263

### PR DESCRIPTION
**Pull request by beroso**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes (except hhvm)
| Fixed issues  | #15684, #15677

### CODE REVIEW

**Comment by SilverFire** [comment]
Thank you for finding it out

**Comment by schmasterz** [comment]
In my point of view this feature is breaking BC. For example I have a SerializerBehavior  and it is attached to the model like this:
`  'serialize' => [
                'class' => '\path\to\SerializerBehavior',
                'attributes' => ['category_ids'],
                'serializer' => new JsonEncodeClosure(),
                'deserializer' => new JsonDecodeClosure()
            ]`
Column type in database is  json. So I have 2 options

1. To change all db types to string and continue using SerialzerBehavior
2. To change all my models and  remove the Behavior.

Also there is a third option to add something like IsValidData() in BaseJson, so it will not break BC, and can be dropped in 2.1

**Comment by Offout** [comment]
Manually applied, works for me (PostgreSQL 9.6 JSONB filed).

**Comment by samdark** [comment]
@schmasterz that's separate issue.

**Review by samdark — APPROVED** [review]
Looks OK to me.

**Comment by berosoboy** [comment]
I will write the unit tests in this evening

**Comment by SilverFire** [comment]
@berosoboy Thank you, I will push a commit with test and another issues fixed soon

**Comment by SilverFire** [comment]
Closed in favor of https://github.com/yiisoft/yii2/pull/15732
@berosoboy I've mentioned you in a changelog. Thank you

**Comment by berosoboy** [comment]
Thank you

**Pull request closed without merging**
