### PR TITLE
Fix FileValidator incorrectly validate mimetype with uppercase letter

### PR DESCRIPTION
**Pull request by luqmansungkar**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16305

### CODE REVIEW

**Comment by SamMousa** [comment]
Actually since mime types are case insensitive they should be compared in a case insensitive manner.
This PR solves just one side, if my file containing mime types has upper case mime types they will never be matched...

**Comment by Thoulah** [comment]
`application/vnd.ms-word.document.macroEnabled.12`

**Comment by SamMousa** [comment]
Not sure what your point is @thoulah?

Just because people use capitals it doesn't mean that something is case sensitive.

**Comment by rob006** [comment]
Replaced by 17531

**Pull request closed without merging**
