### PR TITLE
Minor: SCA (unnecessary overrides, potential race conditions)

### PR DESCRIPTION
**Pull request by kalessil**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | n/a

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks alright. Please add changelog lines and I'll merge.

**Comment by kalessil** [comment]
Done

**Review by dmirogin — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by kalessil** [comment]
Super, thank for merging!

**Comment by kalessil** [comment]
@samdark : apparently some side-effects are possible with this PR: see https://github.com/symfony/symfony/issues/25336 for details.

I'll send a PR to revert this week.

**Pull request merged**
