### PR TITLE
Fixed header Content-Type when response is empty

### PR DESCRIPTION
**Pull request by slavcodev**
Now, the empty response sent with invalid "Content-Type", because formatters skipped and not set header.

### CODE REVIEW

**Comment by creocoder** [comment]
:+1: for that, have same trouble.

**Comment by samdark** [comment]
@slavcodev can you add a test for the case you're fixing?

**Comment by qiangxue** [comment]
I don't quite understand the problem. Could you explain it a bit more?

**Comment by samdark** [comment]
@qiangxue when there's no response we're sending content type = HTML even when formatter is set to JSON or XML.

**Comment by qiangxue** [comment]
I see. Make sense.

**Comment by samdark** [comment]
The change seems to be not compatible in terms of output: https://travis-ci.org/yiisoft/yii2/jobs/50559796#L421

**Comment by samdark** [comment]
Merged first commit, added fixed tests and CHANGELOG with https://github.com/yiisoft/yii2/commit/00aafc82ef2f48d161353dce33bb9ddb6ea084d3.

**Pull request closed without merging**
