### PR TITLE
Allows spaces in Mysql unique index names

### PR DESCRIPTION
**Pull request by usecomposable**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13814

### CODE REVIEW

**Comment by df2** [comment]
On my HD I have software encryption, and when I run the db tests, the constant writes max my CPU and make my system halt. It's ugly. I would like to buy another standalone box that I can use to run tests. Until then, it's hard to run the database tests.

**Comment by samdark** [comment]
Push tests here. Travis would take care of running em.

**Comment by cebe** [comment]
@df2 are you willing to work on this further?

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
