### PR TITLE
Add class `ValidatorCollection`

### PR DESCRIPTION
**Pull request by WinterSilence**
- `extend ArrayObject` i.e. compatible with `Model::$validators`
- `Configurable` constructor i.e. can use container to configure new instances
- `sortByOrder()` to run filters and modifiers before validators
- `findByClass()` short-hand to find validators by class
- cloning validators

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
What's the purpose? How to use container to configure new instances and why?

**Comment by WinterSilence** [comment]
@samdark
> How to use container to configure new instances and why?

sounds like trolling

**Comment by samdark** [comment]
It is not.

**Comment by WinterSilence** [comment]
@samdark application configuration:
~~~php
'container' => [
    'definitions' => [
        yii\validators\ValidatorCollection::class => [
            'iteratorClass' => ExtendedArrayIterator::class
        ]
    ],
],
~~~

**Comment by WinterSilence** [comment]
@samdark 
> What's the purpose?

> sortByOrder() to run filters and modifiers before validators
> findByClass() short-hand to find validators by class
> cloning validators

i.e. moves code works around validators from model to collection

**Comment by samdark** [comment]
That looks a bit odd to me:

1. Why do you need the order to be not what's explicitly specified in rules? That is very confusing if you specify validators/filters/validators as A, B, C but get these executed as C, A, B. I'm against trying to fix the order for developer instead of making developer think since that produces unreadable list of validators.
2. What's the deal with iterator? We're simply doing foreach and don't see a use-case for a more complicated iterator.

**Comment by samdark** [comment]
> users can set any order

I'm strictly against it.

**Comment by WinterSilence** [comment]
@samdark can you explain your reasons?

**Comment by samdark** [comment]
I already did: https://github.com/yiisoft/yii2/pull/19335#issuecomment-1092866195

**Pull request closed without merging**
