### PR TITLE
Add namespace for RBAC migration

### PR DESCRIPTION
**Pull request by rapita**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    |no
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by cebe** [comment]
can you explain the change?

**Comment by rapita** [comment]
This makes it possible to configure MigrateController.
It is much easier to automatically deploy project(using db rbac) in production server.

Example usage:
```
    'controllerMap' => [
        ...
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'yii\rbac\migrations',
            ],
        ],
        ...
    ],
```

**Comment by cebe** [comment]
this conflicts with another solution to the problem, which is better imo because it will allow integrating the migration with a timestamp that fits application migration order: https://github.com/yiisoft/yii2/issues/5846#issuecomment-258177811 Will check it out later.

**Comment by resurtm** [comment]
@rapita 

> It is much easier to automatically deploy project(using db rbac) in production server.

One line less in your project deploy script would make your life easier? ;-)

**Comment by klimov-paul** [comment]
This is an existing class renaming, e.g. `m140506_102106_rbac_init` to `app\migrations\m140506_102106_rbac_init`. Thus it can not be applied before 2.1

**Pull request closed without merging**
