### PR TITLE
Fixes #15496: CSRF token is now regenerated on changing identity

### PR DESCRIPTION
**Pull request by makcumka2000**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15496

### CODE REVIEW

**Comment by samdark** [comment]
This is problematic. See https://github.com/yiisoft/yii2/pull/15832

**Comment by makcumka2000** [comment]
I've fixed it

**Comment by makcumka2000** [comment]
I pushed fix with --force and travis CI has failed. Is it possible to restart it?

**Comment by samdark** [comment]
This code is already in master.

**Pull request closed without merging**
