### PR TITLE
Update LinkPager.php

### PR DESCRIPTION
**Pull request by IgorSalevan**
Added "activeLinkable" property. 
It serves for turning off the anchor tag from the LinkPager active item. I set the default value to false and this changed the previous functionality.
The main idea of this revision is to follow google recommendation that the page must avoid links to itself.

### CODE REVIEW

**Comment by samdark** [comment]
Would you please point to that Google recommendation?

**Comment by cebe** [comment]
> The main idea of this revision is to follow google recommendation that the page must avoid links to itself.

This does not really make sense, most of navigation points to itself when you click the link in nav it is still there.

**Comment by mulat** [comment]
**samdark**, **cebe**, there is no direct recommendation from Google. Only indirect. 
As I undersand, internal links serve to provide intuitive interface; create clear navigation; show SE crawlers new pages on sites. So the internal link to itself doesn't make any sense. SERP of Google doesn't have such link in LinkPager functionality, but Yandex has.
There are many threads on SEO forums where webmasters are concerned of getting rid of all excessive internel links and links to itself too. 
So I think that giving such a choice to WM is not a bad idea. At least the the property `activeLinkable` may have default value `true`, like the logic of the current core functionality.

**Comment by samdark** [comment]
I prefer not to include unconfirmed SEO mythical stuff into framework. Closing unless there's a strong evidence of not linking to itself being a good thing.

**Pull request closed without merging**
