### PR TITLE
Feature/dependency fixes for php 8.2

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | tests for PHP 8.2

I tried to build Docker images for 8.2 and tests were failing, see https://github.com/yiisoft/yii2-docker/actions/runs/3987076361/jobs/6836419128

~~I had to raise `config.platform` due to:~~
```
  Problem 1
    - Root composer.json requires ezyang/htmlpurifier ^4.15 -> satisfiable by ezyang/htmlpurifier[v4.15.0, v4.16.0].
    - ezyang/htmlpurifier[v4.15.0, v4.16.0] require php ~5.6.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (5.4; overridden via config.platform, actual: 8.2.1) does not satisfy that requirement.
```
~~Maybe we could get rid of this completely?~~ @rob006

Just removed it to see if tests pass.

### CODE REVIEW

**Comment by schmunk42** [comment]
So, Houston we have a problem.

After loosening the constraints HTMLpurifier gets installed as `4.14.0` which is **not** compatible with PHP 8.2.

All versions before that have an **unbound version constraint** `>=5.2.0` - which means that any version could be installed. (see https://packagist.org/packages/ezyang/htmlpurifier#v4.6.0)

If we raise it to `^4.15.0` which is compatible to PHP 8.2 we'll loose compatibility to PHP 5.5 and 5.4. 
IMHO that's reasonable, but that's just my 2 cents. And we'd need to remove them from the tests.

See https://github.com/yiisoft/yii2-docker/actions/runs/3987998195/jobs/6838557097

**Comment by rob006** [comment]
`^4.6` should install `v4.16.0` on PHP 5.6+. The problem is either `composer.lock` or you need to adjust also `framework/composer.json` (I'm not sure how these tests for `yii2-docker` work, it would be easier to adjust tests matrix and test php 8.2 directly in this repo).

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
:+1

**Comment by samdark** [comment]
@rob006 not if package was previously released w/o constraints.

**Comment by rob006** [comment]
> @rob006 not if package was previously released w/o constraints.

Why? Composer will prefer highest possible version compatible with current PHP/constraints, so it should pick `4.16.0` over `4.14.0`.

Also, this PR seems to be unfinished. Main composer.json still has outdated constraints:

https://github.com/yiisoft/yii2/blob/7c0788537520389269597c41dacf7bbf6ede738a/framework/composer.json#L71

**Comment by samdark** [comment]
> All versions before that have an unbound version constraint >=5.2.0 - which means that any version could be installed. (see https://packagist.org/packages/ezyang/htmlpurifier#v4.6.0)

Composer will prefer highest possible version **not marked as ** incompatible. Therefore, it dependency wasn't properly specified before, that old version will _formally_ satisfy the constraint.

**Comment by samdark** [comment]
> Also, this PR seems to be unfinished. Main composer.json still has outdated constraints

Yes. Should be updated. @schmunk42 would you please do another PR?

**Comment by schmunk42** [comment]
Created PR.

I also found the culprit of the confusion. I updated the wrong `TEST_YII_VERSION` in `yii2-docker`.
There was still a `.gitlab-ci.yml` file - which I've removed now.

**Comment by schmunk42** [comment]
> `^4.6` should install `v4.16.0` on PHP 5.6+. The problem is either `composer.lock` or you need to adjust also `framework/composer.json` (I'm not sure how these tests for `yii2-docker` work, it would be easier to adjust tests matrix and test php 8.2 directly in this repo).

It was indeed a wrong/outdated `.lock` file. 

The tests for `yii2-docker` are meant to test that the built images are compatible with the framework, we already had issues with ie. Alpine and ICU lib, that's why testing it on ubuntu with GHactions is not sufficient.

**Comment by rob006** [comment]
> that's why testing it on ubuntu with GHactions is not sufficient.

IMO fixing tests for PHP 8.2 here should be a first step anyway - if it does not pass test on Ubuntu with GitHub actions, it won't pass in any other docker image.

**Comment by schmunk42** [comment]
> IMO fixing tests for PHP 8.2 here should be a first step anyway - if it does not pass test on Ubuntu with GitHub actions, it won't pass in any other docker image.

Can we run PHP 8.2 tests here? 
I looked into this yesterday and found no way to have something like `allow-failure` for some jobs from the matrix.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/19749

**Comment by samdark** [comment]
Merged your PR there.

**Pull request merged**
