### PR TITLE
docs/guide-pt-BR/db-migrations.md - add [skip ci]

### PR DESCRIPTION
**Pull request by janjitsu**

### CODE REVIEW

**Comment by samdark** [comment]
Will merge when last file will be translated.

**Comment by cebe** [comment]
@samdark there is only one pt-BR file in the PR.

**Comment by samdark** [comment]
Omg, I'm so sleepy :)

@janfrs thanks!

**Comment by davidsonalencar** [comment]
Hi @janfrs! If you want to help, there are other files that can be translated. Have a look at:
https://docs.google.com/spreadsheets/d/1pAMe-qsKK0poEsQwGI2HLFmj4afKSkEUd_1qegU5YqQ

**Comment by janfrs** [comment]
Hey @davidsonalencar, thanks for the heads up! I'm translating the entire Cache section right now. :)

**Comment by lukBarros** [comment]
@davidsonalencar  eu já traduzi 2 vendors (yii2-bootstrap e yii2-gii) como faço para entrar no esforço conjunto linkado na planilha???

**Pull request merged**
