### PR TITLE
Returns object from methods for chaining purpose

### PR DESCRIPTION
**Pull request by arturf**

### CODE REVIEW

**Comment by samdark** [comment]
I'm not sure it's a good idea.

**Comment by samdark** [comment]
@yiisoft/core-developers opinions?

**Comment by klimov-paul** [comment]
Method `setAttributes()` produces a virtual property `attributes`, so usually its return value is never used.
Still we can return a self reference as a result. However, there are many similar 'setters' around the framework. There should be a consistency among them.

**Comment by SilverFire** [comment]
Agree with @klimov-paul

**Comment by samdark** [comment]
Since some setters [return true/false depending on the result](https://github.com/yiisoft/yii2/blob/master/framework/caching/Cache.php#L188) I don't think it's a good idea to return object instance for other cases.

**Pull request closed without merging**
