### PR TITLE
docs/guide* update copyright year to 2015

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by samdark** [comment]
I don't think the change is correct. (c) usage is about year content was initially created.

**Comment by vchenin** [comment]
i think it's reasonable to change year, because content of the guides was particularly changed at this year already

**Comment by cebe** [comment]
it does not really matter, year is mainly updated to keep copyright after 100 years to let it not expire as public domain. I do not think anyone cares if the docs become public domain in 100 years.

**Comment by vchenin** [comment]
ok

**Pull request closed without merging**
