### PR TITLE
fixed NumberValidator so it does not validate boolean as true(as number)

### PR DESCRIPTION
**Pull request by annechko**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by annechko** [comment]
For example, as standalone valdator - it will count boolean as valid number
```php
    $val = new NumberValidator(['integerOnly' => true]);
    $val->validate(false); // true
    $val->validate(true); // true
```
also in models
```php
    /*
    [
        ['field', 'integer'],
    ]
    */
    $model->load(['field' => true], '');
    $model->validate(); // true

    $model->load(['field' => false], '');
    $model->validate(); // true  
```
(but false/true are not numbers so I guess it should not be valid)

**Review by cebe — APPROVED** [review]
Looks good to me. Thanks!

**Comment by cebe** [comment]
Please add an entry in the CHANGELOG

**Comment by samdark** [comment]
Merged. Thank you very much!

**Comment by annechko** [comment]
Thank you!
It's my first ever contribution to Open Source! 
(Sorry, can't help but post this)
image

**Comment by samdark** [comment]
Welcome to our world :)

**Pull request merged**
