### PR TITLE
trim pathInfo slashes

### PR DESCRIPTION
**Pull request by DrDeath72**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |

Not both removed as described
- The starting and ending slashes are both removed.

### CODE REVIEW

**Comment by DrDeath72** [comment]
hm... wtf?
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L669
https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L696

**Comment by SilverFire** [comment]
Why do you suggest to make this change?

**Comment by DrDeath72** [comment]
See prev comment with code comments

**Comment by mikehaertl** [comment]
Instead of changing code which could break BC I suggest to only fix the docs for both methods to:

> If there's a starting slash, it gets removed. End slashes will be kept.

**Comment by DrDeath72** [comment]
php pathinfo, basename etc remove ending slash

**Comment by cebe** [comment]
trailing slash is relevant as `/example/` and `/example` are two different urls.

**Comment by zhou19901104** [comment]
我想找一个Yii项目 练习

**Comment by shuangjie** [comment]
试试将webuploader整合进yii2?哈哈

**Comment by SilverFire** [comment]
Agree with @cebe 

@DrDeath72 would you like to update this PR?

**Comment by samdark** [comment]
Closing since 3.0 implementation is different.

**Pull request closed without merging**
