### PR TITLE
resolve 19243

### PR DESCRIPTION
**Pull request by longthanhtran**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #19243

### CODE REVIEW

**Comment by tanakahisateru** [comment]
I tested `finfo_file()` with PHP versions.

```
% docker run -it --rm -v "$PWD":/demo -w /demo php:7.4-cli php finfo.php
/demo/demo.tar.gz -> application/gzip
/demo/demo.tar.bz2 -> application/x-bzip2
/demo/demo.tar.xz -> application/x-xz

% docker run -it --rm -v "$PWD":/demo -w /demo php:8.0-cli php finfo.php
/demo/demo.tar.gz -> application/gzip
/demo/demo.tar.bz2 -> application/x-bzip2
/demo/demo.tar.xz -> application/x-xz

% docker run -it --rm -v "$PWD":/demo -w /demo php:8.1-cli php finfo.php
/demo/demo.tar.gz -> application/gzip
/demo/demo.tar.bz2 -> application/x-bzip2
/demo/demo.tar.xz -> application/octet-stream
```

**Comment by longthanhtran** [comment]
yes, that the main thing right now. I am looking for the way to replace the mimetype when starting with PHP 8.1. You may want to look at FileValidatorTest's validMimeTypes() and mimeTypes.php content.

**Comment by tanakahisateru** [comment]
Future PHP may fix this bug. I suggest not to change production, instead simply to replace xz with gz for tests.

**Comment by longthanhtran** [comment]
The content of mimetypes was getting from https://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?revision=1884511&view=markup. However, when I look at https://www.iana.org/assignments/media-types/media-types.xhtml, xz doesn't show up. Is that the significant change for this filetype?

**Review by samdark — APPROVED** [review]
👍 Need a line for CHANGELOG.

**Review by Arhell — COMMENTED** [review]
Resolve conflicts @longthanhtran please

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
