### PR TITLE
calling getValue() for each attribute in AttributeBehavior

### PR DESCRIPTION
**Pull request by h0lg**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | I hope not |
| Tests pass? | haven't checked |
| Fixed issues | none |

calling getValue() for each attribute (instead of once for all attributes) and passing attribute name along as a parameter to value function so that value function can return different values depending on current attribute

### CODE REVIEW

**Comment by cebe** [comment]
what is the use case for this? wouldn't it be better to add multiple behaviors in this case?

**Comment by forger** [comment]
Just seeing that this breaks the build. I'll fix this.
Anyway - use case: I want to return a value for an attribute depending on the current value of the attribute. That is, I want to a type conversion. I want to convert a DateTime to a time stamp or string on beforeUpdate/beforeInsert and the timestamp/string back into a DateTime on afterFind.

**Comment by forger** [comment]
@cebe you asked:
> wouldn't it be better to add multiple behaviors in this case?

The behavior is actually the same for each attribute. I just want to be able to change an attribute's value depending on the original value of the attribute. So running the value function once for all attributes won't do because that would set the same new value on all attributes. So I want to have the attribute's name in the value function to identify the attribute`to get its value. Does this make sense to you?
 I can of course do that with a custom attribute which is what I'm doing right now. I just thought the existing AttributeBehavior could benefit from this. Any thoughts?

**Comment by cebe** [comment]
it could maybe, even though that is out of the original scope of it. Need to check it in more detail.

**Comment by forger** [comment]
I basically suggested the change to AttributeBehavior so I can do what I've done in the following subclass. Maybe that makes it easier to understand than my previous comment does.

`final class DateTimeConversionBehavior extends AttributeBehavior
{
    const DATETIME_FORMAT = "Y-m-d H:i:s";
    public $dateTimeAttributes;

    function init()
    {
        parent::init();

        if (empty($this->attributes)) {
            $this->attributes = [
                BaseActiveRecord::EVENT_BEFORE_INSERT => $this->dateTimeAttributes,
                BaseActiveRecord::EVENT_BEFORE_UPDATE => $this->dateTimeAttributes,
                BaseActiveRecord::EVENT_AFTER_FIND => $this->dateTimeAttributes,
            ];
        }

        if ($this->value === null) {
            $this->value = [$this, 'getAttributeValue'];
        }
    }

    function getAttributeValue($event, $attributeName)
    {
        switch ($event->name) {
            case BaseActiveRecord::EVENT_BEFORE_INSERT:
            case BaseActiveRecord::EVENT_BEFORE_UPDATE:
                return $this->convertToMySqlDateTime($event->sender->$attributeName);
            case BaseActiveRecord::EVENT_AFTER_FIND:
                return $this->convertToPhpDateTime($event->sender->$attributeName);
        }
    }

    function convertToMySqlDateTime($phpDateTime)
    {
        return $phpDateTime === null ?
            null :
            $phpDateTime->format(static::DATETIME_FORMAT);
    }

    function convertToPhpDateTime($mySqlDateTime)
    {
        return $mySqlDateTime === null ?
            null :
            date_create_from_format(static::DATETIME_FORMAT, $mySqlDateTime);
    }
}
`

**Comment by samdark** [comment]
Won't make it into 2.0.

**Pull request closed without merging**
