### PR TITLE
Use (array) cast instead of !is_array check for both readability and performance

### PR DESCRIPTION
**Pull request by samdark**

### CODE REVIEW

**Comment by samdark** [comment]
Hmm... HHVM failed. Any idea why?

**Comment by Faryshta** [comment]
If an object is converted to an array, the result is an array whose elements are the object's properties. The keys are the member variable names, with a few notable exceptions: integer properties are unaccessible; private variables have the class name prepended to the variable name; protected variables have a '*' prepended to the variable name. These prepended values have null bytes on either side. This can result in some unexpected behaviour:

https://github.com/yiisoft/yii2/blob/use_array_cast_instead_of_check/framework/helpers/BaseHtml.php#L1075

**Comment by samdark** [comment]
@Faryshta thanks :) I thought it failed on HHVM only but it doesn't seem to be the case. Will check it tomorrow.

**Comment by cebe** [comment]
Blindly casting to array is not a good idea in most cases.

**Comment by cebe** [comment]
I think we should not make any of these changes.

**Comment by Faryshta** [comment]
Some of this changes are cool, for example when you know that the element to be casted will be an string or an integer. The error here comes from casting objects to arrays.

**Comment by creocoder** [comment]
:+1: to changes where it do not break anything

**Comment by samdark** [comment]
I'll re-check which cases could be applied and which could not.

**Pull request closed without merging**
