### PR TITLE
Allow jQuery 3.3

### PR DESCRIPTION
**Pull request by Slamdunk**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | Dependency update

### CODE REVIEW

**Comment by samdark** [comment]
Have you tested framework's JavaScript with it?

**Comment by Slamdunk** [comment]
I thought Travis automatically run at PR

**Comment by samdark** [comment]
It does but we don't have 100% coverage.

**Comment by samdark** [comment]
Do you have any JavaScript-intensive app that uses Yii JS features?

**Comment by Slamdunk** [comment]
Yes, but I don't get the point of your question.

As a maintainer, you can't rely on user's words to handle third party dependencies. Either you test them and take objective decisions, or just upgrade without doubts: if you can't tell if it's broken, it doesn't matter if it breaks.

**Review by samdark — APPROVED** [review]

**Comment by Slamdunk** [comment]
Done

**Comment by bscheshirwork** [comment]
So... I have no effect after double run `composer update`
```
$ composer show|grep jquery
...
bower-asset/jquery                               3.2.1             
```

**Comment by bscheshirwork** [comment]
```sh
yiisoft/yii2                                     dev-master ade07cf Yii PHP Framework Version 2
```
https://github.com/search?q=org%3Ayiisoft+ade07cf&type=Commits

```json
        "bower-asset/jquery": "3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable",
```

```sh
  - Installing bower-asset/jquery (3.2.1): Reading /root/.composer/cache/files/bower-asset/jquery/da2d9b9cec42cc780b0b896c590e2177db070974.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/var/www/html/vendor/bower-asset/jquery/d53f2ccea052f85eb896c4195ca150b5' -d '/var/www/html/vendor/composer/d100b23f'
    REASON: yiisoft/yii2 2.0.x-dev requires bower-asset/jquery 3.2.*@stable | 3.1.*@stable | 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> satisfiable by bower-asset/jquery[3.2.1, 3.2.0, 3.1.1, 3.1.0, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.1-RC2, 2.1.1-RC1, 2.1.1-beta1, 2.1.0, 2.1.0-RC1, 2.1.0-beta3, 2.1.0-beta2, 2.1.0-beta1, 1.12.4, 1.12.3, 1.12.2, 1.12.1-patch1, 1.12.1, 1.12.0, 1.11.3, 1.11.2, 1.11.1, 1.11.1-RC2, 1.11.1-RC1, 1.11.1-beta1, 1.11.0, 1.11.0-RC1, 1.11.0-beta3, 1.11.0-beta2, 1.11.0-beta1].
```

**Comment by rob006** [comment]
Yeah, we have two `composer.json`s here...

https://github.com/yiisoft/yii2/blob/master/framework/composer.json

**Pull request merged**
