### PR TITLE
 Russian translation: some edits - \docs\guide-ru\db-migrations.md

### PR DESCRIPTION
**Pull request by sergey144010**
Something edits

### CODE REVIEW

**Comment by SilverFire** [comment]
Something is definitely wrong with this PR...

**Comment by cebe** [comment]
seems the last commit broke it.

**Comment by cebe** [comment]
> added some commits on 2 Mar 2015 

this branch is based on a very old state of the repo. It can not be applied without huge merge conflicts.

**Comment by sergey144010** [comment]
I had an old repository, update to the latest version by direct file copy. Probably did it wrong. I would be very happy, if you teach correctly update my repository. That would not be problems.

**Comment by SilverFire** [comment]
Please, check out our Git workflow manual https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by sergey144010** [comment]
thanks, will be fixed

**Comment by sergey144010** [comment]
I Hope fixed everything correctly.
https://github.com/sergey144010/yii2/blob/sergey144010-doc/docs/guide-ru/db-migrations.md

**Comment by samdark** [comment]
Nope.

**Comment by sergey144010** [comment]
Ok. And now what are my next steps. Close this topic and open new, because this topic save old changes? Or not and require different actions, and what actions?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Pull request closed without merging**
