### PR TITLE
queryScalar correction

### PR DESCRIPTION
**Pull request by gunnrryy**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | -
| Tests pass?   | -
| Fixed issues  | #14379

### CODE REVIEW

**Comment by gunnrryy** [comment]
removed earlier PR as suggested for maintaining code format.

**Comment by samdark** [comment]
Thanks for fixing formatting. Would be cool to add unit tests as mentioned by our @yii-bot.

**Comment by gunnrryy** [comment]
don't know how to unit test. searched alot but didnt find any understandable source.

can you guide me to some source where i can see examples, in reference with Yii2 unit test.
new to this paradigm and eager to learn.
Thanks in advance.

**Comment by gunnrryy** [comment]
till then, ill try to explain the scenario here.

when ActiveQuery()->count() is called without passing parameter, the 1st parameter being passed to queryScalar() is COUNT(*) by default values. 

when using ORDER BY clause on virtual column, virtual column is not found in * and hence FATAL ERROR.
Since any column that we want to apply aggregate function or Orderby, we need to have that column in select mandatory.

if evaluated from $this->select, the virtual column is calculated from select expression and avoids the issue.

solution: 
if any parameter is passed in ActiveQuery()->count('cases.id'), the parameter being passed to queryScalar is COUNT("cases.id") and evaluated corresponding. if nothing is passed and virtual column is used, current code breaks.

can be handled by checking the 1st parameter passed to queryScalar being default or no to whether evaluate from $this->select or directly by *, the issue seems to  resolve.

**Comment by gunnrryy** [comment]
my bad, 
this doesn't solve it completely. just the evaluation of query part worked by adding the mentioned condition.

but this creates  issue with pagination. coming round from where we started.

for now, a work around that i applied is, 

```
$countQuery = clone $support_case_model;
$countQuery->orderBy = '';
$pages = new Pagination(['totalCount' => $countQuery->count()]);
```

by this, i dont get the error of virtual column and pagination also works correctly.
NOTE: this is not a fix. just a work around.
ISSUE IS STILL THERE FOR HAVING  VIRTUAL COLUMN IN ORDER BY CLAUSE OF QUERY.
issue is STILL there for having **VIRTUAL COLUMN in ORDER BY CLAUSE**

**Pull request closed without merging**
