### PR TITLE
Fixed duplicated quote.

### PR DESCRIPTION
**Pull request by sugiruu**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | https://github.com/yiisoft/yii2/pull/11850#issuecomment-229752720 |

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by pavi32** [comment]
Please somedoby help me i don't know where to ask this type of questions, i m new to yii2, my requirement is , when i run my server first time if database is not exits i want to create and insert some data, how to do this and where(means after loading application or loading container or after loading module). please suggest me thank you

**Comment by samdark** [comment]
Here: http://www.yiiframework.com/forum/ or http://www.yiiframework.com/chat/

**Comment by Bvanleeuwen** [comment]
Thank you for the fix!

**Pull request merged**
