### PR TITLE
fix #10563, #11953 current implementation of file download does not encode UTF8 filenames correctly

### LINKED ISSUE #10563: Current implementation of file download does not encode UTF8 filenames correctly
see https://github.com/yiisoft/yii/issues/2620#issuecomment-20663991

https://github.com/yiisoft/yii2/blob/8f1245553f1b3dcb5b4022780eb83a69f5065f33/framework/web/Response.php#L565

### PR DESCRIPTION
**Pull request by shirase**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | no |
| Fixed issues | #10563, #11953 |

### CODE REVIEW

**Comment by PowerGamer1** [comment]
So now just because `mb_detect_encoding` is not installed or failed to detect encoding UTF-8 filename will be absent in HTTP header?

I would not use `mb_detect_encoding` at all and instead either:
a) require user to always pass `$attachmentName` in 'UTF-8'
or
b) allow to specify the encoding of `$attachmentName` as additional option in `Response::sendFile()` and then specify that encoding in generated HTTP header.

Also, it may be beneficial for compatibility with older browsers to also always include "filename=" (without asterisk , see the last example and explanation here: https://tools.ietf.org/html/rfc6266#section-5) and also not perform any encoding at all if every character in UFT-8 encoded `$attachmentName` is already US-ASCII.

**Comment by shirase** [comment]
a) breaks backward compatibility, because current master works in all modern browsers except IE. 
b) i vote for it and make changes

**Comment by PowerGamer1** [comment]
@shirase 
Sorry, but I don't think you really realize the extent of the problem with regards of what is broken and how to fix it. The following is already wrong (HTTP headers cannot have non US-ASCII characters in them):

```PHP
->setDefault('Content-Disposition', "$disposition; filename=\"$attachmentName\"" .
```

For that same reason when the `$attachmentName` is `null` you cannot just grab `basename($filePath)` disregarding the underlying encoding of `$filePath` (which is completely different on different OSes) and shove it directly into HTTP header.

**Comment by shirase** [comment]
If $attachmentName is null, you must to set attachmentFileNameEncoding to your filesystem encoding, But it is better to set $attachmentName.

**Comment by shirase** [comment]
IE supports only UTF-8, I should think.

**Comment by shirase** [comment]
How about this one?

**Comment by PowerGamer1** [comment]
> How about this one?

Exactly the same problem as before - invalid characters in HTTP header. See my version: https://github.com/yiisoft/yii2/pull/12062.

**Comment by shirase** [comment]
$attachmentName must be ASCII only. If you need UTF-8 file name, use utf8Name option. Your solution can be used in 2.1.x.

**Comment by shirase** [comment]
I made some changes. Not by RFC but it works in modern and old browsers and it have BC.

**Comment by samdark** [comment]
Which old browsers have you tested?

**Comment by samdark** [comment]
The solution technically works in majority of cases but isn't complete.

**Pull request closed without merging**
