### PR TITLE
Use `bool` and `int` in phpdoc

### LINKED ISSUE #12055: Suggestion to use int/bool instead of integer/boolean in doc blocks
Yii currently uses long type names for int/bool in doc blocks:
https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#44-doc-blocks

I adopted this standard, however it always meant a certain discomfort for me since PhpStorm auto-generates PHPDoc stubs using shot type names. It made me submit a feature request to JetBrains to support long type names in auto-generated PHPDoc. Upon this request I was suggested to reconsider the usage of the long form at all as PHP 7 allows only the short form for type hinting.

Thus, I would suggest to consider this change in the Yii Code Style standards as well.

### PR DESCRIPTION
**Pull request by rob006**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #12055 |

fixes #12055

### CODE REVIEW

**Comment by lukeholder** [comment]
Does this mean the core code style doc will need updating?:

https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#44-doc-blocks

**Comment by rob006** [comment]
@lukeholder This is already changed in this PR.

**Comment by lukeholder** [comment]
@rob006 ah, didnt see it in the commits! Sorry for the noise - ignore me.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Verified and merged. Thank you!

**Pull request merged**
