### PR TITLE
mssql: Add brackets for non conventional or reserved keywords column names. issue #18416

### PR DESCRIPTION
**Pull request by sedovserge**
Fix issue #18416

### CODE REVIEW

**Comment by bizley** [comment]
Some tests need fixing. Is this the only place that needs quoting?

**Comment by alligator77** [comment]
I looked through the code, basically there are quotes everywhere, but they forgot to install them in this place. There were no other problems with this.

**Comment by bizley** [comment]
So just the tests fixes and changelog, please.

**Comment by samdark** [comment]
Thanks for contributing but closing this PR in favor of https://github.com/yiisoft/yii2/pull/18427. It is a bit more complete.

**Pull request closed without merging**
