### PR TITLE
Translation of part of the documentation into Uzbek

### PR DESCRIPTION
**Pull request by jakharbek**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by cebe** [comment]
Thank you! I have enabled Uzbek language on the website: https://www.yiiframework.com/doc/guide/2.0/uz

@jakharbek Could you please confirm, that `o‘zbek` is the correct native name of the language?

**Comment by rustamwin** [comment]
@cebe I confirm. I'm from Uzbekistan

**Comment by cebe** [comment]
Thanks!

**Comment by jakharbek** [comment]
@cebe The first letter should be capitalized.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/f8ba14e25a6addd697597119f2180f4eec4b9215

**Pull request merged**
