### PR TITLE
check locks exists in FileMutex::$_files property or in the folder

### PR DESCRIPTION
**Pull request by albertborsos**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | 

I tried to use FileMutex, but I realised it checks for acquired lock files in `$_locks` property instead of `$_files` property. Also if jobs runs over, the latter job finds nothing in `$_files` because it is an other process, so I checked for the existing `*.lock` file.

### CODE REVIEW

**Comment by albertborsos** [comment]
I may be wrong with the essence of mutex.

If I have 2 instances of a mutex object with the same configuration, then this line why should be false? 
https://github.com/yiisoft/yii2/blob/master/tests/framework/mutex/MutexTestTrait.php#L101

If I previously acquired a lock for `$mutexName`, then why should it be "not acquired" for the other instance if I did not release the lock yet.

**Comment by bizley** [comment]
@rob006 could you take a look at this?

**Comment by albertborsos** [comment]
I misunderstood the functionality of `isAcquired()` method. I thought it should check the global existence of the lock file, not just for the current process. Then I realised the `acquire()` method will check for the lock file of other process.

Btw, it is another thing, but if the `\yii\mutex\Mutex::$_locks` property would be `protected`, then a lot of redundancy could be saved.

**Comment by rob006** [comment]
> If I previously acquired a lock for `$mutexName`, then why should it be "not acquired" for the other instance if I did not release the lock yet.

This is because this second instance does not acquired this lock. In general you may get really weird results if you use multiple instances of `Mutex` component in one process, so just don't do this in real life. It should work fine if each process have one mutex component used as singleton. 
Also, I think that `isAcquired()` is really unreliable with current implementation - it is hard/impossible to ensure that lock is still acquired without actual checking of lock backend storage (things like DBMS disconnection may silently release the lock).

I'm not sure what this PR changes in context of this behavior - using `\yii\mutex\Mutex::$_locks` should work just fine, sine it is set on `acquire()` and `release()`.

**Comment by albertborsos** [comment]
Maybe I am misconfigured something. It works fine without my "patch" too. Thanks.

**Pull request closed without merging**
