### PR TITLE
Add tests for `PHP 8.4` branch `master`.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Hi, with the new [RFC of explicit nullable in PHP 8.4](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types), the tests will fail, we must upload the PHP version in the master branch for `2.0.50`, there is already work done around `PHP 7.3`, but i think we should increase to at least `PHP 7.4` , this will allow us to eliminate cwgans patch and use PHPUnit `9.6`.

**Comment by rob006** [comment]
> there is already work done around `PHP 7.3`, but i think we should increase to at least `PHP 7.4` , this will allow us to eliminate `cwgans patch` and use `PHPUnit 9.6`.

phpunit 9.6 works on PHP 7.3

**Comment by rob006** [comment]
There is also a PR with nullable types fix: https://github.com/yiisoft/yii2/pull/20133

@terabytesoftw Do you remember why https://github.com/yiisoft/yii2/pull/19959 was closed?

**Comment by terabytesoftw** [comment]
> There is also a PR with nullable types fix: #20133
> 
> @terabytesoftw Do you remember why #19959 was closed?

I closed it by mistake, but i have it locally, so i will upload it without problems, yes `PHP 7.3` will also work with `PHPUnit 9.6`.

**Review by samdark — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Review by bizley — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Pull request merged**
