### PR TITLE
Remove cache \yii\data\ActiveDataProvider::prepareTotalCount()

### PR DESCRIPTION
**Pull request by lav45**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #20194 #20205

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Review by bizley — APPROVED** [review]

**Review by terabytesoftw — APPROVED** [review]

**Comment by terabytesoftw** [comment]
You can test if this change resolves the yii2-elasticsearch issue.

**Comment by sleptor** [comment]
Cache removal degraded performance. 
Now, every page calls count query 4 times! I use kartik gridview

**Comment by mtangoo** [comment]
Can you test if it is the case with Plain Yii Gridview?

**Comment by sleptor** [comment]
Tested standard yii\grid\GridView (dev-master).
It makes 5 (five) identical count queries during webpage load. Checked from debug panel.

So, the cache definitely does not work, which affects performance notably.

**Comment by sleptor** [comment]
FYI
I described the issue and possible solution here
https://github.com/yiisoft/yii2/issues/20213

**Pull request merged**
