### PR TITLE
typos in en-US concept-di-container.md [skip ci]

### PR DESCRIPTION
**Pull request by jaaf**
| Q | A |
| --- | --- |
| Is bugfix? | yes/no |
| New feature? | yes/no |
| Breaks BC? | yes/no |
| Tests pass? | yes/no |
| Fixed issues | comma-separated list of tickets # fixed by the PR, if any |

### CODE REVIEW

**Comment by samdark** [comment]
Both are correct.

**Comment by samdark** [comment]
Dependent class is the class that depends on something.

Though means something like "still" in this context.

**Comment by jaaf** [comment]
Hi.
I agree on the idea that a dependent class is a class that depends on something (in this case on the dependency).
You are probably more clever than me in OOP but I thought that in the context on this sentence:
> The container will first inspect the class constructor to find out dependent class or interface names
> and then automatically resolve those dependencies recursively
what is passed to the constructor is the dependency. I also thought that the dependent class was the class that was being constructed.  I am probably confusing things. 

.

**Comment by samdark** [comment]
"dependent class or interface names" means name of either dependent class or dependent interface. When you're getting something from container you're giving it this name. Dependencies of these classes are determined from dependent class constructor signature.

I know the language for dependency injection is rather vague but that's what's commonly used in this field.

**Pull request closed without merging**
