### PR TITLE
Refactor migrations template

### PR DESCRIPTION
**Pull request by Kolyunya**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

- [x] Add a `safeDown()` placeholder.
- [x] Make `safeUp()` consistent with `up()`.
- [x] Add a missing period in a comment.
- [x] Update tests.

### CODE REVIEW

**Comment by Kolyunya** [comment]
Ooops missed the tests.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Please add a line for changelog and I'll merge it.

**Comment by Kolyunya** [comment]
Would
> Enh: Refactored migrations template
be sufficient?

**Comment by samdark** [comment]
If you'll add `#13823` and your username — yes.

**Comment by Kolyunya** [comment]
I used to think that the `#xxxx` is the issue number, isn't it?

**Comment by samdark** [comment]
It is. In this case it's pull request number because there's no issue.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by Kolyunya** [comment]
Glad to help!

B.t.w. is unsafe template generated by default purposefully? I know that there are DBMS which don't support transactions but it seems like this adds friction for the majority of the developers. I personally use safe migrations only.

**Comment by samdark** [comment]
@Kolyunya that's a good question.

**Comment by samdark** [comment]
Deserves separate issue. I don't remember why unsafe ones are used and it doesn't look good.

**Comment by Kolyunya** [comment]
Shall I open an issue for that?

**Comment by Kolyunya** [comment]
I think the rationale behind that is that *some* DBMSs don't support transactions and safe migrations may cause errors.

**Pull request merged**
