### PR TITLE
Update yii.activeForm.js

### PR DESCRIPTION
**Pull request by DrDeath72**
simplify

```
$('#contact-form').data('yiiActiveForm').submitting = true;
$('#contact-form').yiiActiveForm('validate');
```

### CODE REVIEW

**Review by samdark — CHANGES_REQUESTED** [review]
Need a line for CHANGELOG. Additionally code style should match the one we're using.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by koxu1996** [comment]
@samdark What if I want to validate form without submitting, is it currently impossible?

**Comment by samdark** [comment]
With this method it's possible. Try it.

**Comment by koxu1996** [comment]
@samdark When I call ``yiiActiveForm('validate')`` undefined is returned and nothing happens. Also afterValidate is not triggered.

**Comment by samdark** [comment]
Yes. That's 2.0.9 behavior and this pull request changes it.

**Comment by koxu1996** [comment]
@samdark You don't understand me. I am talking about this issue #12374

**Comment by samdark** [comment]
Well, that's different issue.

**Pull request closed without merging**
