### PR TITLE
Performance of `yii\base\Model` methods `attributes()` and `formName()`

### PR DESCRIPTION
**Pull request by klimov-paul**
Extracted from #8247

> The proposed optimization approach is problematic. See this gist: https://gist.github.com/qiangxue/9c6635ffeacef3eff8a9
> You will get "BB" rather than "BA".

Fixed

### CODE REVIEW

**Comment by cebe** [comment]
have you run any script to test how much this brings?

**Comment by klimov-paul** [comment]
I am afraid I don't have a pure environment for this.
Still, you can refer to begining of this at #8189

**Comment by laszlovl** [comment]
I have created a benchmark script to go with https://github.com/laszlovl/yii2-staticactiverecord. It works on `ActiveRecord` instead of `Model`, so it can't test `Model::attributes()`, but you could adapt it fairly easily.

**Comment by qiangxue** [comment]
>  We should mainly do this to deal with performance bottlenecks on the critical path. If we take a look at the three places being optimized in this PR, we may find they are not really called frequently (formName() is only used when you take form inputs, which usually happens once; tableName() is usually overridden with a plain string; attributes() is mainly used when setting/getting attributes in batch mode, which again usually happens once at most.)

This is my comment about such optimization. I think in this situation, it's better we keep simple code rather than micro-optimization.

**Comment by klimov-paul** [comment]
`Model::attributes()` is involved at `setAttributes()` and `getAttributes()`, thus it is involved at `Model::popuplate()` and at any processing, which comes in case of successful validation.

> formName() is only used when you take form inputs, which usually happens once

This is not true. `Model::formName()` is invoked by `Html::getInputName()`, which is invoked per each(!) created form control. Also `Html::getInputId()` invokes `Html::getInputName()`.
If form have 10 inputs `formName()` will be executed 20 times.

Also do not forget about possible tabular input.

**Comment by cebe** [comment]
why did you close it?

**Comment by klimov-paul** [comment]
I have found somehing interesting:
https://github.com/yiisoft/yii/pull/2739#discussion_r5756308

Although I still think `attributes()` and `formName()` may be improved, unless there is a benchmark, which proofs such optimization makes actual sense, I will not proceed with it.

Unfortunally, I don't have a clear environment to perfrom such benchmark.
If anyone is willing to investigate issue further, feel free to reopen this.

**Comment by cebe** [comment]
lets keep this open, I will run some benchmarks, when I find time.

**Comment by klimov-paul** [comment]
Relates #7280

**Comment by Faryshta** [comment]
I don't like that the `static` variable declaration is inside the function. I know its allowed on php 5.4 but it will make it harder to debug since all the other functions and methods are class properties and not static function properties.

And I also think you need to update the `ActiveRecord::refresh()` to unset the formName and attribute list after refreshing.

And finally... how much this would affect the usage of scenarios?

**Comment by klimov-paul** [comment]
> I don't like that the static variable declaration is inside the function. I know its allowed on php 5.4 but it will make it harder to debug since all the other functions and methods are class properties and not static function properties.

Using class properties in this case will produce redundant meta data, if you will you may override  `attributes()` or `formName()` creating your own implementation.

> I also think you need to update the ActiveRecord::refresh() to unset the formName and attribute list after refreshing.

Why? `ActiveRecord::refresh()` reloads attribute values(!) from DB, it does not relates to `attribute()` method. And most of all this PR does NOT affect `ActiveRecord` at all.

> how much this would affect the usage of scenarios?

It will not affect it anyhow.

**Comment by cebe** [comment]
closing as this is minor. If someone finds the time feel free to do a benchmark.

**Pull request closed without merging**
