### PR TITLE
routing redirect

### PR DESCRIPTION
**Pull request by np25071984**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14553

I would like to implement this feature on Yii2 and only after that transfer the code to Yii3 branch.

### CODE REVIEW

**Comment by rob006** [comment]
I don't think that redirection should be done by rule - redirecting is `UrlNormalizer` job.

**Comment by GHopperMSK** [comment]
I thought about this, but every time I go through
https://github.com/yiisoft/yii2/blob/fe3ae964cdd439e7f96a99cf9d625cf7d8ca2f2c/framework/web/UrlRule.php#L440-L443
I get `$normalized` equal to false.
Here is my `web.php` config:
```
...
'urlManager' => [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules' => [
        [
            'pattern' => 'posts/<year:\d{4}>/<category>',
            'redirect' => 'redirect_destination/<category>/<year>',
            'statusCode' => 301,
        ],
    ],
],
...
```

**Comment by samdark** [comment]
Sorry but enhancements aren't accepted into 2.0.

**Comment by GHopperMSK** [comment]
All I wanted is just find out the solution and after that implement it over v3.0 I even didn't make any changes in `CHANGELOG.md` file due to I knew it will not be merged.

Now I have only one question - do we need this feature implementation with configuration as was described in #14553? As I can understand, the configuration doesn't imply `UrlNormalizer` existence?

**Comment by rob006** [comment]
Considering https://github.com/yiisoft/yii-web/issues/5 and https://github.com/yiisoft/yii-core/issues/165 the whole idea may be obsolete - all you need is parse-only rule with simple handler for redirection.

**Comment by rob006** [comment]
And from `UrlNormalizer` perspective it may be  fixed in some more generic way:

1. Parse request URL.
2. Try create URL using current route and GET data.
3. If current URL is different that generated one - redirect.

In this way URL will be always normalized to one version. If you want to support some old URLs, all you need is to put old rule after new one - new rule will have precedence for creating URLs and old URL will redirect to new URL.

**Comment by GHopperMSK** [comment]
Thank you. It is clear now.

**Pull request closed without merging**
