### PR TITLE
[REST] extraPatterns should take precedence over patterns

### PR DESCRIPTION
**Pull request by Agrumas**
According to docs extraPatterns should take precedence over patterns.

### CODE REVIEW

**Comment by cebe** [comment]
the original code is correct, left most parameter of array_merge takes precedence.

**Comment by Agrumas** [comment]
@cebe could you check again, because array_merge appends items to previous
ones.
2015 bal. 12 23:41 "Carsten Brandt" <notifications@github.com> rašė:

**Comment by cebe** [comment]
http://php.net/manual/en/function.array-merge.php

see the example code, array2 takes precedence over array1 for key 'color'.

**Comment by cebe** [comment]
Hm... I see what you mean now. There is a duplicate meaning of `precedence` here. It could mean:

- extraPatterns overwrite patterns or
- extraPatterns will be in the list of patterns before patterns

@qiangxue what is the purpose of having extraPatterns and how should this work?

**Comment by Agrumas** [comment]
@cebe oh, i interpreted precedence as matching order.
I use MongoDB, so my id pattern accepts letters. When i try to access custom route (module/test) defined in extraPatterns, router invokes actionView with id test. I could make id regex more precise, but main issue still exits - i could not add higher priority route without redefining all rests rules.
So should extraPatterns cover this case or not?

**Comment by cebe** [comment]
I am not sure, lets wait for @qiangxue for a decision.

**Comment by Agrumas** [comment]
This covers both cases:
```php
$patterns = $this->extraPatterns + $this->patterns
```

**Comment by qiangxue** [comment]
By "taking precedence", I mean patterns specified in `extraPatterns` will overwrite those in `patterns` if they are the same. This gives you chance to customize the route. So the original code was written for this purpose.

I understand your problem about specifying a higher priority rule via `extraPatterns`. I think your proposal `$this->extraPatterns + $this->patterns` should be fine. Would be great if you could add some unit test.

**Comment by Agrumas** [comment]
@qiangxue @cebe here you go

**Comment by qiangxue** [comment]
Thanks!

**Pull request merged**
