### PR TITLE
Fixed writing tags that dont close.

### PR DESCRIPTION
**Pull request by sharkbit**
Adjusted the closing of tags, and added /> to close tags that are Void Elements.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | didn't feel like making an issue very simple fix

### CODE REVIEW

**Comment by Thoulah** [comment]
I vote strongy against this

**Comment by sharkbit** [comment]
Well you give a great reason for such a strong disagreement.

**Comment by SilverFire** [comment]
While the change is not bad itself, it will break a lot of tests in framework and in developer's code, so the necessity is disputable.

**Comment by samdark** [comment]
It isn't necessary in HTML5. http://blog.teamtreehouse.com/to-close-or-not-to-close-tags-in-html5

**Pull request closed without merging**
