### PR TITLE
Remove duplicate tests in CI.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by terabytesoftw** [comment]
With this latest modification, it will work correctly by eliminating double flows for pull requests. Additionally, it runs the flows in the fork, and only pushes to the master branch. 

This should cut the number of workers and test time in half.

**Comment by bizley** [comment]
@terabytesoftw can we merge it or does it require more work?

**Comment by terabytesoftw** [comment]
> @terabytesoftw can we merge it or does it require more work?

Let's wait better, try it some more.

**Comment by samdark** [comment]
@terabytesoftw enough time passed?

**Comment by terabytesoftw** [comment]
After reviewing well, it is not necessary, all the PR in Yii2 come from a fork, so it is not a problem.

**Comment by xicond** [comment]
I'm wandering, can we only execute ci-node on js changed
a job intermittently failed [17871509197](https://github.com/yiisoft/yii2/actions/runs/6578233064/job/17871509197?pr=20007) while I'm not changing js #20007

**Pull request closed without merging**
