### PR TITLE
Fix header collection from array

### PR DESCRIPTION
**Pull request by rhertogh**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

`HeaderCollection` uses lower case keys for the header names. This PR ensures the keys are lower case in case of `::fromArray()`.

### CODE REVIEW

**Comment by WinterSilence** [comment]
@rhertogh it's wrong solution, please read [1.2 HTTP Headers](https://www.php-fig.org/psr/psr-7/)

**Comment by rhertogh** [comment]
@WinterSilence 
> it's wrong solution, please read [1.2 HTTP Headers](https://www.php-fig.org/psr/psr-7/)

Could you please be more specific what is wrong? As far as I know Yii2 is not PSR-7 compliant.
When setting a header with [`set()`](https://github.com/yiisoft/yii2/blob/master/framework/web/HeaderCollection.php#L90) or  [`add()`](https://github.com/yiisoft/yii2/blob/master/framework/web/HeaderCollection.php#L106) the name is converted to lower case. The same goes for [`get()`](https://github.com/yiisoft/yii2/blob/master/framework/web/HeaderCollection.php#L73).
Therefore the following code would fail without this patch:
```php
$headerCollection = new HeaderCollection();
$location = 'my-test-location';
$headerCollection->fromArray([
    'Location' => [$location],
]);
$headerCollection->get('Location'); // returns `null` instead of 'my-test-location'
```
Using lowercase everywhere except in `fromArray()` makes the header names case-sensitive while they shouldn't be (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

**Comment by WinterSilence** [comment]
@rhertogh PSR7 based RFCs Header field names are case-insensitive. You can use 'Foo: bar; foo: baz;'. headers sends "as is" (define by user) any changes are denied.

**Comment by rhertogh** [comment]
> PSR7 based RFCs Header field names are case-insensitive. You can use 'Foo: bar; foo: baz;'. headers sends "as is" (define by user) any changes are denied.

Could you please explain what PSR7 has to do with it? Earlier you wrote that Yii2 does not implement PSR7 (https://github.com/yiisoft/yii2/pull/18837#issuecomment-899702117)?
My point is that it currently does *not* behave case-insensitive. Given the example:
```php
$headerCollection = new HeaderCollection();
$location = 'my-test-location';
$headerCollection->fromArray([
    'Location' => [$location],
]);
$headerCollection->get('Location'); // returns `null` instead of 'my-test-location'
$headerCollection->get('location'); // returns `null` instead of 'my-test-location'
```
So a header set with `fromArray()` containing any capital letter in it is inaccessible via `get()`, is this the desired behavior?

**Comment by WinterSilence** [comment]
@rhertogh 
> Earlier you wrote that Yii2 does not implement PSR7

it's still true

> common interfaces for representing HTTP messages as described in RFC 7230 and RFC 7231, 

PSR7description better than my explanation (my English so bad)

**Review by bizley — APPROVED** [review]

**Comment by bizley** [comment]
This fix makes it consistent with the rest of methods here.

**Review by Arhell — APPROVED** [review]

**Comment by bizley** [comment]
Thank you.

**Comment by WinterSilence** [comment]
@bizley better update class to compatible with RFC
Also class must use self methods:
~~~php
public function fromArray(array $array)
{
    $this->removeAll();
    foreach ($array as $name => $value) {
        $this->set($name, $value);
    }
}
~~~

**Pull request merged**
