### PR TITLE
8549 fix file cache unserialize error: change file_get_contents for stream_get_contents

### PR DESCRIPTION
**Pull request by iworker**

### CODE REVIEW

**Comment by cebe** [comment]
seems there is something wrong with this branch, I could neither merge or cherry pick your commit. Could you fix that?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/251c316977ecb3584f623c935816144ca41dfbe2

**Comment by samdark** [comment]
Thanks for testing!

**Comment by iworker** [comment]
@samdark @cebe anytime :)
Thank you also for cleaning commit. I was kind of running when did it.

**Pull request closed without merging**
