### PR TITLE
12009 label for

### PR DESCRIPTION
**Pull request by shevchik87**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | yes |
| Tests pass? | no |
| Fixed issues | #12009 |

RadioList and CheckboxList - The for attribute of the label element must refer to a non-hidden form control.

This is my first commit not judge strictly

### CODE REVIEW

**Comment by samdark** [comment]
This pull request is backwards compatibility breaking. Can't be applied to 2.0.

**Comment by shevchik87** [comment]
what i have to do?

**Comment by samdark** [comment]
You can either change method signature to be compatible or wait till 2.1 when we can technically break method signatures.

**Comment by shevchik87** [comment]
I am sorry but 
I did not get anything

**Comment by samdark** [comment]
BC = backwards compatibility break i.e. inability to just update via Composer w/o modifying existing application code. If method signature (number or order or parameters in a method) changes, it breaks compatibility with previous versions because of inheritance i.e.:

```php
class X
{
    public function hello($name)
    {
        return 'Hello, ' . $name;
    }
}

// application defines Y:

class Y extends X
{
    public function hello($name)
    {
        return 'Welcome,' . $name;
    }
}
```

If we'll change `X::hello()` method to be

```php
public function hello($name, $word = 'Hello, ')
{
    return $word . $name;
}
```

then Y will fail with PHP error.

**Comment by shevchik87** [comment]
Thak you 
Now I all understand

**Comment by samdark** [comment]
Looks like wrong solution to me.

**Comment by samdark** [comment]
Merged with adjustments: https://github.com/yiisoft/yii2/commit/b8c07f6839ef5facf67ff1482e3189abf1145978

**Pull request closed without merging**
