### PR TITLE
11804 active record attributes typecasting

### PR DESCRIPTION
**Pull request by NaLLiFFuNT**
| New feature?  | yes
| Fixed issues  | https://github.com/yiisoft/yii2/issues/11804

### CODE REVIEW

**Comment by samdark** [comment]
Seems to be BC compatible.

**Comment by samdark** [comment]
@yiisoft/core-developers opinions?

**Comment by klimov-paul** [comment]
I am against the change.

Issue #11804 is a Redis specific trouble. Attributes typecasting for relational database works fine, in its scope this change is absolutely redundant.
If it should be fixed - it should be fixed at `yii2-redis` repository.

Besides solution based on static helper `TypecastingHelper` does not looks appropriate.

**Comment by NaLLiFFuNT** [comment]
You can face this problem with MySQL too. For instance, boolean values are strored as TINYINT. When you load model from MySQL, model's filed have value 1 instead true value, which you saved before. Anyway if you won't use this feature, AR's behavior won't change.

**Comment by cebe** [comment]
does the issue occur in any other place than tinyint in mysql? we should just get the handling of tinyint(1) to be fixed then.

**Comment by klimov-paul** [comment]
> does the issue occur in any other place than tinyint in mysql? we should just get the handling of tinyint(1) to be fixed then.

In case you create field using migration mechanism and use `boolean` type for it - there will be no problem whatever DB driver you are using.
`tinyint` DB type can strore more then 2 values even if it length set to 1. In particular possible values will be `1`, `0`, `-1`. Only `unsigned tinyint` allows 2 values only.
Although it can be fixed, there is no complain on such problem so far.

**Comment by NaLLiFFuNT** [comment]
No, the problem is only with TINYINT and boolean in MySQL. Do you suggest to apply this or similar solution for Redis-AR only? Or, may be other suggestion?
----
Other example.  You load data from the POST request. All data come as string. You load data into model and validate it. At this moment you can work with your model, but data fields have string values. You have to save model and load model from DB to make typecasting of their fields.

**Comment by klimov-paul** [comment]
> Other example. You load data from the POST request. All data come as string. You load data into model and validate it. At this moment you can work with your model, but data fields have string values. You have to save model and load model from DB to make typecasting of their fields.

This is already covered by filters validators such as `NumberValidator` and `BooleanValidator`.

**Comment by klimov-paul** [comment]
> Do you suggest to apply this or similar solution for Redis-AR only? Or, may be other suggestion?

Attributes typecasting for relational database is already covered by other means.
MongoDB and ElasticSearch do not have such problem at all: they operate via JSON and its ability of data-type storage.
So, yes I consider this is a Redis only problem.

**Comment by NaLLiFFuNT** [comment]
NumberValidator and BooleanValidator only verify that your string match with number pattern. This validators don't make typecasting of your value.

**Comment by klimov-paul** [comment]
> NumberValidator and BooleanValidator only verify that your match with number pattern. This validators don't make typecasting of your value.

Indeed, I admin I was wrong about that.

Speaking of validation. Imagine we have a model with attribute 'price' which is considered as `integer`.
Thus this attribute has a validator `NumberVallidator` with `integerOnly` set to `true`.
We have a web form (or REST API) for our model, which has an imput for 'price'.

With this fix in case user enters value `abc` it will be automatically and silently typecasted to `0` and model validation will pass, without notifying user about his mistake.
Thus I suppose this fix is unacceptable, since it could ruin the model validation workflow.

The typecasting could be done before saving record, after restoring record from DB or after successsful validation. But it should NOT be performed on attribute setter level.

**Comment by klimov-paul** [comment]
Alternative solution proposed at #12067

**Comment by NaLLiFFuNT** [comment]
> The typecasting could be done before saving record, after restoring record from DB or after successsful validation. But it should NOT be performed on attribute setter level.

I have thought about it. My realisation should be used in pair with validation rules .

For instance:

We have AR with fields intValue, boolValue, stringValue & etc. We add attibuteCasts() (typecast rules)  method & rules() (validation rules) method .
Following code is part of model:
```
public function rules() {
    return [
        ['stringValue', 'string'],
        ['boolValue', 'boolean'],
        ['boolValue', 'default', 'value' => true],
        ['intValue', 'integer'],
        [['intValue1','intValue2'], 'integer']
    ];
}

public function attributeCasts() {
    return [
        ['someString', 'string'],
        ['boolValue', 'boolean'],
        ['intValue', 'integer'],
        [['intValue1','intValue2'], 'integer']
    ];
}
```

How we can use it. By default typecasting will be in soft mode. If it's impossible to convert some value into scalar value of defined type, attribute will have raw value. There are some examples:

```
$model->intValue = '123'; // attribute will get 123 value
$model->load(['intValue'=>'200'], '') // attribute will get 200 value
$model->intValue = '124a3'; // attribute will get'124a3' 
//(because, it isn't an integer value and it cannot be coverted to int), 
//after that you will use validator before saving model and it will say: you have some error.
```


My realization solves following issues:
1) issue with Redis-AR ( it made me find some solution)
2) issue with typecasting tinyint to bool
3) you can use strict comparison of model fields before you save model & load model from DB

So, it doesn't matter how you set attributes values, you can load it from DB, from any POST\GET request, you can set set some attibute's value by one, if it's possible, value converts into scalar value of defined type.

I believe, this solution is very helpful.

Now i have described my suggestion completely. What do you think about it?

PS: Alternative solution proposed at #12067, also looks good.

**Comment by klimov-paul** [comment]
> My realisation should be used in pair with validation rules

I have added auto dection for the typecast attribute map from validation rules:
https://github.com/yiisoft/yii2/pull/12067/commits/608b886a4fc15027f3a41b7c326fad246f2ca566

> Now i have described my suggestion completely. What do you think about it?

I still think there should not be any typecast at setter level. 
In most cases typecasting is not needed at all. Lets take your 'tinyint' example. Any value, which passes `BooleanValidator` will be saved into 'tinyint' column correctly without extra typecasting to `boolean`.
Maintainance of strict types is requried only in relatively rare cases. Thus typecast should be triggered manually only if needed.

**Comment by NaLLiFFuNT** [comment]
In that case, i guess your solution is the best. So I guess we can decline & close this pull request.

**Pull request closed without merging**
