### PR TITLE
Added clearErrors parameter in validateMultiple()

### PR DESCRIPTION
**Pull request by hector-del-rio**

### CODE REVIEW

**Comment by hector-del-rio** [comment]
@cebe I think this is not a BC braking issue... right?

**Comment by samdark** [comment]
It is. Public method signature was changed.

**Comment by hector-del-rio** [comment]
But the default value of the new parameter $clearErrors is the same as in ```yii\base\model::validate()``` method. The behaviour is the same than previously if you do not add that parameter, so no BC is broken.

**Comment by samdark** [comment]
It is broken since if you have any class that extends from `Model` and overrides `validateMultiple` method, it will break.

**Comment by hector-del-rio** [comment]
I am sorry, but I still can't see how. Could you spare few minutes to write an example?

**Comment by samdark** [comment]
```php
class MyForm extends Model
{
    public function validateMultiple($models, $attributeNames = null)
    {
        // whatever
    }
}
```

would cause the following error:

```
Strict standards: Declaration of MyForm::validateMultiple() should be compatible with Model::validateMultiple($models, $attributeNames = null, $clearErrors = true)
```

**Comment by hector-del-rio** [comment]
Ok, I see. Thank you for the clarification @samdark. Learning something new everyday. :)

**Pull request closed without merging**
