### PR TITLE
Fix #12715: deadlock exception lost with nested transaction

### LINKED ISSUE #12715: Exception `SAVEPOINT LEVEL1 does not exist` instead of deadlock exception
### What steps will reproduce the problem?

``` php
\Yii::$app->db->transaction(function () {
    \Yii::$app->db->transaction(function () {
        // here comes queries to cause unexpected deadlock
    });
});
```
### What is the expected result?

See an exception about deadlock.
### What do you get instead?

Exception `SAVEPOINT LEVEL1 does not exist` from https://github.com/yiisoft/yii2/blob/2.0.9/framework/db/Connection.php#L690
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.8 |
| MySQL | 5.7 |
| OS | Ubuntu 16.04.2 |

### PR DESCRIPTION
**Pull request by Vovan-VE**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12715

Confirmed and fixed in PR #13346.

### CODE REVIEW

**Comment by samdark** [comment]
@Vovan-VE isn't #13346 include this pull request changes?

**Comment by Vovan-VE** [comment]
I thought #13346 will not be merged because of too complicated and possibly unstable test case. So, here is fix only.

**Comment by samdark** [comment]
I see. Thanks for explanation.

**Comment by Vovan-VE** [comment]
This PR is included by #13346, which has also test case. Closing this.

**Pull request closed without merging**
