### PR TITLE
do not use reserved php words as function in schemabuilder

### PR DESCRIPTION
**Pull request by cebe**
there is a reason for them to be reserved, we should not add such workarounds to still use them.
- [x] adjust tests

### CODE REVIEW

**Comment by samdark** [comment]
I disagree. It's very convenient.

**Comment by cebe** [comment]
what is convenient? using reserved words as function names should be avoided, even if it is possible using some hack with __call().

**Comment by nineinchnick** [comment]
It matches the SQL keyword, making all methods naming more consistent. But I agree with CeBe, you could memorise this as an exception quickly and IDE autocompletion would help too.

**Comment by samdark** [comment]
Well, it's not a big issue for me...

**Comment by cebe** [comment]
I agree that `default` is the best name if we were free to use it as a normal method name. As it is a reserved word in php I still would not use it and choose the next best name which is `defaultValue` imo.

**Comment by samdark** [comment]
OK. Let's merge it.

**Comment by cebe** [comment]
k, will do it in a separate commit by also adjusting the tests.

**Pull request closed without merging**
