### PR TITLE
Fix #9718: Fix user staying authorized despite authKey change

### LINKED ISSUE #9718: User stays authorized despite auth key is changed
While renewAuthStatus() method of yii\web\user is getting user id from session variable, it's not checking auth key. If auth key changes, the user still will be authorized while his id is stored in session.

Steps to reproduce this issue with Advanced application template:
1. Add `$user->generateAuthKey();` in resetPassword method of frontend\models\ResetPasswordForm directly after `$user->setPassword($this->password);`
2. Login as any user in browser
3. Open new inconito tab
4. Login as same user in incognito tab
5. Change password in incognito tab
6. Check that you are still authorized in all tabs

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌ (may break BC if IdentityInterface wasn't implemented properly)
| Tests pass?   | ✔️/❌
| Fixed issues  | #9718

### CODE REVIEW

**Review by bizley — COMMENTED** [review]
LGTM. Tests are required though

**Comment by samdark** [comment]
@bizley added tests.

**Comment by SamMousa** [comment]
@samdark I just got bit by this.. :(
The fix you applied now makes implementing `getAuthKey()` mandatory.
Before, when not using identity cookies it was optional.

If I don't want to use identity cookies I shouldn't be forced to implement this. I can't just do a dummy implementation because that's a potential security risk (ie if I someone enables identity cookies in the future).

My current implementation just looks like this:
```php
    public function getAuthKey()
    {
        throw new NotSupportedException();
    }
```

**Comment by bizley** [comment]
Isn't your way the recommended one when this is not implemented?

**Comment by SamMousa** [comment]
But it is broken now, because now normal sessions without identity cookies will also call `getAuthKey()` to store the auth key in the session...

**Comment by bizley** [comment]
Ok, I've read your previous comment again and this part

> If I don't want to use identity cookies I shouldn't be forced to implement this. I can't just do a dummy implementation because that's a potential security risk (ie if I someone enables identity cookies in the future).

is not a reason to not implement it with `return null;` for example. Changing this part of application should automatically be followed by changing other related parts.

And this feature is not used only with connection to cookies. It allows as well to log out users by changing their authKey.

**Comment by SamMousa** [comment]
It didn't before this pr. Previously changing authkey invalidated only the identity cookies. It didn't end current sessions. Which is actually logical because now if you rotate a users auth key you will log them out of current session as well

**Comment by bizley** [comment]
If I understand correctly you have a custom session storage that is broken after this change, am I right?

**Comment by SamMousa** [comment]
No, I have standard sessions, I just do not use auth keys.
I don't have them in my database I don't use them in cookies.

**Comment by SamMousa** [comment]
If I look at validation code in `renewAuthStatus`:
```php
if ($identity !== null) {
            $authKey = $session->get($this->authKeyParam);
            if ($authKey !== null && !$identity->validateAuthKey($authKey)) {
                $identity = null;
                $ip = Yii::$app->getRequest()->getUserIP();
                Yii::warning("Invalid session auth key attempted for user '$id' from $ip: $authKey", __METHOD__);
            }
        }
```
It seems authkey is optional, but that means that `getAuthKey()` has return type `null|string`, which is not documented. In that case I can return `null`.

I guess that'll work, since validation is always done using my code ie `validateAuthKey()` there is no risk that an identity cookie with `null` authKey ever breaks.

Either this change should be reverted (since it is a BC break) or at the very least the return type of `authKey()` should be widened to include `null`...

**Comment by bizley** [comment]
Ok... so it's a case when having `validateAuthKey()` and/or `getAuthKey()` throwing something makes everything broke...

**Comment by SamMousa** [comment]
Yes exactly, and specifically `getAuthKey()`. For `validateAuthKey()` I can just implement it as `return false`. But the `getAuthKey()` docs:
```php
     * The key should be unique for each individual user, and should be persistent
     * so that it can be used to check the validity of the user identity.
     *
     * The space of such keys should be big enough to defeat potential identity attacks.
```
Make it impossible for me to safely implement it with `return null;`. Since that explicitly violates the constraints placed on the implementation.

**Comment by SamMousa** [comment]
Someone on slack just mentioned the upgrade notes, and those actually do say that `return null` is acceptable... :)

**Pull request merged**
