### PR TITLE
Fix for #9317, #9353

### PR DESCRIPTION
**Pull request by creocoder**
Removed two Yii 2 disservices which may lead to fatal errors in several components.

### CODE REVIEW

**Comment by creocoder** [comment]
Rethink my mind. It may be interested to know that components not defined.

**Comment by dynasource** [comment]
its quite confusing that some application's components do return an error and some dont. I would choose for consistency and let the enduser decide if an error is to be thrown

**Comment by creocoder** [comment]
@dynasource This PR is closed 8 minutes before you write comment ;-) Correct fix is https://github.com/yiisoft/yii2/pull/9369

**Comment by dynasource** [comment]
I know. I would like to know why you choose to skip this commit and prefer inconsistency.

**Comment by creocoder** [comment]
@dynasource #9369 is much more consistent and agile.

**Pull request closed without merging**
