### PR TITLE
Fix undefined array key errors in ActiveRelationTrait

### PR DESCRIPTION
**Pull request by stevekr**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #19148

### CODE REVIEW

**Comment by stevekr** [comment]
I just added checks if array key is declared and this should be covered with other tests.

**Comment by samdark** [comment]
It definitely isn't covered since tests passed before this change.

**Review by schmunk42 — APPROVED** [review]
Looks OK to me. CC: @handcode @eluhr

**Comment by samdark** [comment]
@stevekr please add a line for CHANGELOG.

**Comment by stevekr** [comment]
Done

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks/

**Pull request merged**
