### PR TITLE
Update documentation for setCookieParams

### PR DESCRIPTION
**Pull request by clemens-it**
The link for more information about "sameSite" leads to a 404 Not Found.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Review by rhertogh — APPROVED** [review]

**Comment by rhertogh** [comment]
@clemens-it Why was the PR closed?

**Comment by clemens-it** [comment]
I deleted the repository from which originated the PR prematurely. My mistake.
Please advice, should I create a new PR from scratch?

**Comment by rhertogh** [comment]
Yes please, since I don't think this one can be reopened from a new repo.

**Comment by clemens-it** [comment]
Ok, i just created a new PR -> #19921

**Pull request closed without merging**
