### PR TITLE
Fix PhpDoc for yii\db\QueryInterface

### PR DESCRIPTION
**Pull request by WinterSilence**
https://github.com/yiisoft/yii2/blob/8cc9aeb2f0b2ffe02fb54a817064e9da75512706/framework/db/Query.php#L368
https://github.com/yiisoft/yii2/blob/8cc9aeb2f0b2ffe02fb54a817064e9da75512706/framework/db/Query.php#L459

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by bizley** [comment]
Yes, this checks. Can we also get all other methods relying on `queryScalar()` fixed with `null` in return? In `QueryInterface` and `Query` itself.

**Comment by WinterSilence** [comment]
@bizley we can auto fix all classes with [Psalter](https://psalm.dev/docs/manipulating_code/fixing/)

**Comment by bizley** [comment]
Sure, if possible, yes.

**Comment by WinterSilence** [comment]
@bizley yes, it's easy - see link to examples

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
