### PR TITLE
HTTP Methods can prefix a pattern in yii\web\GroupUrlRule like in yii\web\UrlManager

### PR DESCRIPTION
**Pull request by schojniak**
#7996

### CODE REVIEW

**Comment by schojniak** [comment]
I need this to group REST API rules.

Instead of:
```
new GroupUrlRule([
    'prefix' => 'api2',
    'rules' => [
	['route' => 'server/ping', 'pattern' => 'ping', 'verb' => 'GET'],
//...
    ],
]),
```
I prefer simpler format
```		
new GroupUrlRule([
    'prefix' => 'api2',
    'rules' => [
        'GET ping' => 'server/ping',
//...
    ],
]),
```

**Comment by schojniak** [comment]
In `yii\web\UrlManager` rules without `GET` method are considered as `UrlRule::PARSING_ONLY`, I could also add this behavior to `GroupUrlRule` if you wish.

**Comment by cebe** [comment]
@schojniak are you willing to work on this further?

**Comment by samdark** [comment]
Replaced by https://github.com/yiisoft/yii2/pull/15166

**Pull request closed without merging**
