### PR TITLE
Fix #11252 use strict comparison on hasAttribute()

### LINKED ISSUE #11252: ActiveRecord::hasAttribute(0) return true
### What steps will reproduce the problem?
```php
class Project extends \yii\db\ActiveRecord 
{
    public static function tableName()
    {
        return 'projects';
    }
}

$Project = Project::findOne(1);
var_dump($Project->hasAttribute(0));
```
### What is the expected result?
it should be false
### What do you get instead?
it returned true

### Additional info
The reason because `in_array($name, $this->attributes())` in `hasAttribute()` has returned true
[http://stackoverflow.com/questions/13846769/php-in-array-0-value](http://stackoverflow.com/questions/13846769/php-in-array-0-value)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0.2
| Operating system | MacOSX 10.11 El Capitan

### PR DESCRIPTION
**Pull request by Faryshta**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #11252 |

### CODE REVIEW

**Comment by SilverFire** [comment]
It is not the only place, where `is_array` is used for similar purpose and may need strict flag. I think it will be good to fix this in other parts of code.

@yiisoft/core-developers should we?

**Comment by samdark** [comment]
Yes.

**Comment by SilverFire** [comment]
@Faryshta would you like to expand? :)

**Comment by samdark** [comment]
Be careful with string/int/boolean though.

**Comment by Faryshta** [comment]
@SilverFire @samdark its quite the opposite, the strict flag is used in every other part of the models code but here.

https://github.com/yiisoft/yii2/blob/da82ff3fb1625597706d9da3c76ca5a0a1ee7ad5/framework/base/Model.php here `in_array` is used 5 times, 4 use the strict flag and the last one uses an string conversion by concatenation.

**Comment by cebe** [comment]
quite unlikely in general but could there be column names like '1', '2', '3', '4' ... ?

**Comment by cebe** [comment]
okay, given http://stackoverflow.com/questions/13846769/php-in-array-0-value this should totally be fixed...

**Comment by cebe** [comment]
Merged, thank you!

**Pull request closed without merging**
