### PR TITLE
17653 unserialize rbac rule

### PR DESCRIPTION
**Pull request by OlegTDev**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️/❌
| Tests pass?   | ✔️/❌
| Fixed issues  | #17635

### CODE REVIEW

**Comment by samdark** [comment]
Seems to cause errors: https://travis-ci.com/yiisoft/yii2/jobs/266838304#L455

**Comment by toatall** [comment]
I found another way. I added an attribute in the config file `console/config/main-local.php`:

`'db' => ['attributes' => [ \PDO::SQLSRV_ATTR_ENCODING => \PDO::SQLSRV_ENCODING_SYSTEM ]]`

**Comment by samdark** [comment]
Hmm... which solution do you think is the best one?

**Comment by toatall** [comment]
I would leave the commit changing varbinary to varbinary(max) -> 6c9f962c1b537c8de886f6463d7a606b37a7e9e0
And for the correct save a binary data use the db attribute `\PDO::SQLSRV_ATTR_ENCODING`

**Comment by samdark** [comment]
So we need both?

**Comment by toatall** [comment]
Yes

**Comment by samdark** [comment]
I think then https://github.com/yiisoft/yii2/pull/17735#issuecomment-565944429 should be added to docs around https://github.com/yiisoft/yii2/blob/master/docs/guide/db-dao.md#creating-db-connections- and to MSSQL Connection phpdoc. Do you have time to handle it?

**Comment by toatall** [comment]
@samdark Ok, but a little later

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
