### PR TITLE
MSSQL: fix tests

### PR DESCRIPTION
**Pull request by alexkart**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17413, #17418

### CODE REVIEW

**Comment by alexkart** [comment]
Trying to fix `\yiiunit\framework\db\ActiveRecordTest::testDefaultValues`.
But the question is should we fix the test to match current implementation which is currently incorrect or fix implementation? If we fix implementation it may break the existing code as someone could rely on it using incorrect default values.
The issue is that default values are stored in such format in MSSQL `('value')`.
af3a717d124f4a046795bc0d11dfd2a3

Has the format changed since the test was written or it was incorrect from the beginning?

**Comment by samdark** [comment]
The test may have been incorrect .

**Comment by alexkart** [comment]
OK, I'll move this change to a separate pull request then.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
