### PR TITLE
Coding Standard fixes

### PR DESCRIPTION
**Pull request by TomasVotruba**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

Few CS fixes

### CODE REVIEW

**Comment by samdark** [comment]
Requirements script is meant to work with PHP 5.3 and inform that 5.4 is required for the framework. Thus, short arrays syntax should not be applied there.

**Comment by TomasVotruba** [comment]
I see. I thought there was bump to min PHP 7.1, that's why I sent this. Is there some other branch this would be useful in?

Isn't this handled already by PHP requirement in composer.json?

**Comment by samdark** [comment]
Yii could be obtained through zip archive so composer constraints won't be triggered.

Part of your pull request (removed use statements) could be merged so if you'll remove requirements part, I'll make it part of master.

**Comment by TomasVotruba** [comment]
I see. I will fix that later when not on mobile.

Thanks for explaining to me.

**Comment by TomasVotruba** [comment]
Wrong button, ups

**Comment by TomasVotruba** [comment]
Done!

**Comment by TomasVotruba** [comment]
Btw, do you run Coding Standard checks on Travis?

I see you have "no_unused_imports" added, but this still somehow passed.

**Comment by samdark** [comment]
Thanks.

It was removed from travis temporarily till we stabilize code and rules.

**Comment by TomasVotruba** [comment]
You're welcome.

> It was removed from travis temporarily till we stabilize code and rules.

What happend if you took it the other way? Adding only fixers that pass (like this one).

**Comment by samdark** [comment]
We'll do soon. There are other things going on so it was too distractive at the moment.

**Comment by TomasVotruba** [comment]
Sure. Let me know if you need any help with cs. I love them

**Pull request merged**
