### PR TITLE
Update redis connection

### PR DESCRIPTION
**Pull request by pyurin**
Add pconnect option to redis connection. It`s a rather simple but, I suppose, a good improvement when redis is set up on a different machine and especially when you run an application in clouds.

### CODE REVIEW

**Comment by cebe** [comment]
Can you give a link to some documentation that explains what this does?

**Comment by pyurin** [comment]
Hi.

There must be made a correction - on line 267:
from:
if ($this->pconnect){

to:
if ($this->pconnect && $this->database == 0){


The idea of this commit is to use persistent connection to redis. This is useful only when redis is on a different machine.
Well, what I did - I`ve added flag STREAM_CLIENT_PERSISTENT (+default STREAM_CLIENT_CONNECT). 
http://php.net/manual/ru/function.stream-socket-client.php
I`ve tested, it takes less time to connect.

But I suppose that pconnects must do harm if to use 'subscribe/unsubscribe' mechanisms.

**Comment by pyurin** [comment]
To be true, I`m not sure that this improvement is safe in case of extended redis usage.

**Comment by pyurin** [comment]
I`ve modified this pull request to: https://github.com/yiisoft/yii2/pull/7076

**Pull request closed without merging**
