### PR TITLE
Introduced Command interface

### PR DESCRIPTION
**Pull request by samdark**
https://sourcemaking.com/design_patterns/command

My intent:
- Prepare for queues.
- Would allow to create standard command executor components.

### CODE REVIEW

**Comment by nineinchnick** [comment]
Looks a bit like an auth rule. They're also serialized and stored in the db.

**Comment by klimov-paul** [comment]
I am unsure I understand the intent.
Can you provide some code snippet for usage example?

**Comment by samdark** [comment]
```php
class FetchFacebookInfo implements Command
{
    private $userID;

   public function __construct($userID)
   {
        $this->userID = $userID;
   }

    public function execute()
    {
        $user = User::findOne($this->userID);
        // ... fetch data from facebook ... (it takes time)
        $user->email = $facebookData['email'];
        $user->username = $facebookData['username'];
        $user->save();
    }
}
```

Web controller:

```php
class SiteController extends Controller
{
    public function actionSignup()
    {
        $user = new User();
        // usual signup stuff
        if ($user->save()) {
            // fetching facebook data isn't critical, could do it later
            $command = new FetchFacebookInfo($user->id);
            Yii::$app->queue->push($command);
        }
    }
}
```

**Comment by klimov-paul** [comment]
Such abstraction is untypical for Yii. It is too... abstract.
Such addition may be useful in queue implementation, but it does not seem to be general unless there is any check for this interface inside the framework.

**Comment by cherifGsoul** [comment]
Very interesting, in some complicated business logic this can be very useful, for example we can use it for spliting ActiveRecord as Command and Query, the logic in commands can be used with any UI or delivery system (Web or console)

```php
class AddTodoCommand implements Command
{
   private $toDoListId;
   private $priority;
   private $description;

  public function __construct($todoListId,$priority,$description){
   $this->todoListId=$todoListId;
   $this->description = $description;
   $this->priority = $priority;
  }

 public function execute() {
  $list = Yii::$app->listFinder->findById($this->todoListId);
  $list->addTodo($priority,$description);
 }
```

**Comment by samdark** [comment]
It's quite similar to `BootstrapInterface` and `Configurable` in its spirit. There will be `instanceof` checks in at least queue component.

**Comment by samdark** [comment]
@nineinchnick serialization itself isn't part of this interface.

**Comment by samdark** [comment]
@klimov-paul probably you're right and the interface itself makes sense only for domain part of the app which isn't covered by framework in any way.

**Comment by cherifGsoul** [comment]
@samdark for the same I like having command bus component instead

**Comment by samdark** [comment]
Bus component isn't really useful. For anything that's currently in Yii and isn't queue replacement in any way. I guess I'll close this pull request.

**Pull request closed without merging**
