### PR TITLE
Fix messy .gitlab-ci.yml file

### PR DESCRIPTION
**Pull request by mikk150**
Gitlab CI definition file is kind of messy, I cleaned it up a bit with not using docker-compose

screenshot from 2018-01-10 20-30-50

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    |no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by mikk150** [comment]
I may even be able to add mssql tests #14971

I tried, but have no idea how to make default DB - always got
```
Something wrong when preparing database: SQLSTATE[42000]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot open database "yii2test" requested by the login. The login failed.
```

**Comment by schmunk42** [comment]
> Gitlab CI definition file is kind of messy

"messy" in which way, could you elaborate this a bit more?
While I like certain parts of this PR, ie. using YML templates, I think it very different from the current implementation, which has some very useful features...

> I cleaned it up a bit with not using docker-compose

Using `docker-compose` was a main idea behind developing this test setup, since you can reproduce it easy locally. 
Moreover you can pick any DB version just by using a variable in a trigger, which is really helpful for spotting incompatibilities with ie. newer DB versions.

> I may even be able to add mssql tests #14971

I doubt those will run on a standard (free) runner, since you need at least 3,5 GB of RAM for the MSSQL image - at least the last time I tried, the free runners were not providing that amount of memory.

> I tried, but have no idea how to make default DB - always got

I had a hard time figuring that out, since you need a separate image with `sqlcmd` to create the db, etc... https://github.com/yiisoft/yii2/blob/master/.gitlab-ci.yml#L98 

Overall I do not really see an improvement in this PR.

**Comment by mikk150** [comment]
> Using docker-compose was a main idea behind developing this test setup, since you can reproduce it easily locally.

$ gitlab-ci-multi-runner exec docker test:mssql:7.0

> Moreover you can pick any DB version just by using a variable in a trigger, which is really helpful for spotting incompatibilities with ie. newer DB versions.

When you have issue with particular SQL version, shouldn't you add those specific tests with that specific SQL version to testing suite

> I doubt those will run on a standard (free) runner, since you need at least 3,5 GB of RAM for the MSSQL image - at least the last time I tried, the free runners were not providing that amount of memory.

Did run... Tho had [errors](https://gitlab.com/mikk150/yii2/-/jobs/47485049) (Not running out of memory tho)

**Comment by schmunk42** [comment]
> $ gitlab-ci-multi-runner exec docker test:mssql:7.0

That actually sounds like a nice feature, but what do you need to execute tests locally? Did you install a runner binary locally?

> When you have issue with particular SQL version, shouldn't you add those specific tests with that specific SQL version to testing suite

There can be so many combinations of versions considering PHP, DB, Cache, Yii Framework.

Travis is really good for testing the above combinations (matrix) you described, GitLab is pretty strong when using triggers with custom variables and also for running partial sets of tests, just by pushing to a branch. Also parallelizing tests are done very well by GitLab.

I tried to use the strengths of GitLab with the current test-setup, not just doing the same like on Travis.

> Did run... Tho had errors (Not running out of memory tho)

The `services` part is also nice, since it looks pretty reliable for running on GitLab. On the other hand, how do you bring up a testing stack locally, keep it running for running single tests in when fixing issues etc.?

**Comment by samdark** [comment]
Doesn't seem to be valid/active anymore. Closing.

**Pull request closed without merging**
