### PR TITLE
Fix BaseActiveRecord __isset() exception suppress

### PR DESCRIPTION
**Pull request by paulzi**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | ?
| Fixed issues  | #16653

### CODE REVIEW

**Comment by samdark** [comment]
How about a test that verifies behavior?

**Comment by paulzi** [comment]
@samdark, I added test.

**Comment by paulzi** [comment]
Sorry, now build failed in php <7.0. I don't now how to make unit test for php 5 without parse error for ?? operator.

**Comment by rob006** [comment]
Is there any reason why you're not using `isset()` for testing this?

**Comment by paulzi** [comment]
@rob006 maybe you're right. fixed.

**Comment by SamMousa** [comment]
@samdark this is really a big backwards compatibility break that should not be changed.

The magic property functionality explicitly suppresses errors and have has so for a long time, changing this in a minor update seems like a bad idea.

**Comment by koteq** [comment]
Maybe desired behavior may be achieved by checking for certain exceptions instead of total silencing.
```patch
Index: framework/base/Component.php
<+>UTF-8
===================================================================
--- framework/base/Component.php	(date 1535713105000)
+++ framework/base/Component.php	(date 1536066463000)
@@ -147,10 +147,6 @@
             }
         }
 
-        if (method_exists($this, 'set' . $name)) {
-            throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
-        }
-
         throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
     }
 
Index: framework/db/BaseActiveRecord.php
<+>UTF-8
===================================================================
--- framework/db/BaseActiveRecord.php	(date 1535713105000)
+++ framework/db/BaseActiveRecord.php	(date 1536066463000)
@@ -16,6 +16,7 @@
 use yii\base\ModelEvent;
 use yii\base\NotSupportedException;
 use yii\base\UnknownMethodException;
+use yii\base\UnknownPropertyException;
 use yii\helpers\ArrayHelper;
 
 /**
@@ -335,9 +336,7 @@
     {
         try {
             return $this->__get($name) !== null;
-        } catch (\Throwable $t) {
-            return false;
-        } catch (\Exception $e) {
+        } catch (UnknownPropertyException $t) {
             return false;
         }
     }

```

**Comment by rob006** [comment]
W could just log this exception, so code will still work the same, but there will be some trace in logs.

**Comment by paulzi** [comment]
I agree that changing behavior is dangerous, and can reveal some problems in existing projects. But complete suppression without logging is also bad.

**Comment by paulzi** [comment]
Created PR for branch 3.0: https://github.com/yiisoft/yii2/pull/16683

**Comment by samdark** [comment]
I should really delete that branch soon... That's not what will become Yii 3.0...

**Comment by samdark** [comment]
Won't be accepted into 2.0.

**Pull request closed without merging**
