### PR TITLE
Update BaseHtml.php

### PR DESCRIPTION
**Pull request by wcoc**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by wcoc** [comment]
Usage example:

View
```
<table class="table table-bordered table-condensed">
        <thead>
               <tr>
                     <th>ID Item</th>
                     <th>Description</th>
        </thead>

        <tbody>
         <?php foreach($items as $item): ?>
            <tr>
                <td><?= Html::activeCheckbox($modelForm, 'array_id_item', [
                                        'label' => false, 
                                        'value' => $item->id_item,
                       ]) ?></td>
                <td>Description....</td>
           </tr>
         <?php endforeach; ?>
        </tbody>
</table>
```

Modelform
```
class ItemModelForm extends Model {
        /* this attribute is used to save all ids selecteds in view array checkbox. */
        public $array_id_item;

        function rules(){
               return [['array_id_item'], 'safe'];
        }
}
```

**Comment by dmirogin** [comment]
try to use https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1665

**Comment by wcoc** [comment]
@dmirogin this not working for me, because i need show several informations in columns for each line.

Example: [https://imgur.com/KoTxSxs](https://imgur.com/KoTxSxs)

**Comment by rob006** [comment]
This will result multiple checkboxes with the same name - it will not work correctly, since on form submit last checkbox will replace all previous checkboxes.

**Comment by wcoc** [comment]
@rob006 Actually, I just let this happen.

I solved my problem by passing in the option of activeCheckbox `'uncheck' => false`  so that it does not send unselected values, and attribute `'array_id_item['.$item->id_item.']'`.

Thanks.

**Pull request closed without merging**
