### PR TITLE
Can create fixtures throw anonymous function and Fixture

### PR DESCRIPTION
**Pull request by bscheshirwork**
#13974

Can create from the anonymous function (key `token`) and from the anonymous class (php7, key `user`)

Anonymous class must use alias `@codecept_data_dir` in `dataFile`.

`depends` use name of fixture `user`

Can create multiply fixture by same class.

[source createFixtures](https://github.com/bscheshirwork/yii2/blob/27b294606455bf73ed808ec11ae8e9096525f6df/framework/test/FixtureTrait.php#L164-L253)

```php
//inside Cest
    public function _fixtures(){
        Yii::setAlias('codecept_data_dir', codecept_data_dir());
        return [
            'user' => new class extends \yii\test\ActiveFixture {
                public $modelClass = 'dektrium\user\models\User';
                public $dataFile = '@codecept_data_dir/user.php';
            },
            'token' => function(){
                return Yii::createObject([
                    'class' => \yii\test\ActiveFixture::className(),
                    'modelClass' => 'dektrium\user\models\Token',
                    'depends' => ['user'],
                    'dataFile' => codecept_data_dir() . 'token.php',
                ]);
            },
        ];
    }

```
This definition can be used instead of this classes with 1 line:
```php
    public function _fixtures(){
        return [
            'user' => [
                'class' => UserFixture::className(),
                'dataFile' => codecept_data_dir() . 'user.php'
            ],
            'token' => [
                'class' => TokenFixture::className(),
                'dataFile' => codecept_data_dir() . 'token.php'
            ],
        ];
    }
```
```php
<?php

namespace frontend\fixtures;

use yii\test\ActiveFixture;

class ProfileFixture extends ActiveFixture
{
    public $modelClass = 'dektrium\user\models\Profile';

    public $depends = [
        'common\fixtures\UserFixture'
    ];
}
```
```php
<?php

namespace frontend\fixtures;

use yii\test\ActiveFixture;

class TokenFixture extends ActiveFixture
{
    public $modelClass = 'dektrium\user\models\Token';

    public $depends = [
        'common\fixtures\UserFixture'
    ];
}
```

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no (can create multiple fixture with same class. Depends `class` called first of it)
| Tests pass?   | yes/no
| Fixed issues  | #13974

### CODE REVIEW

**Comment by leandrogehlen** [comment]
The `dataDirectory` property  does not solve this issue?

related #14546

**Comment by bscheshirwork** [comment]
The dataDirectory property can avoid fixture class file creation?

**Comment by leandrogehlen** [comment]
@bscheshirwork, sorry i don't pay attention about the issue

**Comment by samdark** [comment]
Won't make it into 2.0.

**Pull request closed without merging**
