### PR TITLE
Implemented __sleep in yii\db\Connection to support serializing the c…

### PR DESCRIPTION
**Pull request by SamMousa**
…onnection object without exceptions.

### CODE REVIEW

**Comment by samdark** [comment]
Can it be unserialized like that?

**Comment by SamMousa** [comment]
Yes, I think so ^^.

**Comment by cebe** [comment]
could you add the unserialization to the test?

**Comment by SamMousa** [comment]
Yes, will do tomorrow.

**Comment by SamMousa** [comment]
Done.

**Comment by samdark** [comment]
Great. A line for the changelog file is needed. Then we'll merge it.

**Comment by SamMousa** [comment]
I think this is mergable, it only fails on PHP7 but logs suggest that is PHP compilation error, not a source code error.

**Comment by cebe** [comment]
Merged, thank you!

**Pull request closed without merging**
