### PR TITLE
Added `scrollToErrorOffset` option for `ActiveForm`

### PR DESCRIPTION
**Pull request by mg-code**
Now `scrollToError` option does not work correctly with sticky headers.
`scrollToErrorOffset` option adds ability to specify offset in pixels when scrolling to error.

| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |

### CODE REVIEW

**Review by samdark — CHANGES_REQUESTED** [review]
- JavaScript code formatting needs to be fixed.

**Comment by mg-code** [comment]
Alexander, what is wrong with JavaScript code formatting?

**Comment by samdark** [comment]
`if(top < 0) {` missing spaces before `(`

**Comment by mg-code** [comment]
@samdark fixed.

**Review by samdark — APPROVED** [review]

**Comment by mg-code** [comment]
@samdark should I change @since tag and remove changelog entry from version 2.0.10?

**Comment by samdark** [comment]
Yes, it will be 2.0.11.

**Comment by mg-code** [comment]
@since tag changed.
changelog entry removed.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
