### PR TITLE
no longer render label by default in `ActiveField::hiddenInput()`

### PR DESCRIPTION
**Pull request by lennartvdd**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | yes |
| Tests pass? | yes |
| Fixed issues | #2990 |

### CODE REVIEW

**Comment by agungsijawir** [comment]
hi @samdark 

this PR set to 2.1.x milestone, is due to changes in behaviour the way hiddenInput() on 2.0?

**Comment by cebe** [comment]
@agungsijawir yes

**Comment by SilverFire** [comment]
Merged c64cfa9373867ec72638de4e3e6b97ef4036b481

**Comment by SilverFire** [comment]
Thank you

**Pull request closed without merging**
