### PR TITLE
entangled parameters Lines and Columns on Windows

### PR DESCRIPTION
**Pull request by Spell6inder**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | may be |
| Tests pass? | no |
| Fixed issues | yes |

entangled parameters Lines and Columns on Windows
'Lines' on line 3
'Columns' on line 4 

http://www.computerhope.com/modehlp.htm#examples

```
Status for device CON:
----------------------
Lines: 300
Columns: 80
Keyboard rate: 31
Keyboard delay: 1
Code page: 437
```

### CODE REVIEW

**Comment by cebe** [comment]
it would be better to search for the words instead of trusting the output to be always in order.

**Comment by samdark** [comment]
I'd not rely on it either. It's as fragile as order.

**Comment by samdark** [comment]
Hmm... probably you're right. Parsing names may be better...

**Comment by samdark** [comment]
Fixed. Thanks!

**Comment by kids-return** [comment]
`C:\Users\root>mode con

设备状态 CON:
---------
    行:　       9001
    列:　　     120
    键盘速度:   31
    键盘延迟:　 1
    代码页:     936


C:\Users\root>mode con cp select=437

Status for device CON:
----------------------
    Lines:          9001
    Columns:        120
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      437


C:\Users\root>`

**Comment by samdark** [comment]
@kids-return seems to be OK, isn't it?

**Pull request closed without merging**
