### PR TITLE
Add upsert support

### PR DESCRIPTION
**Pull request by SilverFire**
Follow-up to #15276

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | not yet
| Fixed issues  | #13879, #15276, #15357, #15415

Another little PR from me. The PR implements an upsert support for all DBMSes. `ConstraintFinderInterface` was "backported" from a coming migration table column/constraint builder.

TODO:

- [x] Implement the feature
- [x] Add QB tests
- [x] Add basic `Command` tests
- [x] Finish `Command` tests for PostgreSQL >= 9.5 & CUBRID
- [ ] Add concurrency `Command` tests
- [x] Add multi command `Command::execute()` support for SQLite (#15357)
- [x] Add transaction support to `Command` to reliably test SQLite, Oracle and pre-9.5 PostgreSQL (#15415)
- [x] Add retry support to `Command` to reliably test Oracle and pre-9.5 PostgreSQL (#15415)

These "add support" entries require their own PRs I think. Mostly they are not too hard/too long to be implemented. But I need a feedback to start working on them.

### CODE REVIEW

**Comment by SilverFire** [comment]
Merged with master, tests are green now. I see @sergeymakinen wanted to add concurrency Command tests, but I think it's not blocking this PR from merge. @samdark

**Comment by samdark** [comment]
Great!

**Comment by samdark** [comment]
Huge thanks to @sergeymakinen for working on it and thanks @SilverFire for resolving conflicts.

**Comment by sergeymakinen** [comment]
Glad to see it coming. Thanks!

I'm sorry I could not finish it but I plan to get back to work on Yii on March.

**Comment by sergeymakinen** [comment]
I definitely have something to read:

screen shot 2018-02-09 at 01 38 04

Sorry for offtop. :)

**Comment by samdark** [comment]
You did the hardest part of it. Ha-ha, 1744 is quite a number :)

**Pull request merged**
