### PR TITLE
Applying A Callback To Each Model Collection as per the issue #13644

### PR DESCRIPTION
**Pull request by ElijahGM**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13644

### CODE REVIEW

**Comment by SilverFire** [comment]
What is the use case for this ehancement?

**Comment by ElijahGM** [comment]
What is the use case for this enhancement? 
It provide the array_map() functionality on query of models, you can iterate on models modifying or filtering return objects 

instead of 

```
$models = Model::find()->all();
array_map($models,function($model,$index){
  //code
)))
```

It provide a neater way of doing the same 
```
Model::find()->iterate(function($model)
{
    return model->attribute=modify(model->attribute)
})->all();
```
Maybe is I should rename the function to map instead of iterate

**Comment by samdark** [comment]
It's not map but iterate since it leaves objects as is. Also `return` looks odd in your example. Overall it's an equivalent of simple foreach:

```php
$models = Model::find()->->all();
foreach ($models as $model) {
    $model->attribute = modify($model->attribute);
}
```

**Comment by samdark** [comment]
Foreach actually looks better...

**Comment by ElijahGM** [comment]
@samdark I have corrected the return error, am still seeing the iterate being neat way to do it, without a lot of codes especially for those guys coming from Laravel where this is an inbuilt function

**Comment by samdark** [comment]
Well, the `foreach` in this case works much faster and is actually shorter, isn't it?

**Comment by ElijahGM** [comment]
@samdark i don't think so, but maybe am wrong 
`Model::find()->iterate(function)->all();` is in a single line where models returned are only those filtered/modified by the closure function,

**Comment by ElijahGM** [comment]
@samdark if foreach in this case works much faster, i can use it in the design to do the iteration on the function applyClosure() function

**Comment by samdark** [comment]
Overall, conceptually the pull request is not correct. If something like that is to be done, proper collections and populating models into collections should be introduced. Closing pull request, leaving issue open for discussion.

**Pull request closed without merging**
