### PR TITLE
Saving model removed from yii\db\BaseActiveRecord::bindModels().

### PR DESCRIPTION
**Pull request by aleskiontherun**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #12147, #14398, #4834

### CODE REVIEW

**Comment by dizeee** [comment]
@samdark Why was it closed?

**Comment by samdark** [comment]
Automatically because 2.1 branch was deleted. Rebased and reopened.

**Review by dmirogin — APPROVED** [review]

**Review by samdark — CHANGES_REQUESTED** [review]
Guide should be adjusted. db-active-record section.

**Comment by samdark** [comment]
Won't be merged into 2.0. Issue with a link to PR was moved to yiisoft/ar.

**Pull request closed without merging**
