### PR TITLE
Use array_replace_recursive instead of array_merge

### PR DESCRIPTION
**Pull request by alex-code**
Use `array_replace_recursive` instead of `array_merge` for `$config`

e.g.
I had this in with the config to set the `ActiveField` class for forms.

```
Yii::$container->set('yii\bootstrap\ActiveForm', [
    'fieldConfig' => [
        'class' => 'common\components\ActiveField',
    ],
]);
```

When using the form I wanted to change some css classes.

```
<?php $form = ActiveForm::begin([
    'layout' => 'horizontal',
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'label' => 'col-sm-2',
            'wrapper' => 'col-sm-8',
            'hint' => 'col-sm-2'
        ]
    ]
]) ?>
```

This would overwrite the initial config falling back to the default `ActiveField` class

If it's OK I will update the changelog.

### CODE REVIEW

**Comment by lherry** [comment]
Hi Qiang (and others of the Yii team !),

First of all, thanks for all you've done for Yii with all of your team members and nice to speak to you!

I understand your point of view, but, like explained in the guide, the DI container could be used to create initial default configuration values to a class ?

So, to me, if we don't want a initial default value like you mentioned for `horizontalCssClasses` (normally in rare cases), we don't need to put it into a DI container but we need to put it in all class's specific calls... (or effectively Yii could implement a the '!' operator to unset value)

My problem #6922 was revealing behaviors problem: Yii doesn't have the same behavior between 'direct' values (like the `layout` value in the first post of this issue) and sub arrays values (like values in `fieldConfig`). 

Actually, on class instanciation, Yii sets DI container configuration values only if options in class's call are not overriden, right ? So why should it be different for sub arrays values ? Is it coherent ?

Thanks !

**Comment by lherry** [comment]
A class helper merge function like below (which is derived from your ArrayHelper::merge() function) should apply the same behavior to sub arrays, no ?

```php
    /**
     * Merges two or more arrays into one recursively.
     * If each array has an element with the same key value, the latter
     * will overwrite the former (different from array_merge_recursive).
     * Recursive merging will be conducted if both arrays have an element of array
     * type and are having the same key.
     * @param array $arrayTo array to be merged to
     * @param array $arrayFrom array to be merged from. You can specify additional
     * arrays via third argument, fourth argument etc.
     * @return array the merged array (the original arrays are not changed.)
     */
    public static function merge2($arrayTo, $arrayFrom)
    {
        $args = func_get_args();
        $result = array_shift($args);
        while (!empty($args)) {
            $next = array_shift($args);
            foreach ($next as $key => $value) {
                if (is_array($value) && isset($result[$key]) && is_array($result[$key])) {
                    $result[$key] = self::merge2($result[$key], $value);
                } else {
                    $result[$key] = $value;
                }
            }
        }

        return $result;
    }
```

**Comment by lherry** [comment]
No advice about my last comments, except the performance impact ? :worried:

**Comment by cebe** [comment]
@lherry you posted it under a pull request that was closed half a year ago, this is likely to get lost... I reopened your issue: https://github.com/yiisoft/yii2/issues/6922#issuecomment-71185690

**Comment by lherry** [comment]
@cebe You're right ! I thought it was better to continue here to not duplicate comments on the problem even it was closed half year ago. Thanks for your return.

**Pull request closed without merging**
