### PR TITLE
Add testValidateTargetClass for reproduce the bug.

### PR DESCRIPTION
**Pull request by githubjeka**
When IDs targetClass & model(not new)  is same then unique validator passed

### CODE REVIEW

**Comment by githubjeka** [comment]
This pull for reproduce on travic

**Comment by LAV45** [comment]
OK. You only check for the insert of linked data, but what about the updates?

**Comment by meshzp** [comment]
Hi, mates! We've noticed that unique validator logic was changed. So,
a. What we must to do now if we need to update non-unique fields in model that has unique attributes?
b. What we must to do if we need to update single value in unique attribute in model, which has several unique attributes?

For example. We have User model which has unique attributes like nickname and email. We need to allow to change that attributes to any other values which are not in use by other users. 

Right now uniqueness is checking by query like
SELECT 1 FROM `users` WHERE `email`='someuser@somedomain.com'
Can we add to this query current id of model which we are going to update?
SELECT 1 FROM `users` WHERE `email`='someuser@somedomain.com' AND id != {:id}

**Comment by githubjeka** [comment]
@meshzp via [$filter](http://www.yiiframework.com/doc-2.0/yii-validators-uniquevalidator.html#$filter-detail)

This PR not changed logic work with an model. 
See https://github.com/yiisoft/yii2/pull/10265/files#diff-b7eeda2fac6ce8131377ce36953a329aR108 . Changed only `$model::className() !== $targetClass` , It's logic work with diff models.

**Comment by SilverFire** [comment]
@meshzp could you check, whether your case works in another way at 2.0.6?

**Comment by meshzp** [comment]
Yes. Update worked for me and fails now. On the first look, i can see that month ago before my last YII2 update (not sure that it was exactly 2.0.6) uniquiness was checking by query like

SELECT count(*) WHERE email='someuser@somedomain.com' LIMIT 2 

and failed when the count equals two.
Will look deeper through the code and let you know if found some more details. Thanks.

**Comment by meshzp** [comment]
@githubjeka using the filter is the solution, however, we should apply it to all unique attributes in a project and consider on scenarios we are using. Too much unexpected work to do.

**Comment by meshzp** [comment]
@githubjeka @SilverFire 
May be this is my bad but i have stoped \vendor\yiisoft\yii2\validators\UniqueValidator.php on line 109 with xDebug and found that it walks into condition $model->className() !== $targetClass , because
$model->className() = "common\models\User"
$targetClass = "\common\models\User" 

difference in leading slash in some reason.

**Comment by meshzp** [comment]
@samdark
The problem was found, thanks for your attention. This is funny but the problem related with YII2 advanced application template SignUpForm.php. I think that it will not work correctly from now. 
 https://github.com/yiisoft/yii2-app-advanced/commit/cba4e7711d57632a1f5306218bbc471961951a3d line 30.

**Comment by githubjeka** [comment]
Different scope of namespace. Funny ^_^... need a fix

**Comment by samdark** [comment]
@githubjeka can you handle it?

**Comment by githubjeka** [comment]
Done

**Comment by SilverFire** [comment]
@meshzp thank your for your attention, the bug is fixed https://github.com/yiisoft/yii2/commit/c9580b5ba406bdf3652b91004d18e6c59cdb6b05

Could you check now, please?

**Pull request closed without merging**
