### PR TITLE
updated images gii

### PR DESCRIPTION
**Pull request by githubjeka**
https://github.com/yiisoft/yii2/pull/13190

### CODE REVIEW

**Review by SilverFire — APPROVED** [review]
Looks good to me

**Comment by samdark** [comment]
What is rge thing in model name field in the right part of it.

**Review by samdark — APPROVED** [review]

**Comment by githubjeka** [comment]
@samdark Wat? Please provide a screenshoot ^_^ for left right field from model name in right left part of it.

**Comment by samdark** [comment]
https://raw.githubusercontent.com/githubjeka/yii2/df0d4d966702798dd75694752fada0a990343824/docs/guide/images/start-gii-model.png

**Comment by samdark** [comment]
Model class field.

**Comment by githubjeka** [comment]
Oops :( last-pass chrome extension

**Comment by samdark** [comment]
Would be perfect if you'll redo screenshot without it.

**Comment by githubjeka** [comment]
I kill demo server. Tommorow to get involved in my work I will create new the screenshot before. ^_^

**Comment by samdark** [comment]
Well,  it is OK as is :) Too much hassle for such tiny thing.

**Comment by samdark** [comment]
Thanks you very much.

**Pull request merged**
