### PR TITLE
Update BaseYii.php

### PR DESCRIPTION
**Pull request by githubjeka**
$properties must be an array.

### CODE REVIEW

**Comment by samdark** [comment]
Looks OK to me. @yiisoft/core-developers any objections?

**Comment by qiangxue** [comment]
One thing that I'm hesitate about this change is that it may exclude the usage of passing a traversable object as this parameter.

**Comment by samdark** [comment]
@qiangxue any example when it will be instance of `Traversable` instead of array?

**Comment by qiangxue** [comment]
```php
$object1 = new MyClass;
// ...$object's properties are changed here
$object2 = new MyClass;
Yii::configure($object2, $object1);
```

As you can see, it doesn't have be traversable actually.

**Comment by samdark** [comment]
Makes sense.

**Comment by githubjeka** [comment]
Hmm ... 
I will use to `$object2 = clone($object1)` instead 
```php
$object2 = new MyClass;
Yii::configure($object2, $object1);
```

If `object2` much different from `object1`, then resort to `Yi::configure` is a strange way. 
It would be better to call for a declarative framework, obvious way.

**Comment by qiangxue** [comment]
`$object1` could be an instance of the parent class of `$object2`.

**Comment by githubjeka** [comment]
1 chance in 100 that someone will remember `Yii::configure` in this case. But okay, I agree - Makes sense.(с) :)

**Comment by qiangxue** [comment]
`$object2` could also be a configuration object. 

I agree the chance is slim. Type hint is mainly used by PHP parser to help you verify the parameter type. We aren't use type hint extensively in the core code. There are some reasons for this practice:

* It's not clear if adding type hint may degrade runtime performance.
* When a parameter with incorrect type is used, in most cases a PHP error/warning may occur within the function, which serves the same purpose of parameter type verification.
* For type hint like `array`, it prevents the usages like discussed in this thread.
* For class type hints, you are not allowed to change the signature to use subclass type hints.

Overall, I prefer we only use type hints when we are very sure we expect certain type of parameters.

**Comment by githubjeka** [comment]
Thank you for the clarification.

**Comment by githubjeka** [comment]
> Overall, I prefer we only use type hints when we are very sure we expect certain type of parameters.

I found the place https://github.com/yiisoft/yii2/blob/3a1e0f3a5c6f75ed08bb8cea321c2391045bc804/framework/base/Widget.php#L52 

Need PR :dart: :smile:

**Comment by samdark** [comment]
It doesn't look much different to me. Configuration object could be used there instead of array.

**Comment by cebe** [comment]
even there we could pass a configuration class that implements ArrayAccess.

**Comment by githubjeka** [comment]
```php
$o = Yii::createObject('yii\db\Connection');
$w = \yii\base\Widget::begin($o);
$w->end();
```

`PHP Fatal Error – yii\base\ErrorException Cannot use object of type yii\db\Connection as array`

**vs**

`PHP Recoverable Error – yii\base\ErrorException
Argument 1 passed to yii\base\Widget::begin() must be of the type array, object given`

**Comment by githubjeka** [comment]
The first error indicates that the problem of the framework, the second point to user error.

**Comment by cebe** [comment]
@githubjeka you can not pass $o there because `yii\db\Connection` does not implement array access

**Comment by githubjeka** [comment]
Please show me a class that implements. Thank.

**Comment by cebe** [comment]
I thought of something like this:

```php
	    $widgetConfig = new DynamicModel([
		    'class',
		    'property1' => 'a',
		    'property2' => 'b'
	    ]);

	    $w = \yii\base\Widget::begin($widgetConfig);
	    $w->end();
```

But BaseYii does not support this: https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L350

still the error message is better in this case than if we had array constraint in the method imo.

**Pull request closed without merging**
