### PR TITLE
fix mb_strlen \r\n bug

### PR DESCRIPTION
**Pull request by RobinKamps**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no (server side)- may affect count characters left scripts (client side)
| Tests pass?   | yes
| Fixed issues  | #14086

This PR solves the issue by counting line breaks in texareas, etc. the same way as mb_strlen in php will do - so this does not break BC server side.
However it could have some side effects to client side scripts:
Client side scripts wich count the characters left may show a different count.
(Users may also wonder if they actually count their typed in characters.)

### CODE REVIEW

**Comment by Renkas** [comment]
Better convert it from \r\n to \n in server side and leave the old JS implementation.

There's no reason to save \r to database.

**Comment by RobinKamps** [comment]
Thanks.
I guess you are right - it is much more convenient for client side scripts and it is probably better to have only one format in the DB.
Now this PR will replace Win \r\n (and Mac \r) with Linux \n if string-validator is used.
This solution works on my projects (Windows and Linux Servers).

Notes:
- I have not tested this solution with scripts where CR-LF is really neccessary (perhaps terminal/console related stuff?)
-  Really platform tailored solutions (with PHP_EOL e.g.) will be much more complex as estimated (if CR-LF or LF, etc. is really needed, it has to be custom implemented now as well anyway)
- the docs for string-validator should note this new behaviour

**Comment by RobinKamps** [comment]
after writing some unit tests and doing some more research, i believe that this is a much more complex problem and there is no easy solution.
- This problem does only occur on textareas not on inputs (no line breaks possible on inputs).
- If the replacement of \r\n with just \n is placed inside the string validator the server side count by the string validator will be the same as the javascript count - this is the only good thing.
- If this replacement should be applied to the model and be saved to the DB the PR is missing something like
´´´$model->$attribute = str_replace(["\r\n", "\r"], " ", $model->$attribute);
- on windows server/apache/mysql/mariadb this replacement will be automatically converted back to \r\n. With db fields set to a length (191 for utf-8 mb... e.g.) this will cut off the last characters (quantity of \n)
- altering the input string in a validator that is not supposed to change the input value is a bad thing (adhoc validation with validateValue will not work by design, because there is no way to alter the models attribute with validateValue method - what if a string from a model is validated with validateValue and after that the model is saved to DB with save(false))

More thoughts on this issue:
- convert \r\n to \n just for the count - last characters will be cut off if field length is exceeded
- convert \r\n to blank_space and apply it to the attribute - will work in all situations where line breaks are not really needed
- convert \r\n to <br> etc. and apply it to the attribute  - last characters will be cut off if field length is exceeded
- if used with mysql text fields it is unlikely that the count error happens (text is 64 Kibibytes long)
- in case trim, purifier or other filters to delete multiple blanks etc. is called serverside before string validator the client side string validator script will show different values for length as well

Suggestion for a solution:
- Mention the probems (line breaks and trim/filters/purifier before string validator) in the docs (StringValidator and Textarea?)
- suggested working solution: place a custom rule/filter before string validator rule (e.g. for replace line breaks with blank_space):
´´´ ['string_attribute_name', 'filter', 'filter' => function ($value) {
                return str_replace(["\r\n", "\r", "\n"], " ", $value);
            }],

To solve the issue that js counts the \r\n as one char this custom filter is only neccessary for string attributes, that will be wired up to textareas.
The filter should be applied to all string attributes if no line breaks should occur in the db at all - \r\n could still be posted to input attributes via scripts, postman etc. - but that has nothing to do with the issue.
With this solution there is no "magic" attribute alteration hidden in the framework - it just takes one look to the model rules to realize that the attribute is beeing proccessed and line breaks are replaced.

**Comment by samdark** [comment]
Thanks for research.

**Pull request closed without merging**
