### PR TITLE
Added Instagram auth

### PR DESCRIPTION
**Pull request by chuprik**
Instagram auth class implementation.

### CODE REVIEW

**Comment by nsanden** [comment]
Thanks for doing this!

**Comment by Ragazzo** [comment]
should be in separated extension , no ?

**Comment by samdark** [comment]
Yes, should be separate extension. We've decided not to add more providers for now. Can link from docs when you release extension though.

**Comment by Ragazzo** [comment]
@samdark  your [explanation](https://github.com/yiisoft/yii2/pull/5414#issuecomment-58362777) about separated extension, will link it here for more info for others

**Pull request closed without merging**
