### PR TITLE
Finished translation docs/guide-ru/structure-assets.md

### PR DESCRIPTION
**Pull request by sergey144010**
I finished translating of this file.

### CODE REVIEW

**Comment by samdark** [comment]
Комментарии надо убрать.

**Comment by qiangxue** [comment]
The commits should be compacted.

**Comment by samdark** [comment]
Sure.

**Comment by sergey144010** [comment]
I`ve corrected document.

**Comment by samdark** [comment]
Merged. https://github.com/yiisoft/yii2/commit/99f3bf6425675fde131339109bdf2db66619d728 Thank you!

**Pull request closed without merging**
