### PR TITLE
travis: speedup - run coverage just once

### PR DESCRIPTION
**Pull request by TomasVotruba**
Run coverage just once, for ref see accepted PR in Doctrine https://github.com/doctrine/doctrine2/pull/1251

### CODE REVIEW

**Comment by samdark** [comment]
It runs coverage for 5.6 only, right?

**Comment by TomasVotruba** [comment]
@samdark Yep, checkout linked PR for advantages and possible drawbacks.

**Comment by TomasVotruba** [comment]
Scrutinizer coverage looks the same, 68 % - https://scrutinizer-ci.com/g/yiisoft/yii2/inspections/7b540ada-b5e1-48c2-9c67-eec50ae0c903

Just FYI: there's lot of skipped tests due to missing extension - Gmagick, Imagick, Apc etc.

**Comment by samdark** [comment]
Saved about 6 minutes which is good result.

**Comment by samdark** [comment]
Thanks!

**Comment by samdark** [comment]
Improving coverage is very welcome as well... anything about improving tests is welcome.

**Comment by TomasVotruba** [comment]
Thank you!

**Pull request merged**
