### PR TITLE
Added setting forwardUrlParameters to UrlManager

### PR DESCRIPTION
**Pull request by uldisn**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no

### CODE REVIEW

**Comment by uldisn** [comment]
Use case:
For example, when open Fancybox, for navigation in it, add to url fancybox=1. 
This parameter use for determining correct layout.
When open any link in Fnacybox popup, parameter is forwarder and can use correct layout.

**Comment by rob006** [comment]
I don't think that this use case is common enough to be in core. You can achieve the same by overriding `createUrl()` in custom `UrlManager`.

**Comment by uldisn** [comment]
Use case 2:
For providing return URL through more one page.

**Comment by samdark** [comment]
> For providing return URL through more one page.

Haven't got it. Would you please elaborate?

**Comment by Renkas** [comment]
I use similar parameter forwarding for iframe content (same content/view can be in iframe or in normal layout).

This PR would help me clean up some ugly code from controllers

**Comment by samdark** [comment]
@Renkas I still don't get the use case. Would you please help us by elaborating it?

**Comment by Renkas** [comment]
@samdark I have many (10+) admin views that work in normal ways or in a iframe (with autoresize for height). As there is no way (AFAIK) to know if link is opened in iframe or in normal admin layout I use url parameter to differentiate the layout (iframe=1).

Actually this PR would not allow me to clean up anything from controllers - I remembered it incorrectly.

I have overriden `UrlManager` myself for this.

```
namespace common\components;

class UrlManager extends \yii\web\UrlManager
{
    /**
     * @var string the GET parameter name for iframe layout request.
     */
    public $iframeParam = 'iframe';
    /**
     * @var boolean if the request is done from within iframe
     */
    private $iframe = false;

    public function parseRequest($request)
    {
        if ($request->getQueryParam($this->iframeParam)) {
            $this->iframe = true;
        }

        return parent::parseRequest($request);
    }

    public function createUrl($params)
    {
        if ($this->iframe) {
            $params[$this->iframeParam] = 1;
        }

        return parent::createUrl($params);
    }
}
```

IMHO would be a nice to have thing in core. But it is also easy to override `UrlManager` yourself

**Comment by samdark** [comment]
@Renkas so your case isn't related. OK.

**Comment by Renkas** [comment]
@samdark AFAIK it is exactly the use case this PR resolves.

Just I have my own implementation for it already.

**Comment by samdark** [comment]
Won't be merged because it's not that common. Sorry.

**Pull request closed without merging**
