### PR TITLE
Added new token {attribute_name} in DetailView template

### PR DESCRIPTION
**Pull request by mohdqasim98**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | no |
| Fixed issues |  |

Added support for new token `{attribute_name}` in the template property of `yii\widgets\DetailView`.
The occurrence of  `{attribute_name}` in template property  will be replaced by name of the corresponding attribute when rendering.It can be used to add class to the DetailView row.
Eg. 

``` php
   $template = '<tr class="{attribute_name}"><th>{label}</th><td>{value}</td></tr>';
```

### CODE REVIEW

**Comment by mohdqasim98** [comment]
Hi Guys,
This is my first pull request,
Please correct me if I am wrong some whrere

**Comment by unclead** [comment]
You can use an anonimous function as value of a template property for your needs

```php
'template' => function ($attribute, $index, $widget) {
    return '<tr class="' . $attribute['attribute']. '"><th>{label}</th><td>{value}</td></tr>';
}
```

don't you?

**Comment by mohdqasim98** [comment]
@unclead 
Yes, I did that.
But wouldn't it be nice, if this functionality is added ?.
Beside that , can you please tell me why "-integration/travis-ci/pr" failed ?

**Comment by samdark** [comment]
Since attribute name is rarely to be displayed to end user and it could be achieved as @unclead mentioned, I'm rejecting the pull request. Thanks for contribution attempt though. We appreciate it.

What failed in Travis could be found by clicking "Details". In this case it is HHVM and if you'll check output of it, it will be clear that it's not connected in any way with the code itself. So your code is fine.

**Comment by mohdqasim98** [comment]
Thanks for the responses.
Will try some other thing to get involved in this project :)

**Pull request closed without merging**
