### PR TITLE
Update Validator.php

### PR DESCRIPTION
**Pull request by WinterSilence**
- Add aliases for built-in validators: 'bool', 'float', 'int' - to set validator by PHP type, 'range' and 'regex' - similar to class name
- Update examples in phpDoc's

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Thanks for contributing but I don't think that's a good idea to have multiple aliases since it hurts overall readability. In some places it may be one alias, in another - another alias.

**Comment by WinterSilence** [comment]
@samdark 
really?
~~~php
'number' => 'yii\validators\NumberValidator',
'double' => 'yii\validators\NumberValidator',
~~~

**Comment by samdark** [comment]
Yes :) We did it but it doesn't change the fact that it was not a good idea.

**Comment by WinterSilence** [comment]
@samdark L-logic...

**Pull request closed without merging**
