### PR TITLE
[2.1] no assets

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | ?

Detailed description will follow in: https://github.com/yiisoft/yii2/issues/8452

### CODE REVIEW

**Comment by klimov-paul** [comment]
Simple removal of asserts requirement does not solve the issue.
[Here](https://github.com/yiisoft/yii2/issues/8452#issuecomment-329895440) you mention `packages.json`, which should replace them, but I can not see it. 
Our current [packages.json](https://github.com/yiisoft/yii2/blob/master/package.json) does not seem to me as full-scale replacement.

**Comment by schmunk42** [comment]
The current `packages.json` contains only `devDependencies`, so there wouldn't been any packages installed needed during runtime.
I would not recommend to move the removed assets to `packages.json` here, but in a new repo, like `yii2-widgets` or `yii2-grid`...

**Comment by schmunk42** [comment]
I just tried to play around with the recent code of `2.1`, but it still contains `bower-asset` requirements. I think we should drop them and add the functionality later, most likely in another repo.

**Comment by samdark** [comment]
That is because JS was separated but wasn't yet moved out to separate repositories.

**Comment by schmunk42** [comment]
Is is basically moving these files https://github.com/yiisoft/yii2/tree/2.1/framework/jquery into https://github.com/yiisoft/yii2-jquery or more?

**Comment by samdark** [comment]
It is.

**Comment by schmunk42** [comment]
Tests for 7.1 in this PR have passed btw: https://travis-ci.org/yiisoft/yii2/jobs/276048104 - I actually wonder that they did, but anyway.

So the tests need to be moved also - for sure. How could we proceed with this?

**Comment by samdark** [comment]
If you want to handle it, I can grant you write permissions to https://github.com/yiisoft/yii2-jquery. Then:

1. Got everything into yii2-jquery.
2. Make sure travis/tests/docs/composer are OK.
3. Clean up core framewrok.

**Comment by klimov-paul** [comment]
@samdark, haveb't we agreed to use 'git subsplit' to transfer code from the core to extensions?
There is no sense of performing code separation until 2.0.14 release and 2.0.x freeze, since there will be need of merging code from 2.0.x to the 2.1.x.
Stay down - it is not the time yet.

**Comment by samdark** [comment]
We did. Right.

**Comment by schmunk42** [comment]
Is it the time now? :smile: 

2.0.14 is released and ["and 2.0.x will only receive bug fixes from now on. "](http://www.yiiframework.com/news/165/yii-2-0-14-is-released/).

Related: https://github.com/yiisoft/yii2-bootstrap/pull/212

**Comment by klimov-paul** [comment]
It is in the progress.
If you want to help, you may start from fixing NodeJs tests at `yii2-jquery`:
https://travis-ci.org/yiisoft/yii2-jquery/jobs/346919825

**Comment by schmunk42** [comment]
Most tests are passing, see https://travis-ci.org/yiisoft/yii2-jquery/jobs/346996359 - I guess pjax can be removed and captcha also (move test to https://github.com/yiisoft/yii2-captcha)

PR: https://github.com/yiisoft/yii2-jquery/pull/1

**Comment by schmunk42** [comment]
Closing, mostly obsolete due to https://github.com/yiisoft/yii2/issues/14862#issuecomment-369316223

**Pull request closed without merging**
