### PR TITLE
Updates translation pt-BR

### PR DESCRIPTION
**Pull request by sdlins**

### CODE REVIEW

**Comment by samdark** [comment]
Do you plan more commits?

**Comment by sdlins** [comment]
Yeah, I plan now but was not planned till yesterday. Lets do this way: you merge this because I feel it is important to be available asap and the next ones I will PR only once a week. Agree, @samdark ?

**Comment by sdlins** [comment]
Still better, wait more some hours because I just saw that instalation guide is completely outdated and wrong.

**Comment by sdlins** [comment]
Ok, @samdark, go ahead!

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
