### PR TITLE
codeclimate rules update

### PR DESCRIPTION
**Pull request by bizley**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13913

### CODE REVIEW

**Comment by cebe** [comment]
> codeclimate — 175 new issues

In some classes that are meant to wrap superglobals these are fine to use so without a list of exceptions this rule does not make much sense.

**Comment by bizley** [comment]
It would be good to somehow make an exception for these specific places but to keep this rule everywhere else.

**Comment by bizley** [comment]
I can not find an option in documentation to switch off this rule check for individual files so probably this has to be rejected.

**Comment by bizley** [comment]
I guess there is one way https://docs.codeclimate.com/docs/marking-false-positives 
Unfortunately it requires going through every detected issue and adding their fingerprints to the configuration.

**Comment by samdark** [comment]
Merged. Will update fingerprints as it goes.

**Pull request merged**
