### PR TITLE
[minor] Static code analysis

### PR DESCRIPTION
**Pull request by kalessil**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | n/a
| Fixed issues  | n/a

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks good. Should be applied to 2.1 branch as well.

**Review by SilverFire — APPROVED** [review]

**Review by rugabarbo — APPROVED** [review]

**Comment by kalessil** [comment]
Any chance to get this merged next week? I would like to address a little bit more findings but in a separate PR.

**Comment by SilverFire** [comment]
Merged

**Comment by kalessil** [comment]
Thank you =)

**Pull request merged**
