### PR TITLE
Fixed 0-id RBAC not finding roles

### PR DESCRIPTION
**Pull request by TheNodi**
DbManager couldn't get roles of users with id = 0 because empty($userId) was true.

Changed empty with combination of isset, === false.

### CODE REVIEW

**Comment by TheNodi** [comment]
I'm not checking empty string or empty arrays, waiting to know if I have to add them.

**Comment by samdark** [comment]
How come that you have user with ID = 0?

**Comment by TheNodi** [comment]
I copied the user-scheme from the advanced app into a basic app (because I didn't need front-end and back-end but I wanted a DB implementation of the login system).
I didn't changed anything, User Model and database table are the same.

**Comment by TheNodi** [comment]
I figured the mistake out.
My export tool didn't catch the "Auto Increment" of the id in the user table.

Should yii consider zero as a possible User ID?
If not, I think it's better to add something like "Don't use zero as user id" into the RBAC Documentation because you need to check the source to understand it.

**Comment by samdark** [comment]
Zero IDs are extremely rare. All auto incremenets, serials etc. are starting with 1. I don't think we should check for it or mention it in the guide.

**Pull request closed without merging**
