### PR TITLE
Fix #20195 Do not set parts of ColumnSchema->dbType values into Colum…

### LINKED ISSUE #20195: mssql empty strings changed to null for string type colums in 2.0.50
### What steps will reproduce the problem?

Read mssql nvarchar column of a database with db version less then 2017.

In  https://github.com/yiisoft/yii2/commit/9d3c71d6a712a99f42ae1c5d588312f49514523a#diff-ea76a30d7da4b9fb69fe63d479c0764c4fd9bf99fbb859ba664ff0bc79a6bf8cR411

The function booleanTypeLegacy sets non abstract column type in last return statement ( for example nvarchar)

~~~php
$column->type = $this->booleanTypeLegacy($column->size, $type);
~~~

### What is the expected result?

Read empty string from mssql column of type nvarchar.

### What do you get instead?

Read column value is null.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.50
| PHP version      | 8.3.7
| Operating system |

One way to fix would be to move function code directly into code where used:

~~~diff
411c411,419
<                     $column->type = $this->booleanTypeLegacy($column->size, $type);
---
>                     if ($column->size === 1 && ($type === 'tinyint' || $type === 'bit')) {
>                         $column->type = 'boolean';
>                     } elseif ($type === 'bit') {
>                         if ($column->size > 32) {
>                             $column->type = 'bigint';
>                         } elseif ($column->size === 32) {
>                             $column->type = 'integer';
>                         }
>                     }
819,840d826
<     /**
<      * Assigns a type boolean for the column type bit, for legacy versions of MSSQL.
<      *
<      * @param int $size column size.
<      * @param string $type column type.
<      *
<      * @return string column type.
<      */
<     private function booleanTypeLegacy($size, $type)
<     {
<         if ($size === 1 && ($type === 'tinyint' || $type === 'bit')) {
<             return 'boolean';
<         } elseif ($type === 'bit') {
<             if ($size > 32) {
<                 return 'bigint';
<             } elseif ($size === 32) {
<                 return 'integer';
<             }
<         }
< 
<         return $type;
<     }

~~~

### PR DESCRIPTION
**Pull request by axeltomasson**
…nSchema->type for mssql less then version 2017

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | #20195

### CODE REVIEW

**Review by terabytesoftw — APPROVED** [review]

**Comment by terabytesoftw** [comment]
What version of `MSSQL` are you using?

**Comment by axeltomasson** [comment]
> What version of `MSSQL` are you using?

2012 😭️

**Review by Arhell — APPROVED** [review]

**Comment by Tigrov** [comment]
Could you add test?

**Review by Tigrov — APPROVED** [review]

**Comment by marcovtwout** [comment]
@axeltomasson Could you clarify: is this a regression in 2.0.50 or was it also broken in 2.0.49?

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
