### PR TITLE
PHP 8.1 trim(): Passing null to parameter #1 ($string) of type string is deprecated

### PR DESCRIPTION
**Pull request by uaoleg**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by uaoleg** [comment]
> * The method isEmpty() was changed to accept null as a valid value.
> * The addOrderBy() and normalizeOrderBy methods were updated to handle the case where $columns is empty or null, which can happen if order by clause has no columns specified in it (e.g., ORDER BY NULL).

Almost right. The usecase is clear ORDER BY in the query: `$query->orderBy(null)`

**Review by samdark — APPROVED** [review]
👍 Need a line for CHANGELOG

**Review by Arhell — APPROVED** [review]

**Comment by uaoleg** [comment]
@samdark CHANGELOG updated

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
