### PR TITLE
Both offset and limit can set with a Pagination instance or an array …

### PR DESCRIPTION
**Pull request by a761208**
Before:
`$query->offset($pagination->getOffset())->limit($pagination->getLimit());`
After:
`$query->page($pagination);`
Or:
`$query->page([123, 20]);`
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by dynasource** [comment]
Im against such shortcuts. The added value does not weigh up against to facts like:
* perhabs code is shorter but harder to read
* framework pollution
* more ways of doing things adds confusion to developers

**Comment by samdark** [comment]
Same here. I don't see why it's needed. That's why I've asked for use case.

**Comment by a761208** [comment]
Sorry to hear this.
I use active query search things like this:
```php
                                  $query = SomeModel::find();
                                  $query->... add some search filters
                                  $pagination = new Pagination(['totalCount'=>$query->count()]);
                                  $model_list = $query->orderBy(...)->offset($pagination->offset)->limit($pagination->limit)->all(); // It's a little long about this line
                               // $model_list = $query->orderBy(...)->page($pagination)->all();
```

**Comment by Renkas** [comment]
I don't get it. Why are you using Pagination in this usecase at all?

**Pull request closed without merging**
