### PR TITLE
Fixes #9032: Improve scenarios usage docs [skip ci]

### LINKED ISSUE #9032: Improve scenarios usage docs
The default scenario is implemented via constant `SCENARIO_DEFAULT`. However, in multiple docs pages I saw scenarios are used as raw strings, for example: `'default'`, `'update'`. This is not right and can lead to errors. I saw many developers use just raw strings.

### PR DESCRIPTION
**Pull request by arogachev**
Sorry, didn't create separate branch. Is it required for docs changes?

Also I have some questions:
- Should I change translated docs as well? Or it's synchronized by the people who do translation?
- Should we add some additional notes about constants usage?

### CODE REVIEW

**Comment by samdark** [comment]
Separate branch is needed in order to submit multiple pull requests at once.

**Comment by arogachev** [comment]
What should I do in order to correct this? Close this and create new one with separate branch?

**Comment by arogachev** [comment]
Maybe it will be better if the docs will contail both ways of doing this. Also we need to mention that we need to create constants before using it, some new users can misunderstand it.

**Comment by samdark** [comment]
It's OK as is if you aren't going to open another pull request.

That's why I asked about constants. These should be defined in classes.

**Comment by arogachev** [comment]
So what's better to do now?

**Comment by samdark** [comment]
I'll take care of it.

**Comment by samdark** [comment]
Changed to constants in "Models" guide section where it makes sense because full classes are provided.

**Comment by samdark** [comment]
Thanks for idea. It could result in better code in apps.

**Pull request closed without merging**
