### PR TITLE
Add first() and after($column) methods for ColumnSchemaBuilder

### PR DESCRIPTION
**Pull request by dudareviv**
Add methods for ColumnSchemaBuilder:
- first -- adds a `FIRST` constraint to the column.
- after  -- adds a `AFTER` constraint for the column and the column name.

issue #9455

### CODE REVIEW

**Comment by samdark** [comment]
Is it supported by all databases we have in framework?

**Comment by hulyman** [comment]
It seems like a support exists only in mysql.
PostgreSQL doesn't support yet: https://wiki.postgresql.org/wiki/Alter_column_position
Sqlite doesn't support: http://stackoverflow.com/questions/4253804/insert-new-column-into-table-in-sqlite
For ms sql it support in mssql server 2016: https://msdn.microsoft.com/en-us/library/aa337556.aspx
Oracle: http://www.dba-oracle.com/t_change_column_order_within_oracle_table.htm

**Comment by hulyman** [comment]
Add `AFTER` constraint need sometimes. What to do?

**Comment by samdark** [comment]
That would be MySQL-specific things. Not sure if we're going to support that.

**Comment by samdark** [comment]
Closing since this pull request can't be merged because of not being compatible with all DBs supported.

**Pull request closed without merging**
