### PR TITLE
MSSQL: fix tests

### LINKED ISSUE #15880: It is impossible to create a comment to a field. MSSQL
### What steps will reproduce the problem?
$ yii migrate

### What is the expected result?
$ yii migrate
Yii Migration Tool (based on Yii v2.0.14.1)

Total 1 new migration to be applied:
	m180312_073238_review_table.php

Apply the above migration? (yes|no) [no]:y
*** applying m180312_073238_review_table
    > create table foo ... done (time: 0.054s)
*** applied m180312_073238_review_table (time: 0.073s)

1 migration was applied.

Migrated up successfully.

### What do you get instead?
Apply the above migration? (yes|no) [no]:y
*** applying m180312_073238_review_table
    > create table review ...Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]В процедуре "sp_updateextendedproperty" указан неправильный параметр или значение.
The SQL being executed was: sp_updateextendedproperty @name = N'MS_Description', @value = 'id пользователя', @level1type = N'Table',  @level1name = [review], @level2type = N'Column', @level2name = [user_id] (/home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/db/Command.php(1260): yii\db\Schema->convertException(Object(PDOException), 'sp_updateextend...')
#1 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/db/Command.php(1072): yii\db\Command->internalExecute('sp_updateextend...')
#2 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/db/Migration.php(326): yii\db\Command->execute()
#3 /home/xandr/Projects/vipishinew/console/migrations/m180312_073238_review_table.php(18): yii\db\Migration->createTable('review', Array)
#4 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/db/Migration.php(114): m180312_073238_review_table->safeUp()
#5 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#6 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m180312_073238_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#13 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#14 /home/xandr/Projects/vipishinew/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /home/xandr/Projects/vipishinew/yii(31): yii\base\Application->run()
#16 {main}
*** failed to apply m180312_073238_review_table (time: 0.029s)

0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.

### Additional info
<?php

use yii\db\Migration;

/**
 * Class m180312_073238_review_table
 */
class m180312_073238_review_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('review', [
            'id' => $this->primaryKey(),
            'user_id' => $this->integer()->comment('id пользователя'),
            'content' => $this->text()->comment('содержимое')
        ]);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('review');
    }

}

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      |  7.0.25
| Operating system | Ubuntu 16.04

### PR DESCRIPTION
**Pull request by alexkart**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #15880

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks good. Would you please add a line to CHANGELOG?

**Comment by alexkart** [comment]
I think I need to revert the changes related to the comments as they are also fixed in #17413 to avoid merge conflict.
And leave only fix of the `testResetSequence` in this PR.

**Comment by samdark** [comment]
OK. Let's adjust it.

**Comment by alexkart** [comment]
Also, fixed one more test.

**Comment by samdark** [comment]
CHANGELOG?

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
