### PR TITLE
Fixes #5442: Moved `resetTable` to `unload` method

### LINKED ISSUE #5442: ActiveFixture does not delete actual data in unload() method
ActiveFixture unload does not call `resetTable()` in `unload()` and this causes trouble when you have dependant fixtures with foreign key constraints. As ActiveFixture tries to `loadFixtures()`, which calls `resetTable()` it fails as the dependant data is not deleted. The issue description is related with #5441

### PR DESCRIPTION
**Pull request by leandrogehlen**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #5442

### CODE REVIEW

**Comment by samdark** [comment]
Wouldn't this change make tests stuck till you clear DB manually in case there was a failure?

**Comment by leandrogehlen** [comment]
This was solved with the following change:
https://github.com/Codeception/Codeception/pull/4016

In the next execution the fist step is to execute de `unload`

**Comment by samdark** [comment]
Ah, right. Need a changelog line then,

**Comment by cebe** [comment]
`ActiveFixture` is not only used with codeception so it should call the method in both places or have an option to choose when to call it.

**Comment by leandrogehlen** [comment]
Where more is used?

**Comment by samdark** [comment]
Fixture itself could be used manually.

**Comment by cebe** [comment]
> Where else is used?

with PHPUnit for example.

**Comment by leandrogehlen** [comment]
Can be created `FixtureTrait::initFixtures` method?:

```php
public function initFixtures()
{
    $this->unloadFixtures();
    $this->loadFixtures();
}
```

**Comment by samdark** [comment]
Yes.

**Comment by leandrogehlen** [comment]
I think this issue needs to be in 2.012, because the `yii2-codeception` is deprecated and the yii2 codeception module does not allow to use https://github.com/yiisoft/yii2/blob/master/framework/test/InitDbFixture.php.
This way, currently, it's impossible to use fixtures with db-related

**Review by samdark — APPROVED** [review]

**Review by SilverFire — APPROVED** [review]

**Comment by leandrogehlen** [comment]
related Codeception/Codeception#4201

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
