### PR TITLE
creation of hindi framework messages

### PR DESCRIPTION
**Pull request by acto-felix**
the file was created using google translator

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | 
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
I'd prefer it to be verified by native speaker.

**Comment by acto-felix** [comment]
@samdark My company uses yii2 and we need it translated to 10 different languages, hindi is one of them and I couldn't find a way to have hindi messages working on my project other than this... sure google translate is not ideal, but bad translation is better than no translation at all (at least in my case)...

**Comment by samdark** [comment]
@acto-felix I understand that but won't merge Google Translate version unless it's verified by native speaker. I've [asked for help via official Twitter](https://twitter.com/yiiframework/status/1255585082393452553) and there was a response. Hopefully Vekariya Ketan V will dedicate some time to verify the messages.

Until then I'm keeping this one open but unmerged.

**Comment by SOHELAHMED7** [comment]
Hi @samdark 

If Vekariya Ketan has already staretd working on this PR, please ignore this comment.

I am not  native speaker of Hindi. But I know. Are yoy OK if I contribute to this PR? If not I have people in my contact who knows Hindi better than me or native speaker. I will encourage them to contribute to this PR

**Comment by samdark** [comment]
No, he didn't start yet. Yes, I'm fine if you'll check it.

**Comment by SOHELAHMED7** [comment]
Hi @samdark 

I searched but did not get effective results. Is there a way for me with current set of permissions to edit this PR ? Any links  explaining this would be highly recommended

Currently I am going with forking and creating a new PR.

**Comment by samdark** [comment]
Moved to https://github.com/yiisoft/yii2/pull/18023

**Comment by yebowhatsay** [comment]
Alex
I am a native Hindi speaker.
I can help correct the translation if you like. 
Please let me know if you need help.
Thanks
Merson

**Comment by samdark** [comment]
@yebowhatsay help is always welcome. Please check https://github.com/yiisoft/yii2/pull/18023

**Comment by yebowhatsay** [comment]
@samdark 
#18023  reviewed and changes suggested.
Thanks

**Comment by SOHELAHMED7** [comment]
@acto-felix
 Thanks for your this original PR. This PR encouraged us to give better Hindi translation messages.  Enhanced Hindi translation messages can be found at https://github.com/yiisoft/yii2/pull/18023/files

**Pull request closed without merging**
