### PR TITLE
Checking for the existence of a symlink is fixed

### PR DESCRIPTION
**Pull request by raoptimus**
Bugfix

### CODE REVIEW

**Comment by raoptimus** [comment]
screen shot 2017-10-20 at 2 17 31 pm

**Comment by samdark** [comment]
How to reproduce the issue?

**Comment by raoptimus** [comment]
>How to reproduce the issue?
The error happens sometimes. There are no clear steps for the issue
Functions **is_file** returns false if symlink is exists. it`s no correct
I so think. You can check code

**Comment by samdark** [comment]
`is_file()` should resolve symlinks well. What are your OS and file system?

**Comment by raoptimus** [comment]
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )

```
php -r 'var_dump(is_file("/var/www/persdev/site"));'
bool(false)
php -r 'var_dump(is_link("/var/www/persdev/site"));'
bool(true)
php -r 'var_dump(file_exists("/var/www/persdev/site"));'
bool(true)
```

**Comment by samdark** [comment]
Seems the change doesn't pass tests: https://travis-ci.org/yiisoft/yii2/jobs/290372337

**Comment by rob006** [comment]
@raoptimus What returns `php -r 'var_dump(is_dir("/var/www/persdev/site"));'`?

**Comment by rob006** [comment]
This is probably duplicate of #6226. 

@raoptimus Could you try master branch and check if problem still occurs?

**Comment by raoptimus** [comment]
> @raoptimus What returns php -r 'var_dump(is_dir("/var/www/persdev/site"));'?
bool(true)
> @raoptimus Could you try master branch and check if problem still occurs?
i`ll answer later

**Comment by rob006** [comment]
> bool(true)

The this fix is incorrect - you can't use `publishFile()` for directories.

**Pull request closed without merging**
