### PR TITLE
Calculation of activity menu item through the closure

### PR DESCRIPTION
**Pull request by voskobovich**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | empty |

See comments history in old PR #10493.

### CODE REVIEW

**Comment by voskobovich** [comment]
@samdark, this is a new PR for #10493

**Comment by SilverFire** [comment]
Tests and CHANGELOG must be updated

**Review by SilverFire — CHANGES_REQUESTED** [review]
Tests and CHANGELOG must be updated

**Comment by voskobovich** [comment]
@SilverFire who is must added the requested changes?

**Comment by cebe** [comment]
@voskobovich if you want to speed things up, you can add them. Otherwise, we will do it, but later ;)

**Comment by SilverFire** [comment]
Merged https://github.com/yiisoft/yii2/commit/4afbad1aae2d0f2873ae2e5fd6333c1eb7d643be with some enhancements in https://github.com/yiisoft/yii2/commit/a710345ea788530ee4bc903bfcc795a160b63797

**Comment by SilverFire** [comment]
Thank you!

**Pull request closed without merging**
