### PR TITLE
Bug #17685: up and down methods now using proper "db" component

### PR DESCRIPTION
**Pull request by rvkulikov**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | 
| Fixed issues  | #17685

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks good. Please add a line to changelog.md

**Comment by rvkulikov** [comment]
@samdark done

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by My6UoT9** [comment]
The reference to the issue in changelog.md is wrong, 
It should be #17685 instead of #17865.

**Comment by samdark** [comment]
Good catch, @My6UoT9. https://github.com/yiisoft/yii2/commit/9bf2b5261d459cd6def201f135319eb91396791b

**Pull request merged**
