### PR TITLE
Correct rectangle size for Captcha background

### PR DESCRIPTION
**Pull request by alsopub**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | no |
| Fixed issues |  |

### CODE REVIEW

**Comment by cebe** [comment]
can you briefly describe the problem? also we need a CHANGELOG entry to merge it.

**Comment by alsopub** [comment]
This is not a bug.
Function "imagefilledrectangle" gets rectangle as "x1, y1, x2, y2", so to fill rectangle on entire image we need to pass 0, 0, width-1, height-1. Now passed 0, 0, width, height, that 1 pixel more than needed on both axis.

**Comment by samdark** [comment]
OK. `imagefilledrectangle` uses coordinates and these are 0-indexed. The fix is valid.

**Comment by samdark** [comment]
Merged. Thank you.

**Pull request closed without merging**
