### PR TITLE
DbManager $assignmentsCache, reduce db call, fixes #10980

### LINKED ISSUE #7743: Cache RBAC assignments
Save `SELECT * FROM auth_assignment WHERE user_id='...'` results in `User` component property to avoid duplicate DB queries on one page.
[See comment here](https://github.com/yiisoft/yii2/issues/3168#issuecomment-76709786).

### LINKED ISSUE #10980: yii\rbac\DbManager "getAssignments($userId)" not doing caching even "cache" enabled
and it is causing every time whenever calling "$user->can()" function, it will re-query the database.

### PR DESCRIPTION
**Pull request by ryusoft**
- to reduce db call every time for same user id

Closes #7743

### CODE REVIEW

**Comment by SilverFire** [comment]
Related #7743

**Comment by SamMousa** [comment]
Yii core often handles this differently.
1. Caches are private,
2. Caches do not contain the word cache. (`private $_assignments`).

Personally I think these kinds of caches (caching only for the duration of a single request) should be implemented in a trait instead, that would reduce the way the code work and make serialization more consistent (caches shouldn't be serialized).

Example:
````
trait RequestCacheTrait {
private $requestCache = [];

private function requestCacheSet($key, $val) {
    $this->requestCache[$key] = $val;    
} 
private function requestCacheGet($key, $default = null) {
    return isset($this->requestCache[$key]) ? $this->requestCache[$key] : $default;
}
}

````

@cebe What do you think?

**Comment by cebe** [comment]
there is already #9138...

@SamMousa I do not think 2 oneliners justify the existance of a trait...

**Comment by SamMousa** [comment]
Well these exist in a lot of classes. I'll make a small list

**Comment by SamMousa** [comment]
Okay, a list of similiar variables (all private and used for caching during a single request):
`yii\web\User::$_access`
`yii\base\Application:$_runtimePath`
`yii\base\Application:$_vendorPath`
`yii\base\Controller::$_viewPath`

(Quick search of "private $_" gave me 190+ results).

Basically most if not all of these uses are simple caches that have several things in common:
1. They are never accessed directly, only via getters and setters.
2. They are regenerated every request.
3. They are not the source of information (they are never the "only" place where the information is stored).

Optionally:
4. They do not need to be serialized (this is true only for the ones that have no setter).

Anyway, maybe not directly related to this specific issue, just something that could improve code reuse, readability and structure.
Alternatively readability could be improved a lot by altering the name(s) as @ryusoft has done and including `Cache` as part of the variable name. That way when reading the code one can easily see whether this variable is really relevant or just a cache.

**Comment by leandrogehlen** [comment]
It seems duplicated #14061

**Pull request closed without merging**
