### PR TITLE
Update ActiveRecord.php

### PR DESCRIPTION
**Pull request by hooman-mirghasemi**
Hi
I think when programmer use refresh method need to get real time what is actually in db. so it shouldn't load from cache if it is enable.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️/❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Review by bizley — APPROVED** [review]
The question here is - what do you refresh in AR actually? Is it the underlying data or just the instance of mapped underlying data. I'm for the data itself but someone could have other idea. Could we consider this to be a default behavior but leave an optional method argument so when set cache is still used?

**Comment by samdark** [comment]
I see no sense in using cache for `refresh()`.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
I'd consider it a bug. @hooman-pro would you please update changelog? Also, it is possible to make a unit test for it?

**Comment by hooman-pro** [comment]
sorry really i'm busy now and unfortunately  I never write unit test yet!

**Comment by hooman-mirghasemi** [comment]
I commit change log
also i rename my github username so i change my name in line 1395

**Comment by hooman-mirghasemi** [comment]
@bizley I refresh underlying data in db for example user credit that can change by android application on that moment.
or one counter can change by other user requests.

**Comment by samdark** [comment]
Thank you.

**Pull request merged**
