### PR TITLE
Added French structure-filters.md & structure-widgets.md and improved structure-views.md [skip ci]

### PR DESCRIPTION
**Pull request by jaaf**
| Q | A |
| --- | --- |
| Is bugfix? | yes/no |
| New feature? | yes/no |
| Breaks BC? | yes/no |
| Tests pass? | yes/no |
| Fixed issues | comma-separated list of tickets # fixed by the PR, if any |

### CODE REVIEW

**Comment by samdark** [comment]
Thank you!

**Comment by jaaf** [comment]
Thank you for merging my work.
Could you please answer a question I have:
"When looking at this page https://github.com/yiisoft/yii2/tree/master/docs/guide-fr , I can see that some titles of second level have a TBD mark in front of them. Moreover the title is not translated even if the corresponding file is. What does this TDB stand for?"

**Comment by samdark** [comment]
To be done.

**Comment by jaaf** [comment]
Could you be more accurate ? Does this mean that the file is not fully achieved and doesn't deserve translation at the time being?

**Comment by samdark** [comment]
It means original has some significant parts to improve. Currently these are:

1. One section in tabular input called "Combining Update, Create and Delete on one page".
2. APIDoc extension documentation.
3. Core widgets.

**Pull request merged**
