### PR TITLE
Added `Yii::getEnv`

### PR DESCRIPTION
**Pull request by leandrogehlen**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

Helper to retrieve values from enviroment variables

### CODE REVIEW

**Comment by samdark** [comment]
Is it better than any existing dotenv libraries?

**Comment by leandrogehlen** [comment]
The problem is get the value from environment variables.
These libraries just load the environmnet variables from file

**Comment by samdark** [comment]
Nope. These usually do both i.e. environment variables + files with files priority.

**Comment by leandrogehlen** [comment]
I guess that https://github.com/vlucas/phpdotenv is the most popular and used in laravel.
And i didn't find this feature.

Laravel has implemented the same feature
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/helpers.php#L604

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app/issues/1

**Pull request closed without merging**
