### PR TITLE
Allows configure `Connection::dsn` by key=>value

### PR DESCRIPTION
**Pull request by leandrogehlen**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by cebe** [comment]
It should be documented in dsn phpdocs that this is possible.

**Comment by samdark** [comment]
@leandrogehlen can you help with phpdoc? Thanks.

**Comment by leandrogehlen** [comment]
yes, i can do it.

**Pull request merged**
