### PR TITLE
Change loginRequired exception to 401

### PR DESCRIPTION
**Pull request by spikyjt**
As per #9846

### CODE REVIEW

**Comment by spikyjt** [comment]
I know I need to do a changelog entry and probably modify a test. I'll do that if the issue is approved.

**Comment by samdark** [comment]
Please do it. The change is valid.

**Comment by spikyjt** [comment]
Done the changelog. Doesn't look like there is a test for it, as the checks pass.

**Comment by samdark** [comment]
Thanks! https://github.com/yiisoft/yii2/commit/4e715f9d65e75853866b19c1f968b4d9c7969ae7

**Pull request closed without merging**
