### PR TITLE
Remove methods mset, mget and madd of `yii\caching\Cache`, getHasChanged of `yii\caching\Dependency`

### PR DESCRIPTION
**Pull request by jiaweipan**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️

### CODE REVIEW

**Comment by jiaweipan** [comment]
> What's the rationale behind this?
> 
> It's a pretty heavy BC-break.

See in phpdoc, such as `@deprecated This method is an alias for [[multiGet()]] and will be removed in 2.1.0.`

**Review by bizley — APPROVED** [review]

**Comment by bizley** [comment]
@schmunk42 it's for Yii 2.2

**Review by terabytesoftw — APPROVED** [review]

**Comment by terabytesoftw** [comment]
We are going to place in the next PR in the title that is for `Yii 2.2`, so there will be no confusion.

**Comment by jiaweipan** [comment]
> We are going to place in the next PR in the title that is for `Yii 2.2`, so there will be no confusion.

ok

**Review by Arhell — APPROVED** [review]

**Pull request merged**
