### PR TITLE
(#13105) Add yiiActiveForm validate_only property for skipping form a…

### PR DESCRIPTION
**Pull request by ptolomaues**
#13105

    JS validation example:
    
    form = $('#someForm');
    form.data('yiiActiveForm').validate_only = true;
    form.one('afterValidate', afterValidateEvent);
    form.yiiActiveForm('validate', true); //run validation
    
    function afterValidateEvent() {
        if ($('#someForm').find('.has-error').length) {
           // Validation failed
        }
         // Validation successed
    }

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Seems like a good option to have. Would you please add a line for CHANGELOG?

**Comment by ptolomaues** [comment]
> Seems like a good option to have. Would you please add a line for CHANGELOG?

Done

**Comment by samdark** [comment]
Would you also, please, merge master into PR branch? Diff looks weird now.

**Review by Arhell — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
