### PR TITLE
15630 fixed like escaping

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15630

### CODE REVIEW

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
The test fails

**Comment by samdark** [comment]
Yes. But the issue is fixed. It just seems that LIKE conditions are database-specific so test itself should be adjusted.

**Comment by sergeymakinen** [comment]
I would like to review it tomorrow if it’s possible.

**Comment by rob006** [comment]
I simplified test case, this should be enough to test #15630.

**Comment by samdark** [comment]
Accidentally squashed your tests as my commit. Hope you don't mind...

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
