### PR TITLE
add some unit tests regarding redirection for ResponseTest

### PR DESCRIPTION
**Pull request by thyseus**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    |no
| Tests pass?   | yes
| Tests issues  | https://github.com/yiisoft/yii2/commit/eab3489ec711b1ad9de0158e402fffaba999f4ff

### CODE REVIEW

**Comment by samdark** [comment]
Thank you.

**Comment by rob006** [comment]
I don't think it will prevent bugs like #13430. There should be tests for ``yii\web\Controller::redirect()``.

**Comment by samdark** [comment]
@rob006 ;)

**Comment by thyseus** [comment]
https://github.com/yiisoft/yii2/pull/13439

**Pull request merged**
