### PR TITLE
DbManager invalidate assignment cache only

### PR DESCRIPTION
**Pull request by alex-code**
Addition of method `invalidateAssignmentCache` to invalidate assignment cache for specified user.

My use case may be a little specific but I've got a WebSocket server that needs to clear cached assignments when the user disconnects but doesn't need to clear the other cached items.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by samdark** [comment]
I'd say that is very specific. How about allowing current code to be adjusted instead of implementing the method? i.e. private -> protected/

**Comment by alex-code** [comment]
That works for me.
Just need a way to free memory for users who are no longer connected.

Wan't me to update this PR or make a new one?

**Comment by samdark** [comment]
Update this one.

**Comment by alex-code** [comment]
Did you want a `@since` noting the change from `private` to `protected`?

**Comment by samdark** [comment]
Yes, change of scope to higher visibility should be tagged with "since".

**Review by samdark — APPROVED** [review]

**Review by bizley — APPROVED** [review]

**Pull request merged**
