### PR TITLE
Several application templates fixes

### PR DESCRIPTION
**Pull request by creocoder**

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by cebe** [comment]
Well, this was intentionally there to have stability set to dev in the dev version and set to stable in the release version.

https://github.com/yiisoft/yii2/blob/master/build/controllers/ReleaseController.php#L187

Also why did you make so many commits for this? Would have been good to squash these before merge...

**Comment by samdark** [comment]
Oh. Should be reverted then?

**Comment by qiangxue** [comment]
I think it should be reverted.

**Comment by creocoder** [comment]
@cebe, @qiangxue Why it should be reverted? Users who create application always have unstable Yii 2 installed. Releases does not affect anything when create project from composer. Also you can control stability from commant line only. Its absoluttely meaningless have it inside `composer.json`, not only meaningless, its huge disservice for users.

**Pull request merged**
