### PR TITLE
Fix #17123

### LINKED ISSUE #17123: ErrorException when run `./yii fixture/unload` without arguments
### What steps will reproduce the problem?

`$ ./yii fixture/unload`

### What is the expected result?

`$ ./yii fixture/unload`
Unloads the specified fixtures.
Use yii help fixture to get usage info.

### What do you get instead?

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 0'

in /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/controllers/FixtureController.php:194

Stack trace:
#0 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/controllers/FixtureController.php(194): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/ricardo/y...', 194, Array)
#1 [internal function]: yii\console\controllers\FixtureController->actionUnload(Array)
#2 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('unload', Array)
#5 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('unload', Array)
#6 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('fixture/unload', Array)
#7 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('fixture/unload', Array)
#8 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /home/ricardo/yiiaffinity/yii(21): yii\base\Application->run()
#10 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.1
| Operating system | Ubuntu 18.04.2 LTS

### PR DESCRIPTION
**Pull request by ricpelo**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #17123

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by GHopperMSK** [comment]
I don't like `exitWhenNoArguments` method. It doesn't terminate the program. Sometimes it prints help message, but it isn't obvious. I would like to have simple method `printHelpMessage()` and call it like that:
```
if ($fixturesInput === []) {
    $this->printHelpMessage();
    return ExitCode::OK;
}
```

**Comment by samdark** [comment]
@ricpelo would you please make adjustments as @GHopperMSK suggested?

**Comment by ricpelo** [comment]
@samdark Sure, I'll try it :+1: .

**Comment by ricpelo** [comment]
@GHopperMSK looks OK now?

**Comment by GHopperMSK** [comment]
> @GHopperMSK looks OK now?

Way better! I like it.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by ricpelo** [comment]
Thanks to you!

**Pull request merged**
