### PR TITLE
add isset check on index which might not be set

### PR DESCRIPTION
**Pull request by EliasZ**

### CODE REVIEW

**Comment by samdark** [comment]
How to reproduce the error you're fixing?

**Comment by cebe** [comment]
Can one of the admins verify this patch?

**Comment by EliasZ** [comment]
A colleague of mine got the error on a Windows 7 machine, upon inspecting the `$output` variable, it was consistently empty. I don't know the exact environment of his machine. A quick Google reveals a [similar issue].

**Comment by cebe** [comment]
check looks valid, it should not crash if no output is received.

**Comment by cebe** [comment]
Merged. Thanks!

**Comment by samdark** [comment]
Changelog?

**Comment by cebe** [comment]
not sure it is needed for such a small thing but I can add it if you insist

**Comment by samdark** [comment]
Worth adding, I think.

**Comment by cebe** [comment]
done.

**Pull request closed without merging**
