### PR TITLE
Fix #6642 [skip ci]

### LINKED ISSUE #6642: Confirm dialog on submit button is fired twice
I created a submit button using following markup:
```
Html::submitButton(
   Yii::t('admin-game', 'Delete'), 
   [
      'class' => 'btn',
      'data-confirm' => Yii::t('yii', 'Are you sure you want to delete selected items?'),
   ]
),
 ```

Now yii.js fires when I click the button and handleAction triggers the form submit again. If this is triggered the confirm popup will be also triggered.

yii.js line 173
```
$form.trigger('submit');
```

### PR DESCRIPTION
**Pull request by pana1990**
Fix #6642

### CODE REVIEW

**Comment by qiangxue** [comment]
This is a good one. A concern is that if `$form.submit()` fails, the hidden input will remain there and cause bad effect the next time the form is submitted.

**Comment by pana1990** [comment]
if first we try check hidden input exits, it can resolve concern,

for example, we can use the following : 

```js
if ($button.length && $button.prop('name')) {
     var hiddenSubmit = $('#button-submit');
     if (hiddenSubmit.length) {
             hiddenSubmit.attr('name', $button.prop('name'));
             hiddenSubmit.attr('value', $button.prop('value'));
    } else {
             $('<input>').attr({
                 type: 'hidden',
                 id: 'button-submit',
                 name: $button.prop('name'),
                 value: $button.prop('value'),
           }).appendTo($form);
      }
}

       $form.submit();
```
@qiangxue  What do you think ?

**Comment by qiangxue** [comment]
This is still problematic in the following case:

* You have two active forms on the same page.
* One form is submitted but failed. It will get the hidden input added.
* Submitting the other form now. The hidden field is not added to this form because it exists in the first form already.

**Comment by pana1990** [comment]
oh, it is truth, We use form's id for this case.

```js
if ($button.length && $button.prop('name')) {
     var hiddenSubmitId = $form.prop('id') + '#button-submit'; // id for hidden input
     var hiddenSubmit = $form.find(hiddenSubmitId);
     // check whether hidden input exists 
     if (hiddenSubmit.length) {
             hiddenSubmit.attr('name', $button.prop('name'));
             hiddenSubmit.attr('value', $button.prop('value'));
    } else {
             $('<input>').attr({
                 type: 'hidden',
                 id: 'button-submit',
                 name: $button.prop('name'),
                 value: $button.prop('value'),
           }).appendTo($form);
      }
}

$form.submit();
```

The problem is when the form have not id, if we use activeform it is not problem (it generate id automatic) but if development use static form without id it is problematic, i think that should be document this change.

**Comment by qiangxue** [comment]
Fixed in https://github.com/yiisoft/yii2/commit/3abc07d16cb4f877cdff9e24d97269345a6c8b44
Thanks!

**Pull request closed without merging**
