### PR TITLE
Update start-installation.md

### PR DESCRIPTION
**Pull request by matjack1**
Fix the horizontal overflow of the picture at this link: http://www.yiiframework.com/doc-2.0/guide-start-installation.html while preserving the visualisation in Github.

### CODE REVIEW

**Comment by samdark** [comment]
It's better to be done via website CSS.

**Comment by matjack1** [comment]
@samdark is that something I can help with? Is the repo/file public?

**Comment by samdark** [comment]
No, it's not public.

**Comment by cebe** [comment]
well, new site is not public, but current apidoc is using the css from bootstrap template. Adjusted it there: https://github.com/yiisoft/yii2-apidoc/compare/bed861930f544f19f9304d84c9b30e674abfadfd...6ed4f0b037754004479a4ae1b712b319c0ab9f9f

**Comment by matjack1** [comment]
cool, thanks @cebe

**Pull request closed without merging**
