### PR TITLE
Fix DbSession::writeSession race condition.

### PR DESCRIPTION
**Pull request by ddinchev**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13212

It has been previously reported #13212 There is a race condition in `DbSession::writeSession()`. 

```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kupbup8mepuaco3dr5qdretsde' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `YiiSession` (`data`, `id`, `expire`) VALUES ('__flash|a:0:{}', 'kupbup8mepuaco3dr5qdretsde', 1510386856)
```

After updating to `2.0.13`, I get around a dozen of those errors per day (I use MySQL 5.7), on a low traffic website that has less than a thousand visits a day. The session table has less than 1000 rows, the garbage collector is working correctly. I guess prior to `2.0.13` the errors were not exposed through the standard error logger - now this is fixed by #14908 

I'm not entirely sure why would the generated session id collide so often. My solution does the check if session id already exists in the storage in a transaction. Performance impact should be negligible as there should be only one session read/write per request.

### CODE REVIEW

**Comment by ddinchev** [comment]
Based on the DBMS, this might not prevent race conditions. However, I'm not sure if we can write it in DBMS-independent SQL. The mechanisms to lock tables are different in all databases and approaches like `INSERT .. ON DUPLICATE KEY UPDATE` are also DBMS-specific.

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/yii2/issues/13879

**Comment by rob006** [comment]
I'm afraid that this will not change anything. Opening transaction will not prevent other processes from reading this table -  you will still get:
1. Request A opens transaction and reads session table.
2. Request B opens transaction and reads session table.
3. Request A inserts new record to session table.
4. Request B waits till request A commit transaction and tries to save the same record again.

**Comment by ddinchev** [comment]
@rob006 you are correct, I realized that soon after opening the proposed MR. I'm a bit concerned however about that we actually hit this at all. The session id shouldn't collide so often.

**Comment by njasm** [comment]
this still is an issues, even if @ddinchev approach is not the solution, we should have this issue reopened and try to find a solution for it..

This issue concerns me since i'm finding it one or two time a day and still in development environment!

**Pull request closed without merging**
