### PR TITLE
yii\base\Application: fix mailer

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18955

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by rob006** [comment]
This will trigger autoloading even if mailer is never used.

**Comment by WinterSilence** [comment]
@rob006 yes, you can check it by `$extensions`, but it's not "pure" too

**Comment by samdark** [comment]
@My6UoT9 it was added before as well.

**Comment by My6UoT9** [comment]
Seems fine to me, if u try to use swiftmailer now, its not going to work either - without installing it first.
if any - add a good error msg, when trying to get the mail component, but its not installed.

**Comment by WinterSilence** [comment]
@My6UoT9 your idea - your implementation

**Comment by My6UoT9** [comment]
> @My6UoT9 your idea - your implementation

Yes, I am just stating I am not happy with that solution.

**Pull request merged**
