### PR TITLE
Update BlameableBehavior.php

### PR DESCRIPTION
**Pull request by oleh-ozimok**
Added ability to specify default user in BlameableBehavior

### CODE REVIEW

**Comment by cebe** [comment]
what is the use case for this?

**Comment by oleg-ozimok** [comment]
When the model changed by application (e.g. cron job) both attributes = null. By means of current property can be avoided of this (Sorry for my english).

**Comment by cebe** [comment]
why don't you use `$value` property for this?

**Comment by oleg-ozimok** [comment]
too much code

**Comment by cebe** [comment]
It is not more code:
```
'value' => function() { return 123; },
vs.
'defaultUserId' => 123,
```

**Comment by oleg-ozimok** [comment]
if ($this->value === null) {
  $user = Yii::$app->get('user', false);
  return $user && !$user->isGuest ? $user->id : null;
} else {
  
 // there is no verification of the user
 // ---------------------------------------------
          
  return call_user_func($this->value, $event);
}

**Pull request closed without merging**
