### PR TITLE
Added user-friendly error messages for NumberFormatter configuration

### PR DESCRIPTION
**Pull request by bizley**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18674

### CODE REVIEW

**Comment by bizley** [comment]
Oh, this requires more work apparently ;)

**Comment by bizley** [comment]
Fortunately only a small fix was needed.

**Review by samdark — APPROVED** [review]
Looks good. Need a changelog line.

**Comment by bizley** [comment]
Added.

**Comment by samdark** [comment]
Awesome! Merged.

**Pull request merged**
