### PR TITLE
18660 fix migration template not working

### PR DESCRIPTION
**Pull request by iridance**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #18660

### CODE REVIEW

**Comment by samdark** [comment]
Seems my edit broke the changelog :)

**Comment by bizley** [comment]
This doesn't parse properly strings like `\a` -> `\a` instead of `a`.

**Comment by iridance** [comment]
> This doesn't parse properly strings like `\a` -> `\a` instead of `a`.

I don't understand what you mean
it should be a feature in yii2(? 
can you give me some examples?

**Comment by bizley** [comment]
Previously when you provided name as `\migrationName` it would be `migrationName` - now it's still `\migrationName`.

**Comment by iridance** [comment]
my console.php setting
```php
'controllerMap'       => [
        'migrate' => [
            'class'               => yii\console\controllers\MigrateController::class,
            'migrationTable'      => '{{%migration}}',
            'migrationPath'       => null, // disable non-namespaced migrations if app\migrations is listed below
            'migrationNamespaces' => [
                'app\migrations',
            ],
        ],
    ],
]
```
image

No similar problems in my environment.
`os:ubuntu 18.04.5; php:7.4.23; yii2:2.0.43`

**Comment by bizley** [comment]
Yes, for simple thing like `\migrateName`, but what about for example `\createTestTable`? Does it use proper template then?

**Comment by iridance** [comment]
image

yes, in your case , we can generate proper template code.

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
