### PR TITLE
Fix #20191

### LINKED ISSUE #20191: ActiveRecord::getDirtyAttributes() not working for JSON columns with multi-dimensional arrays
### What steps will reproduce the problem?

1. Create a DB table with a JSON column, and an ActiveRecord class for it.
2. Create a row and set the JSON column to the value:
   ```json
   {"foo": ["c", "b", "a"]}
   ```
3. Run the following code:
   ```php
   $record = MyActiveRecord::findOne();
   $record->jsonColumnName = [
       'foo' => ['b', 'c', 'a'],
   ];
   $record->save();

### What is the expected result?

The new value will save.

### What do you get instead?

The new value isn’t saved, because `ActiveRecord::isValueDifferent()` will return `false` for `jsonColumnName`.

This happens because `isValueDifferent()` normalizes each value with `ArrayHelper::recursiveSort()`, which sorts the array and all nested arrays using either `sort()` (if indexed) or `ksort` (if associative).

The intent seems to be to only do this for associative arrays, which probably makes sense since the order of values is generally not important for associative arrays. But it should definitely not be happening for non-associative arrays.

https://github.com/yiisoft/yii2/blob/d9d168b036158ba2b3f139bf5155c0bb4b093d20/framework/db/BaseActiveRecord.php#L1784-L1787

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45, 2.0.50
| PHP version      | n/a
| Operating system | n/a

### PR DESCRIPTION
**Pull request by brandonkelly**
Fixes #20191 by only sorting associative arrays when comparing old/new array column values, recursively.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #20191

### CODE REVIEW

**Review by terabytesoftw — APPROVED** [review]

**Comment by samdark** [comment]
@brandonkelly would you please add a line for CHANGELOG? Thanks.

**Review by bizley — APPROVED** [review]

**Comment by schmunk42** [comment]
Don't we need a test for this?

**Comment by brandonkelly** [comment]
@samdark Release note added.

@schmunk42 Test case added. Confirmed it fails on `master` and passes with my fix in place.

**Review by Arhell — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
