### PR TITLE
Fixes #16028: valid serialization of complex cache keys that contain non-UTF sequences

### LINKED ISSUE #16028: \yii\caching\Cache::buildKey can generate identical cache keys for different $key attribute
So method is written like this:

    public function buildKey($key)
    {
        if (is_string($key)) {
            $key = ctype_alnum($key) && StringHelper::byteLength($key) <= 32 ? $key : md5($key);
        } else {
            $key = md5(json_encode($key));
        }

        return $this->keyPrefix . $key;
    }

The problem is in passing `json_encode` output directly to `md5` function.
It can return `false` in case of error. In my case it was an SQL query with special symbols, key generated from Yii2 components itself, when i used query caching. So it returned the same md5 key and caused multiple errors (same result for different queries)

Maybe it is better to throw an exception if output of `json_encode` is `false` in this case?
And i guess i need to create another ticket for `\yii\db\Command::queryInternal`?

### PR DESCRIPTION
**Pull request by rugabarbo**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16028

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by tyler-ham** [comment]
I am (slightly) of the opinion that this should have been considered potentially BC breaking, though I can understand how the potential impact was deemed to be small enough not to rise to the level of "breaking".

Changing the serialization of keys causes the new keys to no longer match entries that already exist in the cache. In terms of `get` operations, it is as if much of the cache was flushed. However, the old entries remain as orphans in the cache store until the whole cache is flushed (or the entries are evicted if the entries have expirations and the cache store supports automatic eviction).

I will work around it by implementing a `Cache` subclass to maintain the original key serialization algorithm or migrate entries to the new algorithm over time.

Perhaps key serialization should be configurable the way value serialization/deserialization is? Then developers could choose whichever method performs best for their use case (and could easily replace the default algorithm without having to write one or more Cache subclasses).

**Comment by rugabarbo** [comment]
@tyler-hav, I do not understand what the problem is. Why you need to maintain the original key serialization? What exactly has stopped working correctly in your application?

**Comment by tyler-ham** [comment]
Maintaining support for the original key serialization is a temporary solution to allow the keys to change slowly over time to avoid a sudden performance degradation due to a cold cache. To be clear, I don't believe that is something that should be implemented in the framework. The main reason for my comment is to document my experience with this change in case anyone else comes across it and is looking for a workaround to avoid essentially flushing most of the cache all at once in a production system after installing an updated Yii framework.

Secondarily, while it may not rise to the level of breaking backward-compatibility (as it does not change any function signatures, names, etc.), I would suggest making a note of changes like this that could have an impact on performance or resource usage, even if only temporarily, in the `UPGRADE.md` documentation.

**Comment by samdark** [comment]
@tyler-ham noted for Yii 3.

**Pull request merged**
