### PR TITLE
Xml element attributes feature

### PR DESCRIPTION
**Pull request by codespede**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

This will allow having attributes for xml elements generated from yii\web\XmlResponseFormatter.

For having attributes for an XML element, one has to return an array as the value of that element in the following format:

`[
	'value' => 'value for that element',
	'xml-attributes' => [
		'attribute-1' => 'value-1',
		'attribute-2' => 'value-2',
		...
		...
	]
]`

For example, if the element returned is 'city', and it needs two attributes 'type' and 'population', the return value for the attribute 'city' should be like:
`

    return [
          'value' => 'New York',
          'xml-attributes' => [
                  'type' => 'Metropolitan',
                  'population' => '10000000'
          ]
    ]
`

In the above example, the xml element generated will be like this:
`<city type="metropolitan" population="10000000">New York</city>`

### CODE REVIEW

**Comment by samdark** [comment]
Can't be merged into master. Please rebase for 2.0 branch.

**Comment by samdark** [comment]
Yes.

**Comment by codespede** [comment]
Sorry, shall reopen this in a new pull request because of some conflicts.

**Comment by codespede** [comment]
Hi @samdark, this is created as a new pull request https://github.com/yiisoft/yii2/pull/16285 here

Please review.

**Pull request closed without merging**
