### PR TITLE
fixes fatal error when authManager is not yet defined

### PR DESCRIPTION
**Pull request by dynasource**
#9317

### CODE REVIEW

**Comment by cebe** [comment]
if we do this, we should do it inside of `getAuthManager()` but I am not sure it is really needed.

**Comment by dynasource** [comment]
its a choice. Either catch a fatal error or not.

**Comment by creocoder** [comment]
Suggest to fix different way by default config to `access manager` component.

**Comment by dynasource** [comment]
good suggestion

should I update this commit to fix this in https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L591

Currently:
```php
    public function getAuthManager()
    {
        return $this->get('authManager', false);
    }
```

To:
```php
    public function getAuthManager()
    {
        return $this->get('authManager');
    }
```

**Comment by creocoder** [comment]
@dynasource https://github.com/yiisoft/yii2/pull/9368 (fix for asset manager and cache component)

**Pull request closed without merging**
