### PR TITLE
Fix documentation of DbMessageSource.

### PR DESCRIPTION
**Pull request by nkovacs**
Setting cachingDuration to 0 doesn't disable caching,
enableCaching controls that.

[ci skip]

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by nkovacs** [comment]
But setting cachingDuration to 0 does not disable caching.

**Comment by cebe** [comment]
@samdark PR is correct, cachingDuration=0 does not disable, it will cause the cache to never expire.

**Comment by samdark** [comment]
There's not a single word about anything being disabled:

> The messages data will be cached using this cache object. Note, this property has meaning only
> in case [[cachingDuration]] set to non-zero value and [[enableCaching]] is true.

**Comment by nkovacs** [comment]
why would the property not have meaning if cachingDuration is set to zero? The cache is still used, but cached data never expires.

**Comment by cebe** [comment]
fixed by rewording the comment.

**Comment by samdark** [comment]
:+1:

**Pull request closed without merging**
