### PR TITLE
fix: CheckboxColumn: check-all checkbox must be checked on page load …

### PR DESCRIPTION
**Pull request by AndreyPootMay**
credits to @PowerGamer1

Hacktoberfest PR.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | check-all checkbox must be checked on page load if all row checkboxes are checked #18867

### CODE REVIEW

**Comment by samdark** [comment]
Nice one! Thanks!

A bit too early to be counted for Hacktoberfest though.

**Review by samdark — APPROVED** [review]

**Review by bizley — APPROVED** [review]

**Review by machour — APPROVED** [review]

**Comment by PowerGamer1** [comment]
@AndreyPootMay Sorry for nitpicking but in the `tests/js/tests/yii.gridView.test.js` the code of the tests was modified to expect new number of calls but the nearby comments still mention old numbers from before.

**Review by Arhell — APPROVED** [review]

**Comment by AndreyPootMay** [comment]
> @AndreyPootMay Sorry for nitpicking but in the `tests/js/tests/yii.gridView.test.js` the code of the tests was modified to expect new number of calls but the nearby comments still mention old numbers from before.

I can check and fix it.

**Comment by PowerGamer1** [comment]
Now comments don't make sense at all:
```PHP
// Check all rows ("prop" should be called 6 times, 1 time for each row)
...
// Check all rows ("prop" should be called 5 times, 1 time for each row)
```
None of the GridView test tables have that many data rows to begin with (see `tests\js\data\yii.gridView.html`).
Obviously, the call count *per row* has increased, and it is unclear to me why.

**Comment by samdark** [comment]
Won't merge until @PowerGamer1 is clarified.

**Pull request closed without merging**
