### PR TITLE
Several classes should be abstract

### PR DESCRIPTION
**Pull request by creocoder**

### CODE REVIEW

**Comment by qiangxue** [comment]
Why?

**Comment by lynicidn** [comment]
Object 100% not abstract @see rbac\Items

**Comment by creocoder** [comment]
@qiangxue 

From OOP theory

> If a class is abstract and cannot be instantiated, the class does not have much use unless it is subclass. This is typically how abstract classes come about during the design phase. A parent class contains the common functionality of a collection of child classes, but the parent class itself is too abstract to be used on its own.

Lets think. Does `Object`, `Component`, `Widget`, `InputWidget` instantination make sence? I'm sure there is no use cases for that. I'm still not sure it full list of classes which should be marked to be abstract.

**Comment by creocoder** [comment]
@qiangxue By marking class abstract we just show that its designed to be extended. Its not necessary to have any abstact methods inside it to mark class abstract. Its not rule. There is rule that classes should be marked as abstract if it contains abstract methods. On other side class can be abstract without anstract methods inside it. I think that main role of abstraction is to show that it born to be extended and its meaningless to instantiate that. Example of another class which should be abstract is base controller. Its designed to be extended.

Currently we just have inconsistency with that. Some classes designed to be extended like `yii\caching\Cache` marked as abstact and some others not.

**Comment by qiangxue** [comment]
Please do not call this as OOP theory. This is abstracted from some Java tutorial. There's never such a requirement in OOP theory.

There's a good discussion here: http://programmers.stackexchange.com/questions/96947/why-should-i-declare-a-class-as-an-abstract-class

IMO, we should keep the rule simple rather than vague: A class should be declared abstract (and of course) only if it contains abstract methods. 

I know you can argue it's useless or impractical to instantiate `Object` or `Component` and they should be declared abstract. But there's really no practical benefit of doing so, and it would trap us into endless debate about whether or not a class should be abstract.

FYI, `Cache` is abstract because it doesn't implement all required interface methods. We are very consistent about using `abstract` so far.

**Comment by qiangxue** [comment]
`Object` and `Component` may sound easy that they should not be instantiated. Other classes may not be this easy to identify whether they should be abstract or not. In fact, even for `Object` I have a valid use case for it to be instantiated: I once wrote a benchmark to see how much memory `Object` would take and I need to instantiate it many times.

**Comment by creocoder** [comment]
> Please do not call this as OOP theory. This is abstracted from some Java tutorial. There's never such a requirement in OOP theory.

Its true and you can cleanly see that in that tutorial class marked as abstract and does not contain any abstact methods. Also i'm sure inheritance chain like:

```
interface => non abstact => non abstact => abstract => non abstact
```

Is wrong from OO design point of view. But we have such situation many times inside core. Mark classes as abstract prevend coders from instantiating that. So its second role is just defence.

The similar situation with finalizing classes. Many classes can be declared as final. I know in other conversation you talk about that its rare case, but its not... PHP world go to right OOP design. For example you can check `Imagine` library:

https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/Box.php

Lot of classes finalized. I'm pretty sure we need to show inside Guide examples when concrette application controllers finalized. Because its always meaningless to extends controllers. User can do that, but in 100% cases it would be wrong OO design decision. So `final` and `abstraction` is just prevent coders from bad decisions. More about finalizing classes. For example all `yii\caching\*` concrette implementation can be easily marked as `final`.

Why i think its **practical and important**. Several times i meet inside real Yii 1 application inheritance chain like:

```
User extends BaseUser {}
BaseUser extends PLoggingActiveRecord {}
PLoggingActiveRecord extends PActiveRecord {}
PActiveRecord extends CActiveRecord {}
```

No joke! It was even longer. And finally i want to show brilliant explaination why finalizing is so important: http://ocramius.github.io/blog/when-to-declare-classes-final/

**Comment by qiangxue** [comment]
> Mark classes as abstract prevend coders from instantiating that.

Why do you want to do that if instantiating the class is not harmful, like in the example of `Object`? `Object` by itself is a complete class, not missing functionalities.

> For example all yii\caching\* concrette implementation can be easily marked as final.

This is definitely wrong. What if as a user I want to customize some of the implementations of a concrete cache class? For example, I want to override `DbCache::getValues()` to make it better.

If you read the comments of your mentioned article about "final", you may find most people do not quite agree with the author.

**Comment by creocoder** [comment]
> What if as a user I want to customize some of the implementations of a concrete cache class? For example, I want to override DbCache::getValues() to make it better.

User can use composition.

> If you read the comments of your mentioned article about "final", you may find most people do not quite agree with the author.

Author is well known and have great reputation. Also all disagree users posts was answered with strong points. But OK, finalizing classes require ideal OOP design in background, right DI usage, avoid usage OO design antipatterns, etc. We can not afford it now. But backing to `abstract` proposal. I read link you gave and found:

```
Abstract class
- ...
- Inheritance child can have only one base abstract class
```

So my assumptions about inheritance chain like:

```
interface => abstact => non abstact => abstract => non abstract
```

is correct. Right? It possible inside php, but its wrong from design point of view.

> IMO, we should keep the rule simple rather than vague: A class should be declared abstract (and of course) only if it contains abstract methods.

I do not think that thinking that way is absoluttely correct. Abstract method necessity is just aspect which force you to mark class as abstract. While real decision about abstraction should be maden from other points.

P.S. But OK, i think its too early to make such radical PRs )

**Pull request closed without merging**
