### PR TITLE
Add parentItemOptions

### PR DESCRIPTION
**Pull request by strelov1**
Often it is necessary to extend the class for this property

### CODE REVIEW

**Comment by klimov-paul** [comment]
What is a use case for this?

**Comment by strelov1** [comment]
https://toster.ru/q/264067

**Comment by klimov-paul** [comment]
```php
Menu::widget([
    'items' => [
        [
            'label' => 'Parent Menu',
            'items' => [],
            'options' => [
                'class' => 'parent-li' // applies only to this menu item
            ],
        ],
    ],
    'itemOptions' => [
        'class' => 'all-li', // applies to all menu items
    ],
]);
```

**Comment by strelov1** [comment]
Yes, you can add to the array on the fly the desired properties, but it seemed to me that it's easier
```html
<ul class="parent_ul">
	<li class="left-arrow"><a href="/parent/1">Parent Menu 1</a>
	<ul class="dropdown-menu">
		<li><a href="/sub_menu/1">Sub Menu 1</a></li>
		<li><a href="/sub_menu/2">Sub Menu 2</a></li>
		<li><a href="/sub_menu/3">Sub Menu 3</a></li>
	</ul>
	<li class="left-arrow"><a href="/parent/2">Parent Menu 2</a>
	<ul class="dropdown-menu">
		<li><a href="/sub_menu/1">Sub Menu 1</a></li>
		<li><a href="/sub_menu/2">Sub Menu 2</a></li>
		<li><a href="/sub_menu/3">Sub Menu 3</a></li>
	</ul>
	<li><a href="/parent/3">Parent Menu without sub-menu</a>
	<li><a href="/parent/4">Parent Menu without sub-menu</a>
</ul>
```

**Pull request closed without merging**
