### PR TITLE
Do not replace URL started with # using yii asset

### PR DESCRIPTION
**Pull request by vitalyzhakov**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

Using CSS file with rule
```
clip-path: url('#xxx')
```

yii asset command append path to this url, but it is not correct.

### CODE REVIEW

**Comment by SilverFire** [comment]
According to our  [roadmap](https://github.com/yiisoft/yii2/wiki/Plan-for-next-major-versions), we are willing to drop `AssetCompressor` in our closest major release (v. 2.1), therefore we suggest not to use it for your projects.

@yiisoft/core-developers should we accept this PR?

**Comment by dynasource** [comment]
That AssetController is actually quite useful to me. I would not see it dropped in 2.1. If it is dropped in 2.1, I still would like to use it as an extension. Regarding this, adopting PR's and/or fixes is still useful.

One can ask, why arent you using a Gulp pipeline instead? Well, I have a fully stacked gulp pipeline, but I am dependant on Yii2 for the Assets processing.

**Comment by samdark** [comment]
Well, we're not going to drop it... maybe move it out of the core.

**Review by samdark — CHANGES_REQUESTED** [review]
Change itself looks good. Need a line for changelog at least. Ideally — tests.

**Comment by klimov-paul** [comment]
Resolved by commit 18b0dab360bcbcd41a7bd152ac6c66844746242f

**Pull request closed without merging**
