### PR TITLE
Bug #8225: Fixed ajax Validation with checkboxList only on first select

### PR DESCRIPTION
**Pull request by execut**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #8225

### CODE REVIEW

**Comment by execut** [comment]
I tried to write a test, but I didn’t have enough jsunit testing experience. It is interesting to see how it should be implemented. I also did not find tests for the method, just to add it for this bug

**Review by arzzen — APPROVED** [review]

**Comment by samdark** [comment]
@execut so how about tests?

**Comment by execut** [comment]
> @execut so how about tests?
I will try this week

**Comment by execut** [comment]
> @execut so how about tests?

Done. Is everything right?

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
@execut looks fine to me.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
