### PR TITLE
Rearrange code

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Review by SilverFire — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thought that it could be optimization about unsetting multiple variables at once but it seems opcodes generated are the same.

**Review by cebe — APPROVED** [review]
needs a CHANGELOG.

**Comment by Lanrik** [comment]
I dont know what write in changelog  ¯\_(ツ)_/¯

**Comment by cebe** [comment]
```
Enh #13550: Refactored unset call order in `yii\di\ServiceLocator::set()` (Lanrik)
```

**Comment by dynasource** [comment]
IMO, these kind of changes (rearranges, refactoring etc) don't need a changelog unless its useful information

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
