### PR TITLE
Fix comparison in `BaseHtml::renderSelectOptions()`

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #19522

### CODE REVIEW

**Comment by samdark** [comment]
Would you please add a line for CHANGELOG?

**Review by bizley — APPROVED** [review]

**Comment by bizley** [comment]
Some tests maybe are to be updated?

**Comment by samdark** [comment]
Fails in 5.4: https://github.com/yiisoft/yii2/runs/8056613656?check_suite_focus=true#step:11:153

**Review by Arhell — APPROVED** [review]

**Comment by bizley** [comment]
Why is this closed?

**Pull request closed without merging**
