### PR TITLE
FileMutex: unlink(...): No such file or directory #12860

### PR DESCRIPTION
**Pull request by schojniak**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | no |
| Fixed issues | #12860 |

### CODE REVIEW

**Comment by cebe** [comment]
looks good to me in general, is it possible to write a test case for this?

**Comment by SilverFire** [comment]
I've tried to cover this fix with a test, but I failed.

```php
public function testDeleteLockConcurrency()
{
    $mutex = $this->createMutex();
    $concurrentMutex = $this->createMutex();

    $name = self::$mutexName;
    $fileName = $this->invokeMethod($mutex, 'getLockFilePath', [$name]);

    // Acquire lock
    $mutex->acquire($name);
    $this->assertFileExists($fileName);

    // Reproducing step-by-step the `release()` method and
    // make sure that new lock can not be acquired until all steps are finished
    $files = $this->getInaccessibleProperty($mutex, '_files');

    $this->assertFalse($concurrentMutex->acquire($name));

    // Step 1
    $this->assertTrue(flock($files[$name], LOCK_UN));
    $this->assertFalse($concurrentMutex->acquire($name));

    // Step 2
    $this->assertTrue(unlink($fileName));
    $this->assertFalse($concurrentMutex->acquire($name));

    // Step 3
    $this->assertTrue(fclose($files[$name]));
    $this->assertTrue($concurrentMutex->acquire($name));

    $this->assertTrue($concurrentMutex->release($name));
    $this->assertFileNotExists($fileName);
}
```

This test fails. The most interesting thing is that `$concurrentMutex->acquire($name)` will success after any of steps 1-3, the order is not important.

I do not know we can solve this probable race condition

**Comment by SilverFire** [comment]
Btw, anybody knows why do we remove the file after lock is released?

**Comment by SilverFire** [comment]
[NinjaMutex](https://github.com/arvenil/ninja-mutex/blob/master/src/Lock/FlockLock.php) does not remove the file, for example

**Comment by kidol** [comment]
Symfony doesn't remove it either. But it's simply the ideal behavior to get rid of the log file if possible, isn't it?

Please take a look for possible solution: https://github.com/yiisoft/yii2/issues/12860#issuecomment-256901532

Alternative is to just keep the log file...

**Comment by SilverFire** [comment]
Possible solution does not work

**Comment by SilverFire** [comment]
> But it's simply the ideal behavior to get rid of the log file if possible, isn't it?

You've meant "lock" instead of "log", right?

Actually, not always. Sometimes we need to create a lock file outside of the web project dir to share lock with other (even non-PHP) processes. In this case I put lock somewhere in `/tmp/locks/geedyProcesses.lock`. The `/tmp/locks` directory itself is not writable for `www-data`, but the lock files could have `chmod 666` and be writable. 

So I don't think we should delete lock file

**Comment by kidol** [comment]
Yes lock 😆 

>Possible solution does not work

Why?

In your use case you could set `$autoRelease` to `false` for given mutex component.

**Comment by rob006** [comment]
> Btw, does anybody know why do we remove the file after lock is released?

To avoid leaving hundreds of thousands of old lock files. But this could be solved by garbage collector (could be disabled by default).

**Comment by SilverFire** [comment]
> To avoid leaving hundreds of thousands of old lock files

Disagreed. Lock files are not generated randomly, because they are based on name given by the developer. It means that the count of files will be equal the maximum count of unique lock names in your code.

```php
$mutex->acquireLock('billingCalculation');
```

It does not make any sense to acquire locks with random name, because it will not end up in locking something.

**Comment by kidol** [comment]
>Lock files are not generated randomly

But dynamically based on some id for example.

**Comment by rob006** [comment]
Lock name could be generated. For example it could contain ID of record from database - having table with 1kk records is not a big deal for DBMS, having 1kk useless files in single directory is serious problem fore most of the filesystems. I already use mutex for generating thumbnails for images (to avoid doing the same job multiple times) - one unique ID is used only once for 1-5 seconds and never reused (because I already have a thumbnail). End up with 20k old lock files after 2 weeks.

**Comment by SilverFire** [comment]
Yes, makes sense.

Atomicity is one of the most important things in MUTEX. We have the situation when lock releasing is not atomic - there is a micro-time gap between lock releasing and file deletion.

Another interesting thing is that according to the [`flock()` CHANGELOG on PHP.net](http://php.net/manual/en/function.flock.php), since PHP 5.3.2 - "The automatic unlocking when the file's resource handle is closed was removed. Unlocking now always has to be done manually". So `fopen(); flock(); fclose();` should not release lock... Need to check it once more.

> I already use mutex for generating thumbnails for images (to avoid doing the same job multiple times) - one unique ID is used only once for 1-5 seconds and never reused (because I already have a thumbnail). End up with 20k old lock files after 2 weeks.

Wow, that's cool. Good that files are empty :D

**Comment by cebe** [comment]
> Good that files are empty :D

that does not help, you can not enter that directory. You can not run ls or rm on it :)
https://twitter.com/cebe_cc/status/783762785171861509

**Comment by SilverFire** [comment]
Closing in favor https://github.com/yiisoft/yii2/pull/13258

**Pull request closed without merging**
