### PR TITLE
Add new event  \yii\base\Model::EVENT_AFTER_CREATE_VALIDATORS

### PR DESCRIPTION
**Pull request by lav45**

### CODE REVIEW

**Comment by klimov-paul** [comment]
What is the sense of it?
Looks useless at the first glance.

**Comment by LAV45** [comment]
This event will give the opportunity for the Behavior to add your own validators to the moment when they are initialized in the owner class.

**Comment by klimov-paul** [comment]
And what is the benefit? We already have 'beforeValidate'.

**Comment by fernandezekiel** [comment]
if that's the case then yes, why not just use beforeValidate() ?

**Pull request closed without merging**
