### PR TITLE
10869 query hint index

### PR DESCRIPTION
**Pull request by fdezmc**
Code and unit tests for query hint index #10869

### CODE REVIEW

**Comment by samdark** [comment]
Tests seem to error: https://travis-ci.org/yiisoft/yii2/jobs/109650849

**Comment by cebe** [comment]
Thank you for your contribution. The code looks good and also the documentation you added.
But as I wrote in the issue https://github.com/yiisoft/yii2/issues/10869#issuecomment-184856367 this is already possible with the existing API and I prefer to not add further methods if they add further abstraction.

**Comment by nsanden** [comment]
seems this would do what i need

@cebe - can you reconsider merging this in light of the fact that your comment in #10869 only works for basic queries, not joins?

**Comment by nsanden** [comment]
Workaround for this - use innerjoin and leftjoin instead of innerjoinwith and leftjoinwith. its not DRY but it works - mostly

**Pull request closed without merging**
