### PR TITLE
Adding support for custom rule in EachValidator

### PR DESCRIPTION
**Pull request by bizley**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | should
| Fixed issues  | #18051 

This changes a bit how the InlineValidator is created in case of model-method-based inline validators. Instead of just passing a method's name now there is an array with an instance of Model in question and the method's name. This works thanks to the fact that `call_user_func` can take such array as first parameter so there should be no BC change.

Since EachValidator creates a new instance of DynamicModel internally this change allows inline validators defined in the original model to be used.

I haven't checked all possible drawbacks here. Definitely now method that is inline validator cannot have limited visibility but I haven't checked if it could be the case before this change.

Please take a look and see if this can be the solution to the issue. If so, I will add changelog.

### CODE REVIEW

**Comment by samdark** [comment]
> I haven't checked all possible drawbacks here. Definitely now method that is inline validator cannot have limited visibility but I haven't checked if it could be the case before this change.

I think it was allowed before.

**Comment by bizley** [comment]
As I can see the validator is doing the same thing when `$type` is just a string - it uses `[$model, $type]` for `call_user_func` but then the $model is the original one. So I think limited visibility methods were no good previously as well.

**Comment by SilverFire** [comment]
Hm, I also thought it always worked

**Review by SilverFire — APPROVED** [review]

**Review by samdark — APPROVED** [review]
👍 Please add a line for CHANGELOG.md.

**Comment by bizley** [comment]
Added :heavy_check_mark:

**Comment by samdark** [comment]
👍

**Pull request merged**
