### PR TITLE
Update runtime-routing.md

### PR DESCRIPTION
**Pull request by zmilan**
Clean 's' character from example of url route

### CODE REVIEW

**Comment by cebe** [comment]
why?

**Comment by zmilan** [comment]
it is typo. 
'<controller:(post|comment)>s' => '<controller>/index'
If I'm right this 's' on end of rule is totally not needed and will make this rule not useful in application.

**Comment by cebe** [comment]
it is not a typo, the resulting urls are as follows:
```
/posts => list of posts
/post/1 => show post no.1
/comments => list of comments
/comment/1 => show comment no.1
```

**Comment by zmilan** [comment]
Ok sorry, I not catch this part with comments, so it was looks like type.

**Comment by cebe** [comment]
no problem :)

**Pull request closed without merging**
