### PR TITLE
Fix submit form (#15791)

### PR DESCRIPTION
**Pull request by s1lver**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #15791

Simple bug fix

### CODE REVIEW

**Comment by samdark** [comment]
Why waiting? Can't you do it as well?

**Comment by s1lver** [comment]
Ok I'll add.
I was confused by the fact that there are tests for yii.js, but they were not started at the commit.

**Comment by s1lver** [comment]
I tested this change. Need another option (

**Comment by rustamwin** [comment]
How about checking with `hasOwnProperty`

**Pull request closed without merging**
