### PR TITLE
Added `updateMessages()` to `yii.activeForm.js` to support manually upda...

### LINKED ISSUE #5991: Ability to manually update ActiveForm error messages on client-side
I am facing problem regarding manually adding error msgs to form. In my case I don't have any problem with ajax validation. I have two scenarios in rules. one is 'default' and one is 'login' like this

```php
public function rules() {
    return [
      // email and password are both required
      [['email', 'password' ], 'required' ],
      ['email', 'email' ],
      // email is validated by validateEmail()
      ['email', 'validateEmail', 'on' => 'login' ],
      // password is validated by validatePassword()
      ['password', 'validatePassword', 'on' => 'login' ],
    ];
  }

```
I am using default scenario for ajax validation on blur and change and it is being handled fine with ajax validation. The problem is with 'login' scenario, I want to validate using 'login' scenario only when user clicks on submit button. To achieve this I attached 'beforeSubmit' event like this

```javascript

$('body').on('beforeSubmit', 'form#loginForm', function() {
    var form = $(this);
    if (form.find('.has-error').length) {
      return false;
    }

    $.ajax({
      url: form.attr('action'),
      type: 'post',
      data: form.serialize(),
      success: function(errors) {
        // How to update form with error messages?
      }
    });

    return false;
  });

```

Now above event is working fine and it sends the ajax request to server when user clicks on submit button and I validate the fields with 'login' scenario and return the errors in json if there are any otherwise redirect the user to some other page. 

Now the problem is if I get validation errors in return at this point I can not show those errors in form to user using ```yii.activeForm.js```, because [updateInputs] (https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L474) is not accessible publicly. Or is there another way to update the form error messages manually?

And the reason I have this 'login' scenario is because I want to validate email and password together in database only when user clicks on submit button.

### PR DESCRIPTION
**Pull request by nkovacs**
...ting ActiveForm messages.

Fixes #5991, #5420, #3017

### CODE REVIEW

**Comment by TimNZ** [comment]
Please get this into 2.0.6, I'm maintaining a fork solely for updateMessages()

**Comment by samdark** [comment]
@nkovacs conflicts...

**Comment by samdark** [comment]
Would be cool to have it. @nkovacs do you have time to resolve conflicts?

**Comment by nkovacs** [comment]
Yes, I'm going to look at it now, I just need to fix a BC break caused by the change in AssetManager::hash in my extension. When do you plan to release 2.0.6?

**Comment by samdark** [comment]
BC break? It should be compatible...

**Comment by samdark** [comment]
The plan is to do it early next week.

**Comment by samdark** [comment]
@nkovacs btw., which kind of break?

**Comment by nkovacs** [comment]
I'll comment on the other issue.

**Comment by nkovacs** [comment]
Rebased, and I also removed the this.cancelled check.
Haven't tested it yet.

**Comment by nkovacs** [comment]
Seems to work, you can use the basic template's contact form to test it:

```
$('form').yiiActiveForm('updateMessages', {"contactform-name":["Name cannot be blank."],"contactform-email":["Email cannot be blank."],"contactform-subject":["Subject cannot be blank."],"contactform-body":["Body cannot be blank."],"contactform-verifycode":["The verification code is incorrect."]})
```

**Comment by nkovacs** [comment]
Done. You can now do this: 

```
$('form').yiiActiveForm('updateAttribute', "contactform-email", ["Email cannot be blank."])
```

and the other attributes will not be affected.

**Comment by samdark** [comment]
Merged: https://github.com/yiisoft/yii2/commit/11de09bf8b5b2186d75f8cddfb530f4511674f5d

**Comment by samdark** [comment]
Thanks!

**Comment by nkovacs** [comment]
Thanks.
One thing's been bothering me, I'm not sure these are the best method names (especially for updateAttribute, which is probably unclear), do you have any suggestions?

**Comment by samdark** [comment]
Nope. These are fine to me.

**Comment by nkovacs** [comment]
The example in the [release announcement](http://www.yiiframework.com/news/88/yii-2-0-6-is-released/) is incorrect, the summary parameter is just a boolean, not a string (the example works because string is also truthy, but it's misleading).

**Comment by samdark** [comment]
Fixed.

**Comment by nkovacs** [comment]
Thanks.

**Pull request closed without merging**
