### PR TITLE
Error message grammar fix

### PR DESCRIPTION
**Pull request by creocoder**

### CODE REVIEW

**Comment by qiangxue** [comment]
The original syntax is correct.

**Comment by creocoder** [comment]
Proposed systax is also correct and consisitent with `must not be equal to` error message.

**Comment by samdark** [comment]
I think it's OK as is.

**Comment by qiangxue** [comment]
I don't think consistency matters here. There's slight tone difference between `must be no` and `must not be`. The latter feels much stronger.

**Comment by creocoder** [comment]
Ok, thanks for explaination.

**Pull request closed without merging**
