### PR TITLE
Added `not` parameter to the `yii\validators\RequiredValidator`

### PR DESCRIPTION
**Pull request by developeruz**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15391

I am not sure about naming because "not required" doesn't mean "prohibited". Also, I need some help with client-side validation.

### CODE REVIEW

**Comment by developeruz** [comment]
I've added client-side validation and JS test

**Review by samdark — APPROVED** [review]

**Comment by rob006** [comment]
How does it differ from `CompareValidator`?

**Comment by developeruz** [comment]
@rob006, as I know, there is no way to compare with null, so it impossible check on empty or not empty value with `CompareValidator`

**Comment by rob006** [comment]
@developeruz You can always compare to empty string. 

Anyway, using `RequireValidator` for prohibiting some values is really confusing. :/

**Comment by samdark** [comment]
Hmm... yes, it actually is confusing semantically. @developeruz are you OK with closing the pull request and the issue as "won't fix"?

**Comment by developeruz** [comment]
Yes, sure

**Pull request closed without merging**
