### PR TITLE
Add PHPDoc for properties "request" and "response" in controllers

### PR DESCRIPTION
**Pull request by vjik**
Add PHPDoc for `request` and `response` in web and console controllers for better auto-completion in IDE.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
No need for it. It's done automatically each release.

**Comment by vjik** [comment]
Hm... in IDE for web and console controllers for auto-complete use base response and request, but should be web and console response and request. Now it's not work.

**Comment by samdark** [comment]
OK. Let's have it but I guess it will be overwritten by doc generator anyway...

**Comment by rob006** [comment]
Why `@property-read`? These are regular properties, you can write to them.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/835971c6f64d344f68535d5f2e4a87e8e4e13a14

**Pull request merged**
