### PR TITLE
don't convert int to string if db type of column is numeric

### PR DESCRIPTION
**Pull request by egorrishe**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #14663

### CODE REVIEW

**Comment by egorrishe** [comment]
Here we see that check [ci-mssql / PHP 8.0-mssql-server:2017-latest (pull_request)](https://github.com/yiisoft/yii2/pull/18741/checks?check_run_id=2976562952) failed.
But if you open it's report, you will see that crash occurred on the 2nd step _"Initialize containers"_ > `Starting mssql service container` > `error pulling image configuration`.
I.e. this fail is not related to my PR.

Even more. In the bottom of issue #14663 you can find, that my last commit have already passed successfully exactly this check (as well as all 24 checks) - [screenshot](https://prnt.sc/184u0nr).

**Review by bizley — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Comment by bizley** [comment]
Does it require UPGRADE mention?

**Comment by samdark** [comment]
Yes. Would not hurt.

**Comment by egorrishe** [comment]
Done.

**Comment by bizley** [comment]
Cheers

**Comment by brandonkelly** [comment]
The change to `ColumnSchemaBuilder::$categoryMap` should probably be mentioned in the upgrade notes. It broke this code:

https://github.com/craftcms/cms/blob/972d611d3f38d8ee830df485618d3064e3de4f19/src/db/mysql/ColumnSchemaBuilder.php#L25-L28

**Comment by bizley** [comment]
You are right, I'm very sorry for that. I'll add the note.

**Pull request merged**
