### PR TITLE
Fix for #18171. Changed case of columns names in sql query for findConstraints

### PR DESCRIPTION
**Pull request by darkdef**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | #18171

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks good to me. A changelog line is needed.

**Comment by samdark** [comment]
@PitBult, @alex-code, @DavidOliver, @omsi668 would you please try this pull request?

**Comment by alex-code** [comment]
Looks good to me too, having the lowercase alias on the columns returns as lowercase.

**Comment by DavidOliver** [comment]
Based on a quick click around in Craft CMS, this fix seems to be working well. Thanks.

**Comment by samdark** [comment]
👍

**Pull request merged**
