### PR TITLE
#20199 Reverted BaseUrl::isRelative() behaviour to previous 2.0.49 ve…

### PR DESCRIPTION
**Pull request by edegaudenzi**
…rsion due to yii\web\UrlManager::createAbsoluteUrl() malfunction depending on this.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #20199

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
@edegaudenzi please check failing tests.

**Review by Arhell — APPROVED** [review]

**Review by rob006 — CHANGES_REQUESTED** [review]
This change is incorrect, in reverts fix for https://github.com/yiisoft/yii2/issues/17191 (that is why tests fails). 

Also, see https://github.com/yiisoft/yii2/issues/20199#issuecomment-2163622226

**Comment by edegaudenzi** [comment]
Ok @samdark, I will at a certain point today. I've just given a brief look at them and seems a couple of tests are starting from the wrong assumption links like `acme.com/test?tnt-link=https://tnt.com/` are valid URIs; accordingly to [rfc3986 (T. Berners-Lee)](https://www.ietf.org/rfc/rfc3986.txt) they are not: their 'legal' counterpart would be instead the **Percent-Encoding** version of it: `acme.com/test?tnt-link=https%3A%2F%2Ftnt.com%2F`
But I'll let you know as soon as I can give a deeper look into it.

**Comment by rob006** [comment]
I'm not sure why do you think that `acme.com/test?tnt-link=https://tnt.com/` is not valid. This RFC explicitly mentions that you can skip encoding for readability:

https://stackoverflow.com/a/68151221/5812455

**Comment by edegaudenzi** [comment]
As promised, on Friday I've dug deeper and found out the problem was in fact the a non rfc3986 compliant url  in the tests. I've changed that one, and for sake of clarity I've also added an additional case aimed to test a more relaxed version of rfc3986, but still legal. Everything's is committed now in the pr.

**Comment by rob006** [comment]
@edegaudenzi You may argue that `acme.com/test?tnt-link=https://tnt.com/` is not a valid URL, but it is correctly handled by many tools (PHP included) and it is definitely not an absolute URL. Your PR introduces regression that treats `acme.com/test?tnt-link=https://tnt.com/` as absolute URL (and thus breaking `ensureScheme()`) and you altered tests to hide this regression.

**Pull request closed without merging**
