### PR TITLE
Apply child table alias/name for joinWith case to condition columns (with test)

### PR DESCRIPTION
**Pull request by bscheshirwork**
One step to resolve the problem with ambigous column name and apply alias.

As part of #7263:

For case `joinWith` functional: only one child table inside `joinWithRelation` for each time
i.e. not allowed 
```SQL
SELECT * FROM
a JOIN b,c 
WHERE a.id = b.a_id and b.id = c.b_id
```
i.e. ActiveQuery for the child table is have single `from` and can be use single prefix.

Note:
for #14161
This method can be private or 
`framework/validators/ExistValidator.php`
`framework/validators/UniqueValidator.php`
can use this method too

Example: after path
```php
class Duration extends \yii\db\ActiveRecord {
...
    public function getUnit()
    {
        return $this->hasOne(DurationUnit::className(), ['id' => 'unitId'])->inverseOf('durations');
    }
...
}
```
```php
        echo Duration::find()
            ->joinWith([
                'unit as unitAlias' => function (DurationUnitQuery $query) {
                    $query->andWhere(['id' => [5, 3, 2, 1]]);
                }
            ])
            ->andWhere(['id' => [4, 5, 9]])
            ->alias('durationAlias')
            ->createCommand()->getRawSql();
```
produce
```SQL
SELECT `durationAlias`.* FROM `duration` `durationAlias` LEFT JOIN `duration_unit` `unitAlias` ON `durationAlias`.`unitId` = `unitAlias`.`id` WHERE (`id` IN (4, 5, 9)) AND (`unitAlias`.`id` IN (5, 3, 2, 1))
```
current 
```SQL
SELECT `durationAlias`.* FROM `duration` `durationAlias` LEFT JOIN `duration_unit` `unitAlias` ON `durationAlias`.`unitId` = `unitAlias`.`id` WHERE (`id` IN (4, 5, 9)) AND (`id` IN (5, 3, 2, 1))
```

and "as target" result must be
```SQL
SELECT `durationAlias`.* FROM `duration` `durationAlias` LEFT JOIN `duration_unit` `unitAlias` ON `durationAlias`.`unitId` = `unitAlias`.`id` WHERE (`durationAlias`.`id` IN (4, 5, 9)) AND (`unitAlias`.`id` IN (5, 3, 2, 1))
```

include some tests

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | #7263, #14166, #14161, #14150

### CODE REVIEW

**Comment by samdark** [comment]
@bscheshirwork seems tests aren't passing in this one.

**Comment by bscheshirwork** [comment]
@samdark this PR is use another concept (my first proposition) of `applyTableAlias` and must be changed

**Comment by samdark** [comment]
@bscheshirwork please close/fix ones that aren't actual. Hard to review all these...

**Comment by bscheshirwork** [comment]
I will close it. I don't have a time for fix this now.

**Pull request closed without merging**
