### PR TITLE
Guide about Client side Javascript of ActiveForm

### LINKED ISSUE #7137: Request for documentation on the methods of yii.activeForm.js
Please, read the two comments below. We just want to know how to make this conventionally.

---

HorsePreferredFood's rules:

```
    public function rules()
    {
        return [
            [['name', 'horse_id'], 'required'],
            [['horse_id'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }
```

---

JavaScript to add dynamic submodels' fields:

**This function was build manually, but we want to know if there is a way, using Yii 2, of getting the model JS validation function automatically. We did so just to test.**

```
        var horsePreferredFoodValidateFunction = function(attribute, value, messages) {
            yii.validation.required(value, messages, {"message": "Nome é obrigatório."});
        };

        $(window).load(function() {
            $('.container').on('click', '#add-horse-preferred-food', function() {
                var horsePreferredFoodsCount = (parseInt($('#horsePreferredFoodsCount').val())) + 1;
                $.post(
                    '/horse/add-horse-preferred-food',
                    {index : horsePreferredFoodsCount},
                    function(data) {
                        $('#horsePreferredFoodsCount').val(horsePreferredFoodsCount);
                        $("#horse-preferred-food-list").append(data);
                        var horseForm = $('#horse-form');
                        console.log(horseForm.data('yiiActiveForm'));
```

**How should we do the attributes adding if we have a submodel with many fields?**

```
                        $(horseForm).yiiActiveForm('add', {
                            id: 'horsepreferredfood-' + horsePreferredFoodsCount + '-name',
                            input: '#horsepreferredfood-' + horsePreferredFoodsCount + '-name',
                            name: 'name',//'[' + horsePreferredFoodsCount + '][name]',
                            container: '.field-horsepreferredfood-' + horsePreferredFoodsCount + '-name',
                            validate: horsePreferredFoodValidateFunction,
                            error: '.help-block.help-block-error'
                        });
                        console.log(horseForm.data('yiiActiveForm'));
                    }
                );
            });
        });

        function removeHorsePreferredFood(id) {
            $('#div-horse-preferred-food-' + id).remove();
        }
```

---

The main form (horse/_form.php):

```
<div class="horse-form">
<?php
        $form = ActiveForm::begin(
            [
                'id' => 'horse-form',
                'action' => '/horse/' . (($horse->isNewRecord) ? 'create' : 'update/' . $horse->id),
                'errorCssClass' => 'errorMessage',
            ]
        );
?>
    <?= $form->field($horse, 'name')->textInput(['maxlength' => 255]) ?>
    <?= $form->field($horse, 'age')->textInput() ?>

    <!-- HORSE PREFERRED FOODS -->

    <fieldset class="fieldset">
        <legend>Comidas Preferidas:</legend>
        <div id ="horse-preferred-food-list">
<?php
        $horsePreferredFoodsCount = count($horsePreferredFoods);

        foreach ($horsePreferredFoods as $horsePreferredFoodIndex => $horsePreferredFood) {
            $this->renderPartial(
                '/horsePreferredFood/_form',
                array(
                    'index' => $horsePreferredFoodIndex,
                    'horsePreferredFood' => $horsePreferredFood,
                    'form' => $form,
                )
            );
            echo $form->field($horsePreferredFood, 'name')->textInput(['maxLength' => 255]);
        }
?>
        </div>
        <div class="form-group">
<?php
            echo \yii\bootstrap\Button::widget(
                [
                    'label' => 'Adicionar Comida Preferida',
                    'options' => [
                        'id' => 'add-horse-preferred-food',
                        'class' => 'btn-lg',
                    ],
                ]
            );
?>
        </div>
    </fieldset>
    <div class="form-group">
        <?= Html::submitButton(
                $horse->isNewRecord ?
                        'Criar' : 'Alterar',
                [
                        'class' => $horse->isNewRecord ?
                                'btn btn-success' : 'btn btn-primary'
                ]
        ); ?>
    </div>
<?php
    ActiveForm::end();
    echo Html::hiddenInput(
        'horsePreferredFoodsCount',
        $horsePreferredFoodsCount,
        [
            'id' => 'horsePreferredFoodsCount',
        ]
    );
?>
</div>
```

---

The submodel form (horsePreferredFood/_form.php):

```
<?php
    if (isset($isAjaxCall) && ($isAjaxCall)) {
        $horsePreferredFood = new \app\models\HorsePreferredFood();
    } else {
        $isAjaxCall = false;
    }

    if (! isset($form)) {
        $form = \yii\bootstrap\ActiveForm::begin(
                [
                    'id' => 'horse-form',
                    'enableAjaxValidation' => false,
                    'enableClientValidation' => true,
                ]
        );
    }
?>
<div class="form" id="div-horse-preferred-food-<?php echo $index; ?>">
        <fieldset class="fieldset">
            <div class="form-group">
<?php
                echo \yii\helpers\Html::activeHiddenInput($horsePreferredFood, "[$index]id");
                echo $form->field($horsePreferredFood, "[$index]name")->textInput(['maxlength' => 255]);
?>
            </div>
        </fieldset>
        <div class="form-group">
<?php
            echo \yii\bootstrap\Button::widget(
                [
                    'label' => 'Remover Comida Preferida',
                    'options' => [
                        'id' => "btn-remove-horse-preferred-food-$index",
                        'class' => 'btn-lg',
                        'onClick' => "removeHorsePreferredFood($index);",
                    ],
                ]
            );
?>
        </div>
</div>
```

---

In HorseController, the action invoked via AJAX to return the submodel fields:

```
public function actionAddHorsePreferredFood() {
        $index = $_POST['index'];
        $partialView = "/horsePreferredFood/_form";

        return $this->renderPartial(
            $partialView,
            [
                'index' => $index,
                'isAjaxCall' => true,
            ]
        );
}
```

---

### PR DESCRIPTION
**Pull request by cebe**
I feel that this part is not documented very well and deserves a
dedicated guide page to handle the different possibilities and use
cases.

This covers questions like https://github.com/yiisoft/yii2/issues/11177#issuecomment-200586587

Some parts of what is covered in
https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md
should be covered in the official guide too.

This is WIP, comments and additions welcome.

- [ ] include https://github.com/yiisoft/yii2/issues/4985#issuecomment-55687472

fixes #7137

### CODE REVIEW

**Comment by mikehaertl** [comment]
@cebe How about starting with a description of the `jQuery.activeForm()` plugin first? We could show, that you can even use the plugin standalone. Then take it from there: 

 * Describe the main configuration options `yiiActiveForm`
 * List all public methods and events
 * Explain all the validation features of `yii.validation`
 * Add some more advanced standalone examples

Then finally demonstrate how things interact with `ActiveForm` on the serve rside.

I'd start with something like this:

----

At the heart of Yii's `ActiveForm` on the client side lies a powerful jQuery plugin: `jQuery.yiiActiveForm()`. It takes care of many otherwise tedious logic to deal with form validation and submission. You could even use it without an `ActiveForm`. Here's an example view file:

```php
<?php
yii\widgets\ActiveFormAsset::register($this);
yii\validators\ValidationAsset::register($this);
$this->registerJs(<<<JS
    jQuery('#query-form').yiiActiveForm(
        [
            {
                id: "query",
                name: "query",
                container: ".query-container",
                input: "[name=query]",
                error: ".query-error",
                validate: function (attribute, value, messages, deferred, form) {
                    yii.validation.required(value, messages, {
                        message: "Please enter a query."
                    });
                }
            }
        ],
        {
            errorCssClass: "error"
        }
    );
JS
);
?>

<form id="query-form" method="post" action="query">
    <div class="query-container">
        <input type="text" name="query">
        <span class="query-error"></span>
    </div>
    <div>
        <input type="submit" value="Search">
    </div>
</form>
```

**Comment by samdark** [comment]
@cebe do you need help with this one?

**Comment by cebe** [comment]
if you have time to help, feel free to work on it.

**Comment by samdark** [comment]
Updated it a bit. Did you plan a full featured A-Z example in "Adding fields dynamically" section?
What else should be covered?

**Comment by cebe** [comment]
> Updated it a bit. Did you plan a full featured A-Z example in "Adding fields dynamically" section?

its fine like that for now, we can make it more detailed later.



> What else should be covered?

yii.js features are not covered in the guide iirc.

**Comment by samdark** [comment]
> yii.js features are not covered in the guide iirc.

That's separate issue. Let's merge it.

**Pull request merged**
