### PR TITLE
Update git-workflow.md

### PR DESCRIPTION
**Pull request by derekisbusy**
vendor/bin/phpunit is bash script not php

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by rob006** [comment]
It **is** PHP script, but with shebang.

**Comment by derekisbusy** [comment]
Okay true but if you try to run `php vendor/bin/phpunit` it outputs the file contents.

**Comment by rob006** [comment]
> Okay true but if you try to run php vendor/bin/phpunit it outputs the file contents.

No, it should execute script.

**Comment by derekisbusy** [comment]
Actually no it is a shell script...

```sh
#!/usr/bin/env sh

dir=$(d=${0%[/\\]*}; cd "$d"; cd "../phpunit/phpunit" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
	# Cygwin paths start with /cygdrive/ which will break windows PHP,
	# so we need to translate the dir path to windows format. However
	# we could be using cygwin PHP which does not require this, so we
	# test if the path to PHP starts with /cygdrive/ rather than /usr/bin
	if [[ $(which php) == /cygdrive/* ]]; then
		dir=$(cygpath -m "$dir");
	fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phpunit" "$@"
```

**Comment by cebe** [comment]
not sure where you go that shell script from but for me it installs a php script. Also the file in the phpunit repo is a php script: https://github.com/sebastianbergmann/phpunit/blob/fc2561af7296fd54ca3d6ca086e0ddedc01425d9/phpunit

**Comment by rob006** [comment]
@cebe It looks like this is some proxy script generated by composer: https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Installer/BinaryInstaller.php#L187

**Comment by derekisbusy** [comment]
I guess you must be using Linux? Might want to add note that it's different on Windows.

**Comment by cebe** [comment]
does running it without `php` work on windows?`Then we could accept this PR as `vendor/bin/phpunit` works on linux too.

**Comment by derekisbusy** [comment]
No, in Windows it outputs the contents of the shell script.

**Comment by samdark** [comment]
It works for me under regular Windows 10 CMD. Running `phpunit` from `vendor/bin` executes phpunit as expected.

**Comment by samdark** [comment]
One thing that it doesn't really work well with relative paths so first `cd` to `vendor/bin` then execute `phpunit`.

**Review by dynasource — APPROVED** [review]

**Review by SilverFire — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
