### PR TITLE
[WIP] Remove sizzle

### PR DESCRIPTION
**Pull request by SamMousa**
Work in progress, do not merge.

### CODE REVIEW

**Comment by SamMousa** [comment]
Find the differences:

https://htmlpreview.github.io/?https://gist.github.com/SamMousa/9ef09eb0213ec86fbcd9/raw/3630296007f2473c8861716f31617de443db6641/Exception-nosizzle.html

https://htmlpreview.github.io/?https://gist.githubusercontent.com/SamMousa/9ef09eb0213ec86fbcd9/raw/3630296007f2473c8861716f31617de443db6641/Exception.html

**Comment by cebe** [comment]
difference is as described in my comment here: https://github.com/yiisoft/yii2/commit/dbc6d106b489c22a8fb8ff967bb3fd87a729adbf#commitcomment-16331000

**Comment by SamMousa** [comment]
Yes, thanks I'll look at it in detail tomorrow. Let me know if you find anything else.
There's still a lot of javascript for a page that is essentially mostly static ;-)

**Comment by SamMousa** [comment]
Have fully removed sizzle and made the JS used a bit lighter.
1. No more classes that get added on hover.
2. Disable pointer events for formatted code.
3. On mouse button down re-enable hover events to allow for text selection (which doesn't work very well on the current exception page due to line numbers). This could be improved by fully disabling hover events and text selection for line numbers.

**Comment by cebe** [comment]
Looks good to me, merged. Thank you!

**Comment by SamMousa** [comment]
Did you test this properly? I didn't remove the work in progress tag and am unsure if it was 100% ready.

**Comment by cebe** [comment]
I tested on various exception pages and I could not find anything that would not work.

**Pull request closed without merging**
