### PR TITLE
update schema.php getLastInsertedId

### PR DESCRIPTION
**Pull request by Sanya1991**
I become ORA00936 errors and ORA-08002: sequence MySequence.CURRVAL is not yet defined in this session.
This is the soulution.

### CODE REVIEW

**Comment by samdark** [comment]
@cebe do we have test environment for it?

**Comment by Sanya1991** [comment]
Yes, but not public test environment.

**Comment by cebe** [comment]
not yet, @nineinchnick can you check it?

**Comment by nineinchnick** [comment]
I can't confirm that. I've added unit tests for `Schema::getLastInsertId()` in #8441 but it's working with the current code.

@Sanya1991 you are supposed to run an `INSERT` statement before calling `Schema::getLastInsertId()`, otherwise it won't work and it doesn't make sense anyway. If you just want to check the sequence value, execute a specific query.

**Comment by Sanya1991** [comment]
08002. 00000 -  "sequence %s.CURRVAL is not yet defined in this session"
In a same session the sequence hasn't CURRVAL value if one is unused, you know?

The problem: I click the save button and yii catch the exception: sequence %s.CURRVAL is not yet defined in this session => the record is unsaved. 
After I push F5 on my keyboard and click yes send data again.. Then bumm the record is saved. Attach pictures?

I have a solution: SELECT LAST_NUMBER - 1 FROM USER_SEQUENCES WHERE SEQUENCE_NAME=:sequenceName

The -1 is important, because, the LAST_NUMBER is not the last inserted number, it's the next number..

This problem is old... http://saadnawaz.blogspot.hu/2010/10/using-single-query-determine-current.html

**Comment by psrustik** [comment]
MR is not valid because: 
1) System object USER_SEQUENCES don't contains [all sequenses] (http://docs.oracle.com/cd/B14117_01/server.101/b10755/statviews_2630.htm). Schema for connected user and ActiveRecord schema may be various, for example:
```
//config.php
'db'=>[
    'class' => 'yii\db\Connection',
    'dsn' => 'oci:dbname=CRMDB',
    'username' => 'web_user',
    'password' => 'mypassword',
];
// Model
class Record extends ActiveRecord {
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ANOTHER_SCHEMA.RECORDS';
    }
}
```
2) CURRVAL method for sequence may be called only after inserting data with NEXTVAL.

In your case probably insert query not called.

**Comment by samdark** [comment]
@psrustik you mean `PR` is not valid, not `MR`, right?

**Comment by psrustik** [comment]
Yes, mean pull request

**Comment by Faryshta** [comment]
can we still keep the idea to use parameters instead of php concatenation?

**Comment by samdark** [comment]
No since parameter binding doesn't work for schema names.

**Pull request closed without merging**
