### PR TITLE
Fix `\yii\rest\CreateAction::run()`

### PR DESCRIPTION
**Pull request by WinterSilence**
Use `Yii::createObject()` to import configuration added by service locator.
Use response/request defined in parent controller

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by WinterSilence** [comment]
When you create instance native by `new`, you ignore predefined configuration.
~~~php
class \app\models\Foo extends \yii\db\ActiveRecord
{
      public $bar = 0;
}

\Yii::$container->set('\app\models\Foo', ['bar' => 1]);

echo (new \app\models\Foo())->bar; // 0
echo \Yii::createObject('\app\models\Foo')->bar; // 1
~~~

**Comment by samdark** [comment]
Why should Active Record instances be configurable via DI container? These aren't meant for it, they aren't services/components.

**Comment by WinterSilence** [comment]
@samdark [nope](https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#selecting-extra-fields)

**Comment by samdark** [comment]
@WinterSilence how's that connected?

**Comment by WinterSilence** [comment]
@samdark that's fields fills by config

**Comment by bizley** [comment]
I also don't understand the connection and I don't think AR should be done like that.

**Pull request closed without merging**
