### PR TITLE
Fixed PhpDoc in Migration.php (revert #18886)

### PR DESCRIPTION
**Pull request by rhertogh**
Fixed the return type of `up()`, `down()`, `safeUp()` and `safeDown()` functions to match the described behavior.
The current implementation checks for `false`, "all other return values mean the migration succeeds".
This PR also reverts #18886 since it was a code fix for what was documentation error.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #18886

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Comment by WinterSilence** [comment]
`mixed` contain `false`, it's must be `false|void`

**Comment by rhertogh** [comment]
@WinterSilence 
> `mixed` contain `false`, it's must be `false|void`

According to https://wiki.php.net/rfc/union_types_v2:
> "The void type can never be part of a union."

and 
>"While we nowadays encourage the use of null over false as an error or absence return value, for historical reasons many internal functions continue to use false instead."

And from https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.void-functions
> Functions declared with void as their return type must either omit their return statement altogether, or use an empty return statement. null is not a valid return value for a void function.

I agree that there is an overlap in `false|mixed` since `mixed` indeed includes a `boolean`, but it this case it has a special indicative function.

**Comment by WinterSilence** [comment]
@rhertogh it's not union type - we return only `false`, `void` need only for Psalm, PhpStan and etc.

**Comment by rhertogh** [comment]
If you want to return `false` the return type could never be `void` that would break static analysis.

**Comment by WinterSilence** [comment]
@rhertogh nope, it's return false or no return result. which analyzers are having problems with this?

**Comment by rhertogh** [comment]
Interestingly enough PHPStan does seem to accept `false|void`:
https://phpstan.org/r/d1a58b02-057b-4ff1-855c-d28e28686900
Which looks like a missing rule since trying to run such code would result in an error:
http://sandbox.onlinephpfunctions.com/code/884e149187314e4125dc46be46bbf5a9cea2dcec

I've double checked the PHP documentation (to see if it has changed from the RFC), but there it also states:
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.void

But back to finding a solution for the original problem.
The [documentation](https://github.com/yiisoft/yii2/blob/master/framework/db/Migration.php#L107-L108) states:
> @return `bool` return a false value to indicate the migration fails and should not proceed further. **All other return values mean the migration succeeds.**

Which means that return `true` is ok, and people might have implemented as such. But this breaks the static analysis:
https://phpstan.org/r/bbebe328-93c6-4458-a975-e9def166b09d

**Comment by WinterSilence** [comment]
@rhertogh what you don't understand in phrase "it's not union type"? `false|mixed` valid union type? https://phpstan.org/r/bca2e05e-ace7-45b1-829a-32413eadd064 and without `void` https://phpstan.org/r/5f617b26-f9b8-479e-b3db-be6d5205bd33

**Comment by rhertogh** [comment]
> `false|mixed` valid union type?

Yes, this is a valid union type: https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.union.false
> The false literal type is supported as part of unions, and is included as for historical reasons many internal functions return false instead of null for failures.

Again I would like to point to the Yii documentation which states: "All other return values mean the migration succeeds."
If we would declare the return value as `false|void` that would go against:
* the described behavior in the documentation
* the current implementation in the code
* the PHP Language Reference

`false|mixed` is also used in many other projects to describe exactly this behavior:
https://sourcegraph.com/search?q=context:global+lang:php+false%7Cmixed&patternType=literal

**Comment by WinterSilence** [comment]
@rhertogh https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.union.false
> function foo(): bool|false {} // Disallowed

**Comment by rhertogh** [comment]
> 🤣

@WinterSilence If you are unable to have a discussion in an adult fashion please don't join the conversation. Especially coming form a Yii team member this is not constructive behavior unless your aim is to damage the community.

---

Although [often](https://sourcegraph.com/search?q=context:global+lang:php+false%7Cmixed&patternType=literal) used in PhpDocs for this use case, it is true that `mixed` can't be used in a union type for the code itself:
http://sandbox.onlinephpfunctions.com/code/2266e086ccdb89ac1afad039825203cd590e2e86
> Type mixed can only be used as a standalone type

So in that regard it means that both `false|mixed` and `false|void` would be invalid. I think that would only leave us the `mixed` option.
@samdark, @bizley , @Arhell What do you think?

**Comment by WinterSilence** [comment]
@rhertogh you tried to deceive me, that's you calling "an adult fashion"?

> I think that would only leave us the `mixed` option.

`mixed` not/cant contain `void` - it's still generate phpstan error

**Comment by rhertogh** [comment]
@WinterSilence Based on what I read in the PSRs, PHP documentation and the usages in other projects I referenced I was under the assumption that `false|mixed` was a valid type.
But if you think that people who make mistakes are trying to *deceive* you, then that's on you.

---

> mixed not/cant contain void - it's still generate phpstan error

That's indeed the case, what about `mixed|void`? It's definitely not a valid PHP type, but it would satisfy every use case
(and PHPStan is happy https://phpstan.org/r/c8af53f9-3ea3-41a5-99d3-541555e78c0c)

**Comment by WinterSilence** [comment]
@rhertogh
> It's definitely not a valid PHP type

PhpDoc types similar to PHP types, but not same. PhpDoc created to describe what cannot be described by PHP like as `string[]`, `(string|int)[]` or `$this`

> But if you think that people who make mistakes are trying to deceive you, then that's on you.

you posted link refuting your assertion, it's really funny

**Comment by bizley** [comment]
@WinterSilence you are doing it again, stop.

I'm not really sure why the discussion about that trivial thing is so heated. Let's do `false|void|mixed` since it goes well with PHPStan and while not super proper it indicates the values we expect.

**Comment by WinterSilence** [comment]
@bizley nope, https://phpstan.org/r/d0b8cd34-31a5-4328-b11d-b1546eb70c2b

**Comment by bizley** [comment]
With **strict rules** it shows error, yes. I don't have problems with that.

**Comment by rhertogh** [comment]
@bizley 
> Let's do `false|void|mixed` since it goes well with PHPStan and while not super proper it indicates the values we expect.

I agree, PR has been updated accordingly.

**Comment by WinterSilence** [comment]
@bizley do you check PhpStan, Rector, CS-Fixer, CodeSniffer?

**Comment by bizley** [comment]
No.

**Comment by rhertogh** [comment]
It looks more like a bug in PhpStan, when including all types that are included in `mixed` PhpStan thinks it's ok:
https://phpstan.org/r/6e87646b-7a93-4c8a-ba18-e2e2a0532abd
But when using mixed the `|void` part seems to be ignored.

**Comment by WinterSilence** [comment]
@rhertogh drawing conclusions on basis of demo functionality of one tool is not good idea

**Comment by My6UoT9** [comment]
maybe https://php.watch/versions/8.0/mixed-type#mixed-union
> Because mixed represents all types, mixed cannot be used in union with other types:
weird

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
