### PR TITLE
Batch Query improve for large mysql tables #9269 #11152

### PR DESCRIPTION
**Pull request by aivanouski**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #9269, #11152 |

### CODE REVIEW

**Comment by ihipop** [comment]
`each()` is `batch()` with `internel iteration`
i ditn't see  any `$split` parameters in `each()`

**Comment by cebe** [comment]
right, this change is not correct.

**Comment by ihipop** [comment]
@cebe I think the only thing to make it  right is just add `$split` parameters in `each()` function, and pass it to  ` Yii::createObject` of `BatchQueryResult::className()` .The others a fine.
@aivanouski

**Comment by ihipop** [comment]
anyone ?
#9269

**Comment by Sammaye** [comment]
This PR is not correct, it is too simple for one, it does not take pre-defined offset or limit into account

**Comment by andrey-denisenko** [comment]
@Sammaye 
> This PR is not correct, it is too simple for one, it does not take pre-defined offset or limit into account
Your solution does that?

**Pull request closed without merging**
