### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by yuzilog**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by SilverFire** [comment]
Wow, it looks enormous :open_mouth:

**Comment by schmunk42** [comment]
It's very similar to https://github.com/yiisoft/yii2/pull/14878/files - I don't speak Chinese, so I can't tell what's going on. Are these real PRs or are they accidentally created?

What makes me sceptic is that the commit history is starting back in 2015.

**Comment by SilverFire** [comment]
@logwood could you explain this PR, please?

**Comment by samdark** [comment]
Can't be merged anyway. Please open new one made against current master branch.

**Pull request closed without merging**
