### PR TITLE
Fix #13922 controller `request` and `response` properties

### LINKED ISSUE #13922: Request/response should be injected in controller and actions via constructor
## Current state

Currently we're working with request/response globally via `Yii::$app->request` and `Yii::$app->response`.

## Problem

Encapsulation violated. Request and response aren't meant to be dealt with outside of controller and related classes. Accessing them directly and especially doing that in the guide could be easily interpreted like "accessing request anywhere via Yii::$app->request is OK".

## Suggested syntax

```php
// old
Yii::$app->request->...
Yii::$app->response->...

// new
$this->request->...
$this->response->...
```

### PR DESCRIPTION
**Pull request by klimov-paul**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13922

### CODE REVIEW

**Comment by SamMousa** [comment]
I don't like this implementation, why not do proper dependency injection?
This implementation still uses the global service locator instead of injection..

You can already do controller constructor injection by just adding the params after the `$module` param and configuring them in the DI container to be singletons.

The same goes for actions.

If you want to do it properly, you could even go one step further and inject a `ControllerFactory` into each `Module` and an `ActionFactory` into each `Controller`. That way you move away from using the DI container as a Service Locator (`Yii::createObject`) and towards actual DI.

**Comment by klimov-paul** [comment]
> I don't like this implementation, why not do proper dependency injection?
This implementation still uses the global service locator instead of injection..

Binding request and response to a controller has nothin gto do with the dependency injection.
It is the matter of controller handling the particular request assigned to it. It is the matter of how controller handles request passed to it by application. Request data and thus entire request object should be determined elsewhere at application request processing level. Controller should not instantiate requests by it own will, even using DI specification.

In the scope of regular Yii web or console application this PR changes almost nothing, as these application are always single-request and single-response ones. However, you may create your own Application class, which will provide different request handling flow.
Current fix allow you to instantiate and run controller with its own request and response instances, which might be different from the `Application::$request` and `Application::$response`.

Also note, that this fix is meant to be applied to Yii 2.0.x, thus adjusments are limited by the BC keeping.

**Comment by cebe** [comment]
why do we need to make this change in 2.0.x? I'd vote to make a proper change in 2.1, which is not limited by BC and leave 2.0 as is.

**Comment by samdark** [comment]
Agree.

**Pull request closed without merging**
