### PR TITLE
Added Yii logo (https)

### PR DESCRIPTION
**Pull request by philipgura**

### CODE REVIEW

**Comment by SilverFire** [comment]
I've checked about 10 other popular repositories on GitHub and nobody put a logo in Readme.
Do we need it @yiisoft/core-developers

**Comment by philipgura** [comment]
I had this idea looking at: https://github.com/tensorflow/tensorflow (it seem to look nice)

**Comment by SilverFire** [comment]
https://github.com/gulpjs/gulp

**Comment by klimov-paul** [comment]
I don't like idea with the logo.
GitHub is a bug tracking and source code service.
For the advertisement and visual effects we have official website.
Also we have a logo at the @yiisoft organization profile.

Placing logo in readme just make this file longer to scroll.
For me adding logo to the repository main page in this way is disrespectful to the possible visitor.

**Comment by samdark** [comment]
My opinion isn't as strong as Paul's but I agree that it doesn't bring any significan pros. @philipgura thanks for an attempt to make it better but this time we won't accept pull request.

**Comment by philipgura** [comment]
Thanks guys, makes sense

**Pull request closed without merging**
