### PR TITLE
WIP spellcheck for the guide

### PR DESCRIPTION
**Pull request by cebe**
could be useful. currently fails the build.

I wonder however why it did only find a single spelling mistake :)

### CODE REVIEW

**Review by dynasource — APPROVED** [review]

**Comment by SilverFire** [comment]
@cebe bash, sed and PHP simultaneously is a quite interesting stack for spellchecking :D

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
```
./spell-check.sh: 23: ./spell-check.sh: aspell: not found
```

**Comment by cebe** [comment]
@samdark where are you trying that? you need aspell installed for this to work.

**Comment by samdark** [comment]
Travis build.

**Comment by samdark** [comment]
Doesn't seem to be going anywhere. Closing.

**Pull request closed without merging**
