### PR TITLE
Update tutorial-yii-integration.md

### PR DESCRIPTION
**Pull request by ahmadasjad**
Detailed instruction to use both versions or gradually move from yii1 to yii2

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
There is a section about it: https://www.yiiframework.com/doc/guide/2.0/en/intro-upgrade-from-v1

It could be expanded. An external link isn't a good idea.

**Comment by ahmadasjad** [comment]
> An external link isn't a good idea

I agree with your statement 

> It could be expanded.

This link is not only about the doc how to move, but it also has the library to run both versions simultaneously. I was able to develop this library with lots of effort, chich made may able to understand the entire architecture of both versions. This library will save lots of time for others.

**Comment by samdark** [comment]
That's fine. How about posting info about it to https://yiifeed.com/ and https://www.yiiframework.com/wiki?

**Comment by ahmadasjad** [comment]
Ok
I'll do the same way

**Pull request closed without merging**
