### PR TITLE
docs/guide/README.md - "Database access objects" [ci skip]

### PR DESCRIPTION
**Pull request by softark**
for consistency sake

### CODE REVIEW

**Comment by samdark** [comment]
Nope. https://en.wikipedia.org/wiki/Data_access_object

**Comment by softark** [comment]
I see.
But what about the title of the linked section?

**Comment by samdark** [comment]
Should be changed to Data Access Objects, I think.

**Comment by samdark** [comment]
@qiangxue it was introduced by you if I remember correctly. Which one was meant to stay?

**Comment by softark** [comment]
OK, I'll wait and see.
Besides, I'll delete the branch, anyway.

**Pull request closed without merging**
