### PR TITLE
Correct phpDoc for return in several cases

### PR DESCRIPTION
**Pull request by creocoder**
http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.return.pkg.html

### CODE REVIEW

**Comment by suralc** [comment]
This is still true for non ancient version of phpdoc and apparently at the current state PSR-5 would support that. 

* http://www.phpdoc.org/docs/latest/references/phpdoc/types.html
* [PSR-5 definition](https://github.com/php-fig/fig-standards/pull/169/files#diff-9a10a11696dc38209c125ea9c57a565fR1971)

**Comment by samdark** [comment]
Are PhpStorm and NetBeans OK with it?

**Comment by lynicidn** [comment]
шторм вроде ок

**Comment by cebe** [comment]
Well, false is not a type so while the value is false, the type is still bool, in which case does this help? Imo it is confusing...

**Comment by creocoder** [comment]
@cebe Its not confusing, it just clarification. Moreover its phpDoc official feature. For example some method returns `object` or `false`. Look at official example from mine first link.

@samdark Its fine not only with PhpStorm, its fine with famous code analyzers.

@cebe Read carefully that document http://www.phpdoc.org/docs/latest/guides/types.html#keywords

> false or true
An explicit boolean value is returned; usually used when a method returns ‘false’ or something of consequence.

**Comment by samdark** [comment]
@creocoder what about netbeans?

**Comment by creocoder** [comment]
samdark I guess all fine with NetBeans. On other side why you care about NetBeans when its *official phpDoc documentation where its clearly written that you should use true of false in case of explicit boolean returns.

**Comment by creocoder** [comment]
@samdark Just cheked NetBeans 8.0.2 Do not see any troubles with what PR suggests.

**Comment by cebe** [comment]
merged, thanks!

**Pull request closed without merging**
