### PR TITLE
PHP 8.2 support

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

- https://github.com/yiisoft/yii2/pull/19699
- https://github.com/yiisoft/yii2/pull/19685
- https://github.com/yiisoft/yii2-app-advanced/issues/536

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by myname1614** [comment]
What is the current state of the fix?

**Comment by samdark** [comment]
Incomplete. 8.2 tests fail. Need help with squashing more cases and validating incoming PRs.

**Comment by xepozz** [comment]
Memcache troubles were fixed, but not released: https://github.com/websupport-sk/pecl-memcache/pull/104#issuecomment-1527940223

**Comment by tomassrnka** [comment]
PHP 8.2 released, sorry for the delay here!

**Comment by xepozz** [comment]
@samdark trigger the jobs, I don't have permissions to do it :(

**Comment by xepozz** [comment]
About `memcache` errors. Memcache tests pass on my Mac with newest memcache. Looks like github actions don't use the latest version.

**Comment by tbreuss** [comment]
Does anyone here keep track of what issues need to be fixed for PHP 8.2? I might be able to help, but would need some hints.

**Comment by schmunk42** [comment]
> Does anyone here keep track of what issues need to be fixed for PHP 8.2? I might be able to help, but would need some hints.

See failed 8.2 builds: https://github.com/yiisoft/yii2/actions/runs/4860081966/jobs/8663490394?pr=19749#step:11:146

**Comment by tbreuss** [comment]
> > Does anyone here keep track of what issues need to be fixed for PHP 8.2? I might be able to help, but would need some hints.
> 
> See failed 8.2 builds: https://github.com/yiisoft/yii2/actions/runs/4860081966/jobs/8663490394?pr=19749#step:11:146

So, anyone can fix one of the failed tests and send a pull request? One does not have to open an issue before, etc.?

Will try it.

**Comment by schmunk42** [comment]
> One does not have to open an issue before, etc.?

You need to check this yourself in the open PRs.

> So, anyone can fix one of the failed tests and send a pull request?

Sure :)

**Comment by tbreuss** [comment]
Hm... It gets very different test results on my machine. Is there a suitable docker image for testing?

**Comment by xepozz** [comment]
> Hm... It gets very different test results on my machine. Is there a suitable docker image for testing?
> 
> Ah, here we go: https://github.com/yiisoft/yii2/tree/master/tests#dockerized-testing

Probably you have`ext-memcache` 8.2, but CI 8.0

**Comment by xepozz** [comment]
@tbreuss have you tried to run tests again? What version of memcache do you have locally?

**Comment by tbreuss** [comment]
> @tbreuss have you tried to run tests again? What version of memcache do you have locally?

Sorry for my late answer @xepozz, I was involved into another project. I now run the unit tests with docker compose. 

There was only one failure which I fixed (#19834).

But I run into another issue with composer:

~~~
 => ERROR [4/5] RUN /usr/local/bin/composer install --prefer-dist                                                                                                      0.7s
------
 > [4/5] RUN /usr/local/bin/composer install --prefer-dist:
#8 0.566 Installing dependencies from lock file (including require-dev)
#8 0.570 Verifying lock file contents can be installed on current platform.
#8 0.600 Your lock file does not contain a compatible set of packages. Please run composer update.
~~~

As the error message says, the fix was to run "composer update".

**Comment by samdark** [comment]
Things to fix:

1. https://github.com/yiisoft/yii2/actions/runs/4971866311/jobs/8896690982?pr=19749#step:11:148
2. https://github.com/yiisoft/yii2/actions/runs/4971866311/jobs/8896690873#step:11:148 (that's the current master issue as well)

**Comment by tbreuss** [comment]
I have some difficulties to run and memcache tests and reproduce failed tests.

Are you running (memcache) tests in a docker container? I see `stream_socket_client('127.0.0.1:11211')` in a test, which kind of confuses me (in relation to docker-compose.caching.yml).

**Comment by samdark** [comment]
Kind of. We run it in GitHub actions. Memcached is up with https://github.com/niden/actions-memcached. It is basically this https://github.com/niden/actions-memcached/blob/master/entrypoint.sh#L4

**Comment by samdark** [comment]
This is super-weird:

```
1) yiiunit\framework\caching\MemCacheTest::testSet
Creation of dynamic property Memcache::$connection is deprecated

/home/runner/work/yii2/yii2/framework/caching/MemCache.php:197
/home/runner/work/yii2/yii2/framework/caching/MemCache.php:144
/home/runner/work/yii2/yii2/framework/caching/MemCache.php:117
/home/runner/work/yii2/yii2/framework/base/BaseObject.php:109
/home/runner/work/yii2/yii2/tests/framework/caching/MemCacheTest.php:36
/home/runner/work/yii2/yii2/tests/framework/caching/CacheTestCase.php:87
/home/runner/work/yii2/yii2/vendor/phpunit/phpunit/phpunit:52
/home/runner/work/yii2/yii2/vendor/bin/phpunit:123
```

Since there's no release of memcached for 8.2 I'm going to mark these tests as skipped for it.

**Comment by samdark** [comment]
I've tried to set it up locally with PHP 8.2 + memcache and all tests pass. Not sure what's wrong with the environment.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/19843

**Pull request merged**
