### PR TITLE
lazily-instantiated constructor-injected dependencies 

### PR DESCRIPTION
**Pull request by h0lg**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | untested |
| Fixed issues | none |

added Lazy class for expensive constructor dependencies that are lazily instantiated on first use and added special treatment of lazy parameters in Container

### CODE REVIEW

**Comment by samdark** [comment]
I think it kinda defeats the purpose of dependency injection overall...

**Comment by samdark** [comment]
Doesn't look correct to me.

**Comment by forger** [comment]
@samdark The Lazy class is basically a helper inspired by the .Net class with the same name: https://msdn.microsoft.com/en-us/library/dd642331%28v=vs.110%29.aspx
Obviously, without the generic type parameter.
You say "coupling" - I don't understand what you mean by this. I am thinking of coupling between types introduced by inheritance (as in https://en.wikipedia.org/wiki/Coupling_%28computer_programming%29#Object-oriented_programming) but no inheritance is used here. The type of Lazy::$instance and therefore the return type of Lazy::getInstance() is mixed. It will have the type of the dependency once instantiated.

using the types from the code example in Lazy.php:
```
get_class ($this->costlyService) // yii\base\Lazy
get_class ($this->costlyService->getInstance()) // app\models\BloatedService
```

And what do you mean by "doesn't look correct"? What looks incorrect?

**Comment by forger** [comment]
@samdark Got carried away and forgot your main point in the process:
> I think it kinda defeats the purpose of dependency injection overall
I disagree. For me the purpose is to delegate dependency creation to an object outside of the class, in our case the DI Container. We generally want this to make testing easier by swapping dependencies with mocks or fakes. This still works. What is the purpose of DI for you?

**Comment by samdark** [comment]
The whole point of DI is that a class requires some interfaces and doesn't care on how instances of these interfaces are getting into it be it some fancy dependency injector or just manually passed instance.

With your solution instead of an interface the receiving class is relying on an `yii\base\Lazy` utility. By coupling I mean exactly that. The class that should depend on interface only now depends on a concrete utility thing.

**Comment by samdark** [comment]
It's clearly visible from phpdoc example:

```php
function __construct(
    $id,
    $module, \app\models\SomeRepository $cheapRepository,
    \yii\base\Lazy $expensiveService, // <-- here
   $config = []
)
```

**Comment by forger** [comment]
@samdark Yes, you are right. The SiteController now is dependent on the Yii framework class Lazy.
I would like to avoid that too, but can't think of a much better way to do this.
The only other solution I know of that allows for lazy instantiation of expensive dependencies is using a ServiceLocator,
which then makes the SiteController directly dependent on the \Yii.
I consider that to be a 'worse' dependency because it's harder to mock.
Please have a look at https://github.com/yiisoft/yii2/compare/master...forger:lazyConstructorDependencyInjection.withoutTypeDeclaration
It now uses a the parameter prefix 'lazy_' instead of the type declaration to resolve a lazy loaded dependency. Would that be a viable solution? If not, please suggest an alternative. Thanks!

**Comment by samdark** [comment]
That's better but still isn't good. The instance injected should be of required class, not of something else be it declared in method signature or not. I don't have better alternative if we're talking about dependency injection via constructor.

**Comment by Faryshta** [comment]
how about

```
public function setExpensive($data)
{
    $this->expensive = $data;
}

public function getExpensive()
{
    if (!is_object($this->expensive) {
        $this->expensive = is_string($this->expensive)
            ? Yii::$app->container->get($this->expensive)
            : Yii::createObject($this->expensive);
    }

    return $this->expensive;
}
```

**Comment by samdark** [comment]
Where do you intend to put your `getExpensive()`? If it's the object you're injecting into then it is plain wrong.

**Comment by Faryshta** [comment]
@samdark `setExpensive()` sets an alias or object configuration and `getExpensive()` returns an object based on the alias or object configuration.

**Comment by forger** [comment]
@samdark 

> The instance injected should be of required class

Why? I specifically want it _not_ to be of the required dependency because that one is too expensive to instantiate unless I really need it. That's the whole point of lazy initialization. I want to inject a lightweight container (a.k.a. Lazy) that knows how to instantiate whatever expensive dependency it is configured to create - and only if it is asked to do so. Lazy does it the first time the getInstance() method is accessed.

The only way I see to inject a lazy initialized dependency with the same type of the dependency would be to inject a dynamically created Proxy (https://en.wikipedia.org/wiki/Proxy_pattern) - a type that has the same interface as the required dependency and instantiates the dependency on first access, then forwards all calls to the dependency. This type would be created via reflection of the required type. I don't really want to go there because reflection and dynamic type creation is not all that cheap itself - which kind of defeats the purpose of lazy instantiating the expensive dependency.

>  I don't have better alternative if we're talking about dependency injection via constructor.

I am open to other suggestions. Please keep in mind that I don't want my types to depend on a ServiceLocator to get a required dependency.

@Faryshta I don't understand which type these methods would belong to and where they would be called. Are these Container methods?

**Comment by Faryshta** [comment]
@forger thats for lazily starting an object similar to your class but in two methods instead of an entire class.

**Comment by forger** [comment]
@Faryshta You did not specify which type these methods belong to and which type would call them. I still cannot make any of this, sorry. Could I ask you to please explain it to me in a more elaborate way?

**Comment by samdark** [comment]
@forger well, Lazy class is OK by itself if we're **not** talking about dependency injection. You depend on it if you use it thus it will cause more coupling. I'd rather not to introduce it in the framework not to encourage shady practices which could be OK for your particular case.

**Comment by forger** [comment]
@samdark What "shady practices" are we talking about? I rather consider lazy initialization to be a powerful feature. The .NET framework developers seem to agree to that, as I pointed out above. Plus, using the yii framework I depend on so many classes already, I don't see how this particular one is bad.
- It's dead simple (meaning easy to rewrite in case you swap frameworks),
- does not depend on any other framework classes other than the `Yii->app` ServiceLocator - which can be easily swapped out (meaning the coupling is minimal)
- and even works without dependency injection (making testing so much easier and more transparent).

The coupling to the (mutable!) global `Yii` or even the promoted use of the (rather intrusive) ActiveRecord pattern instead of the Repository pattern makes the coupling to the yii framework so much tighter. So what's the problem with `Lazy`?

Also, how about alternative suggestions?

**Comment by samdark** [comment]
"shady practices" = violating ideas of dependency injection by injecting container instead of object instance so object is tightly coupled to to this lazy container and can't work w/o it.

**Comment by samdark** [comment]
Today me service is heavy and I'm using lazy container. Tomorrow there's another implementation which is light. But I still have to use lazy container because that's what existing class depends on.

I've already said that I don't have better alternative if we're talking about dependency injection via constructor.

@yiisoft/core-developers need more opinions on the matter.

**Comment by forger** [comment]
@samdark you said
> violating ideas of dependency injection by injecting container instead of object instance so object is tightly coupled to to this lazy container and can't work w/o it.

what ideas of DI is this violating? The receiving type _chooses_ to declare a lazily-instantiated dependency in its constructor because it knows it only needs it for 1% of all requests and doesn't want it to be instantiated for the remaining 99% because the dependency is rather expensive to create and that would be an tremendous waste of resources.

The idea of constructor injection as far as I understand it is: I declare what I need in my constructor and let somebody else worry about where to get it from and how to create it. That is the principle of Inversion of Control. Bottom line: This is **not** violating **any** ideas of DI.

>Today me service is heavy and I'm using lazy container. Tomorrow there's another implementation which is light. But I still have to use lazy container because that's what existing class depends on.

If your expensive dependency magically turns cheap tomorrow (they don't tend to do that in my experience though), just ditch the laziness of the dependency and declare it non-lazy instead. Boom, no more dependency on Lazy.
If you don't want to change your constructor because you've created some kind of inheritance mess instead of relying on composition, that's no big deal because the overhead of the Lazy wrapper is minimal.

> I've already said that I don't have better alternative if we're talking about dependency injection via constructor.

I thought you had another suggestion that doesn't include constructor injection. Or a ServiceLocator, which I personally dislike because
- instead of declaring all dependencies in a constructor, you have to read through the whole code for hidden dependencies. This makes code rather opaque
- it makes testing more cumbersome, because I additionally have to set up the ServiceLocator
- it makes the class dependent on a specific ServiceLocator (if no Proxy is used)

**Comment by forger** [comment]
@yiisoft/core-developers please have a look at
https://github.com/yiisoft/yii2/compare/master...forger:lazyConstructorDependencyInjection
which declares lazy dependencies explicitly using the `yii\base\Lazy` type:

register an alias for an expensive dependency
`\Yii::$container->set('expensiveService', 'app\models\BloatedServiceInterface');`

then use the alias as a constructor parameter name where the dependency is required
type must be \yii\base\Lazy and parameter name must match registered alias

`
function __construct($id, $module,
   \app\models\SomeRepository $cheapRepository,
   \yii\base\Lazy $expensiveService,
   $config = [])
{
   [...]
}
`

and
https://github.com/yiisoft/yii2/compare/master...forger:lazyConstructorDependencyInjection.withoutTypeDeclaration
which uses the rather magical "lazy_" prefix on an untyped parameter

register an alias for an expensive dependency
`\Yii::$container->set('expensiveService', 'app\models\BloatedServiceInterface');`

then use the alias as a constructor parameter name where the dependency is required
parameter must not be typed and its name must match the registered alias prefixed with "lazy_"

`
function __construct($id, $module,
   \app\models\SomeRepository $cheapRepository,
   $lazy_expensiveService,
   $config = [])
{
   [...]
}
`

I rather like it more explicitly (option 1), although the second branch might be worth for you to have a look at because it contains another feature:
constructor injection of dependencies registered with the DI Container by alias using the parameter name with the "alias_" prefix (similar to how the "lazy_" prefix works) - if you're at all interested in that

**Comment by forger** [comment]
As I'm running this now subclassing `\yii\di\Container`, you might alternatively be interested in the respective subclasses if you're reluctant to change `\yii\di\Container`. Or anybody else for that matter.
https://gist.github.com/forger/163b7b6f851d0adf0f7f627d355b7fd5

**Comment by samdark** [comment]
> what ideas of DI is this violating?

None. I realized now that I wrote not what I've thought. What it's violating is Law of Demeter (getting real dependency via `->getInstance()` and the calling its methods), not Dependency Injection.

>  The receiving type chooses to declare a lazily-instantiated dependency in its constructor ... that would be an tremendous waste of resources

I agree about waste of resources and I want to avoid it as well but there's a problem.
It chooses to depend on container with interface different than it should actually be.

If it would be a proxy with the same interface as original dependency as you've mentioned earier, theoretically it would be perfectly fine and Law of Demeter won't be violated thus there will be strong contract enforced.

It's not that important for controllers but I'm afraid of `Lazy` class in form of a container with `getInstance()` method would be used in other classes.

**Comment by samdark** [comment]
Now about my thoughts about how it could be solved:

1. Instead of constructor injection method injection could be used. There was implementation of that in master but it [didn't made it to release](https://github.com/yiisoft/yii2/pull/10765). Probably worth discussing another attempt to it.
2. A lazy proxy sharing the same interface could be created. I guess that would be a trait and you'll have to actually extend original class.

**Comment by forger** [comment]
@samdark Thank you for your suggestions! Here are my thoughts about them:
1) The only way of implementing Method Injection that I can think of is through interception of calls to that method. All Dependency Injection Containers supporting "Method Injection" that I know
- require the Client method to be decorated with some kind of attribute for that to work, so that the container knows where to inject what. This couples the receiving type to a DI container implementation.
- actually do Setter Method Injection, that means the injection happens shortly after the Client is instantiated by the container. That is, the injected dependency is not lazy.

If they actually did inject a dependency lazily into a method once that method is called, I can't see a way around a dynamic Proxy that intercept the calls to the Client. Which means returning creating and returning a dynamic proxy for each Client that needs a dependency injected into a method. That would probably eat up as many resources as constructor-injecting the client with that expensive dependency.

I've had a look at the method injection implementation feature you've linked and found out it works for Controller actions only. That's not what I need - I require lazy injection into non-Controller types as well. I merely chose a Controller as the receiving Client in my example.
Controller action calls are not like method calls on non-Controller objects. Action calls have to be intercepted anyway in order to construct their arguments from some input (console or HTTP request arguments). Therefore the interception of the call already takes place without any need for specially marking the action or configuring it with the DI Container.

Also, as you point out, the feature is not in the master, so I cannot use it.

2) A lazy Proxy using a trait would change the expensive dependency to always be lazy, since I have to use the trait in the dependency class code. I as a Client cannot choose any more whether I want the dependency to be lazy or not. If I wanted that, I might as well change the dependency type to be lazy itsself. Also, I would have to implement the whole interface of the dependency in the trait, which would result in a lot of 'dumb' methods doing the exact same thing.

>If it would be a proxy with the same interface as original dependency as you've mentioned earier, theoretically it would be perfectly fine and Law of Demeter won't be violated thus there will be strong contract enforced.

As far as I understand it, the Law of Demeter (https://en.wikipedia.org/wiki/Law_of_Demeter) is about encapsulation of the knowledge about the internal workings of a type. It tries to _limit_ leaking that knowledge into other types, not to _avoid_ it altogether. Since there's not much to know about the `Lazy::getInstance()` method that you cannot read from its signature, you could argue that this is a minor violation if one at all. Yes, I would like to have a generic type parameter on the `Lazy` class that tells you what to expect when you call `Lazy::getInstance()`. But PHP is a loosely-typed language and does not know anything like that. It doesn't even have return types for functions. Yet, we accept that and use PHP for what it is.

As mindful Software Engineers we try to abide by laws and principles that we know and embrace. Following one often leads to disregarding another, as most of them have certain disadvantages or trade-offs. The Law of Demeter has them as well as Dependency Injection in general does. Advantages come in an inseparable package with disadvantages. There are almost as many opinions about software development as there are software developers. Sometimes they contradict each other which leads to contradicting principles. That means we have to make compromises. I made a conscious attempt to minimize or avoid the disadvantages that I consider to be worse than others, accepting others that I don't know how to avoid if I want to have certain advantages. However, I cannot avoid all of them and in the end, the discussion becomes philosophical.

**Comment by forger** [comment]
@samdark you wrote:
> I'm afraid of Lazy class in form of a container with getInstance() method would be used in other classes.

Some people hurt themselves if you give them a hammer. That doesn't mean we should dispose of all hammers.

**Comment by cebe** [comment]
> Resource-intensive dependencies are a reality.

Could you give an example? I would normally think that if a dependency is heavy on construction it may be better to fix that dependency implementation to only aquire ressources when they are really needed and not on construction. That applies to nearly all Yii classes and the philosophy we apply when writing code.

> I declare what I need in my constructor and let somebody else worry about where to get it from and how to create it.

With a Lazy class you do not declare an explicit dependency but only depend on "something" that is lazily loaded after and you only know what you get when you try to access it.

> Instead of constructor injection method injection could be used. There was implementation of that in master but it didn't made it to release. Probably worth discussing another attempt to it.

We have method injection: https://github.com/yiisoft/yii2/blob/master/framework/di/Container.php#L485 it is just not automatically used in controller actions.

So you can add a method that needs the dependency:

```php
class MyClass
{
    public function __construct(/*Some lightweight dependencies here*/, $config = [])
    {
        // ...
    }
    
    public function doSomethingWithHeavyDependency($param1, \my\heavy\Dependency $something)
    {
        // do something with $something
    }
}
```

You may call that method either by passing an instance yourself or using

```php
$obj = new MyClass(/*...*/);
Yii::$container->invoke([$obj, 'doSomethingWithHeavyDependency'], ['param1' => 42]);
```

**Comment by samdark** [comment]
@cebe I think that's to be documented at http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html, right?

**Comment by cebe** [comment]
yep

**Comment by forger** [comment]
@cebe Thank you for your elaborate contribution to this discussion :) You asked for an example:
I am currently integrating an issue tracker into a software to make feedback easy. I've realized it using the following dependency structure in which some are only required **sometimes**, meaning they could be lazy: 

an `IssueController`
 . handling HTTP requests concerning issues
 . requiring an `IssueService` **sometimes**
 .  . handling the business logic of writing/command requests
 .  .  . requiring (always) an `IssueRepository`
 .  .  .  . which encapsulates the Issue data access
 .  .  .  . requiring an `IssueTrackerAdapter` **sometimes**
 .  .  .  .  . to make REST requests to the external issue tracking software
 .  .  .  . requiring (almost always) an `IssueCache`
 .  .  .  .  . to get the cached issues a previously from the external issue tracking software, avoiding expensive REST requests for every request to the IssueRepositpry
 .  . a `UserRepository` **sometimes**
 .  .  . for getting user related info like roles and email
 .  . a `MailerInterface` **sometimes**
 .  .  . to send emails about issue updates
 . requiring (almost always) an `IssueRepository` for reading/query request (with above mentioned dependencies)

As you can see, the whole subtree that is required for the initialization of `IssueService` is only required for writing/command requests which in most software make up a tiny fraction of all requests. That means that for the vast majority of the requests all those dependencies would be initialized but never used. That is, if we're talking about constructor-injected dependencies.
Now I have two possibilities to stop this waste of resources:

1. I can either choose to not declare those dependencies in the constructor and use a ServiceLocator to get them if and only if I need them. Every Client is now coupled to the ServiceLocator and the dependency is hidden somewhere in the classes code. Every time I use a Client now I have to _know_ to set up the ServiceLocator, because the constructor doesn't declare the dependency (bad encapsulation in my view). I cannot even test the Client without setting up a ServiceLocator.
2. Or, I can choose to inject a lazy dependency, that is a cheap `Lazy` container that only instantiates the dependency on first access. The Client is now coupled to `Lazy`. Sadly, the dependency is now not strongly-typed because PHP does not support function return types or generic types (the same would be true for using alias feature of the Container or ServiceLocator btw). But at least the dependency is declared in the constructor which prevents me from "misusing" the Client by not giving him what he needs. I am relieved of having to know about the hidden dependency and the Client's encapsulation is maintained in this point.  And I can still try to choose a descriptive parameter name that makes up for PHPs limitations of being loosely typed and not having type parameters. Testing works without a ServiceLocator as described in the example code of the `Lazy` type.

> With a Lazy class you do not declare an explicit dependency but only depend on "something" that is lazily loaded after and you only know what you get when you try to access it.

Yes, the lazy dependency's type is not obvious. This is the trade-off that I have to make using this container. PHP does not support passing along a generic type parameter that describes what type of dependency is instantiated by the container. No, I wouldn't depend on "something" because I would obviously try to find a better name for the parameter than that. Ideally a name so well chosen that it makes up for not knowing the type.

> I would normally think that if a dependency is heavy on construction it may be better to fix that dependency implementation to only aquire ressources when they are really needed and not on construction. That applies to nearly all Yii classes and the philosophy we apply when writing code.

If I understand correctly, this means you favor option 1. Obviously, I cannot argue with your philosophy. Mine is different and if that is the outcome of our discussion I accept that.

Thanks for your method injection code example. Good to know about this. Sadly, it's not what I'm looking for, because of the way the injection works - it references the Container which couple any class that uses this code to the Container. Following my philosophy, this is just as smelly as referencing the ServiceLocator. In fact, having to choose between the two I would rather prefer to not use method injection in this case, just because I find the code more explicit calling the method myself using the ServiceLocator to get the dependency:
```
$obj = new MyClass(/*...*/);
$obj->doSomethingWithHeavyDependency(42, Yii::$app->get('\my\heavy\Dependency'));
```

**Comment by SamMousa** [comment]
@forger I have implemented the described behavior (injection for controller actions) in a trait:

https://github.com/SAM-IT/yii2-magic/blob/master/src/Traits/ActionInjectionTrait.php

This obviously does not fully remove the smelliness of using the Service Locator pattern.
Alternatively you could use a separate class for each action, which will allow you to use constructor injection. Obviously, internally this will also mean that somewhere the controller refers back to the container to help it build the action object.

Alternatively you could look at using a proxy manager: https://packagist.org/packages/ocramius/proxy-manager.

I'm not sure the approach you use is really less smelly by the way. One part of DI is for the dependent class not to be aware dependencies are being injected; requiring dependency definitions like this:
````
function __construct($id, $module,
    \app\models\SomeRepository $cheapRepository,
    // type must be \yii\base\Lazy and parameter name must match registered alias
    \yii\base\Lazy $expensiveService,
    $config = [])
{
    parent::__construct($id, $module, $config);
    $this->cheapRepo = $cheapRepository;
    // an 'empty' Lazy wrapper is injected
    $this->costlyService = $expensiveService;
}
````

Doing this basically means I'm depending on your implementation for DI to do something intelligent, this is not any better than just using the ServiceLocator pattern.

**Comment by emailismail** [comment]
Guys, any update on this.. This might be one important thing for us..to reduce the memory footprint, we need lazy injection, method injection.  PHP-DI is giving the ability to make it lazy injection via multiple ways via annotation, via code or configuration file. 

> How it works #
> 
> If you define an object as "lazy", PHP-DI will inject:
> 
> the object, if it has already been created
> or else a proxy to the object, if it is not yet created
> The proxy is a special kind of object that looks and behaves exactly like the original object, so you can't tell the difference. The proxy will instantiate the original object only when needed.
> 
> Creating a proxy is complex. For this, PHP-DI relies on ProxyManager, the (amazing) library used by Doctrine, Symfony and Zend.

`<?php
$containerPHP->set('foo', \DI\object('MyClass')->lazy());`

@forger @cebe did you guys made any progress, please share?

@samdark 

http://php-di.org/doc/lazy-injection.html

**Comment by Faryshta** [comment]
@forger how is it better than

`$container->set('foo', ['class' => 'MyClass'])`

which is the documented way on yii2 http://www.yiiframework.com/doc-2.0/yii-di-container.html#set()-detail

**Pull request closed without merging**
