### PR TITLE
PHPStan level 0

### PR DESCRIPTION
**Pull request by bizley**
This is an attempt to introduce static analysis to Yii 2 with well known and widely used PHPStan package (level 0 for the good start).
Few things were required:
- composer's config.platform was removed in order to install PHPStan (it requires PHP 7|8)
- composer's constraint for friendsofphp/php-cs-fixer was changed to `^2.2` because of the above removal.

As we can see even with level 0 it proves to show some things to be fixed, like missing returns. To keep everything as it was before I've added `ignore` comments for the lines with `new static` (PHPStan correctly throws warnings there, see https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static ).

If we want to keep it I would be happy to increase the level as high as possible while keeping Yii 2 compatible with PHP 5.4.

### CODE REVIEW

**Comment by samdark** [comment]
We're using Psalm for Yii3. What's the benefit in using PHPStan compared to Psalm?

**Comment by bizley** [comment]
Both are for the same purpose, I don't know if one is better than other. I'm using PHPStan myself so that is why I chose it. I've heard some people are using Psalm and PHPStan at the same time to increase the analysis complexity.

**Comment by bizley** [comment]
I just tried to make similar PR with Psalm but I cannot get it to work, there are some issues with config file (?). If you prefer Psalm instead of PHPStan someone more experienced with Psalm should do it.

**Comment by samdark** [comment]
Well, I'm just more experienced in Psalm annotations and it's everywhere in Yii3 codebase. Using two distinct tools is OK but maybe it doesn't worth it.

**Comment by bizley** [comment]
I'm fine with both as long as you or someone else can properly configure it 😉

**Comment by samdark** [comment]
OK. I'll close this PR then. It's better to have the same stack without deviations.

**Comment by WinterSilence** [comment]
@samdark @bizley Yii2 have many magic properties, methods and untyped/mixed parameters - PHPStan easier to write Yii2 extensions to better analyze code

**Comment by samdark** [comment]
Psalm has many levels as well.

**Comment by WinterSilence** [comment]
@samdark 🤦🏻‍♂️  https://phpstan.org/user-guide/rule-levels

**Comment by samdark** [comment]
I know. We've started with PhpStan for Yii3 as well then switched to Psalm.

**Comment by WinterSilence** [comment]
@samdark can you explain why you focus on Psalm levels? [just for lulzz](https://youtube.com/watch?v=i9DrGNL_LZ8)

**Comment by samdark** [comment]
I don't.

**Pull request closed without merging**
