### PR TITLE
Fix to get data methods and pjax working together

### PR DESCRIPTION
**Pull request by derekisbusy**
This is a fix for the issue of pjax links/buttons not working when using data methods. This fix also requires a change in the Pjax widget that adds the attribute data-pjax-container to the container element so that it can be found via JavaScript. The pjax container can be defined in two ways, either by setting the data-pjax-container="#someSelector" in the link/button attributes, or else it will find the closest element with data-pjax-container="". So the HTML attribute 'data-pjax-container' is used in two ways: if the value is blank than that means the element is a pjax container, if the value is set then that means it's a selector pointing to a pjax container. If neither are set and the container is not found it will default to the body tag.

### CODE REVIEW

**Comment by derekisbusy** [comment]
Fixes these issues:

https://github.com/yiisoft/yii2/issues/8582
https://github.com/yiisoft/yii2/issues/8301
https://github.com/yiisoft/yii2/issues/6363

**Comment by derekisbusy** [comment]
I also forgot to mention that when using pjax with data method you have to set data-pjax attribute in the link element. This could be removed if we change it to check for $e.parents('[data-pjax-container=""]').length instead. Since the Pjax widget would now add the data-pjax-container attribute to the container element you could use that to check if the link is contained within a pjax container. However depending on the pjax settings not all links may be pjax enabled so might be best to leave it the way it is. For example right now you would set a link like this...

```php
Html::a('My Link','/controller/action',[
            'data-confirm'=>Yii::t('common','Are you sure?'),
            'data-method'=>'post',
            'data-pjax'=>'', // define a pjax link
        ]);
```

**Comment by derekisbusy** [comment]
Another issue I found with this is that when pjax is submitted it uses to default pjax settings. This is because there's no way to get the settings from a pjax container after it is created. There are two ways to fix this, either add the pjax settings to the container as data attributes, or update pjax so that the options for each pjax container can be referenced via something like $('.container').pjax('settings').

**Comment by elastic-od** [comment]
I have just tested your fix on delete button in GridView and I faced an issue of pjax pushs new state even if I set  'enablePushState' to false. Can you give an example how to handle this issue? Here is my code:
```
\yii\widgets\Pjax::begin([
    'id' => 'subject-channels-grid',
    'timeout' => false,
    'enablePushState' => false,
]);
```
```
'buttons' => [
    'delete' => function ($url, $model, $key) {
        $options = [
            'title' => Yii::t('yii', 'Delete'),
            'aria-label' => Yii::t('yii', 'Delete'),
            'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
            'data-method' => 'post',
            'data-pjax' => '1',
            'data-pjax-container' => '#subject-channels-grid',
        ];
        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, $options);
    },
]
```

**Comment by derekisbusy** [comment]
@elastic-od Please use the new patch here #9952. They never merged this patch and ran into problems with git so had to re-apply them. 
@samdark Please disregard this pull request and merge the new one #9952. It fixes most the issues people are having with Pjax and data methods. Thanks!

**Pull request closed without merging**
