### PR TITLE
Fix boolean check

### PR DESCRIPTION
**Pull request by mj4444ru**
Correction of checking the value of the type of bit received from mysql

### CODE REVIEW

**Comment by samdark** [comment]
@mj4444ru are you trying to fix #9006?

**Comment by mj4444ru** [comment]
@samdark Yes, there is described the same problem

**Comment by samdark** [comment]
Do you have reliable way to reproduce it? A unit test maybe?

**Comment by mj4444ru** [comment]
@samdark I have installed OS Ubuntu and this problem is present

**Comment by Faryshta** [comment]
I think you should check http://www.yiiframework.com/doc-2.0/yii-db-columnschema.html#phpTypecast()-detail and make the patch there. This will work for the format check, anywhere else the problem is still there.

**Pull request closed without merging**
