### PR TITLE
bug fix #16044

### LINKED ISSUE #16044: Cors filter is broken since 2.14
### What steps will reproduce the problem?
We have some action responding to the OPTIONS calls. 
It is replying with the Access-Control-Allow-Methods set to available verbs. That is required for CORS requests to be done. 

### What is the expected result?
We see the response header.

### What do you get instead?
We have 200 status and no headers.

### Additional info
That is caused by a wrong condition in a Cors filter. 
https://github.com/yiisoft/yii2/blob/master/framework/filters/Cors.php#L109
We never get our options action running.
image

| Q                | A
| ---------------- | ---
| Yii version      | 2.15.1
| PHP version      | 7.1
| Operating system | Linux

### PR DESCRIPTION
**Pull request by ldar**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  |  #16044

### CODE REVIEW

**Comment by chenxigua** [comment]
dsafdsaf

**Comment by chenxigua** [comment]
good

**Comment by samdark** [comment]
I don't see it anywhere in the spec. What does that change?

**Comment by ldar** [comment]
Sorry. This is my incompetence. My problem can be solved in the configuration
            'cors' => [
                ...
                'Access-Control-Request-Headers' => ['authorization']
            ],

**Pull request closed without merging**
