### PR TITLE
Fix i18n dutch hours

### PR DESCRIPTION
**Pull request by dynasource**
addon #12609

### CODE REVIEW

**Comment by SilverFire** [comment]
Could you resolve the conflict?

**Review by ghost — APPROVED** [review]

**Comment by samdark** [comment]
Why closing?

**Comment by dynasource** [comment]
ehmm...wasnt it merged already? I did some local branches cleanup.

**Comment by samdark** [comment]
I think it was not :)

**Comment by dynasource** [comment]
hmmm...
I was under the conception that I had overwritten my initial commit by force, with I it was merged already.

**Comment by cebe** [comment]
Thanks!

**Pull request merged**
