### PR TITLE
UnauthorizedHttpException insted of ForbiddenHttpException

### PR DESCRIPTION
**Pull request by glagola**
Hi, why `yii/web/User::loginRequired()` throws `ForbiddenHttpException`? According to [wiki](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes):

> #### 401 Unauthorized
> 
> Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided. The response must include a WWW-Authenticate header field containing a challenge applicable to the requested resource. See Basic access authentication and Digest access authentication.
> #### 403 Forbidden
> 
> The request was a valid request, but the server is refusing to respond to it. Unlike a 401 Unauthorized response, authenticating will make no difference.

I think, `UnauthorizedHttpException` (401 http code) describes error more accurately,  in contrast to `ForbiddenHttpException` (403 http code).

### CODE REVIEW

**Comment by samdark** [comment]
Current status code describes it better i.e. there's no loginUrl specified so one basically can't login so it won't help trying. The message is misleading though.

**Comment by qiangxue** [comment]
The original code is correct. Unauthorized means you are authenticated but you are not authorized to perform an action.

**Comment by samdark** [comment]
@qiangxue I don't think it user is authenticated. The exception is there in case method is called and redirect route isn't specified.

**Comment by glagola** [comment]
@qiangxue 401 Unauthorized according to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) means user is **not authenticated**, here is the quote:
>The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource. The client MAY repeat the request with a suitable Authorization header field (section 14.8). If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials. If the 401 response contains the same challenge as the prior response, and the user agent has already attempted authentication at least once, then the user SHOULD be presented the entity that was given in the response, since that entity might include relevant diagnostic information. HTTP access authentication is explained in "HTTP Authentication: Basic and Digest Access Authentication"

**Comment by glagola** [comment]
@samdark Yes, if ```$this->loginUrl !== null```  user will be redirected to login page (where he can authenticate), if ``loginUrl === null``` client won't get any hint that he must be authenticated.

**Comment by glagola** [comment]
@samdark @qiangxue I'm just want to get semantically correct error, I'm developing REST API and it would be great to have an ability to show authentication form only by checking response's http-code, not text of error message.

**Comment by qiangxue** [comment]
Sorry, my explanation above is not correct.

Still, 401 is inappropriate because it is specifically used to respond with a `WWW-Authenticate`  HTTP header.

**Pull request closed without merging**
