### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by drodata**

### CODE REVIEW

**Comment by SilverFire** [comment]
Thank you!

**Comment by klimov-paul** [comment]
Original text was correct: 
> that takes the input from

meaning taking the input **from** model

**Comment by SilverFire** [comment]
@klimov-paul yes, you're right. Reverted the commit: https://github.com/yiisoft/yii2/commit/9691d3dcc117e37085cfb5e7701a334f04b9680c

**Comment by samdark** [comment]
I think the sentence is still incorrect.

**Comment by samdark** [comment]
I think it should be:

```
For filtering data the GridView needs a [model](structure-models.md) to take the input from and the filtering form that adjusts the query of the dataProvider to respect the search criteria.
```

**Comment by klimov-paul** [comment]
Sounds good

**Pull request merged**
