### PR TITLE
added tests for HelpController

### PR DESCRIPTION
**Pull request by dynasource**

### CODE REVIEW

**Comment by dynasource** [comment]
hmmm...these tests pass in PHPStorm

**Comment by samdark** [comment]
The reason is ANSI coloring. In PhpStorm console can't display ANSI codes so we're not generating these.

**Comment by samdark** [comment]
There's `Console::stripAnsiFormat()` that can help preparing output for comparison.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged.

**Pull request merged**
