### PR TITLE
Update AttributeTypecastBehavior

### PR DESCRIPTION
**Pull request by WinterSilence**
Optimize adding attributes in detectAttributeTypes()
Check owner class in events()

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by bizley** [comment]
This is breaking BC and it's limiting the usage described in the documentation for it. We cannot do this.

**Comment by WinterSilence** [comment]
@bizley how it can be BC?

**Comment by bizley** [comment]
We didn't allow this behavior to be used only on BaseActiveRecord classes.

**Comment by WinterSilence** [comment]
@bizley how you can handle BaseActiveRecord events in classes not extends BaseActiveRecord?

**Comment by bizley** [comment]
Just because the event names are defined in the BaseActiveRecord class it doesn't mean you cannot use with any other class.

**Comment by WinterSilence** [comment]
@bizley technically yes, but **we** don't recommend it:

> This behavior should be attached to [[\yii\base\Model]] or [[\yii\db\BaseActiveRecord]] descendant.

**Pull request closed without merging**
