### PR TITLE
fix rbac issue #9775

### PR DESCRIPTION
**Pull request by korvin0**
Very small fix, change from "empty" to "is_null"

### CODE REVIEW

**Comment by SilverFire** [comment]
What's the purpose of your fix?

**Comment by cebe** [comment]
> correct check - is_string && !empty

why? please elaborate about the problem, what are you doing and what is not working as you expect?

**Comment by korvin0** [comment]
Here https://github.com/yiisoft/yii2/issues/9775 the user complained that he has the role name === 0 and the function getItem doesn't work. By the way, it won't be work also with any permissions with name === 0.

**Comment by samdark** [comment]
Ah, I see. `0` is weird role name.

@cebe do you think it should be fixed?

**Comment by cebe** [comment]
if we want to allow 0 as a role name I am quite sure this is not the only place that needs to be changed. not sure if we should allow it.

**Comment by samdark** [comment]
Personally I see no point allowing it.

**Pull request closed without merging**
