### PR TITLE
Fix line break for output in console/widgets/Table.php

### LINKED ISSUE #18047: Console Table Widget width issue with colorized input
### What steps will reproduce the problem?
Use colorized input data in Table Widget rows.

### What is the expected result?
Width of columns should be calculated without console colorization markers.
[Correct Table](https://github.com/erkib/yii2-issues/blob/master/correct_table_widget_output.png)

### What do you get instead?
Messed up widths.
[Incorrect Table](https://github.com/erkib/yii2-issues/blob/master/incorrect_table_widget_output.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.4.5
| Operating system | OS X 10.15.4

### PR DESCRIPTION
**Pull request by issidorov**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️

With partial revert fix #18047.

### CODE REVIEW

**Comment by samdark** [comment]
What's the problem this pull request is fixing?

**Comment by issidorov** [comment]
Problem after #18047 :
image

**Comment by issidorov** [comment]
image

**Comment by schmunk42** [comment]
Is there a test for an ANSI colored string with non-latin chars, like in the screenshot?

**Comment by issidorov** [comment]
image

**Comment by issidorov** [comment]
Screenshot for working code from #16831

image

**Comment by issidorov** [comment]
But has others bugs, example

image

**Comment by cebe** [comment]
here is a failing test I wrote when creating #16831: https://github.com/cebe/yii2/commit/ea4b97b79e1b60416d44a4719350ee27c3402146

you can cherry-pick that onto your branch if you want.

**Comment by issidorov** [comment]
@cebe, thank you. I have already written similar tests. Perhaps someone will add them later.

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
