### PR TITLE
Fixed #12822: Datetime creation from microseconds in i18n\Formatter

### LINKED ISSUE #12822: Exception when using datetime-formatting of log_time
I'm logging errors using Yii/log/DbTarget with the default migration for mysql.
Then I use yii\widgets\DetailView to display the log, and added a datetime-formatter to the attribute log_time, like this:

```
'log_time:datetime',
```

This causes errors occasionally like this...

```
exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (@1477307739.608) at position 12 (6): Unexpected character' in C:\...\vendor\yiisoft\yii2\i18n\Formatter.php:675
Stack trace:
#0 C:\...\vendor\yiisoft\yii2\i18n\Formatter.php(675): DateTime->__construct('@1477307739.608', Object(DateTimeZone))
#1 C:\...\vendor\yiisoft\yii2\i18n\Formatter.php(594): yii\i18n\Formatter->normalizeDatetimeValue('<span class="nu...')
#2 C:\...\vendor\yiisoft\yii2\i18n\Formatter.php(557): yii\i18n\Formatter->formatDateTimeValue('<span class="nu...', '<span class="st...', '<span class="st...')
#3 [internal function]: yii\i18n\Formatter->asDatetime('<span class="nu...')
 #4 C:\...\vendor\yiisoft\yii2\i18n\Formatter.php(316): call_user_func_array('[<span class="t...', '[<span class="n...')
```

The attribute log_time is defined as a double in the database (defined in default migration) but the yii/i18n/Formatter seems to fail whenever the attribute value does not have exactly 4 decimals.

   $a = new Datetime("@1477307739.6080");  // ok
   $b = new Datetime("@1477307739.608");  // fails

When logging errors, eg using Yii::error(), the timestamp will sometimes end with a zero, which then is truncated when saved as a double in the database. 

This behaviour might be a bug in PHP, but it could be corrected if the Formatter did some zeropadding to reach 4 decimals.

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.6.27 |
| Operating system | Win10 |

### PR DESCRIPTION
**Pull request by h311ion**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #12822 |

Fixed datetime creation from microseconds, added tests to \i18n\Formatter::asTimestamp

### CODE REVIEW

**Review by SilverFire — CHANGES_REQUESTED** [review]
composer.lock should be excluded from the PR.

Could you add a line to CHANGLOG.md?

**Comment by SilverFire** [comment]
Good PR otherwise

**Review by samdark — APPROVED** [review]
Good one except what @SilverFire suggested. Please fix it.

**Comment by SilverFire** [comment]
Merged a24abb09909e724f058613403061ed6c366f9e1d

**Comment by SilverFire** [comment]
Thank you!

**Pull request closed without merging**
