### PR TITLE
Update phpdoc.

### PR DESCRIPTION
**Pull request by wirwolf**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | comma-separated list of tickets # fixed by the PR, if any |

If i extend this class

```
class UploadedFile extends \yii\web\UploadedFile

```

and i use my function, IDE not see my method

### CODE REVIEW

**Comment by klimov-paul** [comment]
`$this` can not be used as return type for static methods.

**Comment by cebe** [comment]
should be `static` instead.

**Comment by samdark** [comment]
Hmm. Seems PhpStorm isn't good with `static[]`.

**Comment by cebe** [comment]
there are a few bugs related to this. not sure if this specific case is covered there though https://youtrack.jetbrains.com/issues/WI?q=return+static+%23Open+

**Comment by mdmunir** [comment]
`@return $this` does not work in netbeans if method defined in trait.
screenshot from 2016-04-10 10 54 36
after `limit()`
screenshot from 2016-04-10 10 55 35
`limit()` is defined in `QueryTrait` https://github.com/yiisoft/yii2/blob/master/framework/db/QueryTrait.php#L373

Should i create new issue?

**Comment by cebe** [comment]
report it to Netbeans.

**Comment by mdmunir** [comment]
@cebe 
> report it to Netbeans.

can solve using `@return $this|static`

**Comment by wirwolf** [comment]
I use inetlij idea

**Comment by samdark** [comment]
Closed since IDEs support isn't good for now.

**Pull request closed without merging**
