### PR TITLE
Yii class `include` cass replaced to `require` + CS fix

### PR DESCRIPTION
**Pull request by creocoder**

### CODE REVIEW

**Comment by cebe** [comment]
Why do we need require here? classmap is not critical so a fatal error seems unneeded.

**Comment by creocoder** [comment]
@cebe Any error here is bad thing. Does not matter critical or not. Also class map is about perfomance. If production server display_errors is Off for example than it just ignore this kind of error and application will work with lower perfomance. I see no any use cases for `include` for nova-day applications.

**Comment by cebe** [comment]
well, application will then run instead of showing blank screen and the error will be in the logs.
It is a very rare case but I see no reason in switching to require in this case.

**Comment by creocoder** [comment]
@cebe Lets imagine this from other side. Realize there was `require` always and i made PR to switch it to `include` ;) What reason? To silently ignore rare possible perfomance drawback? All i want to say `include` does not give us anything instead of drawback. Even in case when display error is On you'll see error. How does it matter that application will not stop to work in that case? Moreover since you said its very rare case how `include` help in anything even if you see silent ignorance as benefit. But most important thing here is that *require is faster than include* ;)

**Comment by cebe** [comment]
I'm convinced, thanks!

**Pull request merged**
