### PR TITLE
fix docs [skip ci]

### LINKED ISSUE #10903: migration add column with --fields
```console
yii migrate/create add_status_to_budget --fields=status:integer(1):notNull
```

```php
<?php

use yii\db\Migration;

class m160218_220920_add_status_to_budget extends Migration
{
    public function up()
    {
        $this->addColumn('budget', 'status', $this->integer());
    }

    public function down()
    {
        $this->dropColumn('budget', 'status');
    }
}
```

why the generated code not

```php
$this->addColumn('budget', 'status', $this->integer(1)->notNull);

```

### PR DESCRIPTION
**Pull request by pana1990**
Fix #10903

### CODE REVIEW

**Comment by samdark** [comment]
Thanks!

**Comment by muhammadcahya** [comment]
@pana1990 @samdark 
I write like in documentation `yii migrate/create create_post --fields='title:string,body:text'` in console
And this is generated code :
```php
<?php

use yii\db\Migration;

class m160221_014001_create_post extends Migration{
    public function up(){
        $this->createTable('post', [
            'id' => $this->primaryKey(),
            ''title' => $this->string(),
            'body' => $this->text'()
        ]);
    }

    public function down(){
        $this->dropTable('post');
    }
}

```

**Comment by pana1990** [comment]
@muhammadcahya What operating system are you using ?

**Comment by muhammadcahya** [comment]
Windows 7 X64
Php 5.6
Yii 2.0.7

**Comment by pana1990** [comment]
@samdark  @muhammadcahya Can you check double quotes workss (Linux, Windows and Mac)?

**Comment by muhammadcahya** [comment]
Ok, double quotes is works :+1: 
`yii migrate/create create_post --fields="title:string,body:text"`
```php
<?php

use yii\db\Migration;

class m160221_022252_create_post extends Migration{
    public function up(){
        $this->createTable('post', [
            'id' => $this->primaryKey(),
            'title' => $this->string(),
            'body' => $this->text()
        ]);
    }

    public function down(){
        $this->dropTable('post');
    }
}
```

_checked in windows_

**Comment by cebe** [comment]
works on Debian Linux with `bash` and `sh`.

**Comment by muhammadcahya** [comment]
Ok, waiting for _Mac_

**Comment by cebe** [comment]
should be the same.

**Comment by pana1990** [comment]
@cebe Should we change single quotes to double quotes ?

**Comment by samdark** [comment]
Yes.

**Comment by pana1990** [comment]
@samdark  ready :) https://github.com/yiisoft/yii2/pull/10928

**Pull request merged**
