### PR TITLE
Fix for #17797, activeListInput options

### PR DESCRIPTION
**Pull request by alex-code**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17797

### CODE REVIEW

**Comment by samdark** [comment]
Seems to fail tests...

**Comment by alex-code** [comment]
My bad, had the wrong function which passed the `HtmlTest` I checked,

**Comment by mikehaertl** [comment]
@samdark As commented in #17797 I'd say that the current behavior is fine. If you want to set attributes for the input elements, you can use `itemOptions`. This change will break BC.

**Comment by alex-code** [comment]
@mikehaertl I think you've misunderstood.
This PR stops invalid attributes being added to the `<div/>` element.

**Comment by mikehaertl** [comment]
@alex-code Right, now I see. It's about the specific attributes `name` and `value`. I think the change is fine then. But there is one edge case: If someone used this to set exactly these attributes on the `<div>` (e.g. for some javascript or whatever) it will no longer work. So IMO it's a minor but acceaptable BC break. Not sure if it's worth an upgrade note.

**Comment by alex-code** [comment]
@mikehaertl Might be worth a note.
@samdark Do you want me to add a note?

**Comment by rob006** [comment]
`name` and `value` attributes are not valid for `div` tag. No one should rely on this, note in changelog should be enough.

**Comment by mikehaertl** [comment]
> name and value attributes are not valid for div tag. No one should rely on this, note in changelog should be enough.

Can you point me to a source for this? Never heard before that `<div name="myname">` should be invalid.

**Comment by alex-code** [comment]
A `<div/>` element is allowed global attributes and (`class`, `id` and `slot`).
https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element
https://html.spec.whatwg.org/multipage/dom.html#global-attributes

**Comment by mikehaertl** [comment]
@alex-code Does this really say, that it MUST NOT have any other attribute? I admit, that I've never heard that before. And I'd assume many other developers also. So why not put an update notice just to make sure? Yii2 is very old now and there is a pletora of apps out there. We should be friendly with our devs and not break their apps - even if the use an attribute that may not be perfect in line with the specs.

**Comment by rob006** [comment]
> Does this really say, that it MUST NOT have any other attribute?

This spec whitelists allowed attributes - if it is not on the list of allowed attributes, then it is not allowed. For example https://validator.w3.org/ reports this as an error.

**Comment by mikehaertl** [comment]
Ok, I'm convinced now, thanks for pointing that out.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
