### PR TITLE
Revert DI injection via controller action method signature

### PR DESCRIPTION
**Pull request by cebe**
reverts b7020065c and related commits.
reverts implementation of #9476

For reasons, see discussion https://github.com/yiisoft/yii2/issues/9476#issuecomment-179749039

### CODE REVIEW

**Comment by SilverFire** [comment]
:+1:

**Comment by klimov-paul** [comment]
:+1:

**Comment by samdark** [comment]
OK for me for the reasons described in https://github.com/yiisoft/yii2/issues/9476#issuecomment-180973833

**Comment by samdark** [comment]
Found additional changes.

**Comment by samdark** [comment]
Looks fine to me now.

**Comment by samdark** [comment]
@mdmunir tests are handy.

**Pull request merged**
