### PR TITLE
Speedup Schema::findColumns() for mssql

### PR DESCRIPTION
**Pull request by paulzi**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

20x faster implementation of query in \yii\db\mssql\Schema::findColumns()

### CODE REVIEW

**Comment by samdark** [comment]
Are there new features used?

**Comment by paulzi** [comment]
@samdark , no. I just rewrite the SQL query, and made three changes:
1) convert JOIN to subquery
2) change table name condition
```OBJECT_NAME([t2].[major_id]) = [t1].[table_name]```
to object id condition
```[t2].[major_id] = OBJECT_ID([t1].[TABLE_SCHEMA] + '.' + [t1].[table_name])```
3) re-sorted the conditions for better performance (bad work of SQL SERVER optimizer)

Results:
slow
fast

**Comment by paulzi** [comment]
@samdark, can you accept this request in the release 2.0.12?

**Comment by samdark** [comment]
Yes. In order to do that we need more feedback from the ones using MSSQL.

**Comment by o-rey** [comment]
Works fine, thanks Paul.

**Comment by WebdevMerlion** [comment]
We have same problem:
your variant
yourvariant
Our variant
myvariant

**Comment by sergeymakinen** [comment]
Let the optimization battle begin! :)

I could review those next week if needed (as I'm also working on constraint's SQL queries).

**Comment by paulzi** [comment]
@WebdevMerlion , can i include your optimization in the pull-request?

**Comment by WebdevMerlion** [comment]
@paulzi  Ок. But this request for MS SQL Server 2005 or higher.

P.S. Variant without dinamicaly SQL:
```
SELECT
       fk.[name] as [fk_name]
       ,cp.[name] as [fk_column_name]
       ,OBJECT_NAME(fk.[referenced_object_id]) as [uq_table_name]
       ,cr.[name] as [uq_column_name]
FROM sys.foreign_keys fk (nolock)
inner join sys.foreign_key_columns fkc (nolock)
       ON fk.[object_id] = fkc.[constraint_object_id]
inner join sys.columns cp (nolock)
       ON fk.[parent_object_id] = cp.[object_id]
             AND fkc.[parent_column_id] = cp.[column_id]
inner join sys.columns cr (nolock)
       ON fk.[referenced_object_id] = cr.[object_id]
             AND fkc.[referenced_column_id] = cr.[column_id]
WHERE fk.[parent_object_id] = OBJECT_ID('Service Center$auth_assignment')
       AND OBJECT_SCHEMA_NAME(OBJECT_ID('Service Center$auth_assignment')) = 'dbo'
```

**Comment by paulzi** [comment]
@WebdevMerlion, As I understand, sys.extended_properties used in Schema::findColumns current version (2.0.12) already [requires SQL Server 2008](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/extended-properties-catalog-views-sys-extended-properties)

**Comment by samdark** [comment]
Seems no more enhancements are going to be made for now. Is it ready?

**Comment by paulzi** [comment]
yes

**Comment by samdark** [comment]
Merged. Thank you very much!

**Comment by sergeymakinen** [comment]
@samdark Sorry, I was busy at my main job to review… But it’s like the code I currently use to get all table constraints, so LGTM.

Thanks, @paulzi & @WebdevMerlion!

**Pull request closed without merging**
