### PR TITLE
fix name method

### PR DESCRIPTION
**Pull request by pana1990**

### CODE REVIEW

**Comment by SilverFire** [comment]
Hm.. it seems that we do not have a convention on this.
Both options are OK to me.

**Comment by pana1990** [comment]
which one? optionAliases or optionsAliases? both is ok for me.

**Comment by SilverFire** [comment]
For me too. Why do you want to rename it then? :)

**Comment by pana1990** [comment]
Currently method name is "optionAliases" (see https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L319). it cause error in HelpController (see https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/HelpController.php#L424). 

Can you understand me?

**Comment by SilverFire** [comment]
Sorry, I've overseen it.

**Comment by pana1990** [comment]
thanks :)

**Pull request merged**
