### PR TITLE
Code Climate PHPMD settings

### PR DESCRIPTION
**Pull request by bizley**
I have recently started using Code Climate for my project as well and I have noticed that PHPMD settings taken from Yii 2 file are not met. You can verify this by looking at [Code Climate Yii 2 analysis](https://codeclimate.com/github/yiisoft/yii2).

Based on the CC and PHPMD docs I've prepared separate PHPMD ruleset that appears to work.  
This set contains all rules previously listed in `checks` and in addition it excludes `naming.xml\BooleanGetMethodName` which states

> Method which returns a boolean should be named 'is...()' or 'has...()'

since it conflicts with Yii 2 component's getters.

### CODE REVIEW

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
Thank you, @bizley 
The changes look good to me.

**Comment by cebe** [comment]
Great, thanks! Could we move that file sowhere into `tests` folder to not clutter the root more than necessary? Maybe `tests/data/codeclimate`?

**Comment by bizley** [comment]
Docs state the path is relative so it should work. Would like me to move it?

**Comment by cebe** [comment]
if you have the time, do it :)

**Comment by bizley** [comment]
Moved, looks like CC is ok with it.

**Comment by cebe** [comment]
> codeclimate — Code Climate found 243 fixed issues.

sounds great :-D

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
