### PR TITLE
Use separate driver for DBLib connections due to transaction issues

### LINKED ISSUE #18480: Transactions are not committed using the dblib driver
### What steps will reproduce the problem?
Create database handle by using de dblib driver, using the following parameters:
```
[
    'class'               => 'yii\db\Connection',
    'dsn'                 => 'dblib:version=7.2;host=myHost;dbname=myDB',
    'username'            => 'myUsername',
    'password'            => 'myPassw0rd',
];
```

excute the following code:
```
$transaction = Yii::$app->db->beginTransaction();;
var_dump(Yii::$app->db->pdo->inTransaction());
$transaction->rollback();
```

### What is the expected result?
`true`

### What do you get instead?
`false`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.4
| Operating system | CentOS

Fix https://github.com/yiisoft/yii2/commit/cafe8e315cc9410e1116141b8256e22b1d1834dc broke transactions completely for database connections using the dblib driver.
There is a check for an active transaction now:https://github.com/yiisoft/yii2/blob/0781b02cc355b171e2eb544bc7897bc458ec56d8/framework/db/Transaction.php#L168
But since `inTransaction` returns false for dblib connections, no commit will be done, resulting in an automated rollback.

The reason for `inTransaction` to return false is that the transaction is not started with `beginTransaction` but with the SQL command 'START TRANSACTION` (see https://www.php.net/manual/en/pdo.intransaction.php#125087)

I've tested this by commenting out the `beginTransaction` method in de mssql pdo component: 
https://github.com/yiisoft/yii2/blob/0781b02cc355b171e2eb544bc7897bc458ec56d8/framework/db/mssql/PDO.php#L34
With this method commented out (thus using the native pdo beginTransaction), `inTransaction` correctly returns true now.
The comment at this method states "_It is necessary to override PDO's method as MSSQL PDO driver does not natively support transactions._" 
I wonder if this is still true, because the native pdo beginTransaction just seems to work fine.

### PR DESCRIPTION
**Pull request by BBrunekreeft**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18480

The DBLib driver seems to support the native PDO beginTransaction, commit and rollback statements.
This PR should resolve #18480.
Tested with transactions on my own test environment.

### CODE REVIEW

**Comment by samdark** [comment]
Looks alright. Please add a line to CHANGELOG.md

**Comment by bizley** [comment]
Maybe we could add tests with dblib driver?

**Comment by samdark** [comment]
Ideally yes but I have no idea on how to set it up in GitHub actions.

**Comment by BBrunekreeft** [comment]
Changelog line added

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
