### PR TITLE
Allow DI references in array in dependencies

### PR DESCRIPTION
**Pull request by hiqsol**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️

Extremely needed for handler maps and like.
Example container config:

```php
return [
    ContentTypeMiddleware::class => [
        '__construct()' => [
            Instance::of(StreamFactory::class),
            [
                'json' => Intance::of(JsonFormatter::class),
                'yaml' => Intance::of(YamlFormatter::class),
            ],
        ],
    ],
];
```

I'll add tests if the idea is ok.
Also same stuff can be implemented in `yiisoft/di`

### CODE REVIEW

**Comment by hiqsol** [comment]
Added test.

**Review by xepozz — APPROVED** [review]
:+1:

**Review by samdark — APPROVED** [review]
Looks good. We need a line for CHANGELOG.md.

**Comment by samdark** [comment]
Thank you!

**Comment by DmLapin** [comment]
This commit fully breaked our Codeception tests. If I remove
```
elseif (is_array($dependency)) {
    $dependencies[$index] = $this->resolveDependencies($dependency, $reflection);
}
```
tests go OK.

First of all, it **IS** breaking change a-priory. You change behaviour of `\yii\di\Container::resolveDependencies`.

Problem starts here: `vendor/codeception/codeception/src/Codeception/Lib/Connector/Yii2.php:75`. We have application config like this:
```
return [
...
    'definitions' => [
        common\interfaces\NewsletterEmailGeneratorInterface::class => [
            ['class' => common\components\newsletter\NewsletterEmailGenerator::class],
            [
                di\Instance::of(web\View::class),
                di\Instance::of('internalFilesystem'),
...
```
Your recursive resolveDependencies call try get 'internalFilesystem' component, but **it's not configured in DI Container on this stage**! We got:
`[yii\base\InvalidConfigException] Failed to instantiate component or class "internalFilesystem".`

Example of stack trace:
```
 Test  unit/commands/news/news_domain/NewsBorrowCommandTest.php:testInvalidData

  [yii\base\InvalidConfigException] Failed to instantiate component or class "internalFilesystem".

.../vendor/yiisoft/yii2/di/Container.php:449
.../vendor/yiisoft/yii2/di/Container.php:447
.../vendor/yiisoft/yii2/di/Container.php:374
.../vendor/yiisoft/yii2/di/Container.php:159
.../vendor/yiisoft/yii2/di/Container.php:484
.../vendor/yiisoft/yii2/di/Container.php:491
.../vendor/yiisoft/yii2/di/Container.php:491
.../vendor/yiisoft/yii2/di/Container.php:491
.../vendor/yiisoft/yii2/di/Container.php:491
.../vendor/yiisoft/yii2/di/Container.php:395
.../vendor/yiisoft/yii2/di/Container.php:159
.../vendor/yiisoft/yii2/BaseYii.php:365
.../vendor/codeception/codeception/src/Codeception/Lib/Connector/Yii2.php:75
.../vendor/codeception/codeception/src/Codeception/Lib/Connector/Yii2.php:53
.../vendor/codeception/codeception/src/Codeception/Module/Yii2.php:185
.../vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
```

**Comment by samdark** [comment]
Please report separately. It's going to be lost as a comment to a closed issue. Thanks.

**Pull request merged**
