### PR TITLE
修复无效链接

### PR DESCRIPTION
**Pull request by zomboo**
如果你要开发一个更复杂的应用，可以更好地适用于团队开发环境的，可以考虑安装高级应用模版。修复此处最后的无效链接。

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by larryli** [comment]
@zomboo 那边文档也有本地化： https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide-zh-CN/README.md

**Comment by zomboo** [comment]
为何我之前点开页面链接提示404，所以我才提交了修改。------------------ 原始邮件 ------------------发件人: Larry Li  <notifications@github.com>发送时间: 2018年3月29日 14:07收件人: yiisoft/yii2 <yii2@noreply.github.com>抄送: zomboo <zomboo@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[yiisoft/yii2] 修复无效链接 (#16003)@zomboo 那边文档也有本地化： https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide-zh-CN/README.md

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yiisoft/yii2","title":"yiisoft/yii2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yiisoft/yii2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@larryli in #16003: @zomboo 那边文档也有本地化： https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide-zh-CN/README.md"}],"action":{"name":"View Pull Request","url":"https://github.com/yiisoft/yii2/pull/16003#issuecomment-377131896"}}}

**Comment by samdark** [comment]
There's http://www.yiichina.com/ with docs translation. I have no idea who did the translation itself. Based on commits, that's @cuileon. These docs there are more up to date then what we have in the repository. Is it possible to somehow merge these changes into official repository?

**Comment by zomboo** [comment]
how to merge ？

**Comment by zomboo** [comment]
ok…

**Comment by cuileon** [comment]
Hi, @samdark , I'm the webmaster of yiichina.com, yiichina/yii2 is forked from yiisoft/yii2. Whenever the official version is released, will be merged from the official. Our translators are all members of yiichina community, with high quality and cultural level, we will proofread after the translation, we guarantee the quality of translation. After this week's translation, a pull request will be submitted to the official yiisoft/yii2

**Pull request closed without merging**
