### PR TITLE
Add support parameters with default values for DI to constructor

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18304

### CODE REVIEW

**Comment by samdark** [comment]
@vjik would you please rebase it?

**Comment by vjik** [comment]
> @vjik would you please rebase it?

Done

**Comment by samdark** [comment]
@vjik seems it doesn't play well with https://github.com/yiisoft/yii2/commit/23cfb38ceaab5d378c5e9ee577fbc3b8a685fbeb. Would you please check it?

**Comment by vjik** [comment]
> @vjik seems it doesn't play well with [23cfb38](https://github.com/yiisoft/yii2/commit/23cfb38ceaab5d378c5e9ee577fbc3b8a685fbeb). Would you please check it?

Done

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Comment by TyRun555** [comment]
I have a class ProjectAccess (extending yii\base\Component) with constructor:
`public function __construct(?Project $model = null, int $userId = null)
    {
        parent::__construct();
        $this->project = $model ?? Project::findOne(Yii::$app->request->get('id'));
        $this->setUser($userId);
        $this->accessObjects = ProjectAccessObjects::find()->all();
    }`

And mention it as component in config:
`'projectAccess' => [
            'class' => ProjectAccess::class
        ],`

If i use ProjectAccess like component (Yii::$app->projectAccess), $model var in constructor aren't null, it's an empty Project object. So i can't handle parameter with null default value ?

How to get back previous behavior ?

**Comment by samdark** [comment]
@TyRun555 we'll handle it soon. Meanwhile, roll back to previous release.

**Comment by vjik** [comment]
@TyRun555, @samdark is right — that's bad way to use component. But if you still need it, try set component in config so:

```php
'components' => [
	'projectAccess' => function(){
		return new ProjectAccess();
	},
],
```

**Comment by TyRun555** [comment]
@samdark , @vjik thx for your answers, It helps. I'll refactor component and write the method. Just want some automation magic)

**Pull request merged**
