### PR TITLE
Add getRolesByRole() to RBAC to fetch the child Roles of a Role

### PR DESCRIPTION
**Pull request by michaelarnauts**
See #11245.

I haven't tested the `getRolesByRole` of `PhpManager`, but it is almost identical to the `getPermissionsByRole`, so I guess it should work.

### CODE REVIEW

**Comment by samdark** [comment]
Could you create a unit test for it?

**Comment by mikk150** [comment]
```php
/**
     * [getChildRoles description]
     * @param  string $parentRole parent role
     * @return yii\rbac\Role[] roles
     */
    public function getChildRoles($parentRole)
    {
        $roles = [];

        $childRoles = array_keys(array_filter($this->childrenList, function ($childrens) use ($parentRole) {
            return in_array($parentRole, $childrens);
        }));
        return array_filter($this->roles, function ($role) use ($childRoles) {
            return in_array($role->name, $childRoles);
        });

        return $roles;
    }
```
should be the same but without query?

**Comment by michaelarnauts** [comment]
@mikk150 `getRolesByRole` is recursive, `getChildRoles` is not. The function is working the same as the `getPermissionsByRole`.

**Comment by samdark** [comment]
@michaelarnauts so how about a unit test?

**Comment by LAV45** [comment]
Maybe we should add phpunit tests?

**Comment by samdark** [comment]
We definitely should.

**Comment by LAV45** [comment]
That did not work then as there => https://github.com/yiisoft/yii2/pull/11033/files

**Comment by samdark** [comment]
?

**Comment by mikk150** [comment]
@michaelarnauts maybe getting it not recursive is a good thing(I actually need it to be not recursive)
If it is not recursive you could make admin panel out of it and show exactly where particular role comes

**Comment by michaelarnauts** [comment]
@mikk150 indeed. I've forgot about this PR. We've used the non-recursive approach (by just using `getChildRoles()` for the admin panel. Then I then wanted to use this to check if a user has a specific Role, but aparently, you can also use the `checkAccess()` for that, so the code in this requrst is not needed anymore.

**Comment by LAV45** [comment]
Походу психанул.

**Comment by mikk150** [comment]
Maybe I'll open PR for getChildRoles()

**Pull request closed without merging**
