### PR TITLE
[Alternative] Fix #9101 resolve appendTimestamp to registerJsFile and registerCssFile 

### LINKED ISSUE #9101: AssetManager appendTimestamp not working if you use registerJsFile()
Timestamp is appended only if you create your own bundle. This is too complicated if you just want to register on JS file on certain page.

`registerJsFile()` creates bundle inside, but does not fill the `basePath`. I guess this is the reason timestamp is not appended.

### PR DESCRIPTION
**Pull request by githubjeka**
This just sketch, for [the discussion](https://github.com/yiisoft/yii2/pull/10297).

### CODE REVIEW

**Comment by saada** [comment]
@githubjeka, this approach is a lot better than where I was heading IMO. Thank you!

**Comment by githubjeka** [comment]
Thank you too.

**Comment by githubjeka** [comment]
I cant merge with master because https://github.com/yiisoft/yii2/commit/01a6235059027c6ab692b86523118498f77055d7#commitcomment-15105103

**Comment by SilverFire** [comment]
It seems, that the PR was overseen, sorry. Will try to verify it

**Comment by SilverFire** [comment]
Sorry for a long delay. Merged: dc23a6d3d8a9cd937cbbc64652db903ee4ff5598 Thank you!

**Comment by SilverFire** [comment]
Reverted 3ec3ce931216a44ec0b850c429c9d8c7f9a17e6d

**Comment by sazo** [comment]
@SilverFire Its stands in the change log for 2.0.10 that #9101 is fixed but it is not. What happens now? is a new PR the way to go or do we fix this one?

**Comment by cebe** [comment]
> @SilverFire Its stands in the change log for 2.0.10 that #9101 is fixed but it is not. What happens now? is a new PR the way to go or do we fix this one?

sorry, I have removed the changelog entry: 40394b8abf18e808253bed809a1df361cd7e3f76

It is questionable if View should depend on AssetManager in this way. If you want functionality of AssetManager it may be better to use an AssetBundle instead of registering the file directly.

**Pull request closed without merging**
