### PR TITLE
Add maxlength attribute to text filter for #18200 issue

### PR DESCRIPTION
**Pull request by rad8329**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️ It's labeled as a bug, however I don't think so
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18200

Filter text field within `maxlength` attribute in tag to add double-check validation (HTML element and model rule)

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks alright. Would you please add a line for CHANGELOG?

**Comment by rad8329** [comment]
> Looks alright. Would you please add a line for CHANGELOG?

It is done

**Comment by bizley** [comment]
Move it up, to 2.0.40 section.

**Comment by rad8329** [comment]
> Move it up, to 2.0.40 section.

Sorry, I didn't realize that milestone was 2.0.40

**Comment by samdark** [comment]
👍

**Pull request merged**
