### PR TITLE
ExistValidator for relations

### PR DESCRIPTION
**Pull request by developeruz**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #8092

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Review by SilverFire — CHANGES_REQUESTED** [review]
Generally good.
It seems that `validateAttribute()` method complexity is increasing. I think we should split it to a couple of more specific, e.g. `checkTargetRelationExistance()` and `checkTargetAttributeExistance()`.

The names are not final.

**Comment by dynasource** [comment]
this PR leads to a Single Responsibility violation. IMO, this should be implemented with a RelationExistsValidator. Its already getting confusing when which Validation logic will apply.

**Comment by developeruz** [comment]
@samdark , @SilverFire do you agree it should be a new validator?

**Comment by cebe** [comment]
@dynasource I do not agree, as far as I see `targetRelation` is just another way of setting `targetClass` and `targetAttribute` so a new class would duplicate a lot of the functionality.

**Comment by rob006** [comment]
This requires #13618 to work properly:
```php
$model->relation_id = 1;
$model->validate();
$model->relation_id = 2;
$model->validate(); // validation uses old relation for $model->relation_id = 1
```

**Comment by SamMousa** [comment]
@cebe 
>  I do not agree, as far as I see targetRelation is just another way of setting targetClass and targetAttribute so a new class would duplicate a lot of the functionality.

Can't this new class just extend the ExistValidator and configure it correctly?

**Comment by cebe** [comment]
@SamMousa that is a good idea! :)

**Comment by Faryshta** [comment]
how about something like

```php
class ExistRelationValidator extends ExistValidator
{
     public $relationName;

     public function validateAttribute($model, $attribute)
     {
           $relationQuery = $model->getRelation($this->relationName);
           // exception will be thrown if relation is invalid.
           $this->targetClass = $relationalQuery->modelClass;
           $this->targetAttribute = $relationalQuery->link;
           return parent::validateAttribute($model, $attribute);
     }
}
```

Maybe add some php doc to `$targetClass` and `$targetAttribute` properties that they will be overwritten by the relation defined in `$relationName`.

This would also solve the issue presented by @rob006

**Comment by SamMousa** [comment]
I'll make a PR, have something simpler in mind.

**Comment by samdark** [comment]
@yiisoft/reviewers need reviews.

**Comment by rob006** [comment]
I still think that #13618 should be merged first to avoid weird bugs with cached relations on validation.

**Comment by samdark** [comment]
#13618 is now merged. @SamMousa do you remember what was that simpler variant you were writing about?

**Comment by SamMousa** [comment]
Yes, the idea was to use the relation definition itself as parameter.
````
[['author_id'], RelationExistValidator::class, 'relation'=> $this->getAuthor()]
````

And then:
````
public function init() {
    parent::init();
    $this->targetClass = $this->query->modelClass;
// Add some checks here for exception cases where there are multiple link thingies.
    $this->targetAttribute = key($this->query->link)
    // Add any other query filters to
    $this->filter = $this->query->where;
}
````

This is by heart untested and not 100% sure if this was the exact original idea.

**Comment by samdark** [comment]
What's the benefit compared to using relation name?

**Comment by SamMousa** [comment]
Type checking / IDE auto complete

**Comment by samdark** [comment]
Well, the con I see is that Query is being built at configuration time instead of validation time...

**Comment by samdark** [comment]
That could affect `index` type of actions significantly...

**Comment by SamMousa** [comment]
That's a fair point; valuable thing is the configuration of the validator so using name is fine as well.

Note that instantiation in php is fairly cheap though, and validators themselves already are lazily loaded.

**Comment by samdark** [comment]
Right but for a 100 ARs per page 100 extra inits for validators may be significant.

**Comment by SamMousa** [comment]
But you don't initialize them unless you validate them?

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by samdark** [comment]
We do. A call to relation inits the relation class.

**Comment by berosoboy** [comment]
I noticed that it checks for the relation existence with
`if (empty($model->{$this->targetRelation})) {` .
It will fetch the relation's row(s) in memory?  If so, it wouldn't better to check with a `->exists()` call?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/15647

**Pull request merged**
