### PR TITLE
Fix #6043 Added support for array type styles and classes

### LINKED ISSUE #6043: Add support for array type styles.
Currently the Html functions interpret the style option as a string.
In reality a css string is a set of key value pairs.
Currently BaseHtml::renderTagAttributes makes an exception for the data attribute and json encodes that  if it is an array.
I propose to add similar functionality for the style attribute:
- If it is an array simply iterate over the keys and values and create the css string.

### PR DESCRIPTION
**Pull request by klimov-paul**
Fix #6043 Added support for array type styles and classes.
BC kept.

Pay attention for unit test `HtmlTest::testMergeCssClass()`: it demonstrates the solution for issues like:
#8229
#4916

https://github.com/yiisoft/yii2-bootstrap/pull/15

### CODE REVIEW

**Comment by samdark** [comment]
Nice!

**Comment by alexandernst** [comment]
Nice to see this :)
Should I close #8229 @cebe @klimov-paul ?

**Comment by klimov-paul** [comment]
First of all, the whole team should accept the approach.
Then we need to decide, which key should be used for classes added by Yii.
I whould like to use 'widget' for the classes added by widgets.

**Comment by alexandernst** [comment]
Attention ping @yii-devs :)
This is something quite important, imho, so the sooner it gets discussed and merged, the better.

**Comment by samdark** [comment]
Well, I like the approach. @qiangxue, @cebe thoughts?

**Comment by cebe** [comment]
looks great to me :)

**Comment by klimov-paul** [comment]
Relates: https://github.com/yiisoft/yii2-bootstrap/pull/52

**Pull request merged**
