### PR TITLE
Simplifies customization for specific items in radio|checkbox lists [resolves #7453]

### LINKED ISSUE #7453: Very complex method used to disable single checkbox in ActiveField::checkboxList()
In Yii 1.x to disable single checkbox in checkboxList we did following:

```
$form->checkBoxList($model, 'items', $selected, array(
  'options' => array(
       'value1'=>array('disabled'=>true),
   ),
));
```

In Yii 2.x we must use Closures to override checkbox rendering:

```
$form->field($model, 'items')->checkboxList($options, [
    'item' => function($index, $label, $name, $checked, $value){
        $disable = false;
        if ($value == 'value1') {
            $disable = true;
        }

        $checkbox = Html::checkbox($name, $checked, ['value' => $value, 'disabled' => $disable]);
        return Html::tag('div', Html::label($checkbox . $label), ['class' => 'checkbox']);
    }
]);
```

I think its very complicated to customize checkboxList now. Maybe we need back to Yii 1.x style in this case?

### PR DESCRIPTION
**Pull request by sdlins**
#7453 is under discussion. If my proposal is accepted, this PR can be merged.

### CODE REVIEW

**Comment by sidtj** [comment]
Please @cebe, could you check the discussion?
Thnx

**Comment by creocoder** [comment]
Vote against by lot of reasons listed start from here https://github.com/yiisoft/yii2/issues/7453#issuecomment-76326915

**Comment by sidtj** [comment]
Hi @creocoder,

Basically this is the same before but now it keeps the consistence for using `options` instead of `customItems`.

**Comment by creocoder** [comment]
@sidtj Now it looks amazing! But seems you forget about merging specific options with default item options.

**Comment by sidtj** [comment]
I found that refactoring other methods would not be necessary nor productive (for now).

**Comment by sidtj** [comment]
@creocoder, what exactly do you mean? Could you give an example?

**Comment by creocoder** [comment]
@sidtj Nevermind, i checked implementation, all fine with merging. Looks great!

**Comment by sidtj** [comment]
Thanks, @creocoder. :v:

**Comment by cebe** [comment]
looks like this PR is outdated as #7453 is closed. Feel free to post here if you disagree and I'll reopen.

**Pull request closed without merging**
