### PR TITLE
Fixes #15286: incorrect formatting of time with tz-information

### LINKED ISSUE #15286: incorrect format `asTime` for postgres fields `timestamp with time zone`
### What steps will reproduce the problem?

formatter->defaultTimeZone = 'UTC'
formatter->timeZone = 'Etc/GMT-3'
formatter->timeFormat = 'php:H:i:s'

after version 2.0.11, incorrect format `asTime` for postgres fields `timestamp with time zone`
#13343
```php
$time = '16:22:00.44297+03';
echo Yii::$app->formatter->asTime($time);
````
### What is the expected result?
'16:22:00'
### What do you get instead?
'13:22:00'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.0.*
| Operating system | ubuntu 16.04

### PR DESCRIPTION
**Pull request by rugabarbo**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15286

### CODE REVIEW

**Comment by schmunk42** [comment]
@rugabarbo On which OS, PHP version and DB version did you test this?

**Comment by rugabarbo** [comment]
> @rugabarbo On which OS, PHP version and DB version did you test this?

https://travis-ci.org/yiisoft/yii2/builds/477077560?utm_source=github_status&utm_medium=notification

**Comment by schmunk42** [comment]
Since this is pgsql 9.6.6 - https://travis-ci.org/yiisoft/yii2/jobs/477077561#L100 - I think it's fine.

**Comment by schmunk42** [comment]
Just one more thing to double check ... is there a test run on pgsql 9.6.6 which fails without this fix?

**Comment by rugabarbo** [comment]
> Just one more thing to double check ... is there a test run on pgsql 9.6.6 which fails without this fix?

No.
There is a test for `Formatter` which fails w/o the fix.
The bug is very indirectly related to PgSQL. The main problem in `Formatter` component.

**Review by schmunk42 — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
