### PR TITLE
Issue #15957: dropped deprecated UniqueValidator::$comboNotUnique

### PR DESCRIPTION
**Pull request by rugabarbo**
See also PR #12305

### CODE REVIEW

**Comment by sdscbr** [comment]
what's the change

**Comment by SilverFire** [comment]
Should we mention each deprecation removing in UPGRADE.md?

**Comment by rugabarbo** [comment]
@SilverFire it seems to me that there will be enough mention that all `@deprecated` things will be deleted: https://github.com/yiisoft/yii2/blame/2.1/framework/CHANGELOG.md#L27 

Also we can give a hint about the possibility of searching for the string '@deprecated'.

**Comment by samdark** [comment]
No, we should not.

**Pull request merged**
