### PR TITLE
Add pagination method

### PR DESCRIPTION
**Pull request by oldy777**
Added method paginate in ActiveQuery class for quick get pagination data

How to use:
```
$result = Article::find()->where(['status' => 1])->paginate(15);
return $this->render('index', [
                 'items' => $result['items'],
                 'pages' => $result['pages'],
           ]);
```

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by dmirogin** [comment]
You can use ActiveDataProvider with configured paginator instead this.

**Comment by oldpunk** [comment]
@dmirogin I think it's not so easy and obviously. Especially when you are newbie in framework. With this construction you can do it in 1 line, and will have code autocomplete

**Comment by samdark** [comment]
It's not the job of the query to do pagination. Existing solution is OK regarding complexity and is described well in the guide.

**Comment by oldpunk** [comment]
@samdark can I dynamically add this method to the class?

**Comment by samdark** [comment]
You can use your own query classes extended from your own base class that contains the method: http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#customizing-query-classes

**Comment by oldpunk** [comment]
@samdark but what if already have a bunch of model files? Maybe it is a good idea add ability to add custom methods like my pagination?

**Comment by samdark** [comment]
You have to do it once for all your models where you're using pagination for. If these don't need any other custom query classes, they can instantiate the same query class.

**Pull request closed without merging**
