### PR TITLE
fix BaseArrayHelper::isIn() in strict mode

### PR DESCRIPTION
**Pull request by taobig**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | yes? |
| Tests pass? | yes |
| Fixed issues | none |

### CODE REVIEW

**Comment by samdark** [comment]
What's the problem exactly?

**Comment by cebe** [comment]
@samdark needle should be compared with value, just as it is the case for non-strict comparsion. seems the tests do not cover this case.

**Comment by cebe** [comment]
Merged, thank you!

**Comment by cebe** [comment]
also added a test case:  	b211e6b

**Pull request closed without merging**
