### PR TITLE
Fixes mssql schema to detect sizes of string fields

### PR DESCRIPTION
**Pull request by sdlins**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16378

### CODE REVIEW

**Comment by sdlins** [comment]
Sure, I will do but it will take a bit more long because of my current sparse time. :+1:

**Comment by sdlins** [comment]
@samdark, PDO sqlsrv driver has a problem in Win10 refering to `PDO::ATTR_EMULATE_PREPARE`. If it is used, an exception is throwed: `PDOException: SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object.` and all tests are skipped!

To make the tests work in my environment, I have to bypass those lines for `sqlsrv` driverName. Even althoug, the pre-existing tests are not passing:
```bash
$ php vendor\phpunit\phpunit\phpunit tests\framework\db\mssql\SchemaTest.php --verbose

# tests resulting error because of the exception refering to emulate_prepare
.EEEEEE..........E.FF.F..................................
# resulting in multiple "PDOException: SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object."

# After bypass emulate prepare:
...............E.FF.F............................................ 65 / 82 ( 79%)
.................

Time: 2.33 minutes, Memory: 10.00MB

There was 1 error:

1) yiiunit\framework\db\mssql\SchemaTest::testCompositeFk
Trying to get property of non-object

C:\Users\c126830\Dev\php\_arquivados\yii2\tests\framework\db\SchemaTest.php:234
C:\Users\c126830\Dev\php\_arquivados\yii2\vendor\phpunit\phpunit\phpunit:52

--

There were 3 failures:

1) yiiunit\framework\db\mssql\SchemaTest::testNegativeDefaultValues
Failed asserting that 0 matches expected -123.

C:\Users\c126830\Dev\php\_arquivados\yii2\tests\framework\db\SchemaTest.php:492
C:\Users\c126830\Dev\php\_arquivados\yii2\vendor\phpunit\phpunit\phpunit:52

2) yiiunit\framework\db\mssql\SchemaTest::testColumnSchema
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'bit_col'
-    1 => 'blob_col'
-    2 => 'bool_col'
-    3 => 'bool_col2'
-    4 => 'char_col'
-    5 => 'char_col2'
-    6 => 'char_col3'
-    7 => 'enum_col'
-    8 => 'float_col'
-    9 => 'float_col2'
-    10 => 'int_col'
-    11 => 'int_col2'
-    12 => 'json_col'
-    13 => 'numeric_col'
-    14 => 'smallint_col'
-    15 => 'time'
-    16 => 'tinyint_col'
-    17 => 'ts_default'
+    0 => 'blob_col'
+    1 => 'bool_col'
+    2 => 'bool_col2'
+    3 => 'char_col'
+    4 => 'char_col2'
+    5 => 'char_col3'
+    6 => 'float_col'
+    7 => 'float_col2'
+    8 => 'int_col'
+    9 => 'int_col2'
+    10 => 'numeric_col'
+    11 => 'smallint_col'
+    12 => 'time'
+    13 => 'tinyint_col'
 )

C:\Users\c126830\Dev\php\_arquivados\yii2\tests\framework\db\SchemaTest.php:510
C:\Users\c126830\Dev\php\_arquivados\yii2\vendor\phpunit\phpunit\phpunit:52

3) yiiunit\framework\db\mssql\SchemaTest::testFindUniqueIndexes
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'somecolUnique' => Array (...)
 )

C:\Users\c126830\Dev\php\_arquivados\yii2\tests\framework\db\SchemaTest.php:565
C:\Users\c126830\Dev\php\_arquivados\yii2\vendor\phpunit\phpunit\phpunit:52

FAILURES!
Tests: 82, Assertions: 364, Errors: 1, Failures: 3.

```

**Comment by sdlins** [comment]
I think the current tests should be reviewed, maybe could be a bug. 

To make a new test for this PR, in my current environment, I have to bypass all emulate prepare in tests for `sqlsrv` (I found it in 3 places). Should I go ahead and make the new test anyway since it seems work in other environments?

**Comment by samdark** [comment]
If your new tests isn't affected by other tests failures then yes, go ahead.

**Comment by sdlins** [comment]
@samdark, tests added. If you preffer I can rebase to remove "Bypass" commit.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
