### PR TITLE
Refactor migrations template

### PR DESCRIPTION
**Pull request by Kolyunya**
Generate "safe" methods uncommented by default.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13827 

- [x] Uncomment safe methods by default.
- [x] Prettify docs a bit.
- [x] Update tests.

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by Kolyunya** [comment]
Do we need a separate changelog line for that?

**Review by dynasource — APPROVED** [review]
this is better indeed.

**Comment by samdark** [comment]
Previous one is OK.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by Kolyunya** [comment]
Glad to help!

**Pull request merged**
