### PR TITLE
No Array_merge In Loops

### PR DESCRIPTION
**Pull request by rumours86**
https://github.com/dseguy/clearPHP/blob/master/rules/no-array_merge-in-loop.md

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | ❌

### CODE REVIEW

**Comment by samdark** [comment]
Seems tests are failing after the change.

**Comment by rob006** [comment]
I'm unsure if it will improve performance overall. AFAIK in most cases `$_eventWildcards` will be empty or contain one element, and in this case old implementation was more efficient.

**Comment by rumours86** [comment]
@samdark  не знаю как исправить codeclimate

**Comment by samdark** [comment]
OK. Now it passes tests. Is there any real performance benefit?

**Comment by rumours86** [comment]
у нас была ошибка
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in vendor/yiisoft/yii2/base/Event.php on line 292

я увидел мержи в цикле и решил их поправить, тем более пхпшторм подсвечивает их красным

**Comment by samdark** [comment]
Was the error you were getting resolved by the change you've made?

**Comment by rumours86** [comment]
no

**Comment by samdark** [comment]
In order to merge it we need to prove that it improves something. I think performance test is needed.

**Comment by rumours86** [comment]
https://github.com/dseguy/clearPHP/blob/master/rules/no-array_merge-in-loop.md

**Comment by mikehaertl** [comment]
Isn't this premature optimization? The benefit looks so extremely small that it can be neglected in almost every thinkable case.

**Comment by My6UoT9** [comment]
When u dont use wildcards it might spend a little more time for this, but if you use wildcards - this patch is surely better.
Does not look like premature optimization, running code in a loop - which does not belong in the loop.

**Comment by rob006** [comment]
> When u dont use wildcards it might spend a little more time for this, but if you use wildcards - this patch is surely better.

If you care about performance, you don't use wildcards at all (or at least no more than one or two). This `array_merge()` micro-optimization is unnoticeable when you compare this with overhead created by actual event processing by wildcard handlers.

**Comment by rumours86** [comment]
i use 
$result = call_user_func_array('array_merge', $source);
because yii2 support php5.4

**Comment by samdark** [comment]
Theoretically it might improve performance but I'd not merge it without a benchmark.

**Comment by terabytesoftw** [comment]
Any update on this topic, it looks like we can close it.

**Pull request closed without merging**
