### PR TITLE
Delay exit in error handler

### PR DESCRIPTION
**Pull request by arrilot**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌ i suppose it's not likely that anyone relies on the current behavior

Our use case is the following. We want to collect prometheus metrics regarding http requests and console commands - rps, duration, number of errors, timeouts e.t.c.
The way we do it is via register_shutdown_function in a filter attached to route or application.
The problem is that ErrorHandler gets on the road.
Error handler registers its own `register_shutdown_function callback and when a fatal error occurs (e.g. a request exceeds max_execution_time) calls exit(1) in the end of it.
As a result no other `register_shutdown_function` callbacks registered in userland have a chance to be invoked and we lose all the metrics for this request.
It is also worth noting that errorHandler is registered in Yii Application very early during request lifecycle that makes things even worse. 

This is by no mean a new issue. It was raised at least [one](https://github.com/yiisoft/yii2/issues/9769), [two](https://github.com/yiisoft/yii2/issues/6637) times

In the last issue Cebe said "If you have any alternative fixes in mind, feel free to do a suggestion" so here we go.

The idea was taken from Yii's logger - https://github.com/yiisoft/yii2/blob/master/framework/log/Logger.php#L135
According to php docs "Shutdown functions may also call register_shutdown_function() themselves to add a shutdown function to the end of the queue."
By moving exit(1) to the end shutdown callbacks queue we preserve the final exit code and leave a room for developers' own callbacks to be executed.

### CODE REVIEW

**Comment by bizley** [comment]
Interesting. And it was dynasource, not Cebe btw ;)
It would be nice to have a test registering additional shutdown.

**Comment by arrilot** [comment]
Frankly, I have no idea how something like that can be tested because:
1. `register_shutdown_function` callbacks are never executed during phpunit tests
2. php does not even expose a list of registered shutdown functions

**Comment by WinterSilence** [comment]
Note: it's only questions.

> Yii Application very early during request lifecycle that makes things even worse.

as any other frameworks/applications. why not use `YII_ENABLE_ERROR_HANDLER` and any handler or Yii container(`$config['components']['errorHandler']['class']`) and custom `yii\base\ErrorHandler`?

**Comment by WinterSilence** [comment]
@arrilot what's you think about PR #19402 ? we can run custom shutdown handler before `exit()`

**Comment by samdark** [comment]
Logically it looks alright.

**Review by samdark — APPROVED** [review]

**Comment by bizley** [comment]
Hm, and how about combining the two?

**Comment by arrilot** [comment]
Yeah, it's possible aswell

**Review by Arhell — APPROVED** [review]

**Comment by WinterSilence** [comment]
> - less intuitive for developers. 

api/guide display `@event`s. I don't think many users will need something like this. On my prev work too using Prometheus by [`beforeSend` event](https://www.yiiframework.com/doc/guide/2.0/en/runtime-handling-errors#error-format).

> - does not help if register_shutdown_function is registred as a part of 3rd party code inside vendor

what you mean?

**Comment by samdark** [comment]
@arrilot would you please add a line for CHANGELOG? Thanks,

**Comment by arrilot** [comment]
@samdark Done

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
