### PR TITLE
fix multiple calls getAttributeNames() for same object

### PR DESCRIPTION
**Pull request by nicdnepr**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

It's fix for this code call https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L241
For each attribute we call this part of code https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L427

### CODE REVIEW

**Comment by dynasource** [comment]
whats the usecase for this PR? When you are doing a validation twice?

**Comment by nicdnepr** [comment]
For each attribute calls the full list of validators and each time calls getAttributeNames

**Comment by dynasource** [comment]
it does not seem to be very relevant with respect to performance gain. It does seem to have some use when you execute validate() twice on the same model, but that is a rare occasion, and mainly in the testing environment.

**Comment by klimov-paul** [comment]
This can not be accepted as runtime change of `Validator::$attributes` will have no effect.
See #13979

**Comment by cebe** [comment]
We should probably add a test that breaks in case such change is made...

**Pull request closed without merging**
