### PR TITLE
Fixed #10784

### LINKED ISSUE #10784: CheckboxColumn, value у всех 1, если checkboxOptions является замыканием
Использую в GridView yii\grid\CheckboxColumn. Если checkboxOptions является замыканием, и если явно не устанавливать value, то у всех чекбоксов value будет 1:
`'checkboxOptions' => function ($model, $key, $index, $column) {
    return ['checked' => 'true'];
}`
Приходится в замыкании явно указывать value, например 'value' => $model->id.

По аналогии, если checkboxOptions массив, то все работает правильно:
`'checkboxOptions' => [
    'checked' => 'true',
]`

Предпологаю, что ошибка кроется [тут](https://github.com/yiisoft/yii2/blob/master/framework/grid/CheckboxColumn.php#L128).

### PR DESCRIPTION
**Pull request by tarasio**
Fixed #10784

### CODE REVIEW

**Comment by SilverFire** [comment]
Could you add a Unit test on this case?

**Comment by nukkumatti** [comment]
Done

**Comment by SilverFire** [comment]
Merged https://github.com/yiisoft/yii2/commit/0c462226fe28e075e2e86b6a5c3c4fb2e629f832

**Comment by SilverFire** [comment]
Thank you!

**Pull request closed without merging**
