### PR TITLE
Update AssetManager.php

### PR DESCRIPTION
**Pull request by msajko**
Avoid php warning: filemtime(): stat failed for

### CODE REVIEW

**Comment by cebe** [comment]
why does it fail?

**Comment by msajko** [comment]
assetManager->linkAssets=true on windows platform using Junction Folders (https://github.com/yiisoft/yii2/pull/7931)

**Comment by samdark** [comment]
I'll check it on Windows.

**Comment by samdark** [comment]
Weird. I'm unable to reproduce issue.

**Comment by samdark** [comment]
@msajko any clues on how to do it?

**Comment by msajko** [comment]
@samdark try clone github [trntv/yii2-starter-kit](https://github.com/trntv/yii2-starter-kit) or [vova07/yii2-start](https://github.com/vova07/yii2-start) on windows home platform

**Comment by cebe** [comment]
closing as duplicate of #7931. please explain in more detail if it is not.

**Pull request closed without merging**
