### PR TITLE
Russian translation: improvements of input-tabular-input

### PR DESCRIPTION
**Pull request by lex111**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes (doc)
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | --
| Fixed issues  | --

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by lex111** [comment]
@samdark when will be updated the site? There are still no my changes to your documentation :cry: 

https://www.yiiframework.com/doc/guide/2.0/ru/input-tabular-input

**Comment by cebe** [comment]
not yet, will add them today.

**Comment by cebe** [comment]
changes are now on the website: https://www.yiiframework.com/doc/guide/2.0/ru/input-tabular-input

**Comment by cebe** [comment]
will be updated from master every night.

**Pull request merged**
