### PR TITLE
added autoloading path for yii (CLI) when installed from yii2-dev

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by schmunk42** [comment]
Yii is installed from from yii2-dev

```
    "require": {
        "yiisoft/yii2-dev": "2.1.x-dev"
    }
```

Run `yii` on CLI:

```
root@74db2321a7ca:/app#  vendor/bin/yii
PHP Fatal error:  Uncaught Error: Class 'yii\console\Application' not found in /app/vendor/yiisoft/yii2-dev/framework/yii:27
Stack trace:
#0 {main}
  thrown in /app/vendor/yiisoft/yii2-dev/framework/yii on line 27

Fatal error: Uncaught Error: Class 'yii\console\Application' not found in /app/vendor/yiisoft/yii2-dev/framework/yii:27
Stack trace:
#0 {main}
  thrown in /app/vendor/yiisoft/yii2-dev/framework/yii on line 27
```

**Comment by schmunk42** [comment]
@klimov-paul Let me know if you need more info

**Review by cebe — APPROVED** [review]
Looks good to me. This is needed as Yii has dropped its own autoloader.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
