### PR TITLE
Handles relation's alias in relation declaration

### PR DESCRIPTION
**Pull request by CedricYii**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | not tested through yii unit tests |
| Fixed issues | #10883 |

Using the syntax `==relationAlias==`, the query inside a relation can now adress the alias of the relation without knowing it in advance.

Example:

``` php
class Customer {
...
  public function getOrders()
  {
      return $this->hasMany( Order::className(), ['customerid' => 'customerid'] )
                  ->andOnCondition( [ '==relationAlias==.statusid' => 1 ] );
  }
...
}
```

Then

``` php
$customer = Customer::find()
                   ->alias( 'c' )
                   ->innerJoinWith('orders o');
```

Build the query:

```
select customer.* from customer c
join order o on o.customerid = c.customerid 
where o.statusid = 1
```

### CODE REVIEW

**Comment by cebe** [comment]
I'd prefer a complete solution to  #7263 insated of this.

**Comment by CedricYii** [comment]
@cebe So would I. However the alias feature is not really usable without this, and it is unsure if a perfect solution will be out with 2.0.8. I believe Yii can't afford to wait too long for it.
Especially since you planed to refactor all those things in 2.1 (this feature could then be dropped for a better one).

Anyhow, would you have the ability to check if this commit pass yii unit tests?

**Comment by cebe** [comment]
as this adds new functionaility, there should be additional tests added to verfy that it works. However I do not think it is worth adding tests for this particular implenetation as I am quite sure I will not merge it this way. I will try to find some time next week to check it out in detail.

**Comment by CedricYii** [comment]
Thanks for your feedback.
Well I was willing to make sure it doesn't break anything at least... And it sounds to be the case since I finally managed to run the tests.

**Comment by cebe** [comment]
there is also the green checkmark on the commit in this PR, which is from travis-ci tests.

**Comment by CedricYii** [comment]
Ah! Good to know! I was wondering what it was about...

**Comment by CedricYii** [comment]
The last commit fixed alias replacement, it should be usable now.

**Comment by Renkas** [comment]
Any progress on better solution? I need this functionality for my project ASAP - I would rather use framework functionality than make some temporary (which will stay there untill end of time like with all "temporay" things) custom solution.

**Comment by CedricYii** [comment]
Closed in favor to a more complete solution in #11646

**Pull request closed without merging**
