### PR TITLE
unit test for ExistValidator with EachValidator

### PR DESCRIPTION
**Pull request by Faryshta**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |

Related https://github.com/yiisoft/yii2/commit/205f16811a6071ad5d1dbea4cba9fd8a3282f6c5

### CODE REVIEW

**Comment by klimov-paul** [comment]
`ExistValidatorTest` should not be affected by `EachValidator` test case. Code should be moved inside `EachValidatorTest`.

**Comment by klimov-paul** [comment]
Still, I don't see much benefit of such unit test.
The invocation of `validateAttribute()` already covered using `CompareValidator`.
There is no sense to test `EachValidator` against all validator classes, which provide thier own implementation of `validateAttribute()` method.

**Comment by Faryshta** [comment]
then why did you asked me to make this pr then?

**Comment by klimov-paul** [comment]
Sorry for that, I did ment no harm.
Still, while the PR needs improvement - there is no sense to waste more of your effots on it.

**Pull request closed without merging**
