### PR TITLE
Fix #4763

### LINKED ISSUE #4763: Line number overlaps text in exception call stack.
It is really a little annoying when exception is thrown and line number overlaps text:

nowrap issue

i'd vote for removing `white-space: nowrap;` form this place.

### PR DESCRIPTION
**Pull request by pana1990**
Fix #4763

View in ie : 

explorer

View in chrome :

chrome

View in mozilla : 

mozilla

### CODE REVIEW

**Comment by cebe** [comment]
not sure if a scrollbar is helpful here. I'd prefer line break.

**Comment by pana1990** [comment]
i hesitated between both sides...

**Comment by samdark** [comment]
Line break is tricky because of line highlighting on hover isn't getting to the next line and line numbering breaks but if it could be solved it's preferred to scrolling.

**Comment by klimov-paul** [comment]
This fix breaks highlighting of the error line:

error_page

**Comment by samdark** [comment]
Closed since it can't be merged as is. @pana1990 if you have an idea on how to fix it, please let us know.

**Comment by pana1990** [comment]
:+1:

**Pull request closed without merging**
