### PR TITLE
Fix #14322: Check the result of pdo-commit() in Transaction.Commit

### LINKED ISSUE #14322: Should Transaction.Commit check the return value of pdo->commit()?
I found that in Tranaction.php, the return value of commit is ignored. But according to the document of pdo, commit() will return true or false. So is it right to ignore the return value?

In http://php.net/manual/en/pdo.commit.php ：
> Returns TRUE on success or FALSE on failure.

In https://github.com/yiisoft/yii2/blob/master/framework/db/Transaction.php#L157 the return value of commit() is ignored.
>  $this->db->pdo->commit();

Please let me know if I do not make it clear. Thanks!

### PR DESCRIPTION
**Pull request by shenli**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14322

Please correct me if I am not using the right way to fix it.
I am trying to figure out where and how to add an unit test.

### CODE REVIEW

**Comment by cebe** [comment]
The change looks okay to me, but I'd like to dig further into PDO to figure out in which cases this could actually happen. See my comments in the issue for more detail: https://github.com/yiisoft/yii2/issues/14322#issuecomment-317240802

**Review by dynasource — CHANGES_REQUESTED** [review]
shouldn't we introduce \yii\base\PDOException or use \yii\base\Exception.

PHP advises not to use \PDOException http://php.net/manual/en/class.pdoexception.php, although I see Doctrine extending from it directly

**Comment by samdark** [comment]
It's not advising not to use it. It advices not to throw it yourself.

**Comment by samdark** [comment]
Seems it's not a good idea to check it.

**Pull request closed without merging**
