### PR TITLE
Fix HttpAuthHeader

### LINKED ISSUE #15693: HttpHeaderAuth сломали
### What steps will reproduce the problem?
Делаем рест контроллер, добавляем 2 метода авторизации HttpBearerAuth::class, HttpBasicAuth::class. 
```
class StageTypeController extends Controller
{
    public function behaviors()
    {
        return [
            'authenticator' => [
                'class' => CompositeAuth::class,
                'authMethods' => [
                    HttpBearerAuth::class,
                    HttpBasicAuth::class
                ],
            ],
        ];
    }

```

Пытаемся авторизоваться используя Basic auth method. 

### What is the expected result?
Ожидается что, HttpBearerAuth не найдет в заголовке Authorization строку Bearer и закончит свою работу. В реальности он использует в качестве токена всю строку заголовка Authorization

### What do you get instead?
https://github.com/yiisoft/yii2/blob/master/framework/filters/auth/HttpHeaderAuth.php#L54-L61

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1 
| Operating system | ubuntu 16.4

### PR DESCRIPTION
**Pull request by bboure**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  | fixes #15693

TODO:
- [x] Add unit tests

### CODE REVIEW

**Comment by StefanWerner23** [comment]
Hi bboure,

why have you removed the line `$this->challenge($response);`

This was a fix for this issue https://github.com/yiisoft/yii2/issues/15494

Kind regards,

Stefan

**Comment by bboure** [comment]
@StefanWerner23  ups sorry that's a mistake.

**Comment by StefanWerner23** [comment]
Thanks for the correction.

**Comment by samdark** [comment]
@vyachin does that work for you?

**Comment by vyachin** [comment]
@samdark yes

**Comment by vyachin** [comment]
@bboure thank you

**Review by SilverFire — APPROVED** [review]
Thank you!

**Pull request merged**
