### PR TITLE
docs/guide/rest-resources.md description fix

### PR DESCRIPTION
**Pull request by softark**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes (doc)
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | --
| Fixed issues  | --

### CODE REVIEW

**Comment by cebe** [comment]
@softark please also check my comment at https://github.com/yiisoft/yii2/commit/3c8aecfbc3a7fd6ed2643f728e4da4501b05783e#r28239533 seems your files are not UTF-8 encoded.

**Comment by softark** [comment]
Oh, really? I'll check.

**Comment by softark** [comment]
@cebe I'm sorry, I've confirmed that I had encoded some files in shift-jis instead of utf-8 by mistake.
I'd like to correct them in the next PR. Is it OK?

**Comment by cebe** [comment]
> I'd like to correct them in the next PR. Is it OK?

sure, thank you!

**Pull request merged**
