### PR TITLE
Fix phpdocs and small bug

### PR DESCRIPTION
**Pull request by pana1990**
Fix small bug, fields need be array by default beacuse yii parse string to array only if option is array by default (https://github.com/yiisoft/yii2/blob/master/framework/console/Controller.php#L84).

I fix test too, sorry for my mistake

### CODE REVIEW

**Comment by SilverFire** [comment]
Merged. Thank you!

**Comment by pana1990** [comment]
@SilverFire why do you  know test fail with hhvm? i dont understand.

**Comment by SilverFire** [comment]
Because of 1-second lag and missing `body` https://travis-ci.org/yiisoft/yii2/jobs/93006055#L220

When I checked the HHVM test fail I didn't see the missing `body` option. I'm not sure why this happens in HHVM only :thought_balloon:

**Comment by pana1990** [comment]
It is a strange behavior. i will check with hhvm in local.

**Comment by pana1990** [comment]
@SilverFire  i think regular expression was wrong. check my pr https://github.com/yiisoft/yii2/pull/10248

**Comment by SilverFire** [comment]
Thank you, merged

**Pull request merged**
