### PR TITLE
Add headers to PO file in GettextPoFile::save()

### PR DESCRIPTION
**Pull request by stevekr**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #11212 |

### CODE REVIEW

**Comment by samdark** [comment]
Seems it doesn't work https://travis-ci.org/yiisoft/yii2/jobs/142155374#L291

**Comment by stevekr** [comment]
Sorry, forgot to run unit tests. Content-Type header uses `Yii::$app->charset` and unit test didn't work without mock application.

**Comment by samdark** [comment]
OK. Looks good to me. Can you add a changelog?

**Comment by stevekr** [comment]
Done.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
