### PR TITLE
phpDoc ActiveQuery:with/joinWith updated

### PR DESCRIPTION
**Pull request by githubjeka**

### CODE REVIEW

**Comment by samdark** [comment]
You're using both `\yii\db\ActiveQuery` and `\yii\db\ActiveQueryInterface` for the same hint. Let's be consistent.

**Comment by githubjeka** [comment]
- The `ActiveQueryInterface` **interface** doesn't know about the `\yii\db\ActiveQuery` class. Because phpDoc of `ActiveQueryInterface` uses the self class. 

- The `ActiveQueryTrait` **trait** doesn't know about the `\yii\db\ActiveQuery` class. Because phpDoc of `ActiveQueryTrait` uses known `ActiveQueryInterface` interface. 

- The `ActiveQuery` class is a specific implementation of the `ActiveQueryInterface` interface and have other methods. For this reason and for the autocompleate phpDoc of `ActiveQuery::joinWith` uses the self class.

**Comment by githubjeka** [comment]
@samdark do you mean the other side - considering as an example of the finished implementation `\yii\db\ActiveQuery` only ?

**Comment by githubjeka** [comment]
Right you are.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
