### PR TITLE
Update AccessRule.php

### PR DESCRIPTION
**Pull request by frontbear**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | no

### CODE REVIEW

**Comment by frontbear** [comment]
according to https://github.com/frontbear/yii2/blob/master/framework/filters/AccessRule.php#L28, code `? true : false`  is not necessary

**Comment by berosoboy** [comment]
Don't do this. `AccessRule::$allow` can be `null`, and the null return has a proper meaning in the `allows` method.

**Comment by berosoboy** [comment]
I think that change could be dangerous.
The current implementation ensure the boolean return;
For example, if `AccessRule::$allow` is `null`, it will cause a improper behavior, because null return has a different meaning in the `allows` method.

**Comment by frontbear** [comment]
@berosoboy i see, thanks.

**Pull request closed without merging**
