### PR TITLE
Fast fix of nightly build

### PR DESCRIPTION
**Pull request by rugabarbo**
This is just a quick fix. It would be correct to use for the test a component that doesn't require graphic extensions.

### CODE REVIEW

**Comment by rob006** [comment]
I'm for using different component for this test - it is a test for `ServiceLocator`, it not necessary needs to be captcha.

**Comment by samdark** [comment]
@rob006 idea sounds better. @rugabarbo could you adjust it?

**Comment by rugabarbo** [comment]
Already working on it. Strange, but with other components the test failed. We may have found another error :)

**Comment by rugabarbo** [comment]
Understood. I tried to use properties of components that are not declared. 

**Fixed.**

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
