### PR TITLE
Moving saving metadata method to cache only if it's not there

### PR DESCRIPTION
**Pull request by nikosid**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14434

### CODE REVIEW

**Comment by xxcarleonexx** [comment]
Yes, issue produce this leaks.. http://joxi.ru/gmvz5Gdcxx795m

**Comment by cebe** [comment]
`$this->_tableMetadata[$name]` is not "the cache", its another instance of caching inside of the class but it does not indicate the state of the schema cache.

**Review by dynasource — APPROVED** [review]

**Comment by sergeymakinen** [comment]
`loadTableMetadataFromCache()` will load metadata from cache if it's possible. If it's not, local `loadTable…()` will fetch data from db and `saveTableMetadataToCache()` will save them to cache if it's possible.

Looks good to me. @nikosid thank you for spotting this!

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
