### PR TITLE
Update rest-quick-start.md

### PR DESCRIPTION
**Pull request by free6k**
The method of the guide does not work

### CODE REVIEW

**Comment by cebe** [comment]
we have a test for this, what exactly is not working?
https://github.com/yiisoft/yii2/blob/master/tests/framework/rest/UrlRuleTest.php#L71

**Comment by cebe** [comment]
note that singular names will be pluralized automatically when not turned off.

**Comment by free6k** [comment]
so why do I have problems with the process of documentation? this solution I found in Google.

**Comment by cebe** [comment]
which problem are you facing exactly?

**Comment by free6k** [comment]
>>>> note that singular names will be pluralized automatically when not turned off.
pluralized! Problem here. In documentation haven't information about it. Reject this pull request

**Comment by cebe** [comment]
> In documentation haven't information about it.

https://github.com/free6k/yii2/blob/ff0e46524eaf2b7a0335523f7363dd5a8dc46985/docs/guide/rest-quick-start.md#trying-it-out-

it is in the info box under the list of HTTP methods.

**Pull request closed without merging**
