### PR TITLE
fix timestamp appending if basePath is not defined

### PR DESCRIPTION
**Pull request by np25071984**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16268

### CODE REVIEW

**Comment by GHopperMSK** [comment]
It looks like @webroot alias doesn't exists in console environment.

**Comment by rob006** [comment]
It does not look right to me. AFAIK #16268 is about configuration errors which are ignored instead of throwing an exception. Blind guess of correct path in case of misconfiguration does not look like correct solution...

**Comment by GHopperMSK** [comment]
What do you mean "blind guess"? All I have done is just check if I able to use absolute path or only relative one to get the file time.

**Comment by rob006** [comment]
Using relative path is a blind guess - result may differ depending on entry script position / current working directory and may give random results in some edge cases.

**Comment by GHopperMSK** [comment]
We don't have to specify `basePath` or `baseUrl`:

https://github.com/yiisoft/yii2/blob/5544d31bb3b7b0959ef51f7c78c7e06c8f5b354f/framework/web/AssetBundle.php#L184-L186

In case relative path gives us "random result" we just don't get timestamp postfix in asset URL. But in common case we always get exactly what we expected.

**Comment by GHopperMSK** [comment]
As an option, I can throw an exception if `$timestamp` equal to `false`.

**Comment by rob006** [comment]
> We don't have to specify `basePath` or `baseUrl`:
> https://github.com/yiisoft/yii2/blob/5544d31bb3b7b0959ef51f7c78c7e06c8f5b354f/framework/web/AssetBundle.php#L184-L186

In this case `basePath` and `baseUrl` are inherited from asset manager. This is not the same as using relative paths.

**Comment by GHopperMSK** [comment]
As you wish! Let me know about your decision. It is not a problem to completely remake the job, but I need understand what I should to do.

**Comment by samdark** [comment]
Alike fix is in master now. https://github.com/yiisoft/yii2/commit/96cd8bcb687d66ae86fba01ac6a3e9c54687d616

**Pull request closed without merging**
