### PR TITLE
fix: typecast for backed enums

### LINKED ISSUE #19318: Support for PHP 8.1 enums
### What steps will reproduce the problem?
Have a backed enum, like this:

```php
enum MyEnum: int
{
    case NONE = 0;
    case TEAM = 1;
    case ALL = 2;
}
```

### What is the expected result?
Being able to use this in `ActiveRecord`:

```php
/**
 @property MyEnum $myEnum
*/
class MyClass extends ActiveRecord
{
}
```

### What do you get instead?
```
Object of class common\models\MyEnum could not be converted to int

#0 /project/vendor/yiisoft/yii2/db/ColumnSchema.php(173): yii\base\ErrorHandler->handleError()
#1 /project/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php(49): yii\db\ColumnSchema->typecast()
#2 /project/vendor/yiisoft/yii2/db/QueryBuilder.php(652): yii\db\mysql\ColumnSchema->dbTypecast()
#3 /project/vendor/yiisoft/yii2/db/QueryBuilder.php(630): yii\db\QueryBuilder->prepareUpdateSets()
#4 /project/vendor/yiisoft/yii2/db/Command.php(591): yii\db\QueryBuilder->update()
#5 /project/vendor/yiisoft/yii2/db/ActiveRecord.php(334): yii\db\Command->update()
#6 /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php(808): yii\db\ActiveRecord::updateAll()
#7 /project/vendor/yiisoft/yii2/db/ActiveRecord.php(680): yii\db\BaseActiveRecord->updateInternal()
#8 /project/vendor/yiisoft/yii2/db/BaseActiveRecord.php(679): yii\db\ActiveRecord->update()
#9 /project/api/controllers/CorporateDesignController.php(486): yii\db\BaseActiveRecord->save()
#10 [internal function]: api\controllers\CorporateDesignController->actionSave()
#11 /project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#14 /project/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#15 /project/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#16 /project/frontend/web/index.php(44): yii\base\Application->run()
#17 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1.3
| Operating system | Ubuntu 21.10

### Possible solutions
I'd be fine implementing some interface on the `enum`, but I could not find any Yii2 interface that makes sense. There is no `PdoValueInterface`, nor does the `ExpressionInterface` offer anything useful.

(One could write their own `ExpressionBuilder`, but this issue is to make it easier/possible to use enums)

### PR DESCRIPTION
**Pull request by EtienneBruines**
Fixes #19318

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #19318

### CODE REVIEW

**Comment by WinterSilence** [comment]
enum converts to array(`UnitEnum::cases()`), property `value` not declared.

**Comment by EtienneBruines** [comment]
> Backed Cases have an additional read-only property, value, which is the value specified in the definition.

Source: https://www.php.net/manual/en/language.enumerations.backed.php

As we are talking about one of those enum-values (not the list, but one instance of the list), we should easily be able to use `->value` to get the integer/string-backed value.

**Comment by WinterSilence** [comment]
@EtienneBruines my fail - I'm confuse class with it's instances. Some fixes:
1. `is_object($value)`: notice at check non-objects by `instanceof`
2. `$value instanceof \UnitEnum`: check main interface - other interfaces extending `UnitEnum` may be added in future

~~~php
if (PHP_VERSION_ID >= 80100 && is_object($value) && $value instanceof \UnitEnum) {`
~~~

**Comment by EtienneBruines** [comment]
Except that we do not care about `UnitEnum`s, but only about the sublcass of it, `BackedEnum`s. 

(Not all enums have a `value` associated with it that is either `string` or `int`.)

**Comment by EtienneBruines** [comment]
Thank you for the fix @WinterSilence - I've updated the code with suggestion 1 (`is_object`).

**Comment by WinterSilence** [comment]
@EtienneBruines yes, you right again 👍🏻

**Comment by WinterSilence** [comment]
@EtienneBruines to be honest, I didn't check it in PHP8, only in PHP7, but I'd rather write it safe against changes in the future.

**Review by samdark — APPROVED** [review]
Please add a line for CHANGELOG. Thanks.

**Review by Arhell — APPROVED** [review]

**Comment by bizley** [comment]
Thank you

**Pull request merged**
