### PR TITLE
[WIP] New method `linkSync` to update junction tables

### PR DESCRIPTION
**Pull request by alex-code**
Allow junction tables to be updated via the relation.

| $model-id | other-id |
| --- | --- |
| 1 | 1 |
| 1 | 2 |
| 1 | 3 |
| 1 | 4 |

`$model->linkSync('relation', [1, 2, 5, 6]);`
This would remove the relation to `3 & 4` and insert new relations to `5 & 6`.
Based this off `laravel->sync()` from an article I read.

This is more of a demo to get some thoughts as it would need updating to support relations more strongly.

### CODE REVIEW

**Comment by githubjeka** [comment]
A good method. I often use it.

**Comment by Alex-Code** [comment]
Need to write some tests but should support composite keys now.

The method can take either an array of foreign key ids or an array of foreign models.

e.g.
Using `Html::checkboxList` you could do,
`$model->linkSync('relation', \Yii::$app->request->post((new OtherModel)->formName(), []));`
or
`$model->linkSync('relation', OtherModel::findAll(\Yii::$app->request->post((new OtherModel)->formName(), [])))`

Thoughts?

**Comment by Faryshta** [comment]
Very good, what is needed for integration?

**Comment by samdark** [comment]
Tests, docs.

**Comment by Faryshta** [comment]
@samdark the name of the method is ok? I think `setRelation` or `syncRelation` are easier to understand.

@Alex-Code can I change the function signature to add `$columns = []` and `$delete = false` ?

**Comment by samdark** [comment]
No, method name is not OK. Totally confusing.

**Comment by Faryshta** [comment]
@samdark which method name would you prefer?

**Comment by samdark** [comment]
Something like `updateLink`.

**Comment by Alex-Code** [comment]
@Faryshta Please do make changes, I put this up so it can be improved and expanded.

**Comment by Faryshta** [comment]
@samdark I was thinking more along the lines of `setRelation` since we already have a `getRelation` method.

**Comment by samdark** [comment]
It's not really about relations. It's about junction table...

**Comment by Alex-Code** [comment]
Maybe `linkMultiple`, I don't think `setRelation` says enough about what the function would do.

**Comment by samdark** [comment]
Won't make it into 2.0.

**Pull request closed without merging**
