### PR TITLE
Small fix phpDoc

### PR DESCRIPTION
**Pull request by lav45**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Hmm... it's definitely exception, isn't it?

**Comment by samdark** [comment]
I don't think this change is needed.

**Comment by LAV45** [comment]
@samdark , open this code in PhpStorm and you will see for yourself
```php
     /**
     * ...
     * @throws \Exception|\Throwable in case insert failed.
     */
    public function insert($runValidation = true, $attributes = null)
    {
        try {
            // ...
        } catch (\Exception $e) {
            // ...
        } catch (\Throwable $e) {
            // ...
        }
    }
```

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by rob006** [comment]
IMO the whole `@throws` section should be removed in this case - almost every method could throw `Exception` or `Throwable`, annotating such general exception without any description what it means is pointless and only generates unnecessary noise.

**Comment by samdark** [comment]
I don't agree. One should be aware than exception may occur in particular case.

**Comment by rob006** [comment]
Can you name any method in ActiveRecord (except `transactions()` :)) that you sure that it will never throw any exception?

**Comment by samdark** [comment]
Yes. Why?

- getDb
- find
- tableName
- equals
- isTransactional

**Comment by rob006** [comment]
All of them will throw an exception if  db connection can not be established. And obviously on misconfiguration or if `Yii::$app` was not initialized.

**Pull request merged**
