### PR TITLE
Bower is deprecated since 2017, we should use npm instead

### PR DESCRIPTION
**Pull request by razvanphp**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

https://bower.io/blog/2017/how-to-migrate-away-from-bower/
https://www.yiiframework.com/wiki/785/use-minified-version-of-jqueryasset-bootstrapasset-and-all-default-assets - @robregonm

### CODE REVIEW

**Comment by razvanphp** [comment]
Related discussion in #14297 and yiisoft/yii2-bootstrap#221

**Comment by razvanphp** [comment]
... or should we better switch to https://github.com/fxpio/foxy already? @francoispluchino what do you think?

**Comment by rob006** [comment]
Yii2 is not using bower or even bower registry directly (packages are fetched from https://asset-packagist.org/ and installed by composer), so bower deprecation has not affect here. https://github.com/yiisoft/yii2-bootstrap/issues/221#issuecomment-371832862 mentioned some clear disadvantages of using npm registry, what are the practical benefits of such change?

**Comment by schmunk42** [comment]
> ... or should we better switch to https://github.com/fxpio/foxy already? @francoispluchino what do you think?

Foxy would be cool, but it requires `npm` or `yarn` to work.

**Comment by terabytesoftw** [comment]
> > ... or should we better switch to https://github.com/fxpio/foxy already? @francoispluchino what do you think?
> 
> Foxy would be cool, but it requires `npm` or `yarn` to work.

btw, i forked it and made some improvements, since fpachucino is busy https://github.com/php-forge/foxy

**Comment by samdark** [comment]
@terabytesoftw asset-packagist works on it so if improvements are critical, it's worth contacting @hiqsol and @SilverFire so they update it there.

**Comment by mtangoo** [comment]
@razvanphp is there anything that did not work for you? 
Yii2 is not using Bower, which make the whole PR invalid.
Do you disagree with that assessment?

**Comment by razvanphp** [comment]
I totally understand, it's more of psychological change, so Yii2 is not using obsolete repositories in it's core code and also to discourage further use of bower. More than that, it can be that bower really stops being maintained and I think then even asset-packagist can't pull the metadata for the packages, right?

**Comment by mtangoo** [comment]
> More than that, it can be that bower really stops being maintained and then even asset-packagist can't pull the metadata for the packages, right?

I think @hiqsol and @SilverFire can comment on this one and the way forward if the shutdown of bower will indeed disrupt the service.

**Comment by mtangoo** [comment]
Looking at the site it clears things up:

> This repository allows installation of Bower and NPM packages as native Composer packages.
> 
> At the moment we've added most popular Bower and NPM packages 4000+ each.
> 
> In case Composer fails to install some asset package, use the search line at the top of the page to check specific package health.
> 
> For NPM scoped packages use `scope--package` instead of `@scope/package`, e.g. `npm-asset/pusher--chatkit`.

It seems, at least to me, that it works for both Bower and NPM. Which means as long as NPM is up, we have nothing to worry if Bower goes away!

**Comment by mtangoo** [comment]
Moreover, if there is further doubt, it is better to log it on the repository at https://github.com/hiqdev/asset-packagist

If you have no further objection, I will close this PR

**Pull request closed without merging**
