### PR TITLE
Fixed doc about supporting inheritance (traits vs behaviors)

### PR DESCRIPTION
**Pull request by masterklavi**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

> Traits, on the other hand, can be considered as language-supported copy and paste. They do not support inheritance.

There is something wrong. Look at http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.multiple
> Multiple Traits can be inserted into a class.
```
class MyHelloWorld {  
    use Hello, World;  
    public function sayExclamationMark() {  
        echo '!';  
    }  
}
```

### CODE REVIEW

**Comment by samdark** [comment]
What's supported by traits isn't inheritance.

**Comment by masterklavi** [comment]
But it's not a negative point of traits.

**Comment by samdark** [comment]
In context of behaviors it is. That's what initially prevented us dropping behaviors in favor of traits while Yii 2 was designed.

**Comment by samdark** [comment]
Don't think these changes are appropriate but thanks for proposal anyway.

**Pull request closed without merging**
