### PR TITLE
Fix `\yii\db\QueryInterface` type hints

### PR DESCRIPTION
**Pull request by Kolyunya**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

Not sure if we should specify `Expression` as one of the acceptable types. `\yii\db\QueryTrait` accepts it too. I will adjust the PR if needed.

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by Kolyunya** [comment]
Shouldn't we have added the `Expression` as well?

**Comment by cebe** [comment]
Expression is not necessarily supported by non-SQL implementations so I would keep it out of the interface.

**Comment by Kolyunya** [comment]
Thanks for the clarification!

**Pull request merged**
