### PR TITLE
Revert `move_uploaded_file()` function for saving uploaded files when POST request

### PR DESCRIPTION
**Pull request by hyuzea**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17875

### CODE REVIEW

**Comment by sup-ham** [comment]
Should we delete these unused methods?

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
Thank you!

**Comment by rob006** [comment]
This change should be mentioned in `UPGRADE.md`.

**Comment by samdark** [comment]
@rob006 this one is actually makes everything compatible again.

**Comment by rob006** [comment]
@samdark It removes protected methods, which is against [BC policy](https://github.com/yiisoft/yii2/blob/master/docs/internals/bc.md).

It also reverts fix for issue that is marked as fixed, and it is not clear from changelog whether this issue is still fixed, or not.

**Comment by samdark** [comment]
@rob006 you're correct about removal of protected methods but the fix isn't removed.

**Comment by samdark** [comment]
1f8ca7b7b153a5590e2e4928e2d28604c3331ccf

**Pull request merged**
