### PR TITLE
 Modify the typos in the document

### PR DESCRIPTION
**Pull request by kernight**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | nothing

### CODE REVIEW

**Comment by SilverFire** [comment]
@steve-liuxu it seems you have merged branch `steve-liuxu/master` in a wrong direction multiple times.

Restore your `master` branch to be the same as `yiisoft/yii2:master`, apply changes and create PR again. Thank you

**Comment by steve-liuxu** [comment]
OK. If I want to fix the docs of ```2.1``` branch,would i create PR on ```2.1``` branch?

**Comment by samdark** [comment]
Yes. Checkout 2.1 first, then branch off it.

**Comment by steve-liuxu** [comment]
Thanks.

**Pull request closed without merging**
