### PR TITLE
Add support for tinyint as DB column type

### PR DESCRIPTION
**Pull request by rob006**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes (not sure about OCI and MSSQL)
| Fixed issues  | #14638

MySQL: https://dev.mysql.com/doc/refman/5.7/en/integer-types.html
OCI: https://docs.oracle.com/cd/E12151_01/doc.150/e12155/oracle_mysql_compared.htm
SQLite: https://sqlite.org/datatype3.html
MSSQL: https://msdn.microsoft.com/en-us//library/ms187745(v=sql.110).aspx

PostgreSQL: https://www.postgresql.org/docs/9.2/static/datatype-numeric.html
Cubrid: http://blog.cubrid.org:8080/cubrid_mysql_oracle_data_type_mapping

### CODE REVIEW

**Review by dynasource — APPROVED** [review]

**Review by dmirogin — APPROVED** [review]

**Comment by rob006** [comment]
Just to be clear: I'm not sure that this will work correctly for OCI and MSSQL. I have no experience with this DBMS and there are not working tests for them.

**Comment by samdark** [comment]
@sergeymakinen do you have time to help verifying it against MSSQL/Oracle?

**Comment by sergeymakinen** [comment]
@samdark I will test it today and share what I got.

**Comment by sergeymakinen** [comment]
<details><summary>Test output</summary>

```
11) yiiunit\framework\db\mssql\QueryBuilderTest::testCreateTableColumnTypes
yii\db\Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'UNSIGNED'.
The SQL being executed was: CREATE TABLE [column_type_table] (
	[col1] bigint,
	[col2] bigint NOT NULL,
	[col3] bigint CHECK ([col3] > 5),
	[col4] bigint,
	[col5] bigint CHECK ([col5] > 5),
	[col6] varbinary(max),
	[col7] bit NOT NULL DEFAULT 1,
	[col8] bit,
	[col9] date NOT NULL,
	[col10] date,
	[col11] datetime NOT NULL,
	[col12] datetime,
	[col13] decimal(18,0) CHECK ([col13] > 5.6),
	[col14] decimal(18,0) NOT NULL,
	[col15] decimal(12,4) CHECK ([col15] > 5.6),
	[col16] decimal(12,4),
	[col17] decimal(18,0),
	[col18] float CHECK ([col18] > 5.6),
	[col19] float NOT NULL,
	[col20] float CHECK ([col20] > 5.6),
	[col21] float,
	[col22] float,
	[col23] float CHECK ([col23] > 5.6),
	[col24] float NOT NULL,
	[col25] float CHECK ([col25] > 5.6),
	[col26] float,
	[col27] float,
	[col28] int CHECK ([col28] > 5),
	[col29] int NOT NULL,
	[col30] int CHECK ([col30] > 5),
	[col31] int,
	[col32] int,
	[col33] decimal(19,4) CHECK ([col33] > 0.0),
	[col34] decimal(19,4) NOT NULL,
	[col35] decimal(16,2) CHECK ([col35] > 0.0),
	[col36] decimal(16,2),
	[col37] decimal(19,4),
	[col38] tinyint,
	[col39] tinyint UNSIGNED,
	[col40] tinyint,
	[col41] smallint,
	[col42] smallint,
	[col43] nvarchar(255) CHECK ([col43] LIKE "test%"),
	[col44] nvarchar(255) NOT NULL,
	[col45] nvarchar(32) CHECK ([col45] LIKE "test%"),
	[col46] nvarchar(32),
	[col47] nvarchar(255),
	[col48] nvarchar(max) CHECK ([col48] LIKE "test%"),
	[col49] nvarchar(max) NOT NULL,
	[col50] nvarchar(255) CHECK ([col50] LIKE "test%"),
	[col51] nvarchar(255) NOT NULL,
	[col52] nvarchar(255),
	[col53] nvarchar(max),
	[col54] time NOT NULL,
	[col55] time,
	[col56] datetime NOT NULL,
	[col57] datetime,
	[col58] datetime NULL DEFAULT NULL,
	[col59] int COMMENT 'test comment'
)

/yii/framework/db/Schema.php:597
/yii/framework/db/Command.php:1004
/yii/tests/framework/db/QueryBuilderTest.php:1080
/yii/vendor/phpunit/phpunit/phpunit:52

Caused by
PDOException: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'UNSIGNED'.

/yii/framework/db/Command.php:994
/yii/tests/framework/db/QueryBuilderTest.php:1080
/yii/vendor/phpunit/phpunit/phpunit:52
```
</details>

`tinyint` is forcibly unsigned. It doesn't have a specifiable length or signedness.

<details><summary>Test output</summary>

```
6) yiiunit\framework\db\mssql\QueryBuilderTest::testGetColumnType
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'tinyint(1) NOT NULL DEFAULT 1'
+'bit NOT NULL DEFAULT 1'

/yii/tests/framework/db/QueryBuilderTest.php:1055
/yii/vendor/phpunit/phpunit/phpunit:52
```
</details>

No clue yet.

<details><summary>Test output</summary>

```
22) yiiunit\framework\db\oci\QueryBuilderTest::testCreateTableColumnTypes
yii\db\Exception: SQLSTATE[HY000]: General error: 907 OCIStmtExecute: ORA-00907: missing right parenthesis
 (/tmp/tmp.f579yxJhXa/PDO_OCI-1.0/oci_statement.c:142)
The SQL being executed was: CREATE TABLE "column_type_table" (
	"col1" NUMBER(20),
	"col2" NUMBER(20) NOT NULL,
	"col3" NUMBER(20) CHECK ("col3" > 5),
	"col4" NUMBER(8),
	"col5" NUMBER(8) CHECK ("col5" > 5),
	"col6" BLOB,
	"col7" NUMBER(1),
	"col8" CHAR(1) NOT NULL,
	"col9" CHAR(6),
	"col10" CHAR(1),
	"col11" DATE NOT NULL,
	"col12" DATE,
	"col13" TIMESTAMP NOT NULL,
	"col14" TIMESTAMP,
	"col15" NUMBER CHECK ("col15" > 5.6),
	"col16" NUMBER NOT NULL,
	"col17" NUMBER CHECK ("col17" > 5.6),
	"col18" NUMBER,
	"col19" NUMBER,
	"col20" NUMBER CHECK ("col20" > 5.6),
	"col21" NUMBER NOT NULL,
	"col22" NUMBER CHECK ("col22" > 5.6),
	"col23" NUMBER,
	"col24" NUMBER,
	"col25" NUMBER CHECK ("col25" > 5.6),
	"col26" NUMBER NOT NULL,
	"col27" NUMBER CHECK ("col27" > 5.6),
	"col28" NUMBER,
	"col29" NUMBER,
	"col30" NUMBER(10) CHECK ("col30" > 5),
	"col31" NUMBER(10) NOT NULL,
	"col32" NUMBER(8) CHECK ("col32" > 5),
	"col33" NUMBER(8),
	"col34" NUMBER(10),
	"col35" NUMBER(19,4) CHECK ("col35" > 0.0),
	"col36" NUMBER(19,4) NOT NULL,
	"col37" NUMBER(16,2) CHECK ("col37" > 0.0),
	"col38" NUMBER(16,2),
	"col39" NUMBER(19,4),
	"col40" NUMBER(2),
	"col41" NUMBER(3) UNSIGNED,
	"col42" NUMBER(3),
	"col43" NUMBER(8),
	"col44" NUMBER(5),
	"col45" VARCHAR2(255) CHECK ("col45" LIKE 'test%'),
	"col46" VARCHAR2(255) NOT NULL,
	"col47" VARCHAR2(32) CHECK ("col47" LIKE 'test%'),
	"col48" VARCHAR2(32),
	"col49" VARCHAR2(255),
	"col50" CLOB CHECK ("col50" LIKE 'test%'),
	"col51" CLOB NOT NULL,
	"col52" CLOB CHECK ("col52" LIKE 'test%'),
	"col53" CLOB NOT NULL,
	"col54" CLOB,
	"col55" CLOB,
	"col56" TIMESTAMP NOT NULL,
	"col57" TIMESTAMP,
	"col58" TIMESTAMP NOT NULL,
	"col59" TIMESTAMP,
	"col60" NUMBER(1) DEFAULT 1 NOT NULL
)

/yii/framework/db/Schema.php:597
/yii/framework/db/Command.php:1004
/yii/tests/framework/db/QueryBuilderTest.php:1080
/yii/vendor/phpunit/phpunit/phpunit:52

Caused by
PDOException: SQLSTATE[HY000]: General error: 907 OCIStmtExecute: ORA-00907: missing right parenthesis
 (/tmp/tmp.f579yxJhXa/PDO_OCI-1.0/oci_statement.c:142)

/yii/framework/db/Command.php:994
/yii/tests/framework/db/QueryBuilderTest.php:1080
/yii/vendor/phpunit/phpunit/phpunit:52
```
</details>

There's no `UNSIGNED NUMBER` in Oracle. :(

**Review by sergeymakinen — CHANGES_REQUESTED** [review]
I have noted most important failures. Despite this, LGTM.

**Comment by sergeymakinen** [comment]
Just in case: [here](https://gist.github.com/sergeymakinen/0696a5952f160ea28d7b64c3adfecf6f) is my test environment to test all DBMSes we support ATM.

**Comment by samdark** [comment]
@rob006 do you have time to fix errors? Docker images provided by @sergeymakinen should make it easier.

**Comment by dmirogin** [comment]
@samdark would be great move these docker images to contributors section in documentation

**Comment by samdark** [comment]
Yes, indeed. Can you help with it? Busy with experimental stuff right now :(

**Comment by rob006** [comment]
@samdark I don't have enough time to play with it right now. I may try to finish this in next month.

@sergeymakinen 
> No clue yet.

Are you sure that this works fine in master?

> There's no UNSIGNED NUMBER in Oracle. :(

Then how `$this->integer()->unsigned()` works right now for Oracle?

**Comment by sergeymakinen** [comment]
@rob006 
> Are you sure that this works fine in master?

Not really, but here is a DDL for this test:

```sql
create table "column_type_table"
(
	"col1" NUMBER(20),
	"col2" NUMBER(20) not null,
	"col3" NUMBER(20)
		check ("col3" > 5),
	"col4" NUMBER(8),
	"col5" NUMBER(8)
		check ("col5" > 5),
	"col6" BLOB,
	"col7" NUMBER(1),
	"col8" CHAR not null,
	"col9" CHAR(6),
	"col10" CHAR,
	"col11" DATE not null,
	"col12" DATE,
	"col13" TIMESTAMP(6) not null,
	"col14" TIMESTAMP(6),
	"col15" NUMBER
		check ("col15" > 5.6),
	"col16" NUMBER not null,
	"col17" NUMBER
		check ("col17" > 5.6),
	"col18" NUMBER,
	"col19" NUMBER,
	"col20" NUMBER
		check ("col20" > 5.6),
	"col21" NUMBER not null,
	"col22" NUMBER
		check ("col22" > 5.6),
	"col23" NUMBER,
	"col24" NUMBER,
	"col25" NUMBER
		check ("col25" > 5.6),
	"col26" NUMBER not null,
	"col27" NUMBER
		check ("col27" > 5.6),
	"col28" NUMBER,
	"col29" NUMBER,
	"col30" NUMBER(10)
		check ("col30" > 5),
	"col31" NUMBER(10) not null,
	"col32" NUMBER(8)
		check ("col32" > 5),
	"col33" NUMBER(8),
	"col34" NUMBER(10),
	"col35" NUMBER(19,4)
		check ("col35" > 0.0),
	"col36" NUMBER(19,4) not null,
	"col37" NUMBER(16,2)
		check ("col37" > 0.0),
	"col38" NUMBER(16,2),
	"col39" NUMBER(19,4),
	"col40" NUMBER(2),
	"col41" NUMBER(3),
	"col42" NUMBER(3),
	"col43" NUMBER(8),
	"col44" NUMBER(5),
	"col45" VARCHAR2(255)
		check ("col45" LIKE 'test%'),
	"col46" VARCHAR2(255) not null,
	"col47" VARCHAR2(32)
		check ("col47" LIKE 'test%'),
	"col48" VARCHAR2(32),
	"col49" VARCHAR2(255),
	"col50" CLOB
		check ("col50" LIKE 'test%'),
	"col51" CLOB not null,
	"col52" CLOB
		check ("col52" LIKE 'test%'),
	"col53" CLOB not null,
	"col54" CLOB,
	"col55" CLOB,
	"col56" TIMESTAMP(6) not null,
	"col57" TIMESTAMP(6),
	"col58" TIMESTAMP(6) not null,
	"col59" TIMESTAMP(6),
	"col60" NUMBER(1) default 1  not null
)
```

Maybe it could be helpful.

> Then how $this->integer()->unsigned() works right now for Oracle?

Like many other Oracle/MSSQL things ATM - it doesn't.

`$this->integer()->unsigned()` is tested against an SQL it produces: an expected incorrect SQL and tests pass.

**Comment by Renkas** [comment]
If I understand the unsigned problem correctly. Why couldn't you just ignore unsigned call in DB's that don't support it?

I mean `$this->integer()->unsigned()` would generate same SQL than `$this->integer()`.

**Comment by samdark** [comment]
@Renkas either that or throwing an exception. Exception is more verbose, signed fallback allows not worry too much about schema cross-database. It will just work in nearly same way.

**Comment by sergeymakinen** [comment]
Ideally, calling `unsigned()` should add `CHECK "column" >= 0` if there's no check already defined or throw an exception explaining you should alter your existing check and add such statement.

**Comment by rob006** [comment]
This is basically the same problem as #11841. I really think that we should introduce some way to define what is required and what only optional in migration (https://github.com/yiisoft/yii2/issues/11841#issuecomment-230461284).

**Review by samdark — APPROVED** [review]

**Comment by rob006** [comment]
Regrading failed tests mentioned in https://github.com/yiisoft/yii2/pull/15203#issuecomment-346936793:

```
6) yiiunit\framework\db\mssql\QueryBuilderTest::testGetColumnType
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'tinyint(1) NOT NULL DEFAULT 1'
+'bit NOT NULL DEFAULT 1'

/yii/tests/framework/db/QueryBuilderTest.php:1055
/yii/vendor/phpunit/phpunit/phpunit:52
```

I have the same error on master. I think fixing it is outside scope of this PR.

```
yii\db\Exception: SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'UNSIGNED'.
```

This test was invalid and I removed it. 

> There's no UNSIGNED NUMBER in Oracle. :(

This should be fixed for all `NUMBER` types, not only `tinyint`. I think it should to be done in separate PR. Right now I just removed this test for oci (there are no working tests for unsigned numbers for oci and mssql at all).

@samdark Any chance to merge this in 2.0.14? It was already approved by 3 persons and all failing test from https://github.com/yiisoft/yii2/pull/15203#issuecomment-346936793 are not directly related to this PR.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
