### PR TITLE
Adds `custom()` modifier to schema builder

### PR DESCRIPTION
**Pull request by usecomposable**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes/no |
| Fixed issues | #11195 |

### CODE REVIEW

**Comment by samdark** [comment]
I don't like the method name. @yiisoft/core-developers what do you think about the name?

**Comment by Faryshta** [comment]
how about a `comment()` method?

**Comment by samdark** [comment]
@Faryshta that's totally separate thing.

**Comment by SilverFire** [comment]
This method name is not self-documenting. 
How about `concat()`?

**Comment by klimov-paul** [comment]
Could be:
`addRaw()`
`rawSql()`
`expression()`
`addExpression()`

**Comment by samdark** [comment]
Merged with adjustments: https://github.com/yiisoft/yii2/commit/66eabda770c60e389d5a0a61de907d2162173106 and https://github.com/yiisoft/yii2/commit/27866bf9d6bd27b52eae97bf33dba2228058ac88

**Pull request closed without merging**
