### PR TITLE
Validation of authKey for existing session

### LINKED ISSUE #9718: User stays authorized despite auth key is changed
While renewAuthStatus() method of yii\web\user is getting user id from session variable, it's not checking auth key. If auth key changes, the user still will be authorized while his id is stored in session.

Steps to reproduce this issue with Advanced application template:
1. Add `$user->generateAuthKey();` in resetPassword method of frontend\models\ResetPasswordForm directly after `$user->setPassword($this->password);`
2. Login as any user in browser
3. Open new inconito tab
4. Login as same user in incognito tab
5. Change password in incognito tab
6. Check that you are still authorized in all tabs

### PR DESCRIPTION
**Pull request by kidol**
WIP
Fixes #9718

### CODE REVIEW

**Comment by samdark** [comment]
Looks OK to me.

@yiisoft/core-developers any comments?

@kidol is it still WIP? Do you have something in mind to improve?

**Comment by klimov-paul** [comment]
Instead of using `authKey` for this purpose - a new Identity parameter should be added.
Most obvious and quick solution for the original issue can be storing and comparing of the 'password_hash'. Once password has been changed by any mean - user will have to re-login.

However introduction of the new Identity property requires changing of the `IdentityInteface` signature and BC break.

**Comment by samdark** [comment]
Why authkey couldn't be used for the purpose?

**Comment by kidol** [comment]
Well currently docs all say authKey is only needed for cookie.
Also not sure whether session and/or identityCookie should be destroyed when wrong authKey is detected (currently log gets filled with warnings on every pageview).
There is probably more.

Will look into it soon.

**Comment by klimov-paul** [comment]
> Why authkey couldn't be used for the purpose?

It could. However, the original issue sounds: "after user changes his password all other sessions should be dropped". The most obvious solution will be compare `password_hash` sinse it changes once user change his password, while in current state you should regenerate `authKey` on new password setup.
I am saying that we should introduce another method `IdentityInterface::getRestoreValidationKey()`. It can return `authKey` or anything else - `password_hash` is most obvious here.

Also remember that original purpose of the `authKey` is different. Even more it can be left unimplemented for the particular identity, if application does not provides 'auto login' feature.
These should not be mixed up.

**Comment by kidol** [comment]
Original issue title is:
>User stays authorized despite auth key is changed

So if he changes authKey because of new password or some other reason, it doesn't matter. He wants any active session to be invalid and that's what authKey can be used for (at least for cookie-login currently).

>Also remember that original purpose of the authKey is different.

Yes, but current implementation is not logical: The identity gets fetched every time you access session, but only cookie-login uses authKey.

>Even more it can be left unimplemented for the particular identity, if application does not provides 'auto login' feature.

If there is such app, then break BC for them and note in upgrade file: If they don't want to implement authKey feature, they can simply return `null` in `getAuthKey()`. This will keep current behavior.
Also currently they already have to provide the authKey related methods because it's an interface.

**Comment by kidol** [comment]
One problem is if application changes underlying authKey for an active session. For example, if app has button "invalidate all other sessions" which will update authKey in db, then current session will still have old authKey in next pageload. However, user can call `yii\web\User::switchIdentity()` to recreate session with updated authKey. This is noted in upgrade file.

@laendyl Were you able to test this patch yet?

**Comment by kidol** [comment]
@klimov-paul If you look at my explanation and current diff, you still have doubts?

@undestroyer, @dynasource Could you help test this patch?

**Comment by dynasource** [comment]
I will when I find time. thx

**Comment by kidol** [comment]
Most likely outdated, also no interest in working further on this.

**Pull request closed without merging**
