### PR TITLE
Fixed #8779: Automatically set enctype form option when using file in…

### LINKED ISSUE #8779: Automatically set enctype form option when using file input field
What if when using file input like that:

```php
<?= $form->field($model, 'imgFile')->fileInput() ?>
```

the `enctype` will be set to `multipart/form-data` automatically?

### PR DESCRIPTION
**Pull request by pana1990**
https://github.com/yiisoft/yii2/issues/8779

### CODE REVIEW

**Comment by klimov-paul** [comment]
Fix is not correct, because if form have only file inputs there is no need to set `enctype` for it.

**Comment by pana1990** [comment]
@klimov-paul  what is the problem?

For example, Ruby on Rails works well .

view in rails : 

screenshot_1

browser : 
screenshot_2

thanks in advance for your answer.

**Comment by klimov-paul** [comment]
It will work, but following your logic we can just add 'enctype' to all forms by default, which by the way can be done via DI.

**Comment by pana1990** [comment]
But when i use fileinput  helper i always want to add enctype.

I think it is expected behavior in my humble opinion.

**Comment by samdark** [comment]
I think the change is OK.

**Comment by githubjeka** [comment]
Up.

It's the normal fix.

**Comment by mdmunir** [comment]
:+1:

**Comment by pana1990** [comment]
@samdark @klimov-paul @cebe i think to ready to merge

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/7dc984d35928128b3612fb6aa4ed19b03ee963fd merged. Thank you!

**Pull request closed without merging**
