### PR TITLE
.gitignore: add NPM package-lock.json file

### PR DESCRIPTION
**Pull request by kamarton**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | 
| Tests pass?   | ✔️
| Fixed issues  | -

I use PHPStorm. If installing NPM, then creating this file.

### CODE REVIEW

**Comment by samdark** [comment]
Why do we need to ignore it?

**Comment by kamarton** [comment]
It is not at all certain that it created content same things for two developers. If you get into PR, you will have an conflict and you will not be mergeable. 
I'm afraid of being accidentally committing to any pull request.

**Comment by kamarton** [comment]
It was a shame that I did not create an issue for this.

**Comment by rob006** [comment]
IMO it should be committed to repository to ensure that everyone uses the same dependencies. Same story as with `composer.lock`.

**Comment by kamarton** [comment]
I accept the arguments.

**Pull request closed without merging**
