### PR TITLE
single style to structure block (start-workflow.md)

### PR DESCRIPTION
**Pull request by Arhell**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | https://github.com/yiisoft/yii2/issues/18723

One style example here https://www.yiiframework.com/doc/guide/2.0/en/start-workflow#application-structure

I reviewed many options, this one is more suitable

### CODE REVIEW

**Comment by bizley** [comment]
Have you tried `text` or `plaintext`? Or `sh` maybe? And if all fails as well there should be `js` for shorter alias hopefully.

**Comment by Arhell** [comment]
> Have you tried `text` or `plaintext`? Or `sh` maybe? And if all fails as well there should be `js` for shorter alias hopefully.

Tried this is the best option
And there is no short name, for hljs I checked on the library website

**Comment by bizley** [comment]
Which library is that? @samdark which library is used to generate it on the guide page?

**Comment by Arhell** [comment]
> Which library is that? @samdark which library is used to generate it on the guide page?

@bizley 
from this repo https://github.com/yiisoft-contrib/yiiframework.com

and in composer
c46d0b37a6

**Comment by bizley** [comment]
I can see there `shell`, also there [is](https://github.com/scrivo/highlight.php/blob/9.18/Highlight/languages/javascript.json#L3) `js` alias for `javascript`.

**Comment by Arhell** [comment]
shell is similar to this https://www.yiiframework.com/doc/guide/2.0/fr/start-workflow, and if you don't mind, I'll replace js next time (not critical), thanks

Main display is the same on all pages

**Comment by bizley** [comment]
Thank you

**Pull request merged**
