### PR TITLE
Handling prefix in REST UrlRule when parsing request

### PR DESCRIPTION
**Pull request by bizley**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | - (but should help a bit with #18474 )

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Comment by markch123** [comment]
This goes back a long time but would it be an idea to trigger php benchmarks to test 2.0.41? There wasnt really much point before as the rest api dragged down the total score but with this update it would be interesting to see the difference?

[http://www.phpbenchmarks.com/en/benchmark/yii/2.0](url)

**Comment by samdark** [comment]
@markch123 would be interesting but I have no idea about how to trigger these.

**Comment by markch123** [comment]
I see we have a phpbenchmark repo [https://github.com/phpbenchmarks/yii](https://github.com/phpbenchmarks/yii). It maybe as simple as bumping the version in compser.json from 2.0.18 to 2.0.41 and send in a PR? There is bound to be somebody in the community who has some experience with this.

**Comment by bizley** [comment]
IIRC they are not using prefixes for requests so this change would not help.

**Pull request merged**
