### PR TITLE
Added DB2 database driver

### PR DESCRIPTION
**Pull request by nikashitsa**
This Pull Request solves #5.
Tested on Ubuntu 14.04 x64 "DB2 v10.5.0.5", "s141128", "IP23633", and Fix Pack "5"
PHP 5.5.9, PDO_IBM-1.3.3
Tests: 212, Assertions: 1366, Errors: 1, Failures: 1, Skipped: 2.

pdo_ibm is buggy, e.g. using PDO::PARAM_NULL throws error.
It would be nice, if someone update pdo_ibm.

test config

```
$config['databases']['ibm'] = [
    'dsn' => 'ibm:yiitest',
    'username' => 'vagrant',
    'password' => 'vagrant',
    'fixture' => __DIR__ . '/ibm.sql',
];
```

Remaning issues:
- testExplicitPkOnAutoIncrement failed. In db2 it seems to be a problem.
- problems with blob (empty result string) and clob (segmentation fault error). I wrote test for that testClobBlobValues
- Need to implement checkIntegrity. Solution from https://github.com/vbsessa/yii2-db2 doesn't work in my DB2 version.

I can send DB2 and pdo_ibm installation guide below, because it's tricky.
Now we have some beginning :)

### CODE REVIEW

**Comment by vbsessa** [comment]
Nice! Good initiative.
Actually, my work is based on @edgardmessias' one. I don't have a dev environment properly configured so a can't test it, but i think the checkIntegrity function has a syntax error. You could try `SET INTEGRITY FOR $tableName IMMEDIATE $enable"` instead.

**Comment by nikashitsa** [comment]
@vbsessa your work based on @edgardmessias, my work based on yours - evolution :)
btw, your suggestion about checkIntegrity function doesn't work.
I've tried this example and got FOREIGN KEY error.
```
SET INTEGRITY FOR "order" ALL IMMEDIATE UNCHECKED;
INSERT INTO "order" ("customer_id", "created_at", "total") VALUES (2000, 1325502201, 40.0);
SET INTEGRITY FOR "order" IMMEDIATE CHECKED;
```

**Comment by cebe** [comment]
Great job, thanks for starting this! Is there a possibility that I could install a DB2 instance for testing? Do they have a version that I could download for testing purpose?

**Comment by edgardmessias** [comment]
See in my code: https://github.com/edgardmessias/yii2-ibm-db2
It has script to install the database for testing

**Pull request closed without merging**
