### PR TITLE
Corrected the Component::__isset() docs

### PR DESCRIPTION
**Pull request by brandonkelly**
__isset() returns true if the property is set; not if it's null.

### CODE REVIEW

**Comment by cebe** [comment]
well, it is also considered not to be set if it is null, just like php `isset()`.
Could be made clearer by saying `Checks if a property value is set i.e., defined and not null.`

**Comment by brandonkelly** [comment]
@cebe I don’t agree that it is the job of this method’s docs to explain what “set” means.

Take it or leave it. Just offering a correction, as currently the docs are saying the opposite of what the purpose of __isset() is.

**Comment by lynicidn** [comment]
https://github.com/brandonkelly/yii2/blob/86504e6ee0308447ea9a71d0a9af1be685272b47/framework/base/Component.php#L235

**Comment by klimov-paul** [comment]
Magic method `__isset()` serves as a response for `isset()` PHP operator.
For the regular variables this operator considers `null` value as not set:
```php
$var = null;
var_dump(isset($var)); // outputs 'false'
```

**Comment by brandonkelly** [comment]
@klimov-paul That doesn’t mean that it _only_ applies to `null` values though! It also (and primarily) is used to determine if a variable/property exists at all.

@lynicidn Are you pointing out that there is precedence for mentioning "null" in the docs? I disagree; in __unset()’s case, the documentation is (pretty much) accurate: Component::__unset() will actually throw a InvalidCallException if you try to unset a property that doesn’t exist or is read-only. But __isset() on the other hand will simply return `true` or `false` depending on whether the variable exists at all and is set to a non-null value (generally).

**Comment by cebe** [comment]
> @cebe I don’t agree that it is the job of this method’s docs to explain what “set” means.

There is nothing wrong with being explicit about the meaning of something even if it may be clear in some context.

Merged and adjusted it a bit, thanks!

**Pull request closed without merging**
