### PR TITLE
Added 'zh' into 'framework/messages/config.php'

### PR DESCRIPTION
**Pull request by NabiKAZ**
The `zh` directory there is in the `framework/messages` path, but it was not added in the `config.php` file. That I did. (maybe the `zh` folder needed to be deleted, which needs to be checked)

### CODE REVIEW

**Comment by samdark** [comment]
Fallback should've covered it already. Did you have any problems with the current `master` config?

**Comment by NabiKAZ** [comment]
As you can see, I have changed only one file. I didn't test the overall configuration of the framework and I don't know why it gave missing coverage!

**Comment by samdark** [comment]
I mean functionality, not coverage. When `zh-CN` isn't found, it falls back to `zh` automatically.

**Comment by rob006** [comment]
This is config adjustment for https://github.com/yiisoft/yii2/pull/19832, right now command for extracting messages in framework will ignore `zh` directory.

@NabiKAZ I that we should only rename `zh-CN` to `zh` to match current directory structure introduced by https://github.com/yiisoft/yii2/pull/19832

**Comment by NabiKAZ** [comment]
I did that, now we only have `zh` and `zh-TW` in config and directories.

**Pull request merged**
