### PR TITLE
change the signature of FixtureController::actionLoad()

### PR DESCRIPTION
**Pull request by Faryshta**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | yes |
| Tests pass? | yes |
| Fixed issues | #11683 |

Breaks BC but currently the command is broken too.

If this is ok for merge I will update the guide and changelog.

### CODE REVIEW

**Comment by Faryshta** [comment]
@samdark @SilverFire

**Comment by samdark** [comment]
Hmm... what was the meaning of `-` in `-User`?

**Comment by Faryshta** [comment]
to NOT load/unload that fixture. `*, -User` means you run ll the fixtures except UserFixture

**Comment by samdark** [comment]
OK. It makes sense.

**Comment by samdark** [comment]
Merged with additions: https://github.com/yiisoft/yii2/commit/8c240ed0679d55676134ea91eb12f7e5967a7a58

Thank you!

btw., is there a need to adjust faker's fixture command as well?

**Comment by Faryshta** [comment]
@samdark i don't know, i haven't used the faker command, is there doc about it?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-faker/tree/master/docs/guide

**Pull request closed without merging**
