### PR TITLE
Update db-dao.md

### PR DESCRIPTION
**Pull request by yugaego**
Removed table prefix sign, description of which is done in the next paragraph only.

### CODE REVIEW

**Comment by Faryshta** [comment]
please explain to me. how could this break anything at all?

**Comment by yugenekr** [comment]
It misleads readers or the docs. Example doesn't represent the description of the paragraph.

**Comment by Faryshta** [comment]
no, i mean the travis integration error.

i am not saying your PR is unneeded, i was honestly curious why a change on documentation would break the continuous integration

**Comment by samdark** [comment]
It's not related.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
