### PR TITLE
Refactoring yii\web\Request::getMethod

### PR DESCRIPTION
**Pull request by githubjeka**

### CODE REVIEW

**Comment by cebe** [comment]
why?

**Comment by githubjeka** [comment]
easier to read

**Comment by samdark** [comment]
Looks good to me.

**Comment by cebe** [comment]
not a strong opinion but it looks weird to me. Why not use elseif?

**Comment by githubjeka** [comment]
Well, I think it's a well known fact, it is strange that you do not know. Without `ifelse ... else `, the code becomes flat. And it is easier to read, since reading occurs by only vertically. 

I bumped into this "pile" of code, and only after refactoring it saw that GET is always returned for me. :)

**Comment by cebe** [comment]
I'm fine with extracting the 'GET' default but I do not see why not to use elseif anymore.

**Comment by cebe** [comment]
```php
    public function getMethod()
    {
        if (isset($_POST[$this->methodParam])) {
            return strtoupper($_POST[$this->methodParam]);
        } elseif (isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])) {
            return strtoupper($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']);
        } elseif (isset($_SERVER['REQUEST_METHOD'])) {
            return strtoupper($_SERVER['REQUEST_METHOD']);
        } else {
            return 'GET';
        }
    }
```

**Comment by githubjeka** [comment]
```php
public function getMethod()
{
    if (isset($_POST[$this->methodParam])) {
        return strtoupper($_POST[$this->methodParam]); //break up
    } elseif (isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])) { //elseif  why??? before break up was 
        return strtoupper($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']);  //break up
    } elseif (isset($_SERVER['REQUEST_METHOD'])) { //elseif  why??? before break up was 
        return strtoupper($_SERVER['REQUEST_METHOD']);  //break up
    } else {  //else  why??? before break up was 
      return 'GET';  //break up
    }
}
```

vs 

```php
public function getMethod()
{
    if (isset($_POST[$this->methodParam])) {
         return strtoupper($_POST[$this->methodParam]); //break up
    } 
    if (isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'])) { 
       return strtoupper($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']);  //break up
    } 
    if (isset($_SERVER['REQUEST_METHOD'])) {
       return strtoupper($_SERVER['REQUEST_METHOD']);  //break up
    } 
    return 'GET';  //break up       
}
```

**Comment by githubjeka** [comment]
First variant raises questions for me.

**Comment by samdark** [comment]
2nd looks cleaner to me as well. A bit easier to read.

**Pull request merged**
