### PR TITLE
Issue 16639 postgres load indexes

### PR DESCRIPTION
**Pull request by carono**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #16639

### CODE REVIEW

**Comment by samdark** [comment]
Are you sure that sub-query won't affect schema reading performance significantly?

**Comment by carono** [comment]
I will answer this question a little later, I will make measurements of productivity. I'll also try to make a single request

**Comment by carono** [comment]
you're right, there's still something to think about about optimizing the subquery.

tables: 100
columns in each table: 20
indexes in each table: 15
queries: 10000

Current query: 17sec
With sub query: 49sec

I will have to remove the subquery, but I do not yet know how =)

**Comment by samdark** [comment]
Closing since in its current form the pull request affects performance significantly.

**Pull request closed without merging**
