### PR TITLE
ComposerValidatorTest - Fixed PHP7 error

### PR DESCRIPTION
**Pull request by SilverFire**

### CODE REVIEW

**Comment by samdark** [comment]
Aha, the breaking PHP 7 change.

**Comment by SilverFire** [comment]
The test runs with all-ok on php7. The next problem is segfault on travis:
`/home/travis/build.sh: line 41:  3411 Segmentation fault      (core dumped) vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group mssql,oci,wincache,xcache,zenddata,cubrid`

**Comment by samdark** [comment]
Yep.

**Comment by samdark** [comment]
Thanks for digging into it.

**Pull request merged**
