### PR TITLE
Update Controller.php

### PR DESCRIPTION
**Pull request by manyopensource**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by Renkas** [comment]
But why?

It only breaks the framework ...

**Comment by manyopensource** [comment]
Answer: It is very logical: SomeController, someAction

**Comment by manyopensource** [comment]
And Phalcon use that...

**Comment by dmirogin** [comment]
I think, do something, cause it works another way in other frameworks is a bad way. Moreover there is no any benefit. Not to mention the fact that it breaks all solutions based on yii2.

**Pull request closed without merging**
