### PR TITLE
Enh #14094 UrlManager::createUrl() cache may degrade performance in s…

### PR DESCRIPTION
**Pull request by qihuajun**
…ome cases -- optimize createUrl method to cancel repeated call

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14094

### CODE REVIEW

**Comment by rob006** [comment]
This solution seems to be OK, but these tests does not prove anything. I could merge this to #13350 and adjust [this test](https://github.com/rob006/yii2-dev/blob/2f520f339dc616f2875ebf258cbacdd4e9ea597d/tests/framework/web/UrlManagerCreateUrlTest.php#L707).

**Comment by samdark** [comment]
@rob006 would be great.

**Comment by rob006** [comment]
Done: https://github.com/yiisoft/yii2/pull/13350/commits/e25314191b2de8c910ab42e401db97a77cfa3067

**Comment by samdark** [comment]
Closing since @rob006 adopted it.

**Pull request closed without merging**
