### PR TITLE
Provider should force prepare after setModels call

### PR DESCRIPTION
**Pull request by vals2004**
| Q | A |
| --- | --- |
| Is bugfix? | yes/no |
| New feature? | yes/no |
| Breaks BC? | yes/no |
| Tests pass? | yes/no |
| Fixed issues | comma-separated list of tickets # fixed by the PR, if any |

Provider should force prepare after setModels call

### CODE REVIEW

**Comment by SilverFire** [comment]
Why?

**Comment by vals2004** [comment]
$provider = new ArrayDataProvider(['allModels'=>[1, 2]);
$provider->getKeys(); // 0,1

$provider->setModels([1,2,3]);
$provider->getKeys(); // 0,1 but not 0,1,2

because nobody call prepareModels && prepareKeys (from ArrayDataProvider)

**Comment by SilverFire** [comment]
It was not intended to use data providers in this way. If you want to change providers' context (pass another set of models) - you must re-create DataProvider object.

**Comment by cebe** [comment]
forcing prepare on set is against the lazy loading principle. If you change models you have to call prepare() manually afterwards.

**Pull request closed without merging**
