### PR TITLE
Change order checking in \yii\base\ArrayableTrait::toArray() and \yii\rest\Serializer::serialize()

### PR DESCRIPTION
**Pull request by Spell6inder**
As for me, I expect if I call `toArray()` then `toArray()` will be called in nested objects if they implement `Arrayable`.
In my case, I use `JsonSerializable` for serialize, and `Arrayable` for data preparation for Response.
For example, result of `jsonSerialize()` :
```json
{
  "__class": "foo\\bar\\MyClass",
  "prop1": 1,
  "prop2": 2
}
```

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Tests pass?   | Not tested
| Fixed issues  | -

### CODE REVIEW

**Comment by bizley** [comment]
While I think this change is reasonable (at least at first glance) it's a serious BC break. Needs more discussion.

**Comment by Spell6inder** [comment]
> While I think this change is reasonable (at least at first glance) it's a serious BC break. Needs more discussion.

Yes, I agree. But I already get BC break after #17888. That's why I propose a change order of checking.

In general, I do not understand why need mix 2 methods: `toArray()` and `jsonSerialize()`...
I think `jsonSerialize()` must return data that need to create (unserialize) original object and `toArray()` is a proccessed data.
For example, if I have object of CartPosition:
Return of `jsonSerialize()` 
```php
[
    'product_id' => 1,
    'variation_id' => 2,
    'quantity' => 10,
];
```
Return of `toArray()` 
```php
[
    'id' => '1-2',
    'name' => 'Product name',
    'sku' => 'sku',
    'quantity' => 10,
    'price' => 100,
    'cost' => 90,
];
```

**Comment by samdark** [comment]
That would unlikely cause big breakage in real apps. Having both `\JsonSerializable` and `Arrayable` in a single class isn't common. Still, if we're going to merge it, UPGRADE should mention it and provide a solution in case there's something broken.

I'd like to hear @yiisoft/reviewers opinions on the matter as well.

**Comment by bizley** [comment]
I, as I said already, am all for it. Upgrade + correcting tests is in order.

**Comment by schmunk42** [comment]
A also see it more as a fix for the issue introduced in #17888 it makes more sense to check for the "more specific" instance first.

**Comment by samdark** [comment]
OK. @Spell6inder would you please fix tests and add a note to UPGRADE?

**Comment by Spell6inder** [comment]
@samdark I get error `Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop'` and not sure what to do next...
Is this pull request is correct?

**Comment by samdark** [comment]
Fixed that.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks.

**Comment by guntiszarinsh** [comment]
Model's implenets Arrayable. but JsonSerializable not. If extend Model with JsonSerializable implementation, because ``Serializer->serialize()`` first check for ``Arrayable``. 
~~~php
        } elseif ($data instanceof Arrayable) {
            return $this->serializeModel($data);
        } elseif ($data instanceof \JsonSerializable) {
            return $data->jsonSerialize();
~~~
Now json serialization is stopped working. Sad.

**Pull request merged**
