### PR TITLE
FIX Issue #7317 (File "yii" missing in project root)

### PR DESCRIPTION
**Pull request by herzmut**
This file was missing in advanced/apps, as described in the given issue. https://github.com/yiisoft/yii2/issues/7317

### CODE REVIEW

**Comment by lynicidn** [comment]
run php init command

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/7317

**Comment by fernandezekiel** [comment]
it's in the console part of the application

**Comment by dguhl** [comment]
The _init_ command copies "environments/[environment]/yii" to the app root. This somehow didn't work when I initialized the project, but it makes my patch / PR obsolete.

Thanks anyway, guys.

**Pull request closed without merging**
