### PR TITLE
Update `Container::mergeParams()`

### PR DESCRIPTION
**Pull request by WinterSilence**
Merge parameter values, usefull for properties like as `InputWidget::$options`

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17241

### CODE REVIEW

**Comment by samdark** [comment]
Would you please give an example?

**Comment by WinterSilence** [comment]
@samdark merge parameters defined by container with passed config:
~~~php
Yii::$container->set(yii\widgets\InputWidget::class, ['options' => ['class' => 'field-input']]);
yii\widgets\InputWidget::widget(['options' => ['form' => $model->formName()]]);
~~~

**Comment by WinterSilence** [comment]
@samdark [you been looking for better solution?](https://github.com/yiisoft/yii2/pull/18496) that is it

**Comment by samdark** [comment]
Alright. Now I see the issue. Linked it.

**Comment by samdark** [comment]
I suspect that may change behavior significantly though. What if I need to override one associative array with another associative array without merging these?

**Comment by WinterSilence** [comment]
@samdark just don't define that's parameters by container

**Comment by samdark** [comment]
It could be already used so we'll break existing applications.

@bizley, @rob006 maybe you have some use-cases where it breaks for certain?

**Comment by bizley** [comment]
It's BC break for sure I'm afraid.

**Comment by rob006** [comment]
Does it really change anything in terms of #17241? `mergeParams()` is used for merging constructor parameters, AFAIK it is irrelevant in terms of config passed to `Widget::widget()`. Correct solution for #17241 was proposed in https://github.com/yiisoft/yii2/pull/18059, but it was rejected because of BC break. If we don't care about BC break, that is the way. If we care about BC break and want to fix #17241, we probably need to introduce another value-object to pass config that can be merged, and require to use it explicitly:

```php
MyWidget::widget([
    'myOption' => new MergeArrayValue([
         'option' => 'custom value',
    ]),
]);
```

**Pull request closed without merging**
