### PR TITLE
Fix migration history order

### PR DESCRIPTION
**Pull request by devgen-io**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #12980

### CODE REVIEW

**Comment by SilverFire** [comment]
Thank you, this one looks good in general.

How do you suggest to update the `migration` table in case it already exists? Write a new migration? :)

**Comment by evgen-d** [comment]
I don't know, may be.  But now namespaced migrations working incorrect and can break DB data.

**Comment by evgen-d** [comment]
We have to abandon the namespaced migration in our project. I advise others to do the same

**Comment by SilverFire** [comment]
Asking for @yiisoft/core-developers opinions on how to implement migration for migration table.

Suggest to check, whether `namespace` column exists, and if it does not - add it.

**Comment by rob006** [comment]
We could solve this with additional query:

1. Query last X migrations.
2. Query all migrations with `apply_time` equals to results from previous query.
3. Sort them internally ignoring namespace and pick first X results.

**Comment by samdark** [comment]
@klimov-paul need your input.

**Comment by klimov-paul** [comment]
> @klimov-paul need your input.

There is no other option, but removing the limit from the query and use `array_slice()` instead after the sort.
It should be safe in general, since migration history unlikely stores too may records and we use array as result set.

Would be better of course if you have waited for 'my input' before merging #12975, but alright.

I am closing this PR as its solution unacceptable at current state.

**Comment by samdark** [comment]
Should #12975 be reverted?

**Comment by klimov-paul** [comment]
It does not matter: it is too late to do `reset --hard`, which I will override the changes during the fix anyway.

**Comment by samdark** [comment]
OK.

**Pull request closed without merging**
