### PR TITLE
Add binary and other data type to typeMap list

### PR DESCRIPTION
**Pull request by SOHELAHMED7**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/yii2/issues/19705

### CODE REVIEW

**Comment by bizley** [comment]
I think we can add it without any BC issues since we aren't changing QueryBuilder::$typeMap for MySQL.

**Review by bizley — APPROVED** [review]

**Comment by SOHELAHMED7** [comment]
Later I found there are also other data types missing. I have edited description of #19705. So this PR also need its corresponding changes before merge.

I will also edit title of this PR.

**Comment by samdark** [comment]
So... what's the plan, @bizley, @SOHELAHMED7?

**Comment by SOHELAHMED7** [comment]
I will add following non-spatial DB data type to this PR and then this PR can be merged

```
set
binary
bool
boolean
dec
fixed
double precision
```

Currently only one `binary`  is added to the list

We will not add spatial Data types

**Comment by SOHELAHMED7** [comment]
This PR can be merged.

**Review by samdark — APPROVED** [review]
Need a line for CHANGELOG.

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
