### PR TITLE
Fix `CallbackDependency`

### PR DESCRIPTION
**Pull request by rob006**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by schmunk42** [comment]
Why is the test green in both cases?

https://github.com/yiisoft/yii2/commit/8861f7bd9daf66cf7db7edaeefc236e71685273e#diff-57a96cab3e08c948305d1fb793933cfea989debf497119b97fd39b477a4706ad

**Comment by schmunk42** [comment]
Sorry, forget it.

Just noticed that only unit tests (build) were failing https://github.com/yiisoft/yii2/actions/runs/8676707548

**Comment by samdark** [comment]
Wow. Any idea when it was broken?

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
Do we need a CHANGELOG for this one?

**Comment by samdark** [comment]
Alright. Thank you!

**Comment by laxity7** [comment]
@samdark this one of the reason because i used `return call_user_func($this->callback)` in original commit in my PR https://github.com/yiisoft/yii2/pull/20137

**Pull request merged**
