### PR TITLE
[IpValidator] disable ipv6 checks

### PR DESCRIPTION
**Pull request by mikk150**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes (at least IpValidatorTest did)
| Fixed issues  | #13976

### CODE REVIEW

**Comment by cebe** [comment]
do you know why the constant did not exist in your environment.

**Comment by mikk150** [comment]
I actually have no idea, but seems it doesn't matter for inet_* methods

**Comment by mikk150** [comment]
Yep, confirmed.
My container environment has IPv6 support disabled..

**Comment by SilverFire** [comment]
Checked, the fix is valid.

Could you add a line to CHANGELOG.md?

**Comment by mikk150** [comment]
@SilverFire Like this?

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
Yepp. Good to merge in 2.0.12. Any objections, team>

**Review by cebe — APPROVED** [review]

**Review by cebe — CHANGES_REQUESTED** [review]
Seems this is relevant if `expandIPv6` is set to true. http://php.net/manual/en/function.inet-pton.php
inet_pton() does not work when PHP is not compiled with IPv6 support.

**Comment by mikk150** [comment]
So we should watch php compile flags every time we need to validate IPv6? because as it turns out "AF_INET6" constant does not work?

**Comment by mikk150** [comment]
Yes, I checked
I compiled PHP7 with --disable-ipv6 option, and
```
$hex = unpack('H*hex', inet_pton('2001:db8::1'));

Warning: inet_pton(): Unrecognized address 2001:db8::1 in php shell code on line 1
```
So AF_INET6 is certanly not the right way

**Comment by SilverFire** [comment]
@cebe good catch!

@mikk150 is it possible to have `AF_INET6` set to true when PHP is compiled with `--disable-ipv6 option`?

**Comment by mikk150** [comment]
Looking into PHP source code, AF_INET6 does not control inet_pton at all, HAVE_INET_PTON and HAVE_IPV6 are the only constants that matter, but these are only compile-time constants, so you cannot read them

**Comment by SilverFire** [comment]
Have not dig too deep in PHP sources, but [2 lines below](https://github.com/php/php-src/blob/master/ext/standard/basic_functions.c#L3949) constant AF_INET6 is used. Not sure, how it will impact on code execution

**Comment by mikk150** [comment]
This
https://github.com/php/php-src/blob/master/ext/standard/basic_functions.c#L3949
Is actually AF_INET6 that is defined in C library, and is not the same as PHP AF_INET6 BUT what is weird is that AF_INET6 should be defined in  https://github.com/php/php-src/blob/master/ext/sockets/sockets.c#L674 BUT I do not see that..

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
Considering that `AF_INET6` constant does not protect from unexpected errors and we have not discovered a better way to check that IPv6 is supported I merge this PR.

**Comment by SilverFire** [comment]
Added check to `requirements.php`
14a245a4135b90b12dd51f4c7f4ce25b1f0b413a

**Comment by mikk150** [comment]
@SilverFire it has nothing to do with it, why did you add it?

**Comment by SilverFire** [comment]
I've added additional commit https://github.com/yiisoft/yii2/commit/620ce9af191d036efe13018f5626487c9875c1c1 with enhanced wording

> Currently PHP constant <code>AF_INET6</code> is not defined and IPv6 is probably unsupported

It says **probably** because we are not sure. And requirement is defined as not mandatory, so it will just warn developer

**Pull request merged**
