### PR TITLE
Fixed the defaultValue bug in BlameableBehavior for console app

### PR DESCRIPTION
**Pull request by evil1**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16584

### CODE REVIEW

**Comment by evil1** [comment]
I've added unit tests.

**Review by samdark — APPROVED** [review]
Need a line for changelog.

**Comment by evil1** [comment]
I thought that pull request's title - "Fixed the defaultValue bug in BlameableBehavior for console app" completely describes all the changes and is suitable as a text for changelog, doest't it?

**Comment by samdark** [comment]
Yes, it does/

**Comment by SamMousa** [comment]
@evil1 I think the test could be simplified a lot.

1. Use an existing AR test class.
2. Add the behavior dynamically.

```php

$record = new Cat();
$record->attachBehavior('blameable', new BlameableBehavior([
    'defaultValue' => 15
]));
$record->beforeSave(true);
$I->assertEquals(..)
```

After writing this I realize you probably just copied the approach from the other test... :+1:

**Comment by evil1** [comment]
@SamMousa Exactly! To save the time I copied the approach from default BlamableBehavior test, and modified it to test the console app.

**Comment by evil1** [comment]
@samdark Hi Alexander. Please advise what should I do to make this Pull Request appear in the nearest milestone?

**Comment by samdark** [comment]
1. Update with changes from master.
2. A line for CHANGELOG.md

**Comment by evil1** [comment]
@samdark Not sure I did everything correct. This is my very first Pull Request.

**Comment by samdark** [comment]
It's all good. Merged. Thank you!

**Pull request merged**
