### PR TITLE
Improve the user input reliability.

### PR DESCRIPTION
**Pull request by thiagotalma**
This confirmation can be used for vital functions, with serious consequences for the database.

I believe that the confirmation should be foolproof.
The user must consciously respond to the confirmation.

For example, the answer `yno` can not be considered as yes.

### CODE REVIEW

**Comment by samdark** [comment]
I'm not sure about it. I've got used to answer `y` and it seems to be common practice among console software.

**Comment by thiagotalma** [comment]
@samdark , In PR is accepting both forms.

`y` - returns true
`yes` - returns true
`n` - returns false
`no` - returns false
`yxxx` - question again
`nxxx` - question again
`yno` - question again

**Comment by samdark** [comment]
Right. Looks good to me then. Please add a line for changelog.

**Comment by thiagotalma** [comment]
Done!

**Comment by samdark** [comment]
Great. Will wait till CI will finish with tests and then merge it. Thanks!

**Comment by qiangxue** [comment]
Instead of doing it recursively, it's better to be done iteratively, because the former is limited by the max nesting level.

**Comment by thiagotalma** [comment]
@qiangxue you are the man!

Done.

**Pull request closed without merging**
