### PR TITLE
Fixes quoting in QueryBuilder::prepareInsertSelectSubQuery()

### PR DESCRIPTION
**Pull request by sergeymakinen**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | —

This PR fixes insufficient quoting in `yii\db\QueryBuilder::prepareInsertSelectSubQuery()`. For example, it makes Oracle feel sad.

### CODE REVIEW

**Comment by dynasource** [comment]
> For example, it makes Oracle feel sad.

can you supply a reference showing that?

**Comment by sergeymakinen** [comment]
> can you supply a reference showing that?

[Sure](http://docs.oracle.com/cd/E11882_01/server.112/e41084/sql_elements008.htm#SQLRF00223):

```sql
sql> INSERT INTO "category" (id, name) VALUES(41, 'test')
[2017-02-17 15:25:40] [42000][904] ORA-00904: "NAME": invalid identifier
sql> INSERT INTO "category" ("id", "name") VALUES(41, 'test')
[2017-02-17 15:25:55] 1 row affected in 44ms
```

It also applies in this case of course.

**Comment by sergeymakinen** [comment]
It’s already covered by existing tests: they were simply broken (there’s no OCI auto testing on Travis). :)

**Review by dynasource — APPROVED** [review]

**Comment by sergeymakinen** [comment]
There’s no need for the ‘pr:request for unit tests’ label by the way.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
