### PR TITLE
Generator i18n

### PR DESCRIPTION
**Pull request by joshuatam**
Better Support for i18n in gii Generator

### CODE REVIEW

**Comment by samdark** [comment]
@joshuatam would you please explain what are you trying to achieve with it?

**Comment by joshuatam** [comment]
Originally, the modelClass parameter will be replaced with a simple string (e.g. Activities) as the model, even i18n is checked in gii:

```php
$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Activities',
]);
```

It is quite troublesome as we have to update that string like the following in many files generated (admin.php, create.php, etc):

```php
$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => Yii::t('app', 'Activities'),
]);
```

Normally, 'Activities' should have its translation, right?

**Comment by samdark** [comment]
Hmm... I think it should generate

```php
$this->title = Yii::t('app', 'Create activities');
```

because in many languages it's hard to get correct translation by translating these two seprately.

**Comment by cebe** [comment]
> because in many languages it's hard to get correct translation by translating these two seprately.

:+1:

**Comment by joshuatam** [comment]
How about:

```php
$this->title = Yii::t('app', 'Create') . ' ' . Yii::t('app', 'Activities');
```

**Comment by cebe** [comment]
@joshuatam even worse, the whole string has to be translated at once. e.g. German translation for `Create Activity` would be `Aktivität erstellen`.

**Comment by joshuatam** [comment]
@cebe In this case, if we can have this format:

```php
$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => Yii::t('app', 'Activities'),
]);
```

and what we get in messages.php for German:

```php
'Create {modelClass}' => '{modelClass} erstellen',
'Activities' => 'Aktivität',
```

and that for English:

```php
'Create {modelClass}' => 'Create {modelClass}',
'Activities' => 'Activities',
```

**Comment by samdark** [comment]
In Russian it's a bit more complicated.

`Create News` is `Создать новость` while `News` could be `Новости` or `Новость` depending on the context so this placeholder is a bad idea, I think.

**Comment by joshuatam** [comment]
@samdark Why? I think the placeholder is still valid in Russian:

```php
$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => Yii::t('app', 'News'),
]);
```

message.php

```php
return [
    'Create {modelClass}' => 'Create {modelClass}',
    'News' => 'Новости', // OR 'Новость' depending on the context
];
```

**Comment by samdark** [comment]
Unfortunately it's not.

**Comment by joshuatam** [comment]
But if there are different contexts, should he change like this?

```php
$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => Yii::t('app', 'News for Context 1'),
]);

'News for Context 1' => 'Новости',
```

**Comment by joshuatam** [comment]
And my pull request is mainly focus on replacing ```VarDumper::export```

**Comment by samdark** [comment]
I mean in this exact case it's only one context and correct string is `Создать новость`. But `News` alone will be most probably translated as `Новости`. First of all, it's plural unlike in the sentence with "Create". Second, it starts with capital `Н` which is incorrect in a sentence.

**Comment by lynicidn** [comment]
best example:
Создать Пользователя => Create User
1 Пользователь => 1 User
Много Пользователей => Many Users
Привязать к Пользователю => Assign to User

**Comment by joshuatam** [comment]
@samdark Sorry that I don't know about Russian Grammar, in my opinion I prefer to keep original placeholder ```{modelClass}```, and make it translatable be default.

In real case, if I use gii to generate hundreds of CRUD, there will have many ```'Create {modelClass}'```` in every create.php, and I can only translate the values of ```modelClass``` and use only **one** translation for ```'Create {modelClass}'````, which is something like ```'Create {modelClass}' => 'Создать {modelClass}'``` in Russian.

**Comment by samdark** [comment]
@joshuatam yes, I understand that for many languages having these unified noun translations is a pro in terms of translation workload but for many it's a blocker i.e. inablity to adequately translate strings at all.

**Pull request closed without merging**
