### PR TITLE
Fixed #17340

### LINKED ISSUE #17340: Problem to inherit yii\db\Query
The problem is that when you want to inherit after yii\db\Query class I have to also overwrite some functions that refer to new self().
Changing self to static should eliminate possible errors that might appear in such cases and it will maintain object consistency. 
### What steps will reproduce the problem?
https://github.com/yiisoft/yii2/blob/869c8aa22059f3aaa1dbdce0b74b849f0d7cb189/framework/db/Query.php#L466-L469
### What is the expected result?
image

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.3
| PHP version      | 7.3.x
| Operating system |

### PR DESCRIPTION
**Pull request by rskrzypczak**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #17340

### CODE REVIEW

**Comment by samdark** [comment]
Seems the change breaks things: https://travis-ci.org/yiisoft/yii2/jobs/542600371

**Comment by samdark** [comment]
@rskrzypczak are you going to work on it further?

**Comment by rob006** [comment]
This is not that simple: https://github.com/yiisoft/yii2/pull/14729, https://github.com/yiisoft/yii2/pull/16993.

It could be fixed by introducing another protected method for creating instance used by these two methods, so descendants could override it. Changing this to `static` directly in `Query` would break BC.

**Comment by samdark** [comment]
Yes. Seems it can't be applied in this form. Closing.

**Pull request closed without merging**
