### PR TITLE
fixes composite key multi join

### PR DESCRIPTION
**Pull request by joe-meyer**
Fixes issue #9047

### CODE REVIEW

**Comment by samdark** [comment]
Would be cool to get a unit test. It's not trivial thing so it's easy to break.

**Comment by joe-meyer** [comment]
If you guys don't take care of this I'll try and look at building a unit test for it. Really something to make sure of is that we test both single condition relations as well as composite relations. I ihaven't done anything to attempt to correct relations with single conditions in the joins but I fear they may also be subject to this same bug.

**Comment by samdark** [comment]
Yeah, that would be great.

**Comment by nineinchnick** [comment]
@joe-meyer what db are you using? I've set up some composite fks for unit tests for pgsql.

**Comment by joe-meyer** [comment]
@nineinchnick I'm using a custom odbc database driver for a [Progress](http://www.progress.com) database, but it's 99% the same as sqllite. 

If you take a look back at the original issue I feel like I outlined when the problem occurs fairly well (a `hasMany()` with an `innerJoinWith` as a part of the relation)

**Comment by nineinchnick** [comment]
I understand the problem, I just wanted to point out it should be easy to add an unit test for that because there are fixtures ready.

**Comment by PowerGamer1** [comment]
This fixes the problem I am currently having (need to perform order by the field in inner joined table inside active relation), can this be merged into `master` branch ASAP please?

**Comment by cebe** [comment]
@PowerGamer1 if you provide a unit test I can merge it immediately. otherwise I would have to write one myself ;)

**Comment by PowerGamer1** [comment]
> if you provide a unit test I can merge it immediately. otherwise I would have to write one myself ;)

I don't know how you do the unit testing but if you need an example here is a simple one. Lets say there are tables in the database: `user (id, name, ...)`, `project (id, ...)` and `project_participant (project_id, user_id, ...)`. One project can have many participants.

```PHP
class Project extends \yii\db\ActiveRecord
{
  public function getParticipants()
  {
    return $this->hasMany(ProjectParticipant::className(), ['user_id' => 'id'])->innerJoinWith('user')->orderBy(['user.name' => SORT_ASC])->indexBy('user_id');
  }
}

$project->findOne(123);
var_dump($project->participants);
```

Relation `Proejct::getParticipants()` returns no records without the fix in this pull request.

**Comment by cebe** [comment]
> $this->hasMany(ProjectParticipant::className(), ['user_id' => 'id'])

This does not make sense to me. Why is a ProjectParticipant joined with Project on the user_id?

**Comment by cebe** [comment]
Also I am not really able to reproduce the issue so it would be great if someone could create a test case or at least some info on how to reproduce it with AR classes defined in unit test directory of the framework. https://github.com/yiisoft/yii2/issues/9047#issuecomment-213431506

**Comment by PowerGamer1** [comment]
> $this->hasMany(ProjectParticipant::className(), ['user_id' => 'id'])
This does not make sense to me. Why is a ProjectParticipant joined with Project on the user_id?

Just a typo, should be `['project_id' => 'id']`.

**Comment by cebe** [comment]
@PowerGamer1 the case with no composite key involved does not fail for me.

**Pull request closed without merging**
