### PR TITLE
fix name alias [skip ci]

### PR DESCRIPTION
**Pull request by pana1990**
@SilverFire @cebe @samdark  in messageController missing "removeUnused"  and "messageTable" alias, suggestion for this methods?

### CODE REVIEW

**Comment by samdark** [comment]
`-t` for table, `-r` for remove unused?

**Comment by pana1990** [comment]
```-r``` it's okey but ```-t``` is not available (it is using to "translator"), maybe -T?

**Comment by samdark** [comment]
Since `messageTable` isn't used often, it's OK to leave it w/o alias.

**Comment by pana1990** [comment]
:+1:

**Comment by pana1990** [comment]
@samdark done!

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/1989494faa046f89917a6fb2e02516c781b03541 Thanks!

**Pull request closed without merging**
