### PR TITLE
enable one-line $model update

### PR DESCRIPTION
**Pull request by dynasource**
fix for #7331 and enable shorter code

### CODE REVIEW

**Comment by samdark** [comment]
Wasn't it decided not to implement it?

**Comment by cebe** [comment]
yes

**Comment by dynasource** [comment]
have you read my post https://github.com/yiisoft/yii2/issues/7331#issuecomment-127970269

**Comment by dynasource** [comment]
I cannot think of a good reason why the framework should not provide a way of setting & saving a model in 1 line.

* its useful
* its something many people want to use (and finally come to the conclusion its not supported)
* this solution does not affect performance (no magic and not using __call)
* arguments about similar proposals (https://github.com/yiisoft/yii2/issues/7331#issuecomment-74869942) is not an argument

**Pull request closed without merging**
