### PR TITLE
Revoke should be type $item instead of $role

### PR DESCRIPTION
**Pull request by oceanapplications**
Item is the parent of role and permission. Revoke can be used for both.

### CODE REVIEW

**Comment by samdark** [comment]
While it's technically possible to assign user any item, logically it should always be role. Do you have any cases when it makes sense to assign permissions directly?

**Comment by thebluemeanie2** [comment]
In a situation where a role would only have one permission it seems unnecessary to create a role out of one permission and then assign the role instead of simply assigning the permission.

**Comment by samdark** [comment]
Until we add another permission. In this case you have to re-assign all users to newly created role or assign additional permission to all users.

**Comment by lynicidn** [comment]
good style assign only role to user. All permissions should be assigned to role.
russian: https://ru.wikipedia.org/wiki/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BE%D0%BC_%D0%BD%D0%B0_%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5_%D1%80%D0%BE%D0%BB%D0%B5%D0%B9

```
Управление доступом на основе ролей (англ. Role Based Access Control, RBAC) — развитие политики избирательного управления доступом, при этом права доступа субъектов системы на объекты группируются с учётом специфики их применения, образуя роли.[1][2]
```

**Comment by samdark** [comment]
So overall while the hint is technically OK to be Item, I'd leave it as is for the sake of promoting best practice of always assgning a role to user and never doing so with permission.

**Comment by samdark** [comment]
Thanks for the effort anyway.

**Pull request closed without merging**
