### PR TITLE
fixes #12905: expanded using get alias

### LINKED ISSUE #12905: unnecessary cache misses
advanced yii project (multiple apps with different routes) uses same key that is hardcoded into `yii\\web\\UrlManager`

```
    protected $cacheKey = __CLASS__;
```

this would case hash to always be a miss, each hit will do both `get` and `set`

```
        if ($this->cache instanceof Cache) {
            $cacheKey = $this->cacheKey;
            $hash = md5(json_encode($this->rules));
            if (($data = $this->cache->get($cacheKey)) !== false && isset($data[1]) && $data[1] === $hash) {
                $this->rules = $data[0];
            } else {
```

the solution is to suffix `cacheKey` with  let's say basepath or app name ...etc.

### PR DESCRIPTION
**Pull request by muayyad-alsadi**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12905

### CODE REVIEW

**Comment by dynasource** [comment]
why a new PR?

**Comment by muayyad-alsadi** [comment]
it's a different approach, which uses a method suggested by @kidol

**Comment by muayyad-alsadi** [comment]
I have php 5.6. It seems this approach did not work with php < 5.5.

**Comment by muayyad-alsadi** [comment]
to implement this in a php 5.4, we need to create a protected property and a getter and a setter.

**Comment by dynasource** [comment]
because of the string concationation, right. 

But looking at your commit, it could also be solved by using:
'public $cacheKey = '@app/yii\web\UrlManager ';

**Comment by muayyad-alsadi** [comment]
@dynasource yes, by making it literal

**Review by samdark — CHANGES_REQUESTED** [review]
Looks good to me. Need unit tests covering it.

**Review by cebe — CHANGES_REQUESTED** [review]
See https://github.com/yiisoft/yii2/issues/12905#issuecomment-259814617

**Comment by cebe** [comment]
closing as this is not the solution to the problem. see https://github.com/yiisoft/yii2/issues/12905#issuecomment-260491558 for more details.

**Pull request closed without merging**
