### PR TITLE
[WIP] Introduced \yii\di\ConfiguratorInterface

### PR DESCRIPTION
**Pull request by creocoder**
There is many 3rd party libraries and currently there is no option around integration it to Yii 2 instead of using Proxy pattern which is **very** slow and magic.

This new interface solve all those troubles. Use case:

``` php
class ThirdPartyLibConfigurator extends Object implements ConfiguratorInterface
{
    public $foo;
    public $bar;

    public function build() {
        $this->bar = Yii::getAlias($this->bar);

        // other complex logic to proof configurator needs its own instance
        // ...

        return new ThirdPartyLib($this->foo, $this->bar);
    }
}
```

### CODE REVIEW

**Comment by lynicidn** [comment]
:+1: good idea

**Comment by samdark** [comment]
I like the idea. Currently the only way to configure non-Yii object is to do it in anonymous function which isn't really user friendly.

`ConfiguratorInterface` will allow to hide configuration algorithm while surfacing config.

**Comment by samdark** [comment]
@lynicidn 

```php
'components' => [
    'facebook' => [
        'class' => '\app\configurators\Facebook',
        'secret' => 'x',
        // ...
    ]
],
```

```php
class Facebook implements \yii\di\ConfiguratorInterface
{
   public $secret;

    public function build()
    {
        return Facebook::create($this->secret);
    }
}
```

**Comment by lynicidn** [comment]
выглядит нормально, а что если у меня динамическая конфигурация, т.е. не при создании конфигуратора надо инициализироваться (build) компонент, а после каких либо операций, или и планируется метод ::build() вызывать вручную?

**Comment by lynicidn** [comment]
к примеру так
$config = new my\Config();
$config->param = 'val';
$config->other = 'param';
$config->build();

**Comment by creocoder** [comment]
@lynicidn Это компонент для интеграции сторонних сервисов в первую очередь. Метод `build()` вызывается автоматически.

**Comment by lynicidn** [comment]
@creocoder а в чем тогда преимущество перед передачей параметров конструктор? разве что конфигурация в стиле уии, динамическую можно было бы запилить я думаю

**Comment by creocoder** [comment]
@lynicidn О преимуществе чего перед чем речь? Это абсолютно новая возможность, которая позволяет использовать любые сторонние объекты в качестве сервисов, с возможностью конфигурации этих сервисов **аналогично** любым нативным Yii компонентам.

**Comment by lynicidn** [comment]
@creocoder понял, спасибо, меня больше интересовало немного не то, не сервисы, а .... модели :) раз к модулю их привязать нельзя, думал может конфигуратор как то позволит решить эту проблему )
п.с. по теме, но думаю видел - http://symfony.com/doc/current/components/dependency_injection/configurators.html
а хотелось чтото типа как тут, чтобы в инит передавался конфиг, вместо сейчашнего в конструктор [массив]
http://symfony.com/doc/current/cookbook/bundles/extension.html

**Comment by samdark** [comment]
@yiisoft/core-developers thoughts?

**Comment by qiangxue** [comment]
The idea is interesting. My main concern is that you are configuring a component as a configurator class while you actually get an object of a different class, which is unexpected.

An alternative solution I'm thinking about is to introduce an `Configurable` interface:

```php
interface Configurable {
    function configure(array $config);
}
```

The DI container when seeing an object implementing this interface, will call its `configure()` method.

For the Facebook example, you can then subclass the existing Facebook class and implement this interface.

**Comment by samdark** [comment]
@qiangxue won't work. See the following example from [FlySystem](http://flysystem.thephpleague.com/adapter/aws-s3-v3/):

```php
use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;

$client = S3Client::factory([
    'key'    => 'your-key',
    'secret' => 'your-secret',
    'region' => 'your-region',
    'version' => 'latest|version',
]);

$adapter = new AwsS3Adapter($client, 'your-bucket-name', 'optional-prefix');
```

Adapter requires an instance of SDK class and the SDK class is created with a factory method. Ideally the config for Yii should be the following:

```php
'components' => [
    'awss3' => [
        'class' => 'app\configurators\AwsS3',
        'key'    => 'your-key',
        'secret' => 'your-secret',
        'region' => 'your-region',
        'version' => 'latest|version',
        'bucketName' => 'bucketName',
        'prefix' => 'prefix',
    ],
]
```

**Comment by creocoder** [comment]
@qiangxue 

> An alternative solution I'm thinking about is to introduce an Configurable interface

> For the Facebook example, you can then subclass the existing Facebook class and implement this interface.

We can do that now by subclassing Facebook and override it constructor by adding `$config` as last param. Main problem that it will not solve original issue. Third party library may be declared as `final`, it may have very complex factory procedure when several classes should be configured, etc. This is why we need separate "builder/factory" for that. In other frameworks, for example Laravel or Silex there is "service providers" concept. We need some analog. Because without that integrating third party to Yii can be done only by using "proxies" with `__call()` inside.

**Comment by qiangxue** [comment]
@samdark Why can't you do this?

```php
class MyAws3 extends AwsS3Adapter implements Configurable {
    public function __construct($config = []) {
        $client = S3Client::factory([...]);
        parent::__construct($client, ...);
    }
}
```

@creocoder It's very uncommon to see a class to be declared as `final`. And even if it is so, you can still use this to solve the problem: http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#php-callable-injection

I also don't think what you are proposing here is the service provider in Laravel/Silex. The similar feature is already supported via `Application::bootstrap`.

**Comment by samdark** [comment]
@qiangxue what if the class itself is created via static factory as well?

**Comment by qiangxue** [comment]
@samdark Use this method then: http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#php-callable-injection
By doing so, you also save the effort of creating a new class. This method is exactly designed to handle the case when an object needs to be built in a complicated way.

**Comment by creocoder** [comment]
> Use this method then: http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#php-callable-injection

Integrating third party libraries to fw should not affect end users experience. End user should have possibility to configure it like usual component.

I see no other option instead of creating Proxie when integrating third party libraries to Yii.

I do not say it should be done via mechanist i suggested inside that PR. But its clean that Yii need such mechanism. Because currently writing extensions for it is pain (due to proxy pattern nature).

> I also don't think what you are proposing here is the service provider in Laravel/Silex.

Maybe, but this is used for integrating third party libraries to framework. And it maden much more elegant than force users to use callables inside config.

For now i still see no other options instead of use proxies to original libraries. Callable inside config is horrlble, Proxy is horrible (but it at least solve trouble). So solution is needed anyway.

**Comment by creocoder** [comment]
@qiangxue The goal of this PR is to make `Yii::$app->service` return any third party class. And this service should be configured as usual component. If you have another ideas how to reach that it would be great. But callables inside config, etc is just unacceptable. Service Providers inside Laravel/Silex probably is different from that fix, but at least they solve trouble complettely.

**Comment by creocoder** [comment]
@qiangxue Maybe its good idea to introduce new application config section:

```php
'components' => [
    ...
],
'services' => [
    ...
],
```

Components section is for Yii 2 core components and third party components which maden by follow Yii ideology (e.g. extends Object).

Services is for Service Provider, we can develop syntax for it, interface, approach.

**Comment by creocoder** [comment]
I understand that this is not DI issue and PR looks like hack around DI. Probably trouble is on Service Locator side. Anyway it does not mean that trouble is not exists.

**Comment by samdark** [comment]
I agree with @creocoder that in case of extension development such solution is definitely better than anonymous function (too much internals exposed), inheritance (often impossible because of factories), proxies (_call ones are slow, real ones are repetitive) etc.

It would allow very slim configurator extensions except of full featured wrappers.

**Comment by samdark** [comment]
As for implementation proposed, I'm not sure about it. I like idea overall.

**Comment by lynicidn** [comment]
swift mailer it service ? :)

**Comment by creocoder** [comment]
@lynicidn If you about `yii2-swiftmailer`, it maden by using Facade pattern and it change original library api and cause users learn second api for well known library which is not good, but this is topic for another conversation. This PR is about elegant way to integrate third party libraries without changing its api and without using proxy pattern for it.

**Comment by klimov-paul** [comment]
Once, we already had a disscussion on this matter, but from the opposite point of view at #1837

I don't think 3rd party class object can be forced to match Yii 'component' convension. Still I have done similar thing for swiftmailer:
https://github.com/yiisoft/yii2/blob/master/extensions/swiftmailer/Mailer.php#L187
https://github.com/yiisoft/yii2/blob/master/extensions/swiftmailer/Mailer.php#L45

I suppose we already done, what we can at DI.

**Comment by creocoder** [comment]
@klimov-paul As i said trouble is not on DI level. It on Service Locator features level. Currently we can integrate 3rd party to framework using Facade/Proxy/Adapter pattern. But look how this question solved in Silex/Laravel other fw which use Service Provider approach. Its much more easier than our way and result work much more faster than our way. All we need it to enhance service locator way when it can use some Factory/Builder which will return prepared third party library and Yii::$app->service will return third party library itself.

**Comment by creocoder** [comment]
> I don't think 3rd party class object can be forced to match Yii 'component' convension.

I agree with you, this is why extending third party is very bad idea and its hard to imagine how to break SOLID more easily than that. This is why i suggested:

```
'components' => [
    'class' => 'ServiceFactory',
    'param1' => 'foo',
    'param2' => 'bar',
],
```

This `ServiceFactory` will just prepare needed Third Party Library classes (it can be 1 class, it can be 100 classes) and just return it back to Service Locator. This is main idea. What we need to fix for that we need to think. I agree that fixing DI was bad idea. This was just prototype to show that problem is exists and just to start thinking about solution for it.

**Comment by creocoder** [comment]
@klimov-paul Note, that `ServiceFactory` is class written by library integrator, its **not part** of original library.

**Comment by klimov-paul** [comment]
If you still need to write a special 'integrator' class to use 3rd party library - what is the point of this?
It whould be better to create more solid and specific facade or adapter for the library.

**Comment by creocoder** [comment]
> It whould be better to create more solid and specific facade or adapter for the library.

Why you need facade or adapter which change library api if original library api is fine for example? Special `integrator` class is usually up to 10 LOC maximum and this is just simple factory which prepare original library for work. This way it works in every fw i checked for similar feature. Laravel have Service Providers, Silex have Service Providers. Zend have Service Providers. Symfony have Service Providers. We do not have anything instead of hardcore way of integrating. Writing facade make sence only if original library api is complex and you plan to close it complexity. Its very rare when it make sence.

**Comment by klimov-paul** [comment]
My opinion a 3rd party libray has its own design and approach for its object instantiation.
It may provide its own singleton or factory solution, which is supposed to be universal, or least - sufficient, for integration with any other system.

**Comment by creocoder** [comment]
> which is supposed to be universal, or least - sufficient, for integration with any other system

Right, with any system except Yii 2. Please check how 3rd party integrated usually to another frameworks. Thanks.

**Comment by samdark** [comment]
@klimov-paul we can't really expect Yii2-compatible way of doing things from any library out there. It's better to support any.

**Comment by klimov-paul** [comment]
Back at #1837 I have already proposed to modify object creation method, now it is `Container::build()` in the way it can be used not only for `yii\base\Object` but for any abstract class.
We can still do this.
At yii2-switmailer I have already implemented such approach, which allows configuration and creation of the transport of any complexity.
As for intriduction of the special interface for the 3rd library creation - we can do this, but still at the moment DI callback is covered that already just in other way.
In any way, it is better I don't argue about this, I am leaving this matter in your capable hands.

**Comment by samdark** [comment]
Yes, it's the same thing as DI callback but hidden from end user. That's the only difference. The reason to introduce it is to reduce config complexity that is visible to end user.

**Comment by klimov-paul** [comment]
There 2 main enhancements to `Container::build()`, which can make it being able to instantiate almost anything:
- allow specification of `__construct` args via configuration array key, like `constructArgs` or even `__construct`
- check for properties and setters existence, while configuring the created object.
Most libraries provides options as public fields or via setter methods, but not all of them introduce `__set()` method at least in the Yii way.
To save performance we can check if object is an instance of `yii\base\Object` or not before falling in `property_exists()` checks.

Then there will no trouble integrating 3rd party class with "simple API".

**Comment by klimov-paul** [comment]
For example: in order to use Guzzle client as a component all I will need is following config:
```php
components => [
    'mySiteHttpClient' => [
        'class' => '\Guzzle\Http\Client',
        '__construct' => ['http://mysite.com'], // will set base URL via constructor
    ],
],
```
And that is all. And there is no need for extra interfaces or extra 'service integration' classes.

**Comment by lynicidn** [comment]
@klimov-paul :+1:

**Comment by klimov-paul** [comment]
Yet another possible solution could introduction of the special key in the configuration array for a `Closure`, which should return actual instance of the component, so such config may look like:
```php
'components' => [
    'mySiteHttpClient' => [
        '__construct' => function() { return new \Guzzle\Http\Client('http://mysite.com');}
    ],
],
```
Such feature definetely covers any need without extra interfaces or classes.

**Comment by creocoder** [comment]
@klimov-paul

> And there is no need for extra interfaces or extra 'service integration' classes.

If only you want to make users run away from integration with such quality. Never saw more horrible end user config to be honest.

> Yet another possible solution could introduction of the special key in the configuration array for a Closure

Great, now realize that service configuration stored inside yml or database...

Its absoluttely unacceptable to force users to config components like that:

```
components => [
    'mySiteHttpClient' => [
        'class' => '\Guzzle\Http\Client',
        '__construct' => ['http://mysite.com'], // will set base URL via constructor
    ],
],
```

Also what if library have something like `Service::create()` or require 2 classes to be instantiated and passed to constructor. It absoluttely horrible to involve user to all this DI mess. Configs should be understandable and its quality should be same as for Yii core components.

**Comment by creocoder** [comment]
@klimov-paul Why you try to defent out poor (by features) Service Locator instead of suggest real solution?

**Comment by lynicidn** [comment]
@creocoder поэтому я и спрашивал про динамическую конфигурацию, чтобы можно было легко менять способ откуда брать конфиги, аля адаптеров

**Comment by creocoder** [comment]
Feature implementation was changed. DI container untouched. Please check new implementation. I think its good balance.

**Comment by creocoder** [comment]
As alternative to last implementation we can move it to \yii\di\ServiceLocator itself, so such "configurators" will be pure service locator feature.

**Comment by creocoder** [comment]
Implemented as `ServiceLocator` feature.

**Comment by qiangxue** [comment]
I still think this implementation is unnecessary, and the desired feature can be readily done with the current implementation already.

```php
class FacebookSDK {
    public static function service(...) {
        return function () {
        };
    }
}

// app config
return [
    'components' => [
         'facebook' => FacebookSDK::service(...),
    ],
];
```

@creocoder Please give more concrete examples that we can learn about from other frameworks.

**Comment by samdark** [comment]
http://flysystem.thephpleague.com/adapter/gridfs/

```php
use Aws\S3\S3Client;
use League\Flysystem\GridFS\GridFSAdapter;
use League\Flysystem\Filesystem;

$mongoClient = new MongoClient();
$gridFs = $mongoClient->selectDB('db_name')->getGridFS();

$adapter = new GridFSAdapter($gridFs);
$filesystem = new Filesystem($adapter);
```

**Comment by samdark** [comment]
http://flysystem.thephpleague.com/adapter/rackspace/

```php
use OpenCloud\OpenStack;
use OpenCloud\Rackspace;
use League\Flysystem\Filesystem;
use League\Flysystem\Rackspace\RackspaceAdapter;

$client = new OpenStack(Rackspace::UK_IDENTITY_ENDPOINT, array(
    'username' => ':username',
    'password' => ':password',
));

$store = $client->objectStoreService('cloudFiles', 'LON');
$container = $store->getContainer('flysystem');

$filesystem = new Filesystem(new RackspaceAdapter($container));
```

**Comment by samdark** [comment]
http://flysystem.thephpleague.com/adapter/phpcr/

```php
use League\Flysystem\Filesystem;
use League\Flysystem\Phpcr\PhpcrAdapter;
use Jackalope\RepositoryFactoryDoctrineDBAL;
use Doctrine\DBAL\Driver\Connection;
use Doctrine\DBAL\DriverManager;

$connection = DriverManager::getConnection(array(
    'driver' => 'pdo_sqlite',
    'path'   => '/path/to/sqlite.db',
));
$factory = new RepositoryFactoryDoctrineDBAL();
$repository = $factory->getRepository(array(
    'jackalope.doctrine_dbal_connection' => $connection,
));
$session = $repository->login(new SimpleCredentials('', ''));

// this part looks the same regardless of your phpcr implementation.
$root = '/flysystem_tests';
$filesystem = new Filesystem(new PhpcrAdapter($session, $root));
```

**Comment by samdark** [comment]
@qiangxue won't it run during config init instead of when requested?

**Comment by qiangxue** [comment]
Nope, the `service` method returns an anonymous function which doesn't instantiate the desired object until you access it the first time.

**Comment by lynicidn** [comment]
@qiangxue it will be work multiple, with 2 facebook service as example ?

**Comment by qiangxue** [comment]
@lynicidn Yes, if you are using `yii\di\Container::set()`.

**Comment by samdark** [comment]
@qiangxue ah, that's nice idea :)

**Comment by samdark** [comment]
But how to provide config for it right in components?

**Comment by qiangxue** [comment]
Pass them as parameters to the `service()` method.

**Comment by samdark** [comment]
```php
class FacebookSDK {
    public static function service($config) {
        return function() use $config {
             // build the object here
             return $object;
        };
    }
}

// app config
return [
    'components' => [
         'facebook' => FacebookSDK::service([
             'secret' => 'x',
             'version' => 2
         ]),
    ],
];
```

Yeah, looks OK.

**Comment by samdark** [comment]
Let's add such example to docs.

**Comment by creocoder** [comment]
@qiangxue There is only one drawback... Another formats instead of php will not be possible with such approach. But in general it solve original issue.

**Comment by creocoder** [comment]
@samdark Lets extract conclusions than to separate issue and close this one. As i understand all we need is propagate such use case inside Guide and that all.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/6e3bf09e35ed80f5e5ae237bb3b7cb130d29da22

**Pull request closed without merging**
