### PR TITLE
#9425: ActiveQuery::exists() should generate SELECT EXISTS()

### PR DESCRIPTION
**Pull request by PowerGamer1**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | 9425 |

Implementation of https://github.com/yiisoft/yii2/issues/9425.

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by klimov-paul** [comment]
Do all DBMS support `exist` ?

**Comment by PowerGamer1** [comment]
@klimov-paul 
> Do all DBMS support `exist` ?

Well, DBMSes used in Yii2 unit tests do support it (since the tests passed). Also, this feature is a part of SQL99 standard (and not some DBMS-specific extension).

**Comment by samdark** [comment]
@klimov-paul yes.

**Comment by klimov-paul** [comment]
> Well, DBMSes used in Yii2 unit tests do support it (since the tests passed). 

That is not true: there is NO unit test, which actually runs `Query::exists()` method. Especially against all DBMS. Also Oracle and MSSQL are not run at Travis.

**Comment by samdark** [comment]
SQLite, MSSQL, MySQL, Oracle, Cubrid, PostgreSQL all support the syntax.

**Comment by klimov-paul** [comment]
OK, fine then.

**Comment by PowerGamer1** [comment]
@klimov-paul 
> That is not true: there is NO unit test, which actually runs `Query::exists()` method.

`Query::exists()` runs as part of `UniqueValidator` unit tests.

Also, apparently Cubrid, MSSQL and Oracle do not support SQL92 standard form of `SELECT EXISTS()` but they do support their own nearly identical forms of it. Implemented them in https://github.com/yiisoft/yii2/issues/11369.

**Comment by samdark** [comment]
@PowerGamer1 are you sure about that?

**Comment by samdark** [comment]
Seems I was wrong about the support. Merged.

**Comment by cebe** [comment]
there is not a single test for this method, creating a test fails it... :-/
https://github.com/yiisoft/yii2-framework/commit/894b34876faccc0fbe4d58452bb56fec30002159#commitcomment-17280165

**Comment by cebe** [comment]
fixed by  		4411a74

**Pull request merged**
