### PR TITLE
Update start-gii.md

### PR DESCRIPTION
**Pull request by granttrudel**
Ran through the guide and found out that gii does not create views/country/index.php: you must create it yourself (if it does not exist) or else replace the code that is in there.

### CODE REVIEW

**Comment by cebe** [comment]
can you give more details about the issue? CRUD should have created index.php. if it did not there is something wrong in a different place, not in this guide section.

**Comment by granttrudel** [comment]
THe issue is that CRUD did create index.php, but it (along with all the other modules) is created in the app/view/country directory rather than views/country directory. If you type in the following URL in your browser, it is looking in the views/country directory for the index.php file: 
http://hostname/index.php?r=country/index

**Comment by cebe** [comment]
There must be an error in some other place or you made a mistake while creating it the first time. The view file should be in the same place in all situations.

**Comment by granttrudel** [comment]
I followed all the instructions as per the guide, to the letter. All the files are created as per the documentation in the app/view/country directory. You can try this yourself. The issue may be that the URL to try out the generated index page needs to be altered?

**Comment by samdark** [comment]
I think it's duplicate of https://github.com/yiisoft/yii2/pull/7121 i.e. screenshot is missing `@`.

**Comment by cebe** [comment]
yep :+1:

**Pull request closed without merging**
