### PR TITLE
refactored migrate command to handle multiple migrations paths

### LINKED ISSUE #384: improve migrate command
* running migrations from different locations (modules)

more or less like this one from @cebe https://github.com/yiiext/migrate-command

### PR DESCRIPTION
**Pull request by schmunk42**
added migrationLookup property
fixes #384

### CODE REVIEW

**Comment by jacmoe** [comment]
I really want this to be in Yii 2 - I do understand that this would break existing migration dbs, but I see no reason why it can't be implemented for fresh migrations?
This extension is one I always install - it enables me to take back control of migrations, whether or not they be mine or from third-party Yii extensions.
Excellent work @schmunk42 :+1:

**Comment by schmunk42** [comment]
:bow: @jacmoe :)

**Comment by cebe** [comment]
@jacmoe the issue #384 is still open. One day I will take the time to include it in the framework.

**Comment by jacmoe** [comment]
Music in my ears @cebe :+1:

**Comment by schmunk42** [comment]
@cebe Here's a PR https://github.com/dmstr/yii2-migrate-command/pull/9 which is based more on the current Yii 2.0 code. From my side, feel free to move the stuff to the core or contact me if you like...

**Pull request closed without merging**
