### PR TITLE
Added EVENT_INIT to widget

### PR DESCRIPTION
**Pull request by user57376**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | yes |
| Breaks BC? | no |
| Tests pass? | yes |
#12000

### CODE REVIEW

**Comment by unclead** [comment]
i think it is similar with what was discussed in scope of #8133

**Review by SilverFire — APPROVED** [review]
Changelog line should be moved to the active milestone before merge

**Comment by SilverFire** [comment]
Sorry, the PR seems to be overseen.
Waiting for more reviews to mergse

**Review by samdark — APPROVED** [review]
CHANGELOG should be modified so the line is in current release. Otherwise looks OK to me.

**Comment by dynasource** [comment]
this is a useful addon. This would fix part 1 of https://github.com/yiisoft/yii2/issues/7435. Shouldnt we add another trigger after the run to fix part 2?

**Comment by cebe** [comment]
> Shouldnt we add another trigger after the run to fix part 2?

yes, as far as I remember the main reason why this has not been merged is that it is incomplete. If we add INIT event, we should maybe also add others.

**Comment by dynasource** [comment]
> yes, as far as I remember the main reason why this has not been merged is that it is incomplete. If we add INIT event, we should maybe also add others.

so what action is there to take

**Comment by cebe** [comment]
look at how widget could be extended and decide which events to add.

**Comment by samdark** [comment]
Can't we start with just init?

**Comment by dynasource** [comment]
> Can't we start with just init?

IMO, we can, just as we can start with a closing trigger to fix https://github.com/yiisoft/yii2/issues/7435 which is a good example of a usecase. Having a starting & ending trigger enables wrapping by Events and extends the frameworks flexibility significantly.

**Comment by samdark** [comment]
Closed as incomplete. Will work on solution with two events.

**Comment by cebe** [comment]
See https://github.com/yiisoft/yii2/pull/13457#issuecomment-275772363

**Comment by samdark** [comment]
Right. https://github.com/yiisoft/yii2/commit/7c1693479fbc8441d1565958942aeb7490872cb6

Merged. Thanks!

**Pull request closed without merging**
