### PR TITLE
fix #11473 trailing backslash in class

### LINKED ISSUE #11473: UniqueValidator seems to be unhappy with ::class syntax
Failing test on 2.1.x branch:

yiiunit\framework\validators\UniqueValidatorTest::testValidateScopeNamespaceTargetClass:

https://travis-ci.org/yiisoft/yii2/jobs/126971192#L281

### PR DESCRIPTION
**Pull request by Faryshta**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues | #11473 |

### CODE REVIEW

**Comment by Faryshta** [comment]
no idea why QueryBuilder test failed and if it have anything to do with my commit

**Comment by cebe** [comment]
Btw, here is the diff that fails it:

```diff
diff --git a/framework/validators/UniqueValidator.php b/framework/validators/UniqueValidator.php
index b0f415e..545496a 100644
--- a/framework/validators/UniqueValidator.php
+++ b/framework/validators/UniqueValidator.php
@@ -106,7 +110,7 @@ class UniqueValidator extends Validator
             $query->andWhere($this->filter);
         }
 
-        if (!$model instanceof ActiveRecordInterface || $model->getIsNewRecord() || $model->className() !== $targetClass::className()) {
+        if (!$model instanceof ActiveRecordInterface || $model->getIsNewRecord() || get_class($model) !== $targetClass) {
             // if current $model isn't in the database yet then it's OK just to call exists()
             // also there's no need to run check based on primary keys, when $targetClass is not the same as $model's class
             $exists = $query->exists();
```

**Comment by cebe** [comment]
> no idea why QueryBuilder test failed and if it have anything to do with my commit

I'm afraid that was me in another commit.

**Comment by cebe** [comment]
Merged, thank you!

**Pull request merged**
