### PR TITLE
Fixed ArrayHelper::get() for ArrayAccess objects with explicitly defined properties

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ?
| Tests pass?   | ?
| Fixed issues  | -

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
@bizley would you please take care of moving test somewhere better, and adding changelog?

**Comment by bizley** [comment]
Sure

**Comment by bizley** [comment]
Done

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
