### PR TITLE
Update helpers in helper-overview.md [skip ci]

### PR DESCRIPTION
**Pull request by pana1990**
Image and Security helper not exists.

### CODE REVIEW

**Comment by samdark** [comment]
Yes. Better to mention that it's available as extension but leave it.

**Comment by pana1990** [comment]
Of course ;)

**Comment by samdark** [comment]
@pana1990 can you fix it in a pull request?

**Comment by pana1990** [comment]
@samdark done!

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
