### PR TITLE
[WIP] composer.json autoload section fix

### PR DESCRIPTION
**Pull request by creocoder**
This will allow load Yii class by composer and avoid explicit require inside entry scripts.

### CODE REVIEW

**Comment by creocoder** [comment]
Rethink my mind :) Caused side effects when custom Application class used.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/pull/6908#issuecomment-70387617 ;)

**Comment by davidsonalencar** [comment]
Very good!

**Comment by cebe** [comment]
> Very good!

?

**Pull request closed without merging**
