### PR TITLE
updated images gii

### PR DESCRIPTION
**Pull request by githubjeka**
Screen of Gii Doc is out of date.

### CODE REVIEW

**Review by cebe — APPROVED** [review]

**Review by dynasource — APPROVED** [review]

**Comment by samdark** [comment]
Template paths are partially missing which isn't good.

In start-gii-crud.png there's a tooltip leftover.

start-gii-model-preview.png was displaying "diff" thing which was good for showing off features. Also there's something in the model class field (right side of the field).

**Review by samdark — CHANGES_REQUESTED** [review]
Would be good to have full paths and no tip leftovers.

**Comment by SilverFire** [comment]
@githubjeka would you like to apply changes suggested by @samdark, or you have objections?

**Comment by githubjeka** [comment]
It's hard work to do screenshots. Tommorow to get involved in my work I will create new screenshots before.

**Comment by cebe** [comment]
for better review: it would be great to only replace the english images and we copy them ourselfs because github does not display all images in the diff.

**Pull request closed without merging**
