### PR TITLE
detect cors Ajax requests

### PR DESCRIPTION
**Pull request by dicrtarasov**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | #17878

Cross domain requests contains `Origin` header, which is always differ from Request::hostInfo

### CODE REVIEW

**Comment by samdark** [comment]
Would that work for non-CORS fetch()?

**Comment by dicrtarasov** [comment]
Yes, because the old check of `X-Requested-Withrequest` remained in place as before.

**Comment by samdark** [comment]
But fetch doesn't send `X-Requested-With`...

**Comment by dicrtarasov** [comment]
Oh, yes, agree ..... checked just now.
`fetch` does not send any headers that may distinguish it request from ordinal non-ajax.
But ... at least we can detect cross domain requests by the difference between `Origin` and `Request::hostInfo`. It's already a little better than nothing at all :)

**Comment by samdark** [comment]
Added tests, merged. Thanks!

**Pull request merged**
