### PR TITLE
Remove unnecessary comparsion

### PR DESCRIPTION
**Pull request by ghost**
| Q | A |
| --- | --- |
| Is bugfix? | no |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |

Removed unnecessary comparsion

### CODE REVIEW

**Comment by klimov-paul** [comment]
Original code was correct: remember that `&&` has higher priority then `||`.

**Comment by dynasource** [comment]
why should there be checked for larger than 0 again? That has already been done?

**Comment by Lanrik** [comment]
Ok, but may condition be rewrited as "if ($page > 0 || $page == 0 && $this->forcePageParam)" ?

**Comment by dynasource** [comment]
what other options does $page have? It isnt really clear from the class (also room for improvement here) . If 0 is the only option, it can be removed completely.

**Comment by cebe** [comment]
It could be changed to `$this->forcePageParam || $page > 0` to be more clear.

**Comment by dynasource** [comment]
agreed. @Lanrik, can you do an update to your PR?

**Review by cebe — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
