### PR TITLE
$defaultOptions in favor of dependency injection

### PR DESCRIPTION
**Pull request by dan-developer**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by samdark** [comment]
Could you elaborate about the change?

**Comment by AndersonDan** [comment]
In large systems code reuse can be improved with a standard, so you can change everything with a simple configuration, a hypothetical example:

```php
\Yii::$container->set('yii\widgets\ActiveForm', [
    'defaultOptions' => [
        'autocomplete' => 'off',
    ],
]);

ActiveForm::begin([
    'options' => [
        'id' => 'test-form',
        //'autocomplete' => 'off', // It is not necessary to repeat the configuration again. If at some point resolve to return all form to be 'autocomplete' => 'on', just change it in dependency injection.
    ],
]);
```

**Comment by samdark** [comment]
Technically I understand why it's made like that. When overriding `options` via `::widget()` call, it replaces options defined via DI globally. I can't say I like additional property though.

**Comment by samdark** [comment]
Need @yiisoft/core-developers opinions.

**Comment by AndersonDan** [comment]
Exactly.

Another example would be: https://github.com/kartik-v/yii2-krajee-base/pull/77

**Comment by dynasource** [comment]
> I can't say I like additional property though.

agree. The usecase is so common that I prefer a solution to be handled centrally so that it can be reused everywhere.

**Comment by samdark** [comment]
@dynasource any ideas?

**Comment by dynasource** [comment]
by changing array_merge to ArrayHelper::merge() in https://github.com/yiisoft/yii2/blob/master/framework/di/Container.php#L168

Then both DI & custom config arrays can be used side by side. Of course the side effect is that DI is not overwritten, but since you have the power to configure this in the first place, this could be tackled. Its a tradeoff. IMO, ArrayHelper::merge() is more useful in practice.

**Comment by samdark** [comment]
I agree that such merge would be a better solution but I'm afraid that would change too much. Developers may rely on the fact that it replaces properties now.

**Comment by dynasource** [comment]
agree

**Comment by samdark** [comment]
Would be designed differently in 3.0.

**Pull request closed without merging**
