### PR TITLE
Error handler cleaner registration

### PR DESCRIPTION
**Pull request by SamMousa**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️

This PR allows the error handler (`handleException()`) to be used when the error handler is not registered.
Currently the error handler works great in a request cycle (because that generally ends after the error handler is called), but causes issues during testing.
Specifically `handleException()` calling `unregister()` which changes PHPs global state even when it shouldn't.

This implementation simply stores the registration status and uses that to determine of `register()` / `unregister()` should do something.

### CODE REVIEW

**Comment by samdark** [comment]
@SamMousa changelog line?

**Comment by SamMousa** [comment]
Does this do sound good?

- Bug #17801: Fixed `ErrorHandler` unregister and register only change global state when applicable (SamMousa)

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
@SamMousa changed your mind?

**Comment by SamMousa** [comment]
No it was based on old master branch; I've made a new one

**Comment by SamMousa** [comment]
#17804

**Pull request closed without merging**
