### PR TITLE
15858 broken basehtml collecterrors with showallerrors true

### PR DESCRIPTION
**Pull request by fcaldarelli**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15858

### CODE REVIEW

**Review by SilverFire — APPROVED** [review]

**Comment by SilverFire** [comment]
@FabrizioCaldarelli I have simplified code and PHPDocs a bit

**Comment by FabrizioCaldarelli** [comment]
@SilverFire You can remove also line with "$lines = array_values($lines);" because after you are not considering $lines array indexes.

I don't like much using variabile by reference ( " foreach ($lines as &$line) {" ), because if you make some changes and forget to apply "&", the result will change, but code is more concise.

**Comment by SilverFire** [comment]
> You can remove also line with `$lines = array_values($lines)`

No, it works as it should giving consistent sequence on function output

> because if you make some changes and forget to apply "&", the result will change, but code is more concise.

Yes, it is possible. That's why it's good to have tests :)

**Comment by FabrizioCaldarelli** [comment]
> No, it works as it should giving consistent sequence on function output

The sequence order is mantained even if there are some index missing. Isn't it?
Infact $line index is neither mentioned nor used inside foreach cycle.

**Comment by SilverFire** [comment]
Sorry, I didn't get you question.

**Comment by FabrizioCaldarelli** [comment]
For example, if $lines array had 2 elements (as test https://github.com/yiisoft/yii2/pull/15859/commits/52263077c057c71147aacdbe7aeaf87a86a3d540#diff-580fa7c1d99b2db708afd866e9d71cb9R1325), with 0 and 2 as indexes values, applying array_values ( row 1260 ) is indifferent, because at next foreach cycle with don't care about indexes.

**Comment by SilverFire** [comment]
Foreach in this method will not be affected, but developer will get array with non-seq indices, that may crash his code

**Comment by FabrizioCaldarelli** [comment]
@SilverFire You are right.

**Pull request merged**
