### PR TITLE
fix timestamp

### PR DESCRIPTION
**Pull request by np25071984**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17185

### CODE REVIEW

**Comment by s1lver** [comment]
@samdark @GHopperMSK 
```php
@filemtime($dstFile)
```
I don't think that's good. It's better to get an error than to guess what goes wrong

**Comment by samdark** [comment]
@s1lver yes but it's in the same way that other timestamps added in the same class.

**Comment by s1lver** [comment]
really,but don't keep doing that

**Comment by samdark** [comment]
Won't do in Yii 3.

**Pull request merged**
