### PR TITLE
Extracted FormatterInterface from yii\i18n\Formatter yiisoft/yii2#14997

### PR DESCRIPTION
**Pull request by njasm**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #14997

### CODE REVIEW

**Comment by samdark** [comment]
Not sure it makes a lot of practical sense to extract this interface but overall it looks OK...

**Comment by samdark** [comment]
@cebe need you opinion.

**Comment by njasm** [comment]
@samdark not extracting all yii's core/components interfaces, even if they don't make any pratical sense at first will invalidate the possibility in #14997 of autowiring capabilities.. I believe.

**Comment by cebe** [comment]
I don't see why you need an interface to enable autowiring. If there is no other practical sense in using the interface than to enable DI, we should fix DI to work with classes directly. An interface that requires to implement > 20 methods does not make sense.

**Pull request closed without merging**
