### PR TITLE
Update UniqueValidator.php

### PR DESCRIPTION
**Pull request by DrDeath72**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |

fix if indexBy('id') for example

### CODE REVIEW

**Comment by samdark** [comment]
What does the change do?

**Comment by DrDeath72** [comment]
get first array value if indexed by field

**Review by samdark — CHANGES_REQUESTED** [review]
OK. That makes sense. Can you add a line for changelog and a test for it?

**Comment by DrDeath72** [comment]
nope, i noob :D

**Review by SilverFire — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request closed without merging**
