### PR TITLE
Update `yii\helpers\BaseJson`

### PR DESCRIPTION
**Pull request by WinterSilence**
- add errors to `BaseJson::$jsonErrorMessages`
- fix type validation of `$json` in `BaseJson::decode()`
- optimize  `BaseJson::handleJsonError()`
- optimize and fix bug with data types in `BaseJson::processData()`
- fix encoding `BaseJson::errorSummary()`
- optimize `BaseJson::collectErrors()`
- fix data types and exception class in `yiiunit\framework\helpers\JsonTest`
- fix constructor `yiiunit\framework\web\Post`

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by bizley** [comment]
There are some overlaps with #18762 (something to crosscheck)

**Comment by WinterSilence** [comment]
@bizley PR fixes problem described in #18762 - my solution is shortest/easy.

**Comment by zebraf1** [comment]
I suggest to revert "optimize and fix bug with data types in BaseJson::processData()" as it is done in #18762.
As mentioned in that PR this change is breaking BC and needs to be under feature flag. Any code style changes should be done under that PR.

I do not understand this PR description. What is the bug you're targeting to fix? Is it the same processData and everything else is just refactoring and code cleanup?

**Comment by WinterSilence** [comment]
@zebraf1 Changing type of values being sent is not documented, so correcting method result is bugfix and can't be BC. I'm not against your version,  let community decide what's better.

**Comment by machour** [comment]
Dear @WinterSilence 

Thank you a lot for your contributions. 
Could you enhance them by following our git workflow ?

* [meaningfull branch names](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-create-a-new-branch-for-your-feature-based-on-the-current-yii-master-branch)
* [usefull commits messages](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#6-commit-your-changes)

For this PR for example, your commits did update the BaseJson file, so the PR title gives no hint whatsoever to what you're trying to achieve.

All commits message are "Update file foo.php". It's already clear that you're updating the file. Your commit message should explain why you're doing it.

Thanks again !

**Comment by WinterSilence** [comment]
@machour for example, what would you call this PR?

**Comment by machour** [comment]
@WinterSilence, this PR cannot have a good enough title as it is, because you're tackling too many things at once:

 - adding two new error messages (**feature**)
 - optimizing code (**perf**)
 - updating the JSON test to expect different exceptions (and your commit don't explain why) (**tests**)
 - updating a totally unrelated file (Post.php) to add a parameter that you pass on to the constructor (**tests**)

Ideally, this PR would be broken into 3 or 4 PRs:

 - Add new JSON errors messages
 - Code optimization for the Json helper and its test case
 - Fix constructor for Post test file

Even though it may seem a little bit pedantic, breaking up your PR into several smaller ones will enable the team to review & approve them quicker, and for the source code history to be more comprehensible.

As for the commit messages, since the PR would be smaller, they would probably be the same as the PR title. If not, then they should be meaningful. 

For example, the commit message for the exceptions update in the test case would be:
`Expect InvalidArgumentException instead of InvalidParamException`

And you could further explain the logic by adding a second line, so that everyone understand immediately why the test worked while expecting the wrong exception:


```
Expect InvalidArgumentException instead of InvalidParamException

this test file wasn't updated when InvalidParamException was deprecated, 
but it worked because InvalidArgumentException inherits from it
```

Here's a [good commit convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format) that I learned a lot from.

**Comment by WinterSilence** [comment]
@machour I also think that short PRs are better, but @bizley & @samdark  did not agree with me (GII PRs)

**Comment by machour** [comment]
@WinterSilence I (quickly) went through your PR for yii2-gii, you're going from one extreme (a PR with multiple purposes) to another (several PR with the same purpose). And maintainer fatigue can happen from time to time 😄 

I think that what was meant was: try to group your several optimisations into a single PR : It's okay to do a single PR when all the changes have the same purpose, especially if the PR is well titled, and you describe what you did.

Nevertheless, I'm going to decline this PR, as there's a totally unrelated file being changed, and you didn't update the CHANGELOG file.

Please don't be discouraged by this outcome, it's just to help you help us with your next pull requests !

PS: And please don't open a new PR to update just that `Post.php` file, I'm sure you can find several other tests files that need to be updated, and can make it into a single, mono-targeted, PR. Cheers !

**Review by machour — COMMENTED** [review]
This PR addresses too many things at the same time, and should not be merged as is.

**Comment by bizley** [comment]
Yes, we tend to approve PRs like that while we should not. Let's try to do it by the book from now on. Thank you @machour

**Pull request closed without merging**
