### PR TITLE
Fix accidental `getResponseHeader()` fails

### PR DESCRIPTION
**Pull request by maximal**
exc

### CODE REVIEW

**Comment by SilverFire** [comment]
How did you get this error?

**Comment by maximal** [comment]
Yes.
Look at this page: http://domic.pro/project/%D1%82%D0%B8%D0%BF%D0%BE%D0%B2%D0%BE%D0%B9-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%B4%D0%BE%D0%BC%D0%B0-b-004-%D0%B3%D1%80%D1%80

When you do, I delete the link from here.

**Comment by SilverFire** [comment]
On your site it happens because of CSRF polices of host `static.hypercomments.com`.
You are trying to load some resource from `http://static.hypercomments.com`, but get the error: `Uncaught SecurityError: Blocked a frame with origin "http://static.hypercomments.com" from accessing a frame with origin "http://yoursire.com". Protocols, domains, and ports must match.`

Thank you for the interesting example and provided PR.

**Comment by SilverFire** [comment]
Oh snap. The PR is a little bit wrong

**Comment by maximal** [comment]
> P.S.: I'm suggesting you to disable debug panel for untrusted IP addresses even when you are developing since the project is accessible from the Internet

Thank you for suggestion, actually I opened this project only for this issue demo.

**Comment by SilverFire** [comment]
Ok :)

**Pull request merged**
