### PR TITLE
When uses filter \yii\filters\PageCache, then yii\web\JsonResponseFor…

### LINKED ISSUE #17043: JsonResponseFormatter reset Response::$content when use PageCache
When uses filter \yii\filters\PageCache, then yii\web\JsonResponseFormatter sets Response::$content as null, howerer \yii\filter\PageCache has been restore content

### What steps will reproduce the problem?
Use PageCache

### What is the expected result?
Restore content from cache

### What do you get instead?
Response::$content is null

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1
| Operating system | Linux

### PR DESCRIPTION
**Pull request by h0mjam**
…matter sets Response::$content as null, howerer \yii\filter\PageCache has been restore content

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
New feature?  | no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | #17043

closes #17043

### CODE REVIEW

**Comment by h0mjam** [comment]
Wrote tests, check please.

**Comment by h0mjam** [comment]
Will there be changes, if so, when?

**Comment by samdark** [comment]
Need to verify it first.

**Comment by rob006** [comment]
This probably fixes a regression introduced in #14759 - it should be fixed before 2.0.16 release.

**Review by rob006 — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
