### PR TITLE
fix #16184 use self instead of static

### LINKED ISSUE #16184: static::$stack misused in yii\base\Widget of begin() and end functions
### What steps will reproduce the problem?
When re-declare the public static property  `$stack` in the sub class of `yii\base\Widget`,
the exception of 
```php
            throw new InvalidCallException('Expecting end() of ' . get_class($widget) . ', found ' . get_called_class());
```
would not trigger correctly due to `static` keyword before `$stack`.
This happens when two widgets begin and end not correctly.
e.g.
Both WidgetA and WidgetB are instance of yii\base\widget.
ether WidgetA or WidgetB redeclared the $stack;

```php
<?php WidgetA::begin()?>
<?php WidgetB::begin()?>
<?php WidgetA::end()?>
<?php WidgetB::end()?>
```
### What is the expected result?
Even though the public static property $stack redeclared in the widget,
the exception could also be thrown.

### What do you get instead?
when $stack is pushed and popped, use self::$stack instead of static$stack

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.1
| Operating system | CentOs

### PR DESCRIPTION
**Pull request by yanggs07**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 16184

### CODE REVIEW

**Comment by SilverFire** [comment]
Could you add a unit test to check the original problem reported in #16184?

**Comment by yanggs07** [comment]
@SilverFire thx for replying my pr.

it would take me some time to learn how to write test case for this.

I would be as soon as possible.

**Comment by yanggs07** [comment]
@SilverFire unit test added.

**Review by SilverFire — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
