### PR TITLE
#14272 - Added a resetButton method for GridView

### PR DESCRIPTION
**Pull request by rrmontuan**
#14272 

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | Added resetButton Method for GridView

### CODE REVIEW

**Comment by machour** [comment]
Hi @rrmontuan 

What is this reset button supposed to do? I don't see any logic behind it. It just seems to generate a `<a>` which I could do using `yii\helpers\Html`.

**Comment by s1lver** [comment]
Hi!

@machour 
The discussion dealt with the addition of a button without implementation. Because automatic generation is too risky. Implementation can be added independently. If I understood correctly.

@rrmontuan 
I think it's worth using the button naming method.

```php
Yii::t();
```

**Comment by rrmontuan** [comment]
> @machour
> The discussion dealt with the addition of a button without implementation. Because automatic generation is too risky. Implementation can be added independently. If I understood correctly.

Yeah @s1lver, that's why they asked for this implementation. 

> @rrmontuan
> I think it's worth using the button naming method.
> 
> ```
> Yii::t();
> ```

You're right, I'm going to adjust the method to use Yii::t() as you mentioned.

**Comment by samdark** [comment]
Not going to be merged into 2.0.x. Original issue moved to 3.0.

**Pull request closed without merging**
