### PR TITLE
Update yii.php

### PR DESCRIPTION
**Pull request by izemize**
Missing translation.

### CODE REVIEW

**Comment by SilverFire** [comment]
Hello. Thank you for you job. 
There are other messages in Yii framework that were changed or added since last Hungarian translation update.

Could you translate them too, please? Here is a [translations workflow](https://github.com/yiisoft/yii2/blob/master/docs/internals/translation-workflow.md) manual, that will help you to do it with pleasure.

**Comment by SilverFire** [comment]
@izemize so would you like to continue?

**Comment by izemize** [comment]
I am really sorry, but it's really much work and i work on big project now. Maybe later...

**Comment by samdark** [comment]
OK. Thanks for contribution!

**Pull request merged**
