### PR TITLE
Fixed #16945

### LINKED ISSUE #16945: RBAC DbManager does not play well with PDO::NULL_TO_STRING
### What steps will reproduce the problem?

Configuration:
```
    'components' => [
        'db' => [
            'attributes' => [
                PDO::ATTR_ORACLE_NULLS => PDO::NULL_TO_STRING,
            ],
        ],

        'authManager' => [
            'class' => \common\rbac\DbManager::class,
            'db' => 'db',
        ],
    ],
```

Code:

```php
$auth = \Yii::$app->getAuthManager();
$roleName = 'foo';
$role = $auth->getRole($roleName);
$role->name = 'bar';
$auth->update($roleName, $role);
```

This seems that the `ruleName` was set as **empty string** since `PDO::NULL_TO_STRING`,
and then occurs error when update.

### What is the expected result?

No error

### What do you get instead?

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`jobs`.`t_backend_auth_item`, CONSTRAINT `t_backend_auth_item_ibfk_1` FOREIGN KEY (`rule_name`) REFERENCES `t_backend_auth_rule` (`name`) ON DELETE SET NULL ON UPDATE CASCADE)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system | Linux

### PR DESCRIPTION
**Pull request by razonyang**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #16945

### CODE REVIEW

**Comment by samdark** [comment]
Why closing it?

**Comment by razonyang** [comment]
@samdark I thought this patch will break compatibility, if there is a rule which `name` is empty string(although many developers won't do that). Am I worry too much?

**Comment by samdark** [comment]
I think so. It makes no sense to have a rule that is an empty string.

**Comment by samdark** [comment]
Please add a line for changelong mentioning that the issue fixed is specific to Oracle specific mode. Thanks.

**Comment by razonyang** [comment]
Have added this into CHANGLOG :smile:

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
