### PR TITLE
input-validation.md

### PR DESCRIPTION
**Pull request by gugoan**
First part of the translation pt-BR. I will divide into parts to be well done.

### CODE REVIEW

**Comment by samdark** [comment]
Closing since it's not fully translated and there are no updates for a long time.

**Comment by SilverFire** [comment]
Maybe @lukBarros would like to check this and open a new PR

**Comment by lukBarros** [comment]
@SilverFire  Forgive the delay in RESPONSE , I will check this is .
I am very focused on foster yii2 My Country .

**Comment by SilverFire** [comment]
Ok, thank you. We are always happy to get a new PR :)

**Pull request closed without merging**
