### PR TITLE
Fix #14749: Ensured garbage collections for the widgets with behaviors attached to them

### LINKED ISSUE #14749: Widget garbage collection
### What steps will reproduce the problem?

Relates to #14102

Since now widgets may have event handles and behaviors attached to them.
This cause a memory leaks while widget usage as widget instance and behavior introduce a cycle reference.
Thus any usage of the Widget with attached behavior causes memory leak.

```php
AnyWidget::widget([
    'id' => 'test',
    'as test' => [
        'class' => TestWidgetBehavior::className()
    ],
]);
```

### What is the expected result?

Widget instance to be destroyed.
Memory usage stays the same after `Widget::widget()` or `Widget::end()`.

### What do you get instead?

Widget instance remains in memory consuming space without purpose.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  *
| Operating system | *

Unit test to reproduce:

```php
class TestWidget extends Widget
{
    public static $instanceCount = 0;

    public function __construct($config = [])
    {
        parent::__construct($config);
        static::$instanceCount++;
    }

    public function __destruct()
    {
        static::$instanceCount--;
    }
}

class WidgetTest extends TestCase
{
    public function testGc()
    {
        TestWidget::widget([
            'id' => 'test',
            'as test' => [
                'class' => TestWidgetBehavior::className()
            ],
        ]);
        $this->assertSame(0, TestWidget::$instanceCount);
    }
}
```

### PR DESCRIPTION
**Pull request by klimov-paul**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14749

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by rob006** [comment]
This adds some magic to the widgets. Since `end()` methods returns widgets instance, it is completely unsuspected that this instance will have all behaviors detached.

**Comment by samdark** [comment]
Oh... you're right. @klimov-paul how about doing the same in `__destruct()`?

**Comment by rob006** [comment]
> how about doing the same in __destruct()?

It will not work - `__destruct()` is called after GC finds and removes object from memory.

**Comment by samdark** [comment]
Right. Any suggestions then?

**Comment by rob006** [comment]
I suggest do nothing. This is not a real memory leak - GC will finally clean these objects, and detaching behaviors like this may create only unnecessary overhead. Such optimizations have some pros and cons, and I think it should be done at application level. Yii could just rely on PHP GC.

**Comment by samdark** [comment]
Yeah. In this case implications are quite serious so I don't think this pull request should be merged.

**Pull request closed without merging**
