### PR TITLE
Tests: avoid pgsql bugs of 9.5 and 10.0

### PR DESCRIPTION
**Pull request by bscheshirwork**
This is only compare with actual data from database schema.

All of other usercase, who related to this pgsql errors is broken.

note: Wait for fix it in source and set top versions who have errors in next PR's.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15265 #15247

### CODE REVIEW

**Comment by bscheshirwork** [comment]
Also I send info about this errors to pgsql-bugs

**Comment by samdark** [comment]
Would you please post links to posgresql issue tracker bugs here?

**Comment by samdark** [comment]
Should not be merged. It's hiding the issue, not fixing it.

**Comment by polobo** [comment]
Here's a link to the thread on the PostgreSQL online mailing list browser - there is no dedicated bug tracker.

https://www.postgresql.org/message-id/flat/20180124222007.GQ17109%40momjian.us#20180124222007.GQ17109@momjian.us

No one choose to research this report - and whether its a bug or simple compatibility breakage would depend on findings - partly because the reported complaint has not been reduced to something that is demonstrably PostgreSQL-output related.

What would help move this forward in PostgreSQL would be for someone to write up a self-contained script generates data question and then run that script against 9.4, 9.5, 9.6, and 10.  Post the results of each along with the script to the pgsql-bugs@lists.postgresql.org (or replying to the linked thread if you happen to have it in your inbox).  At least 9.4/9.5 where the smallint problem reported seems to have appeared.  At that point the differences in output can either be explained or fixed depending on what caused it in the first place.

David J.

**Comment by polobo** [comment]
FYI - I've done a limited version example of what I think you are talking about (smallint, 9.3 vs 9.6) and posted it to the original bug report thread.

**Comment by bscheshirwork** [comment]
@polobo Thanks!

**Comment by schmunk42** [comment]
From the answer of Tom Lane in the linked [thread](https://www.postgresql.org/message-id/flat/20180124222007.GQ17109%40momjian.us#20180124222007.GQ17109@momjian.us) above:

> Oh, right, this was an intentional change awhile back.
> [...]
> (digs...) It was changed in this 9.5-era commit:

So, I don't think this will be "fixed" in upstream in Postgres.

What can we do about it? Should Yii convert that?

---

Did something change in the core about that, btw?! I can not reproduce the failing `smallint` test locally at the moment.

**Comment by samdark** [comment]
@bscheshirwork would be great if you'll re-check if the issue in still in master?

**Comment by schmunk42** [comment]
> At least 9.4/9.5 where the smallint problem reported seems to have appeared.

@polobo You meant **dis**appeared, right? 😄

**Comment by schmunk42** [comment]
### Postgres test status

All tested against https://github.com/yiisoft/yii2/commit/eb57d4191cbc5a2d8cf5a28345bc81a13e488fa1

#### Broken (only "smallint" bug)
- 9.5.0 - https://gitlab.com/yiisoft/yii2/-/jobs/49501874
- 9.5.1 - https://gitlab.com/yiisoft/yii2/-/jobs/49501843
- 9.5 (9.5.10) - https://gitlab.com/yiisoft/yii2/-/jobs/49503441
- 9.6 (9.6.6) - https://gitlab.com/yiisoft/yii2/-/jobs/49501860
- 10 - https://gitlab.com/yiisoft/yii2/-/jobs/49522348
- 10.1 - https://gitlab.com/yiisoft/yii2/-/jobs/49522413

#### OK
- 9.4 - https://gitlab.com/yiisoft/yii2/-/jobs/49501855

The error with "float_col2" seems to have disappeared.

I am really lost on this issue :(

**Comment by polobo** [comment]
Short answer: The current behavior, since 9.5, is the correct behavior. Those single quotes that now appear are going to stay.  9.4 and earlier (lacking the isngle quotes) was wrong - but won't be fixed in that (or earlier) realeases.  If your code must support both outputs you will need to decide on the best way to do that for your project.

**Comment by schmunk42** [comment]
Isn't the question (or the test) about how we "see" these values on the PHP side?

I.e. Mysql has a [type map](https://github.com/yiisoft/yii2/blob/65f6b59/framework/db/mysql/Schema.php#L41-L70), which explicitly defines `'smallint' => self::TYPE_SMALLINT,` - do we also need that for Postgres?

I do not use Postgres, but from my understanding I'd expect a `smallint` column to be an `integer` in PHP.

**Comment by polobo** [comment]
It boils down to why you are choosing to parse the default expression in the first place instead of just passing through whatever the database returns.  I suppose trimming off the cast would make sense but take the value being cast as-is.  IOW, the failing test should probably be dropped altogether.  But alas I know PostgreSQL but not yii2 so there may be someone feature that depends on the specifics.

**Comment by polobo** [comment]
To make it clear, your are not really parsing a returned value of a smallint, you are parsing the expression that someone happened to attach to a create table command.  In many ways all that is is a string expression whose evaluated result is cast to the column type.  And the client has little means to evaluate the provided expression, only the server can do that.  For the client the expression should just be documentation.  And you should not need to parse documentation.

**Pull request closed without merging**
