### PR TITLE
Added .phpstorm.meta.php for DI container.

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
I think it could be expanded to `Yii::createObject()` and `Instance::ensure()`.

**Review by samdark — APPROVED** [review]
👍  Looks good.

1. Have you tested it?
2. Need a line for CHANGELOG.md about the change.

**Comment by vjik** [comment]
1. Yes, it's work, but have nuances.
If I add only `Instance::ensure` in `.phpstorm.meta.php`, then it's work also for  `\yii\di\Container::get`. I don't know why.
But just in case, I included everything in .phpstorm.meta.php

2. Done

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
