### PR TITLE
fix current time in formatter

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Fixed issues  | #14202

### CODE REVIEW

**Comment by bscheshirwork** [comment]
Can merge it as "hotfix" may be?

**Comment by samdark** [comment]
@cebe if you confirm it's correct fix, it could be merged, I think.

**Comment by samdark** [comment]
@cebe tests are in place and are passing.

**Review by cebe — APPROVED** [review]

**Comment by cebe** [comment]
needs a changelog line to get into 2.0.13

**Comment by githubjeka** [comment]
Oh, and I always thought that this is the default behavior in PHP and added setTime (0,0,0) 😄

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
