### PR TITLE
fix same variable name

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | binding to  #14996

### CODE REVIEW

**Comment by samdark** [comment]
What's the problem it is fixing?

**Comment by bscheshirwork** [comment]
@samdark test is broken: attemp to config each non-first object `$rule` from previous object `$rule` (foreach), not from input array `$rule`

**Review by cebe — APPROVED** [review]
ideally the name should be `$ruleConfig`

**Review by rob006 — APPROVED** [review]

**Comment by bscheshirwork** [comment]
@cebe yes, IMHO you right.  
In my opinion `ruleConfig` is better  
But all other equivalent variables in this file has named "config"

**Comment by samdark** [comment]
Adjusted and merged https://github.com/yiisoft/yii2/commit/eac6a5d6af894606b8b7bdf351594dc451e4b246. Thanks.

**Pull request closed without merging**
