### PR TITLE
Migration: safeUp and safeDown returns bool as are declared in docs

### PR DESCRIPTION
**Pull request by WinterSilence**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Please add a line for CHANGELOG. Thanks.

**Review by Arhell — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Comment by rob006** [comment]
What is the reason behind this change? It is unclear what bug was fixed by this PR.

**Comment by schmunk42** [comment]
@rob006 The docs state a `boolean` return value.

I noticed that this is also the case in `up` and `down`, but there are also these lines with return `null`:

https://github.com/yiisoft/yii2/blob/master/framework/db/Migration.php#L129
https://github.com/yiisoft/yii2/blob/master/framework/db/Migration.php#L158

Looks like `null` was always treated like `true`(?)

**Comment by rob006** [comment]
> The docs state a `boolean` return value.

But this is incorrect. You don't need to return anything if migration is successful, the only meaningful return value is `false` everything else does not matter. If we want to make it consistent, we should update phpdoc to `false|null` - no return if everything is OK, `return false` if migration failed.

**Comment by schmunk42** [comment]
I agree. Since most migrations (overridden methods) do not explicitly `return true` it would make more sense.

**Pull request merged**
