### PR TITLE
Update db-query-builder.md

### PR DESCRIPTION
**Pull request by cgsmith**
Fixing 404 page on guide.

I did not verify other languages or markdown files.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18933

### CODE REVIEW

**Comment by bizley** [comment]
This is not right as well, needs to be `.md`.

**Comment by cgsmith** [comment]
Hmmm. Something with the build process then? I saw another related issue.

Is the build script for docs part of this repo or another one? I forget.

**Review by Arhell — COMMENTED** [review]
Working link
https://www.yiiframework.com/doc/guide/2.0/en/db-dao#quoting-table-and-column-names

**Comment by cgsmith** [comment]
Oh wow... i way overthought that... I didn't see the `.html` until I got to my desk. Thanks @bizley and @Arhell

**Review by Arhell — APPROVED** [review]

**Comment by bizley** [comment]
Thanks

**Pull request merged**
