### PR TITLE
renderDynamic break

### PR DESCRIPTION
**Pull request by xicond**
renderDynamic break while params inside contain string with quote
coz when the string concat then evaluate, it will break the closing quote

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by xicond** [comment]
@samdark I branched out from 2.1, will come out to 2.0.14.2 ?

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Please add a line for changelog. Thanks.

**Comment by xicond** [comment]
@samdark added

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
