### PR TITLE
Do not use $this to call static method

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18613

### CODE REVIEW

**Review by bizley — APPROVED** [review]
At https://github.com/yiisoft/yii2/blob/3d4b0f941ed435d9f178bc7fedc0579e8d99c8d8/framework/db/BaseActiveRecord.php#L1124 as well.

**Comment by WinterSilence** [comment]
it's wrong solution, because **method primaryKey not exists in BaseActiveRecord**, this **method defined in ActiveRecord** as **static**

**Comment by bizley** [comment]
@WinterSilence https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecordInterface.php#L30

**Comment by WinterSilence** [comment]
@bizley wrong context, it's must call as `static::primaryKey()`

**Comment by WinterSilence** [comment]
@bizley refrain from personal grudges when evaluating

**Comment by samdark** [comment]
@WinterSilence it's not wrong a scope. The method is defined in `ActiveRecordInterface`. `BaseActiveRecord` is an abstract class and it implements the interface. Since it's abstract, there's no need to declare abstract methods in the class itself, that's already implied. But all the classes that extend from `BaseActiveRecord` must implement the method so overall it seems to be correct.

**Comment by WinterSilence** [comment]
@samdark  yes that's part - my fail, but you miss https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecordInterface.php#L30

**Comment by WinterSilence** [comment]
@samdark pf.. i miss in pr's.. all fine

**Pull request merged**
