### PR TITLE
Added SofDeleteBehavior

### PR DESCRIPTION
**Pull request by Skysplit**
Related to #2484

I am looking forward your opinion and notices.

Things to be done yet:
- [x] Documentation with examples
- [x] Tests

### CODE REVIEW

**Comment by Skysplit** [comment]
Added the phpDoc coments, but I guess they'll need some polishing.

**Comment by m8rge** [comment]
I think, that trait in this context will be more useful:
```php
trait SoftDeleteTrait 
{
    public static function deleteAll($condition = '', $params = [])
    {
        $command = static::getDb()->createCommand();
        $command->update(static::tableName(), ['deleted' => 1], $condition, $params);

        return $command->execute();
    }
}
```
So, you can use either delete or deleteAll. And those methods will return the number of rows "deleted".

**Comment by mdmunir** [comment]
Where this trait will be used? If class have defined methode, then methode from trait will be ignored.

**Comment by m8rge** [comment]
@mdmunir If you redeclare deleteAll, you must understand, what are you doing. =)

**Comment by mdmunir** [comment]
@m8rge Like this?

Hard delete (default)
```php
class User extends ActiveRecord
{

}
```

Soft delete
```php
class User extends ActiveRecord
{
    use SoftDeleteTrait;
    
}
```

Or what?

**Comment by m8rge** [comment]
@mdmunir Yes.

**Comment by mdmunir** [comment]
@m8rge I have test it, and its work :+1: .

Allow custom field.
```php
trait SoftDeleteTrait 
{
    public static function deleteField()
    {
        return 'delete';
    }

    public static function deleteAll($condition = '', $params = [])
    {
        $field = static::deleteField();
        $command = static::getDb()->createCommand();
        $command->update(static::tableName(), [$field => 1], $condition, $params);

        return $command->execute();
    }
}
```

Usage
(use default field)
```php
class User extends ActiveRecord
{
    use SoftDeleteTrait;

}
```

(use custom field)
```php
class User extends ActiveRecord
{
    use SoftDeleteTrait;

    public static function deleteField()
    {
        return 'custom_field';
    }
}
```

**Comment by m8rge** [comment]
@mdmunir Also you can make it more configurable, like:
```php
trait SoftDeleteTrait 
{
    public static function deletedProperties()
    {
        return ['status' => -1];
    }

    public static function deleteAll($condition = '', $params = [])
    {
        $command = static::getDb()->createCommand();
        $command->update(static::tableName(), static::deletedProperties(), $condition, $params);

        return $command->execute();
    }
}
```

In `deletedProperties()` you can return `['deleted' => 1]` or `['deleted_at' => time()]` or something else.

**Comment by mootensai** [comment]
Please check my extension here 
https://github.com/mootensai/yii2-before-query

**Comment by Skysplit** [comment]
@mootensai How is this connected with this PR?

**Comment by mootensai** [comment]
As you can see here
https://github.com/mootensai/yii2-before-query/blob/master/traits/SoftDeleteBoolTrait.php
or here
https://github.com/mootensai/yii2-before-query/blob/master/traits/SoftDeleteDateTimeTrait.php

I prefer to use soft delete by trait, not behavior. 
1. its faster,
2. behavior maybe replaced by trait at Yii 2.1
on this discussion here 
https://github.com/creocoder/yii2-nested-sets/issues/67
and here
https://github.com/yiisoft/yii2/issues/1053
3. do not override another method, but add new method. because maybe on 1 active record there's a lot of trait that will do the same. it will generate conflict.
4. i added function to restore soft-deleted row

if you have more idea, i'm open for any improvement

**Comment by Skysplit** [comment]
Mind that traits cannot be so easily configured as behaviour. Moreover, traits cannot be programmatically added to model, while behaviours can.

> 1. it's faster
The difference between execution beaviour and trait won't be even noticable

**Comment by m8rge** [comment]
@Skysplit Trait, that i described in https://github.com/yiisoft/yii2/pull/6057#issuecomment-70468321 can configure all that need for Soft delete. Hardly you want do detach SoftDelete behavior.
> The difference between execution beaviour and trait won't be even noticable
Of corse, if you working with one model, difference won't be even noticeable. But if you fetching 1000 or  more models, you will see the difference.

Ex.: 1000 models without trait and behavior are created in ~1.09 sec.  
1000 models with trait are created in ~1.09 sec.  
1000 models with behavior created in ~1.17 sec.

And this is one behavior. Add bunch of behaviors and you app will work slowly. Less behaviors is better.

**Comment by samdark** [comment]
I think there should be methods to restore deleted record.

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-softdelete/blob/master/SoftDeleteBehavior.php#L241

**Comment by samdark** [comment]
Oh. Nice. I think we may link to your extension instead of bringing alike one to the core.

**Pull request closed without merging**
