### PR TITLE
[Work in progress] Update Vietnamese translate

### PR DESCRIPTION
**Pull request by dungphanxuan**
add some update translate

### CODE REVIEW

**Comment by samdark** [comment]
@dungphanxuan are you going to finish translation?

**Comment by dungphanxuan** [comment]
No, can you delay that pull request, when done, i will notify. thank

**Comment by samdark** [comment]
OK.

**Comment by cebe** [comment]
@dungphanxuan why did you close it?

**Comment by dungphanxuan** [comment]
@cebe, i make another Pull request https://github.com/yiisoft/yii2/pull/16231. Some translate not finish yet, so i update translate, cancel this Pull request,  then create new Pull request.
Is there best solution?

**Comment by cebe** [comment]
it's fine, I did not see your new pull request so I thought changes were lost.

**Pull request closed without merging**
