### PR TITLE
Preparing for supporting array type for PostgreSQL

### PR DESCRIPTION
**Pull request by Tigrov**
Added two parameters for `yii\db\pgsql\ColumnSchema`:
ColumnSchema::$dimension
ColumnSchema::$delimiter

### CODE REVIEW

**Comment by Tigrov** [comment]
Related with #7813 and #7481

**Comment by armpogart** [comment]
Any progress on this one?

**Comment by Tigrov** [comment]
It depends on #7481. Without it arrays don't work.

**Comment by cebe** [comment]
this PR does not contain any commits, closing.

**Pull request closed without merging**
