### PR TITLE
using \yii\base\Behavior::events and passing variables to event handlers

### PR DESCRIPTION
**Pull request by smsteel**
For using `\yii\base\Behavior::events` and passing variables to event handlers:

```
public function events()
{
    return [
        ActiveRecord::EVENT_BEFORE_INSERT => [[$this, 'myMethod'], 'parameter']
    ];
}
```

### CODE REVIEW

**Comment by samdark** [comment]
What's your use case?

**Comment by smsteel** [comment]
I have Behavior attached to ActiveRecord and it must do specific calls to external API when events triggered. I can write 3 methods containing the exact same calls, but different parameters in current Yii2:

    public function events()
    {
        return [
            ActiveRecord::EVENT_BEFORE_INSERT => 'myMethodInsert',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'myMethodUpdate',
            ActiveRecord::EVENT_BEFORE_DELETE => 'myMethodDelete',
        ];
    }
   
    public function myMethodInsert()
    {
        $this->beforeAPICall();
        Api::call(['parameter1', 'parameter2']);
        $this->afterAPICall();
    }

    // etc...

Or i can use the same method, but check for $event->name:

    public function events()
    {
        return [
            ActiveRecord::EVENT_BEFORE_INSERT => 'myMethod',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'myMethod',
            ActiveRecord::EVENT_BEFORE_DELETE => 'myMethod',
        ];
    }

    public function myMethod($event)
    {
        $this->beforeAPICall();
        switch($event->name) {
            case ActiveRecord::EVENT_BEFORE_INSERT:
               Api::call(['parameter2', 'parameter3']);
            // etc...
        }
        $this->afterAPICall();
    }

With my changes, code becomes cleaner:

    public function events()
    {
        return [
            ActiveRecord::EVENT_BEFORE_INSERT => [[$this, 'myMethod'], ['param1', 'param2']],
            ActiveRecord::EVENT_BEFORE_UPDATE => [[$this, 'myMethod'], ['param1']],
            ActiveRecord::EVENT_BEFORE_DELETE => [[$this, 'myMethod'], ['param3', 'param4']]
        ];
    }

    public function myMethod($event)
    {
        $this->beforeAPICall();
        Api::call($event->data);
        $this->afterAPICall();
    }

**Comment by samdark** [comment]
OK. Would be great to have unit tests for new behavior.

**Comment by klimov-paul** [comment]
I am against this change. It overcomplecates things.
It is better to use separated methods or `Closure`.

**Comment by smsteel** [comment]
Actually, it is true, it can be done this way, didn't consider (But PHP 5.4+ due to $this usage):

    public function events()
    {
        return [
            ActiveRecord::EVENT_BEFORE_INSERT => function () { $this->myMethod(['param1']) }
            ActiveRecord::EVENT_BEFORE_UPDATE => function () { $this->myMethod(['param2', 'param3']) }
            ActiveRecord::EVENT_BEFORE_DELETE => function () { $this->myMethod(['param4']) }
        ];
    }

    public function myMethod($data)
    {
        $this->beforeAPICall();
        Api::call($event->data);
        $this->afterAPICall();
    }

But i still think it's expected behaviour, since `\yii\base\Component::on` accepts `$data`. At least, i expected it to be parsed from array. Maybe the structure of array must be changed to be more clear?

**Comment by klimov-paul** [comment]
OK, I see your point - it make sense to consider at least.

**Comment by klimov-paul** [comment]
It whould be better to use named array keys for thsi feature:
```php
public function events()
{
    return [
        ActiveRecord::EVENT_BEFORE_INSERT => ['handler' => 'myMethod', 'data' => ['param1', 'param2']],
    ];
}
```

This will also allow to provide an 'append' option, which is availbale at `Component::on()` as well.

**Comment by creocoder** [comment]
Vote against. Looks like violates of standart workflow and smells like wrong refactoring wishes.

**Comment by cebe** [comment]
> But PHP 5.4+ due to $this usage

Yii requires php 5.4 anyway.

I am also against adding this as it does not really add something useful, code does not look cleaner imo.
I am closing this PR now. Thanks for your contribution anyway!

**Pull request closed without merging**
