### PR TITLE
pgsql: properly detect multiple relations between two tables

### LINKED ISSUE #8012: Multiple relations between two PostgreSQL tables detected as one.
`pgsql\Schema::findConstraints()` does not use constraint name as index. Other schemas are fine.

### PR DESCRIPTION
**Pull request by nineinchnick**
Resolves #8012

### CODE REVIEW

**Comment by samdark** [comment]
Please add changelog.

**Comment by samdark** [comment]
Oww... something bad happened to the pull request...

**Comment by nineinchnick** [comment]
Rebased and added changelog. I didn't add it before because I wasn't sure if the bug wasn't introduced after last release.

**Comment by samdark** [comment]
Merged manually https://github.com/yiisoft/yii2/commit/ced423b601c2957fc6d3394b6f24fb2cc994ea76

**Pull request closed without merging**
