### PR TITLE
Fix #13920: Fixed erroneous validation for specific cases

### LINKED ISSUE #13920: ajax validation marks inputs as invalid despite their value changed
### What steps will reproduce the problem?

* setup Yii2 project from Yii2 template
* in `views/site/contact.php` change
`<?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>` into 
`<?php $form = ActiveForm::begin(['id' => 'contact-form', 'enableAjaxValidation' => true, 'enableClientValidation' => false]); ?>`
* in `controllers/SiteController.php` insert
```
    if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            sleep(5);
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return \yii\bootstrap\ActiveForm::validate($model);
    }
```
after `$model = new ContactForm();`
* run `./yii serve`
* enter `/index.php?r=site%2Fcontact`
* quickly fill name and subject fields, then click other field (all must be completed in 5 seconds)

### What is the expected result?

Those 2 fields marked as valid

### What do you get instead?

Only first field is marked as valid

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | c586f19d56d7616be8ba792ffcc134cdcceaf965 (between 2.0.11.2 and 2.0.12)
| PHP version      | 7.1
| Operating system | Ubuntu

I suspect following flow:
* value of email field is changed
* first validation ajax is sent with data like {'name': 'foo', 'subject':''}
* value of subject field is changed
* second validation ajax is sent with data like {'name': 'foo', 'subject':'foo'}
* first validation ajax returns, marks subject field as invalid and non-dirty
* second validation ajax returns, but there are no dirty fields, so it does nothing

### PR DESCRIPTION
**Pull request by tim-fischer-maschinensucher**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #13920

### CODE REVIEW

**Review by mtangoo — APPROVED** [review]

**Comment by samdark** [comment]
@s1lver do you still remember this case? If so, would you please take a look?

**Comment by s1lver** [comment]
> @s1lver do you still remember this case? If so, would you please take a look?

hmm, 2017... yes, I looked at the related issue but I don't remember how I fixed it back then. I can just check again.

**Comment by s1lver** [comment]
If **confirm** is used on the button and the option `'enableAjaxValidation' => true` is enabled, then the form is not validated.

```php
<?= Html::submitButton(
     'Submit',
     [
          'class' => 'btn btn-success',
           'data' => [
               'confirm' => 'Confirm message',
           ],
    ]
) ?>
```

I'm not sure if it can be accepted in this form. Would be nice to add tests

**Comment by samdark** [comment]
@tim-fischer-maschinensucher do you have time to add a test case to ensure it's not broken again ever?

**Comment by tim-fischer-maschinensucher** [comment]
I should be able to get to it this or next week.

**Comment by terabytesoftw** [comment]
Hi, if we can't reproduce it, and everything seems to work fine, can we close it, and if the problem reappears do we open it again?

**Comment by s1lver** [comment]
Hmm... I guess something else could have affected me. It's enough for me that there is a test for the old problem

**Review by s1lver — APPROVED** [review]

**Comment by tim-fischer-maschinensucher** [comment]
Is there anything I still need to do for this pr to progress?

**Pull request merged**
